In [2]:
import pandas as pd
import re
from google.colab import files

# 1. 7~12월 관심집단 파일 직접 선택
uploaded = files.upload()

data_list = []

for filename in uploaded.keys():

    # Excel 읽기
    df = pd.read_excel(filename)

    # 파일명에서 월 추출
    match = re.search(r'(\d{1,2})월', filename)

    if match:
        month = int(match.group(1))
    else:
        raise ValueError(f"파일명에서 월을 찾을 수 없습니다: {filename}")

    # 분석 기준 월 생성
    df["기준연월"] = f"2025-{month:02d}"

    data_list.append(df)

    print(f"{month}월: {len(df):,}행 / {len(df.columns)}열")

# 2. 세로 결합
interest_all = pd.concat(
    data_list,
    ignore_index=True
)

# 3. 기준연월 순서 정렬
interest_all = interest_all.sort_values(
    ["기준연월", "행정동코드", "성별", "연령대"]
).reset_index(drop=True)

print("\n통합 완료")
print("전체 크기:", interest_all.shape)

display(interest_all.head())

Saving 2025.7월_10개 관심집단 수.xlsx to 2025.7월_10개 관심집단 수.xlsx
Saving 2025.8월_10개 관심집단 수.xlsx to 2025.8월_10개 관심집단 수.xlsx
Saving 2025.9월_10개 관심집단수.xlsx to 2025.9월_10개 관심집단수.xlsx
Saving 2025.10월_10개 관심집단수.xlsx to 2025.10월_10개 관심집단수.xlsx
Saving 2025.11월_10개 관심집단수.xlsx to 2025.11월_10개 관심집단수.xlsx
Saving 2025.12월_10개 관심집단수.xlsx to 2025.12월_10개 관심집단수.xlsx
7월: 10,176행 / 18열
8월: 10,176행 / 18열
9월: 10,176행 / 18열
10월: 10,176행 / 18열
11월: 10,176행 / 18열
12월: 10,176행 / 18열

통합 완료
전체 크기: (61056, 18)

,행정동코드,자치구,행정동명,성별,연령대,총인구,1인가구수,커뮤니케이션이 적은 집단,평일 외출이 적은 집단,휴일 외출이 적은 집단,출근소요시간 및 근무시간이 많은 집단,외출이 매우 적은 집단(전체),외출이 매우 많은 집단,동영상서비스 이용이 많은 집단,생활서비스 이용이 많은 집단,재정상태에 대한 관심집단,외출-커뮤니케이션이 모두 적은 집단(전체),기준연월
0,1101053,종로구,사직동,1,20,173.0,52.36,4.48,8.30,2.17,6.40,0.00,3.64,10.17,2.77,7.28,13.23,2025-07
1,1101053,종로구,사직동,1,25,300.0,95.41,18.09,16.77,5.35,15.00,27.11,8.41,16.85,9.48,13.82,22.12,2025-07
2,1101053,종로구,사직동,1,30,366.0,117.40,23.68,18.39,8.08,9.76,9.94,15.49,19.32,14.83,7.50,14.27,2025-07
3,1101053,종로구,사직동,1,35,376.0,109.03,22.57,15.56,7.87,16.55,17.89,12.78,19.15,10.19,10.73,16.06,2025-07
4,1101053,종로구,사직동,1,40,418.0,96.50,19.81,11.53,7.61,10.98,19.89,8.63,20.63,3.42,8.99,16.06,2025-07

In [3]:
# 1. 월별 행 수 확인
print("월별 행 수")
print(interest_all.groupby("기준연월").size())

# 2. 월별 행정동 수 확인
print("\n월별 행정동 수")
print(
    interest_all.groupby("기준연월")["행정동코드"]
    .nunique()
)

# 3. 분석 단위의 중복 확인
key_cols = [
    "기준연월",
    "행정동코드",
    "성별",
    "연령대"
]

duplicate_count = interest_all.duplicated(
    subset=key_cols
).sum()

print("\n중복 행 수:", duplicate_count)

# 4. 결측치 확인
print("\n컬럼별 결측치")
print(interest_all.isnull().sum())

# 5. 성별·연령대 범위 확인
print("\n성별:", sorted(interest_all["성별"].unique()))
print("연령대:", sorted(interest_all["연령대"].unique()))

월별 행 수
기준연월
2025-07    10176
2025-08    10176
2025-09    10176
2025-10    10176
2025-11    10176
2025-12    10176
dtype: int64

월별 행정동 수
기준연월
2025-07    424
2025-08    424
2025-09    424
2025-10    424
2025-11    424
2025-12    424
Name: 행정동코드, dtype: int64

중복 행 수: 0

컬럼별 결측치
행정동코드                      0
자치구                        0
행정동명                       0
성별                         0
연령대                        0
총인구                        0
1인가구수                      0
커뮤니케이션이 적은 집단              0
평일 외출이 적은 집단               0
휴일 외출이 적은 집단               0
출근소요시간 및 근무시간이 많은 집단       0
외출이 매우 적은 집단(전체)           0
외출이 매우 많은 집단               0
동영상서비스 이용이 많은 집단           0
생활서비스 이용이 많은 집단            0
재정상태에 대한 관심집단              0
외출-커뮤니케이션이 모두 적은 집단(전체)    0
기준연월                       0
dtype: int64

성별: [np.int64(1), np.int64(2)]
연령대: [np.int64(20), np.int64(25), np.int64(30), np.int64(35), np.int64(40), np.int64(45), np.int64(50), np.int64(55), np.int64(60), np.int64(65), np.int64(70), np.int64(75)]

In [4]:
# 강남구 데이터 추출
gangnam_interest = (
    interest_all[interest_all["자치구"] == "강남구"]
    .copy()
    .reset_index(drop=True)
)

print("전체 크기:", gangnam_interest.shape)

print("\n월별 행 수")
print(gangnam_interest.groupby("기준연월").size())

print("\n월별 행정동 수")
print(
    gangnam_interest.groupby("기준연월")["행정동코드"]
    .nunique()
)

print("\n강남구 행정동")
print(
    gangnam_interest[["행정동코드", "행정동명"]]
    .drop_duplicates()
    .sort_values("행정동코드")
    .to_string(index=False)
)

display(gangnam_interest.head())

전체 크기: (3168, 18)

월별 행 수
기준연월
2025-07    528
2025-08    528
2025-09    528
2025-10    528
2025-11    528
2025-12    528
dtype: int64

월별 행정동 수
기준연월
2025-07    22
2025-08    22
2025-09    22
2025-10    22
2025-11    22
2025-12    22
Name: 행정동코드, dtype: int64

강남구 행정동
  행정동코드 행정동명
1123051  신사동
1123052 논현1동
1123053 논현2동
1123058 삼성1동
1123059 삼성2동
1123060 대치1동
1123063 대치4동
1123064 역삼1동
1123065 역삼2동
1123066 도곡1동
1123067 도곡2동
1123068 개포1동
1123071 개포4동
1123072 일원본동
1123073 일원1동
1123074 일원2동
1123075  수서동
1123076  세곡동
1123077 압구정동
1123078  청담동
1123079 대치2동
1123080 개포2동

,행정동코드,자치구,행정동명,성별,연령대,총인구,1인가구수,커뮤니케이션이 적은 집단,평일 외출이 적은 집단,휴일 외출이 적은 집단,출근소요시간 및 근무시간이 많은 집단,외출이 매우 적은 집단(전체),외출이 매우 많은 집단,동영상서비스 이용이 많은 집단,생활서비스 이용이 많은 집단,재정상태에 대한 관심집단,외출-커뮤니케이션이 모두 적은 집단(전체),기준연월
0,1123051,강남구,신사동,1,20,369.0,79.86,8.54,3.69,7.18,4.88,2.62,9.58,8.31,8.44,5.00,32.93,2025-07
1,1123051,강남구,신사동,1,25,534.0,129.64,15.34,13.60,8.42,12.71,13.68,16.18,17.52,20.40,14.31,19.65,2025-07
2,1123051,강남구,신사동,1,30,551.0,163.38,27.86,13.56,19.62,20.59,9.36,24.92,19.67,20.66,13.59,10.50,2025-07
3,1123051,강남구,신사동,1,35,521.0,147.35,27.89,20.47,14.11,18.84,16.38,21.84,32.24,19.39,12.47,16.54,2025-07
4,1123051,강남구,신사동,1,40,650.0,79.67,16.14,8.84,8.31,11.66,37.78,13.34,16.19,10.20,7.64,26.77,2025-07

In [5]:
# 일원2동 → 개포3동 명칭 통일
gangnam_interest["행정동명"] = gangnam_interest["행정동명"].replace({
    "일원2동": "개포3동"
})

# 확인
print(
    gangnam_interest[
        gangnam_interest["행정동명"] == "개포3동"
    ][["행정동코드", "행정동명"]]
    .drop_duplicates()
)

       행정동코드  행정동명
360  1123074  개포3동

In [6]:
# 행정동 × 성별 × 연령대별 1인가구수의 월별 변화 확인
single_change = (
    gangnam_interest
    .groupby(
        ["행정동코드", "행정동명", "성별", "연령대"]
    )["1인가구수"]
    .agg(
        월별값개수="nunique",
        최소값="min",
        최대값="max",
        평균="mean",
        표준편차="std"
    )
    .reset_index()
)

print("전체 집단 수:", len(single_change))

print("\n6개월 내 1인가구수가 변한 집단:")
print((single_change["월별값개수"] > 1).sum())

print("\n6개월 내 1인가구수가 동일한 집단:")
print((single_change["월별값개수"] == 1).sum())

# 월별 강남구 전체 1인가구수
monthly_single = (
    gangnam_interest
    .groupby("기준연월")["1인가구수"]
    .sum()
)

print("\n월별 강남구 1인가구수 합계")
print(monthly_single)

전체 집단 수: 528

6개월 내 1인가구수가 변한 집단:
528

6개월 내 1인가구수가 동일한 집단:
0

월별 강남구 1인가구수 합계
기준연월
2025-07    90892.06
2025-08    90989.88
2025-09    90849.19
2025-10    90594.00
2025-11    90494.00
2025-12    90306.56
Name: 1인가구수, dtype: float64

In [7]:
from google.colab import files

# 파일명
output_file = "gangnam_interest_groups_2025_07_12.csv"

# CSV 저장
gangnam_interest.to_csv(
    output_file,
    index=False,
    encoding="utf-8-sig"
)

# 다운로드
files.download(output_file)

print("저장 완료:", output_file)
print("데이터 크기:", gangnam_interest.shape)

저장 완료: gangnam_interest_groups_2025_07_12.csv
데이터 크기: (3168, 18)

In [8]:
import pandas as pd
from google.colab import files

# 1. 파일 업로드
uploaded = files.upload()
filename = list(uploaded.keys())[0]

# 2. 원본 데이터 불러오기
household_raw = pd.read_csv(filename)

print("전체 크기:", household_raw.shape)
print("\n컬럼 목록:")
print(household_raw.columns.tolist())

display(household_raw.head())

Saving 세대원수별+세대수_20260923100552.csv to 세대원수별+세대수_20260923100552.csv
전체 크기: (454, 24)

컬럼 목록:
['동별(1)', '동별(2)', '2025 3/4', '2025 3/4.1', '2025 3/4.2', '2025 3/4.3', '2025 3/4.4', '2025 3/4.5', '2025 3/4.6', '2025 3/4.7', '2025 3/4.8', '2025 3/4.9', '2025 3/4.10', '2025 4/4', '2025 4/4.1', '2025 4/4.2', '2025 4/4.3', '2025 4/4.4', '2025 4/4.5', '2025 4/4.6', '2025 4/4.7', '2025 4/4.8', '2025 4/4.9', '2025 4/4.10']

,동별(1),동별(2),2025 3/4,2025 3/4.1,2025 3/4.2,2025 3/4.3,2025 3/4.4,2025 3/4.5,2025 3/4.6,2025 3/4.7,...,2025 4/4.1,2025 4/4.2,2025 4/4.3,2025 4/4.4,2025 4/4.5,2025 4/4.6,2025 4/4.7,2025 4/4.8,2025 4/4.9,2025 4/4.10
0,동별(1),동별(2),전체세대,1인세대,2인세대,3인세대,4인세대,5인세대,6인세대,7인세대,...,1인세대,2인세대,3인세대,4인세대,5인세대,6인세대,7인세대,8인세대,9인세대,10인세대 이상
1,합계,소계,4505357,2031598,1028698,751100,545338,115278,24675,6018,...,2029785,1031855,750246,541782,114282,24440,6015,1707,538,381
2,종로구,소계,72402,38455,14922,10020,6736,1689,414,103,...,38492,14981,9946,6654,1681,410,97,40,10,13
3,종로구,청운효자동,4914,1884,1204,949,650,164,47,8,...,1857,1215,942,624,172,46,10,4,2,1
4,종로구,사직동,4583,2368,935,670,463,112,18,10,...,2369,946,667,456,110,18,11,3,0,4

In [9]:
# 강남구 행정동별 1인세대 추출
gangnam_household = household_raw[
    (household_raw["동별(1)"] == "강남구") &
    (household_raw["동별(2)"] != "소계")
][
    ["동별(2)", "2025 3/4.1", "2025 4/4.1"]
].copy()

# 컬럼명 정리
gangnam_household.columns = [
    "행정동명",
    "2025_Q3_1인세대",
    "2025_Q4_1인세대"
]

# 숫자형 변환
gangnam_household["2025_Q3_1인세대"] = pd.to_numeric(
    gangnam_household["2025_Q3_1인세대"]
)

gangnam_household["2025_Q4_1인세대"] = pd.to_numeric(
    gangnam_household["2025_Q4_1인세대"]
)

gangnam_household = gangnam_household.reset_index(drop=True)

print("행정동 수:", len(gangnam_household))

print("\n3분기 강남구 1인세대 합계:")
print(gangnam_household["2025_Q3_1인세대"].sum())

print("\n4분기 강남구 1인세대 합계:")
print(gangnam_household["2025_Q4_1인세대"].sum())

display(gangnam_household)

행정동 수: 22

3분기 강남구 1인세대 합계:
98105

4분기 강남구 1인세대 합계:
97519

    행정동명  2025_Q3_1인세대  2025_Q4_1인세대
0    신사동          2451          2444
1   논현1동          9372          9306
2   논현2동          6502          6434
3   압구정동          2680          2663
4    청담동          4176          4265
5   삼성1동          1967          1981
6   삼성2동          6047          6014
7   대치1동           551           547
8   대치2동          2560          2485
9   대치4동          5461          5293
10  역삼1동         17855         17783
11  역삼2동          6379          6328
12  도곡1동          2689          2698
13  도곡2동          2171          2184
14  개포1동          1336          1316
15  개포2동          2579          2559
16  개포3동          2554          2543
17  개포4동          3697          3676
18   세곡동          7853          7847
19  일원본동          1472          1473
20  일원1동          3700          3678
21   수서동          4053          4002

In [10]:
# 관심집단 데이터의 행정동 목록
interest_dongs = set(gangnam_interest["행정동명"].unique())

# 공식 1인세대 데이터의 행정동 목록
household_dongs = set(gangnam_household["행정동명"].unique())

print("관심집단 행정동 수:", len(interest_dongs))
print("공식 세대수 행정동 수:", len(household_dongs))

print("\n관심집단에만 존재:")
print(sorted(interest_dongs - household_dongs))

print("\n공식 세대수에만 존재:")
print(sorted(household_dongs - interest_dongs))

print("\n양쪽 모두 존재:")
print(len(interest_dongs & household_dongs))

관심집단 행정동 수: 22
공식 세대수 행정동 수: 22

관심집단에만 존재:
[]

공식 세대수에만 존재:
[]

양쪽 모두 존재:
22

In [11]:
# 1. 관심집단 데이터에 공식 1인세대 데이터 결합
gangnam_merged = gangnam_interest.merge(
    gangnam_household,
    on="행정동명",
    how="left",
    validate="many_to_one"
)

# 2. 월에 따라 사용할 공식 1인세대 수 선택
gangnam_merged["공식_1인세대수"] = gangnam_merged.apply(
    lambda row:
        row["2025_Q3_1인세대"]
        if row["기준연월"] in ["2025-07", "2025-08", "2025-09"]
        else row["2025_Q4_1인세대"],
    axis=1
)

# 3. 결합 검증
print("결합 후 크기:", gangnam_merged.shape)

print("\n공식 1인세대수 결측치:")
print(gangnam_merged["공식_1인세대수"].isna().sum())

print("\n월별 적용된 공식 기준값 종류:")
print(
    gangnam_merged
    .groupby("기준연월")["공식_1인세대수"]
    .sum()
)

display(
    gangnam_merged[
        ["기준연월", "행정동코드", "행정동명", "성별", "연령대",
         "1인가구수", "공식_1인세대수"]
    ].head()
)

결합 후 크기: (3168, 21)

공식 1인세대수 결측치:
0

월별 적용된 공식 기준값 종류:
기준연월
2025-07    2354520
2025-08    2354520
2025-09    2354520
2025-10    2340456
2025-11    2340456
2025-12    2340456
Name: 공식_1인세대수, dtype: int64

      기준연월    행정동코드 행정동명  성별  연령대   1인가구수  공식_1인세대수
0  2025-07  1123051  신사동   1   20   79.86      2451
1  2025-07  1123051  신사동   1   25  129.64      2451
2  2025-07  1123051  신사동   1   30  163.38      2451
3  2025-07  1123051  신사동   1   35  147.35      2451
4  2025-07  1123051  신사동   1   40   79.67      2451

In [12]:
# 행정동 × 월 단위로 통신 1인가구수 집계
dong_month_compare = (
    gangnam_merged
    .groupby(
        ["기준연월", "행정동코드", "행정동명"],
        as_index=False
    )
    .agg(
        통신_1인가구수=("1인가구수", "sum"),
        공식_1인세대수=("공식_1인세대수", "first")
    )
)

# 공식 기준 대비 통신 데이터 비율
dong_month_compare["대비율_pct"] = (
    dong_month_compare["통신_1인가구수"]
    / dong_month_compare["공식_1인세대수"]
    * 100
)

# 절대 차이
dong_month_compare["차이"] = (
    dong_month_compare["통신_1인가구수"]
    - dong_month_compare["공식_1인세대수"]
)

print("데이터 크기:", dong_month_compare.shape)

# 월별 강남구 전체 비교
monthly_compare = (
    dong_month_compare
    .groupby("기준연월", as_index=False)
    .agg(
        통신_1인가구수=("통신_1인가구수", "sum"),
        공식_1인세대수=("공식_1인세대수", "sum")
    )
)

monthly_compare["대비율_pct"] = (
    monthly_compare["통신_1인가구수"]
    / monthly_compare["공식_1인세대수"]
    * 100
)

display(monthly_compare.round(2))

print("\n행정동별 비교 예시")
display(dong_month_compare.head(22).round(2))

데이터 크기: (132, 7)

      기준연월  통신_1인가구수  공식_1인세대수  대비율_pct
0  2025-07  90892.06     98105    92.65
1  2025-08  90989.88     98105    92.75
2  2025-09  90849.19     98105    92.60
3  2025-10  90594.00     97519    92.90
4  2025-11  90494.00     97519    92.80
5  2025-12  90306.56     97519    92.60

행정동별 비교 예시

       기준연월    행정동코드  행정동명  통신_1인가구수  공식_1인세대수  대비율_pct       차이
0   2025-07  1123051   신사동   2417.03      2451    98.61   -33.97
1   2025-07  1123052  논현1동   9192.65      9372    98.09  -179.35
2   2025-07  1123053  논현2동   5814.59      6502    89.43  -687.41
3   2025-07  1123058  삼성1동   1822.02      1967    92.63  -144.98
4   2025-07  1123059  삼성2동   4723.38      6047    78.11 -1323.62
5   2025-07  1123060  대치1동    534.50       551    97.01   -16.50
6   2025-07  1123063  대치4동   5145.38      5461    94.22  -315.62
7   2025-07  1123064  역삼1동  18184.35     17855   101.84   329.35
8   2025-07  1123065  역삼2동   5406.36      6379    84.75  -972.64
9   2025-07  1123066  도곡1동   2033.22      2689    75.61  -655.78
10  2025-07  1123067  도곡2동   1817.65      2171    83.72  -353.35
11  2025-07  1123068  개포1동   2725.37      1336   203.99  1389.37
12  2025-07  1123071  개포4동   2833.48      3697    76.64  -863.52
13  2025-07  1123072  일원본동   1555.65      1472   105.68    83.65
14  2025-07  1123073  일원1동   3316.21      3700    89.63  -383.79
15  2025-07  1123074  개포3동   2378.89      2554    93.14  -175.11
16  2025-07  1123075   수서동   3924.24      4053    96.82  -128.76
17  2025-07  1123076   세곡동   5975.33      7853    76.09 -1877.67
18  2025-07  1123077  압구정동   2439.48      2680    91.03  -240.52
19  2025-07  1123078   청담동   3829.27      4176    91.70  -346.73
20  2025-07  1123079  대치2동   1717.27      2560    67.08  -842.73
21  2025-07  1123080  개포2동   3105.74      2579   120.42   526.74

In [13]:
# 행정동별 6개월 대비율의 안정성 확인
dong_ratio_summary = (
    dong_month_compare
    .groupby(["행정동코드", "행정동명"], as_index=False)
    .agg(
        평균_대비율=("대비율_pct", "mean"),
        최소_대비율=("대비율_pct", "min"),
        최대_대비율=("대비율_pct", "max"),
        표준편차=("대비율_pct", "std")
    )
)

dong_ratio_summary["변동폭"] = (
    dong_ratio_summary["최대_대비율"]
    - dong_ratio_summary["최소_대비율"]
)

# 평균 대비율이 높은 순서로 확인
dong_ratio_summary = dong_ratio_summary.sort_values(
    "평균_대비율",
    ascending=False
).reset_index(drop=True)

display(dong_ratio_summary.round(2))

print("\n평균 표준편차:",
      round(dong_ratio_summary["표준편차"].mean(), 2))

print("가장 큰 표준편차:",
      round(dong_ratio_summary["표준편차"].max(), 2))

      행정동코드  행정동명  평균_대비율  최소_대비율  최대_대비율  표준편차   변동폭
0   1123068  개포1동  206.36  201.62  209.83  3.64  8.20
1   1123080  개포2동  120.83  119.72  121.97  0.80  2.26
2   1123072  일원본동  106.35  105.62  107.23  0.73  1.61
3   1123064  역삼1동  100.44   99.43  101.84  0.87  2.41
4   1123051   신사동   99.31   98.61   99.84  0.45  1.23
5   1123060  대치1동   98.97   97.01  101.34  1.84  4.34
6   1123075   수서동   98.37   96.82   99.81  0.98  2.99
7   1123052  논현1동   97.83   97.27   98.20  0.32  0.93
8   1123063  대치4동   95.28   93.77   96.52  1.16  2.75
9   1123074  개포3동   94.13   93.14   95.62  0.98  2.48
10  1123078   청담동   91.65   90.68   92.50  0.68  1.82
11  1123077  압구정동   91.31   90.65   92.08  0.61  1.43
12  1123058  삼성1동   90.72   89.04   92.63  1.47  3.59
13  1123073  일원1동   90.53   89.63   91.75  0.80  2.12
14  1123053  논현2동   90.18   89.43   90.76  0.48  1.33
15  1123065  역삼2동   85.09   84.75   85.49  0.30  0.74
16  1123067  도곡2동   84.16   83.36   84.99  0.67  1.63
17  1123059  삼성2동   78.56   78.11   78.87  0.29  0.76
18  1123071  개포4동   76.72   76.00   77.30  0.51  1.30
19  1123066  도곡1동   75.79   75.56   75.99  0.17  0.42
20  1123076   세곡동   75.70   75.01   76.40  0.58  1.39
21  1123079  대치2동   68.70   67.08   70.40  1.35  3.32

평균 표준편차: 0.89
가장 큰 표준편차: 3.64

In [14]:
# 관심집단 10개 지표
group_cols = [
    "커뮤니케이션이 적은 집단",
    "평일 외출이 적은 집단",
    "휴일 외출이 적은 집단",
    "출근소요시간 및 근무시간이 많은 집단",
    "외출이 매우 적은 집단(전체)",
    "외출이 매우 많은 집단",
    "동영상서비스 이용이 많은 집단",
    "생활서비스 이용이 많은 집단",
    "재정상태에 대한 관심집단",
    "외출-커뮤니케이션이 모두 적은 집단(전체)"
]

result = []

for col in group_cols:
    exceed = gangnam_merged[col] > gangnam_merged["1인가구수"]

    result.append({
        "지표": col,
        "1인가구수_초과건수": exceed.sum(),
        "초과비율_pct": exceed.mean() * 100,
        "최대값_대비_1인가구수": (
            gangnam_merged[col] / gangnam_merged["1인가구수"]
        ).max() * 100
    })

check_groups = pd.DataFrame(result)

display(check_groups.round(2))

                        지표  1인가구수_초과건수  초과비율_pct  최대값_대비_1인가구수
0            커뮤니케이션이 적은 집단           0      0.00         26.65
1             평일 외출이 적은 집단           0      0.00         21.12
2             휴일 외출이 적은 집단           0      0.00         32.26
3     출근소요시간 및 근무시간이 많은 집단           0      0.00         26.52
4         외출이 매우 적은 집단(전체)          64      2.02        252.31
5             외출이 매우 많은 집단          25      0.79        182.32
6         동영상서비스 이용이 많은 집단           0      0.00         32.17
7          생활서비스 이용이 많은 집단           0      0.00         37.29
8            재정상태에 대한 관심집단           0      0.00         23.79
9  외출-커뮤니케이션이 모두 적은 집단(전체)          84      2.65        275.86

In [15]:
# 1. 1인가구 분석에 필요한 컬럼만 분리
single_household = gangnam_merged[
    [
        "기준연월",
        "행정동코드",
        "행정동명",
        "성별",
        "연령대",
        "1인가구수"
    ]
].copy()

# 2. 행정동 × 월별 전체 1인가구수
single_household["행정동_월_1인가구수"] = (
    single_household
    .groupby(["기준연월", "행정동코드"])["1인가구수"]
    .transform("sum")
)

# 3. 각 성별 × 연령대 집단의 구성비
single_household["구성비_pct"] = (
    single_household["1인가구수"]
    / single_household["행정동_월_1인가구수"]
    * 100
)

# 4. 기본 검증
print("데이터 크기:", single_household.shape)

print("\n월별 행 수:")
print(single_household.groupby("기준연월").size())

# 각 행정동 × 월에서 구성비 합계가 100%인지 확인
ratio_sum = (
    single_household
    .groupby(["기준연월", "행정동명"])["구성비_pct"]
    .sum()
)

print("\n구성비 합계 최소값:", ratio_sum.min())
print("구성비 합계 최대값:", ratio_sum.max())

display(single_household.head(12).round(2))

데이터 크기: (3168, 8)

월별 행 수:
기준연월
2025-07    528
2025-08    528
2025-09    528
2025-10    528
2025-11    528
2025-12    528
dtype: int64

구성비 합계 최소값: 99.99999999999999
구성비 합계 최대값: 100.00000000000001

       기준연월    행정동코드 행정동명  성별  연령대   1인가구수  행정동_월_1인가구수  구성비_pct
0   2025-07  1123051  신사동   1   20   79.86      2417.03     3.30
1   2025-07  1123051  신사동   1   25  129.64      2417.03     5.36
2   2025-07  1123051  신사동   1   30  163.38      2417.03     6.76
3   2025-07  1123051  신사동   1   35  147.35      2417.03     6.10
4   2025-07  1123051  신사동   1   40   79.67      2417.03     3.30
5   2025-07  1123051  신사동   1   45   85.95      2417.03     3.56
6   2025-07  1123051  신사동   1   50   62.85      2417.03     2.60
7   2025-07  1123051  신사동   1   55   57.58      2417.03     2.38
8   2025-07  1123051  신사동   1   60   43.63      2417.03     1.81
9   2025-07  1123051  신사동   1   65   54.30      2417.03     2.25
10  2025-07  1123051  신사동   1   70   47.84      2417.03     1.98
11  2025-07  1123051  신사동   1   75  154.97      2417.03     6.41

In [17]:
# =========================
# 1. 성별 1인가구 데이터
# =========================

gender_single = (
    single_household
    .groupby(
        ["기준연월", "행정동코드", "행정동명", "성별"],
        as_index=False
    )
    .agg(
        single_count=("1인가구수", "sum"),
        dong_total=("행정동_월_1인가구수", "first")
    )
)

# 컬럼명 변경
gender_single = gender_single.rename(columns={
    "single_count": "1인가구수",
    "dong_total": "행정동_월_1인가구수"
})

gender_single["성별_구성비_pct"] = (
    gender_single["1인가구수"]
    / gender_single["행정동_월_1인가구수"]
    * 100
)


# =========================
# 2. 연령대별 1인가구 데이터
# =========================

age_single = (
    single_household
    .groupby(
        ["기준연월", "행정동코드", "행정동명", "연령대"],
        as_index=False
    )
    .agg(
        single_count=("1인가구수", "sum"),
        dong_total=("행정동_월_1인가구수", "first")
    )
)

# 컬럼명 변경
age_single = age_single.rename(columns={
    "single_count": "1인가구수",
    "dong_total": "행정동_월_1인가구수"
})

age_single["연령대_구성비_pct"] = (
    age_single["1인가구수"]
    / age_single["행정동_월_1인가구수"]
    * 100
)


# =========================
# 3. 검증
# =========================

print("성별 데이터 크기:", gender_single.shape)
print("연령대 데이터 크기:", age_single.shape)

gender_check = (
    gender_single
    .groupby(["기준연월", "행정동명"])["성별_구성비_pct"]
    .sum()
)

age_check = (
    age_single
    .groupby(["기준연월", "행정동명"])["연령대_구성비_pct"]
    .sum()
)

print("\n성별 구성비 합계:")
print(gender_check.min(), "~", gender_check.max())

print("\n연령대 구성비 합계:")
print(age_check.min(), "~", age_check.max())

print("\n성별 데이터 예시")
display(gender_single.head(6).round(2))

print("\n연령대 데이터 예시")
display(age_single.head(12).round(2))

성별 데이터 크기: (264, 7)
연령대 데이터 크기: (1584, 7)

성별 구성비 합계:
99.99999999999997 ~ 100.00000000000003

연령대 구성비 합계:
99.99999999999999 ~ 100.00000000000001

성별 데이터 예시

      기준연월    행정동코드  행정동명  성별    1인가구수  행정동_월_1인가구수  성별_구성비_pct
0  2025-07  1123051   신사동   1  1107.02      2417.03       45.80
1  2025-07  1123051   신사동   2  1310.01      2417.03       54.20
2  2025-07  1123052  논현1동   1  4297.45      9192.65       46.75
3  2025-07  1123052  논현1동   2  4895.20      9192.65       53.25
4  2025-07  1123053  논현2동   1  2754.92      5814.59       47.38
5  2025-07  1123053  논현2동   2  3059.67      5814.59       52.62

연령대 데이터 예시

       기준연월    행정동코드 행정동명  연령대   1인가구수  행정동_월_1인가구수  연령대_구성비_pct
0   2025-07  1123051  신사동   20  176.13      2417.03         7.29
1   2025-07  1123051  신사동   25  301.94      2417.03        12.49
2   2025-07  1123051  신사동   30  355.49      2417.03        14.71
3   2025-07  1123051  신사동   35  310.11      2417.03        12.83
4   2025-07  1123051  신사동   40  156.44      2417.03         6.47
5   2025-07  1123051  신사동   45  162.02      2417.03         6.70
6   2025-07  1123051  신사동   50  128.18      2417.03         5.30
7   2025-07  1123051  신사동   55  107.87      2417.03         4.46
8   2025-07  1123051  신사동   60   93.38      2417.03         3.86
9   2025-07  1123051  신사동   65  131.81      2417.03         5.45
10  2025-07  1123051  신사동   70  108.69      2417.03         4.50
11  2025-07  1123051  신사동   75  384.97      2417.03        15.93

In [18]:
from google.colab import files

output_file = "gangnam_single_household_2025_07_12.xlsx"

with pd.ExcelWriter(output_file, engine="openpyxl") as writer:

    # 성별 집계
    gender_single.to_excel(
        writer,
        sheet_name="성별_1인가구",
        index=False
    )

    # 연령대별 집계
    age_single.to_excel(
        writer,
        sheet_name="연령대별_1인가구",
        index=False
    )

    # 성별 × 연령대 원본
    single_household.to_excel(
        writer,
        sheet_name="성별연령대_원본",
        index=False
    )

files.download(output_file)

print("저장 완료:", output_file)

저장 완료: gangnam_single_household_2025_07_12.xlsx

In [19]:
# 1인가구 데이터에 분기 변수 추가

single_household["분기"] = single_household["기준연월"].map({
    "2025-07": "2025Q3",
    "2025-08": "2025Q3",
    "2025-09": "2025Q3",
    "2025-10": "2025Q4",
    "2025-11": "2025Q4",
    "2025-12": "2025Q4"
})

# 확인
print(single_household.shape)

print("\n월별 분기 매핑")
print(
    single_household[
        ["기준연월", "분기"]
    ]
    .drop_duplicates()
    .sort_values("기준연월")
)

print("\n분기 결측값:", single_household["분기"].isna().sum())

print("\n분기별 행 수")
print(single_household["분기"].value_counts().sort_index())

(3168, 9)

월별 분기 매핑
         기준연월      분기
0     2025-07  2025Q3
528   2025-08  2025Q3
1056  2025-09  2025Q3
1584  2025-10  2025Q4
2112  2025-11  2025Q4
2640  2025-12  2025Q4

분기 결측값: 0

분기별 행 수
분기
2025Q3    1584
2025Q4    1584
Name: count, dtype: int64

In [21]:
from google.colab import files
import pandas as pd
import io

uploaded = files.upload()

# 방금 업로드한 파일명 확인
filename = list(uploaded.keys())[0]
print("업로드된 파일:", filename)

resident = pd.read_csv(
    io.BytesIO(uploaded[filename]),
    encoding="utf-8-sig"
)

print("데이터 크기:", resident.shape)

print("\n컬럼 목록")
print(resident.columns.tolist())

print("\n앞부분")
display(resident.head())

print("\n각 컬럼 자료형")
print(resident.dtypes)

Saving gangnam_resident_population_features_2025Q3_Q4.csv to gangnam_resident_population_features_2025Q3_Q4.csv
업로드된 파일: gangnam_resident_population_features_2025Q3_Q4.csv
데이터 크기: (44, 27)

컬럼 목록
['dong_name', 'quarter', 'resident_total', 'resident_korean', 'resident_foreigner', 'foreigner_ratio', 'resident_age_10', 'resident_age_20', 'resident_age_30', 'resident_age_40', 'resident_age_50', 'resident_age_60_plus', 'resident_age_65_plus', 'resident_age_10_ratio', 'resident_age_20_ratio', 'resident_age_30_ratio', 'resident_age_40_ratio', 'resident_age_50_ratio', 'resident_age_60_plus_ratio', 'resident_age_65_plus_ratio', 'resident_10plus', 'resident_age_10_ratio_10plus', 'resident_age_20_ratio_10plus', 'resident_age_30_ratio_10plus', 'resident_age_40_ratio_10plus', 'resident_age_50_ratio_10plus', 'resident_age_60_plus_ratio_10plus']

앞부분

,dong_name,quarter,resident_total,resident_korean,resident_foreigner,foreigner_ratio,resident_age_10,resident_age_20,resident_age_30,resident_age_40,...,resident_age_50_ratio,resident_age_60_plus_ratio,resident_age_65_plus_ratio,resident_10plus,resident_age_10_ratio_10plus,resident_age_20_ratio_10plus,resident_age_30_ratio_10plus,resident_age_40_ratio_10plus,resident_age_50_ratio_10plus,resident_age_60_plus_ratio_10plus
0,신사동,2025Q3,15327,15114,213,0.013897,1453,1823,2012,2417,...,0.172571,0.273048,0.211261,14535,0.099966,0.125421,0.138424,0.166288,0.181975,0.287926
1,신사동,2025Q4,15291,15081,210,0.013734,1469,1807,1988,2415,...,0.172978,0.273494,0.211432,14506,0.101268,0.124569,0.137047,0.166483,0.182338,0.288294
2,논현1동,2025Q3,21571,20733,838,0.038848,861,3777,5518,3668,...,0.133281,0.201984,0.149274,21056,0.040891,0.179379,0.262063,0.174202,0.136541,0.206924
3,논현1동,2025Q4,21500,20647,853,0.039674,870,3705,5471,3714,...,0.133023,0.203442,0.150326,20994,0.041440,0.176479,0.260598,0.176908,0.136229,0.208345
4,논현2동,2025Q3,20511,20119,392,0.019112,1212,2982,4243,3606,...,0.154064,0.219785,0.163181,19711,0.061489,0.151286,0.215261,0.182944,0.160317,0.228705

각 컬럼 자료형
dong_name                             object
quarter                               object
resident_total                         int64
resident_korean                        int64
resident_foreigner                     int64
foreigner_ratio                      float64
resident_age_10                        int64
resident_age_20                        int64
resident_age_30                        int64
resident_age_40                        int64
resident_age_50                        int64
resident_age_60_plus                   int64
resident_age_65_plus                   int64
resident_age_10_ratio                float64
resident_age_20_ratio                float64
resident_age_30_ratio                float64
resident_age_40_ratio                float64
resident_age_50_ratio                float64
resident_age_60_plus_ratio           float64
resident_age_65_plus_ratio           float64
resident_10plus                        int64
resident_age_10_ratio_10plus         float64
resident_age_20_ratio_10plus         float64
resident_age_30_ratio_10plus         float64
resident_age_40_ratio_10plus         float64
resident_age_50_ratio_10plus         float64
resident_age_60_plus_ratio_10plus    float64
dtype: object

In [22]:
# ========================================
# single_household ↔ resident 결합 key 검증
# ========================================

# 1. 1인가구 쪽 행정동 × 분기 key
single_keys = (
    single_household[
        ["행정동명", "분기"]
    ]
    .drop_duplicates()
    .rename(columns={
        "행정동명": "dong_name",
        "분기": "quarter"
    })
)

# 2. 등록인구 쪽 행정동 × 분기 key
resident_keys = (
    resident[
        ["dong_name", "quarter"]
    ]
    .drop_duplicates()
)

print("1인가구 key 수:", len(single_keys))
print("등록인구 key 수:", len(resident_keys))


# 3. 양쪽 key 비교
key_check = single_keys.merge(
    resident_keys,
    on=["dong_name", "quarter"],
    how="outer",
    indicator=True
)

print("\nkey 대응 결과")
print(key_check["_merge"].value_counts())


# 4. 한쪽에만 존재하는 key 확인
print("\n1인가구에만 존재:")
display(
    key_check[
        key_check["_merge"] == "left_only"
    ]
)

print("\n등록인구에만 존재:")
display(
    key_check[
        key_check["_merge"] == "right_only"
    ]
)


# 5. 행정동 목록 확인
print("\n1인가구 행정동 수:",
      single_keys["dong_name"].nunique())

print("등록인구 행정동 수:",
      resident_keys["dong_name"].nunique())

1인가구 key 수: 44
등록인구 key 수: 44

key 대응 결과
_merge
both          44
left_only      0
right_only     0
Name: count, dtype: int64

1인가구에만 존재:

Empty DataFrame
Columns: [dong_name, quarter, _merge]
Index: []

등록인구에만 존재:

Empty DataFrame
Columns: [dong_name, quarter, _merge]
Index: []

1인가구 행정동 수: 22
등록인구 행정동 수: 22

In [23]:
# 1인가구 연령대를 등록인구 Feature와 동일한 구간으로 재구성

def make_age_group(age):
    if age in [20, 25]:
        return "20"
    elif age in [30, 35]:
        return "30"
    elif age in [40, 45]:
        return "40"
    elif age in [50, 55]:
        return "50"
    elif age in [60, 65, 70, 75]:
        return "60_plus"
    else:
        return None

single_household["age_group"] = (
    single_household["연령대"]
    .apply(make_age_group)
)

print("연령그룹별 행 수")
print(single_household["age_group"].value_counts(dropna=False))

print("\n결측값:")
print(single_household["age_group"].isna().sum())

연령그룹별 행 수
age_group
60_plus    1056
20          528
30          528
40          528
50          528
Name: count, dtype: int64

결측값:
0

In [24]:
# ========================================
# 등록인구: 20세 이상 기준 연령구성비 생성
# ========================================

resident["resident_20plus"] = (
    resident["resident_age_20"]
    + resident["resident_age_30"]
    + resident["resident_age_40"]
    + resident["resident_age_50"]
    + resident["resident_age_60_plus"]
)

age_groups = ["20", "30", "40", "50", "60_plus"]

for age in age_groups:
    resident[f"resident_age_{age}_ratio_20plus"] = (
        resident[f"resident_age_{age}"]
        / resident["resident_20plus"]
    )

# 검증
ratio_cols = [
    f"resident_age_{age}_ratio_20plus"
    for age in age_groups
]

resident["ratio_20plus_sum"] = resident[ratio_cols].sum(axis=1)

print("20세 이상 인구 최소값:", resident["resident_20plus"].min())

print(
    "20세 이상 연령 구성비 합계:",
    resident["ratio_20plus_sum"].min(),
    "~",
    resident["ratio_20plus_sum"].max()
)

display(
    resident[
        ["dong_name", "quarter", "resident_20plus"] + ratio_cols
    ].head()
)

20세 이상 인구 최소값: 11197
20세 이상 연령 구성비 합계: 0.9999999999999999 ~ 1.0

,dong_name,quarter,resident_20plus,resident_age_20_ratio_20plus,resident_age_30_ratio_20plus,resident_age_40_ratio_20plus,resident_age_50_ratio_20plus,resident_age_60_plus_ratio_20plus
0,신사동,2025Q3,13082,0.139352,0.153799,0.184758,0.202186,0.319905
1,신사동,2025Q4,13037,0.138606,0.152489,0.185242,0.202884,0.320779
2,논현1동,2025Q3,20195,0.187026,0.273236,0.181629,0.142362,0.215746
3,논현1동,2025Q4,20124,0.184109,0.271864,0.184556,0.142119,0.217352
4,논현2동,2025Q3,18499,0.161198,0.229364,0.194929,0.170820,0.243689

In [25]:
# ========================================
# 통신 1인가구: 20세 이상 연령그룹별 집계
# ========================================

single_age_group = (
    single_household
    .groupby(
        ["기준연월", "분기", "행정동코드", "행정동명", "age_group"],
        as_index=False
    )
    .agg(
        single_count=("1인가구수", "sum")
    )
)

# 행정동 × 월 전체 20세 이상 1인가구수
single_age_group["single_20plus"] = (
    single_age_group
    .groupby(["기준연월", "행정동코드"])["single_count"]
    .transform("sum")
)

# 1인가구 내부 연령 구성비
single_age_group["single_age_ratio_20plus"] = (
    single_age_group["single_count"]
    / single_age_group["single_20plus"]
)

# ========================================
# 검증
# ========================================

print("데이터 크기:", single_age_group.shape)

print("\n연령그룹별 행 수")
print(single_age_group["age_group"].value_counts())

ratio_check = (
    single_age_group
    .groupby(["기준연월", "행정동명"])["single_age_ratio_20plus"]
    .sum()
)

print(
    "\n1인가구 연령 구성비 합계:",
    ratio_check.min(),
    "~",
    ratio_check.max()
)

print("\n예시")
display(single_age_group.head(10).round(4))

데이터 크기: (660, 8)

연령그룹별 행 수
age_group
20         132
30         132
40         132
50         132
60_plus    132
Name: count, dtype: int64

1인가구 연령 구성비 합계: 0.9999999999999999 ~ 1.0

예시

,기준연월,분기,행정동코드,행정동명,age_group,single_count,single_20plus,single_age_ratio_20plus
0,2025-07,2025Q3,1123051,신사동,20,478.07,2417.03,0.1978
1,2025-07,2025Q3,1123051,신사동,30,665.60,2417.03,0.2754
2,2025-07,2025Q3,1123051,신사동,40,318.46,2417.03,0.1318
3,2025-07,2025Q3,1123051,신사동,50,236.05,2417.03,0.0977
4,2025-07,2025Q3,1123051,신사동,60_plus,718.85,2417.03,0.2974
5,2025-07,2025Q3,1123052,논현1동,20,2279.18,9192.65,0.2479
6,2025-07,2025Q3,1123052,논현1동,30,3243.40,9192.65,0.3528
7,2025-07,2025Q3,1123052,논현1동,40,1955.00,9192.65,0.2127
8,2025-07,2025Q3,1123052,논현1동,50,652.95,9192.65,0.0710
9,2025-07,2025Q3,1123052,논현1동,60_plus,1062.12,9192.65,0.1155

In [26]:
# ========================================
# 1. 등록인구 20+ 연령구조를 long 형태로 변환
# ========================================

resident_age_long = resident[
    [
        "dong_name",
        "quarter",
        "resident_20plus",
        "resident_age_20_ratio_20plus",
        "resident_age_30_ratio_20plus",
        "resident_age_40_ratio_20plus",
        "resident_age_50_ratio_20plus",
        "resident_age_60_plus_ratio_20plus"
    ]
].melt(
    id_vars=["dong_name", "quarter", "resident_20plus"],
    var_name="resident_age_variable",
    value_name="resident_age_ratio_20plus"
)

# 연령그룹 이름 추출
resident_age_long["age_group"] = (
    resident_age_long["resident_age_variable"]
    .str.replace("resident_age_", "", regex=False)
    .str.replace("_ratio_20plus", "", regex=False)
)

resident_age_long = resident_age_long.drop(
    columns="resident_age_variable"
)


# ========================================
# 2. 통신 1인가구와 등록인구 결합
# ========================================

single_age_compare = single_age_group.merge(
    resident_age_long,
    left_on=["행정동명", "분기", "age_group"],
    right_on=["dong_name", "quarter", "age_group"],
    how="left",
    validate="many_to_one"
)


# ========================================
# 3. 검증
# ========================================

print("결합 후 크기:", single_age_compare.shape)

print(
    "등록인구 구성비 결측값:",
    single_age_compare["resident_age_ratio_20plus"].isna().sum()
)

print(
    "등록인구 20+ 인구 결측값:",
    single_age_compare["resident_20plus"].isna().sum()
)

print("\n예시")
display(
    single_age_compare[
        [
            "기준연월",
            "분기",
            "행정동명",
            "age_group",
            "single_count",
            "single_age_ratio_20plus",
            "resident_20plus",
            "resident_age_ratio_20plus"
        ]
    ].head(10).round(4)
)

결합 후 크기: (660, 12)
등록인구 구성비 결측값: 0
등록인구 20+ 인구 결측값: 0

예시

,기준연월,분기,행정동명,age_group,single_count,single_age_ratio_20plus,resident_20plus,resident_age_ratio_20plus
0,2025-07,2025Q3,신사동,20,478.07,0.1978,13082,0.1394
1,2025-07,2025Q3,신사동,30,665.60,0.2754,13082,0.1538
2,2025-07,2025Q3,신사동,40,318.46,0.1318,13082,0.1848
3,2025-07,2025Q3,신사동,50,236.05,0.0977,13082,0.2022
4,2025-07,2025Q3,신사동,60_plus,718.85,0.2974,13082,0.3199
5,2025-07,2025Q3,논현1동,20,2279.18,0.2479,20195,0.1870
6,2025-07,2025Q3,논현1동,30,3243.40,0.3528,20195,0.2732
7,2025-07,2025Q3,논현1동,40,1955.00,0.2127,20195,0.1816
8,2025-07,2025Q3,논현1동,50,652.95,0.0710,20195,0.1424
9,2025-07,2025Q3,논현1동,60_plus,1062.12,0.1155,20195,0.2157

In [27]:
# ========================================
# 1인가구 ↔ 등록인구 연령구조 차이 Feature
# ========================================

# 1. 구성비 차이
single_age_compare["single_resident_age_gap"] = (
    single_age_compare["single_age_ratio_20plus"]
    - single_age_compare["resident_age_ratio_20plus"]
)

# 2. 상대비율
single_age_compare["single_resident_age_ratio"] = (
    single_age_compare["single_age_ratio_20plus"]
    / single_age_compare["resident_age_ratio_20plus"]
)

# ========================================
# 검증 및 확인
# ========================================

print(
    "gap 결측값:",
    single_age_compare["single_resident_age_gap"].isna().sum()
)

print(
    "ratio 결측값:",
    single_age_compare["single_resident_age_ratio"].isna().sum()
)

display(
    single_age_compare[
        [
            "기준연월",
            "행정동명",
            "age_group",
            "single_age_ratio_20plus",
            "resident_age_ratio_20plus",
            "single_resident_age_gap",
            "single_resident_age_ratio"
        ]
    ].head(15).round(4)
)

gap 결측값: 0
ratio 결측값: 0

,기준연월,행정동명,age_group,single_age_ratio_20plus,resident_age_ratio_20plus,single_resident_age_gap,single_resident_age_ratio
0,2025-07,신사동,20,0.1978,0.1394,0.0584,1.4194
1,2025-07,신사동,30,0.2754,0.1538,0.1216,1.7905
2,2025-07,신사동,40,0.1318,0.1848,-0.0530,0.7131
3,2025-07,신사동,50,0.0977,0.2022,-0.1045,0.4830
4,2025-07,신사동,60_plus,0.2974,0.3199,-0.0225,0.9297
5,2025-07,논현1동,20,0.2479,0.1870,0.0609,1.3257
6,2025-07,논현1동,30,0.3528,0.2732,0.0796,1.2913
7,2025-07,논현1동,40,0.2127,0.1816,0.0310,1.1709
8,2025-07,논현1동,50,0.0710,0.1424,-0.0713,0.4989
9,2025-07,논현1동,60_plus,0.1155,0.2157,-0.1002,0.5355
10,2025-07,논현2동,20,0.2030,0.1612,0.0418,1.2591
11,2025-07,논현2동,30,0.3478,0.2294,0.1184,1.5164
12,2025-07,논현2동,40,0.2102,0.1949,0.0152,1.0782
13,2025-07,논현2동,50,0.0933,0.1708,-0.0775,0.5465
14,2025-07,논현2동,60_plus,0.1457,0.2437,-0.0980,0.5980

In [28]:
# ========================================
# 연령별 gap의 월별 안정성 확인
# ========================================

gap_stability = (
    single_age_compare
    .groupby(["행정동명", "age_group"], as_index=False)
    .agg(
        gap_mean=("single_resident_age_gap", "mean"),
        gap_min=("single_resident_age_gap", "min"),
        gap_max=("single_resident_age_gap", "max"),
        gap_std=("single_resident_age_gap", "std")
    )
)

gap_stability["gap_range"] = (
    gap_stability["gap_max"]
    - gap_stability["gap_min"]
)

# %p 단위로 보기 쉽게 변환
for col in ["gap_mean", "gap_min", "gap_max", "gap_std", "gap_range"]:
    gap_stability[col] = gap_stability[col] * 100

print("전체 행 수:", len(gap_stability))

print("\n연령그룹별 평균 변동성(%p)")
print(
    gap_stability
    .groupby("age_group")["gap_std"]
    .mean()
    .round(2)
)

print("\n변동성이 큰 조합 TOP 15")
display(
    gap_stability
    .sort_values("gap_std", ascending=False)
    .head(15)
    .round(2)
)

전체 행 수: 110

연령그룹별 평균 변동성(%p)
age_group
20         0.17
30         0.19
40         0.21
50         0.13
60_plus    0.29
Name: gap_std, dtype: float64

변동성이 큰 조합 TOP 15

    행정동명 age_group  gap_mean  gap_min  gap_max  gap_std  gap_range
59  삼성1동   60_plus      2.09     1.03     2.76     0.60       1.74
34  대치1동   60_plus     23.38    22.60    24.21     0.58       1.61
4   개포1동   60_plus      3.73     2.98     4.35     0.52       1.37
0   개포1동        20     -1.23    -1.67    -0.54     0.52       1.13
19  개포4동   60_plus      2.94     2.32     3.44     0.45       1.12
85  역삼1동        20      2.20     1.65     2.69     0.42       1.04
39  대치2동   60_plus     13.57    13.10    14.28     0.41       1.17
40  대치4동        20      0.55     0.08     0.95     0.39       0.86
84  압구정동   60_plus     16.55    16.10    17.17     0.38       1.07
27  논현2동        40      1.17     0.55     1.52     0.37       0.97
87  역삼1동        40      4.17     3.63     4.69     0.35       1.05
79   신사동   60_plus     -1.77    -2.25    -1.25     0.34       1.00
22  논현1동        40      2.59     2.18     3.10     0.33       0.93
9   개포2동   60_plus     22.82    22.31    23.11     0.32       0.80
31  대치1동        30      7.39     7.04     7.86     0.32       0.82

In [29]:
# ========================================
# 행정동별 1인가구 연령구조 Feature Table
# ========================================

# gap 6개월 평균
single_age_feature = (
    single_age_compare
    .groupby(["행정동코드", "행정동명", "age_group"], as_index=False)
    .agg(
        age_gap_mean=("single_resident_age_gap", "mean")
    )
)

# wide 형태로 변환
single_age_feature = (
    single_age_feature
    .pivot(
        index=["행정동코드", "행정동명"],
        columns="age_group",
        values="age_gap_mean"
    )
    .reset_index()
)

# 컬럼명 정리
single_age_feature.columns.name = None

single_age_feature = single_age_feature.rename(columns={
    "20": "single_age_20_gap",
    "30": "single_age_30_gap",
    "40": "single_age_40_gap",
    "50": "single_age_50_gap",
    "60_plus": "single_age_60_plus_gap"
})

# %p 단위로 변환하지 않고 0~1 단위 유지
# 예: 0.12 = +12%p

print("Feature Table 크기:", single_age_feature.shape)

print("\n결측값:")
print(single_age_feature.isna().sum())

display(single_age_feature.head().round(4))

Feature Table 크기: (22, 7)

결측값:
행정동코드                     0
행정동명                      0
single_age_20_gap         0
single_age_30_gap         0
single_age_40_gap         0
single_age_50_gap         0
single_age_60_plus_gap    0
dtype: int64

,행정동코드,행정동명,single_age_20_gap,single_age_30_gap,single_age_40_gap,single_age_50_gap,single_age_60_plus_gap
0,1123051,신사동,0.0570,0.1212,-0.0528,-0.1076,-0.0177
1,1123052,논현1동,0.0619,0.0825,0.0259,-0.0721,-0.0982
2,1123053,논현2동,0.0431,0.1218,0.0117,-0.0792,-0.0974
3,1123058,삼성1동,-0.0233,0.0774,-0.0021,-0.0729,0.0209
4,1123059,삼성2동,0.0403,0.1384,-0.0515,-0.0892,-0.0379

In [30]:
# ========================================
# 행정동별 1인가구 성별 구조 Feature 생성
# ========================================

# 1. 행정동 × 성별 기준 6개월 평균
single_gender_feature = (
    gender_single
    .groupby(["행정동코드", "행정동명", "성별"], as_index=False)
    .agg(
        gender_ratio_mean=("성별_구성비_pct", "mean")
    )
)

# 기존 구성비가 % 단위이므로 0~1 단위로 통일
single_gender_feature["gender_ratio_mean"] = (
    single_gender_feature["gender_ratio_mean"] / 100
)

# 2. wide 형태로 변환
single_gender_feature = (
    single_gender_feature
    .pivot(
        index=["행정동코드", "행정동명"],
        columns="성별",
        values="gender_ratio_mean"
    )
    .reset_index()
)

single_gender_feature.columns.name = None

# 성별 코드의 의미가 확인되지 않았으므로 코드 그대로 사용
single_gender_feature = single_gender_feature.rename(columns={
    1: "single_gender_1_ratio",
    2: "single_gender_2_ratio"
})

# ========================================
# 검증
# ========================================

single_gender_feature["gender_ratio_sum"] = (
    single_gender_feature["single_gender_1_ratio"]
    + single_gender_feature["single_gender_2_ratio"]
)

print("Feature Table 크기:", single_gender_feature.shape)

print("\n결측값:")
print(single_gender_feature.isna().sum())

print(
    "\n성별 구성비 합계:",
    single_gender_feature["gender_ratio_sum"].min(),
    "~",
    single_gender_feature["gender_ratio_sum"].max()
)

display(single_gender_feature.head().round(4))

Feature Table 크기: (22, 5)

결측값:
행정동코드                    0
행정동명                     0
single_gender_1_ratio    0
single_gender_2_ratio    0
gender_ratio_sum         0
dtype: int64

성별 구성비 합계: 0.9999999999999999 ~ 1.0

,행정동코드,행정동명,single_gender_1_ratio,single_gender_2_ratio,gender_ratio_sum
0,1123051,신사동,0.4562,0.5438,1.0
1,1123052,논현1동,0.4672,0.5328,1.0
2,1123053,논현2동,0.4740,0.5260,1.0
3,1123058,삼성1동,0.4952,0.5048,1.0
4,1123059,삼성2동,0.4592,0.5408,1.0

In [31]:
# ========================================
# 1인가구 인구구조 Feature Table 결합
# ========================================

single_demographic_feature = single_age_feature.merge(
    single_gender_feature[
        [
            "행정동코드",
            "행정동명",
            "single_gender_1_ratio",
            "single_gender_2_ratio"
        ]
    ],
    on=["행정동코드", "행정동명"],
    how="left",
    validate="one_to_one"
)

# ========================================
# 검증
# ========================================

print("최종 크기:", single_demographic_feature.shape)

print("\n결측값:")
print(single_demographic_feature.isna().sum())

print("\n행정동 수:")
print(single_demographic_feature["행정동명"].nunique())

display(single_demographic_feature.head().round(4))

최종 크기: (22, 9)

결측값:
행정동코드                     0
행정동명                      0
single_age_20_gap         0
single_age_30_gap         0
single_age_40_gap         0
single_age_50_gap         0
single_age_60_plus_gap    0
single_gender_1_ratio     0
single_gender_2_ratio     0
dtype: int64

행정동 수:
22

,행정동코드,행정동명,single_age_20_gap,single_age_30_gap,single_age_40_gap,single_age_50_gap,single_age_60_plus_gap,single_gender_1_ratio,single_gender_2_ratio
0,1123051,신사동,0.0570,0.1212,-0.0528,-0.1076,-0.0177,0.4562,0.5438
1,1123052,논현1동,0.0619,0.0825,0.0259,-0.0721,-0.0982,0.4672,0.5328
2,1123053,논현2동,0.0431,0.1218,0.0117,-0.0792,-0.0974,0.4740,0.5260
3,1123058,삼성1동,-0.0233,0.0774,-0.0021,-0.0729,0.0209,0.4952,0.5048
4,1123059,삼성2동,0.0403,0.1384,-0.0515,-0.0892,-0.0379,0.4592,0.5408

In [32]:
# ========================================
# 행정동별 통신 기반 1인가구 규모 Feature
# ========================================

single_scale_feature = (
    single_household[
        ["기준연월", "행정동코드", "행정동명", "행정동_월_1인가구수"]
    ]
    .drop_duplicates()
    .groupby(["행정동코드", "행정동명"], as_index=False)
    .agg(
        single_household_mean=("행정동_월_1인가구수", "mean"),
        single_household_min=("행정동_월_1인가구수", "min"),
        single_household_max=("행정동_월_1인가구수", "max"),
        single_household_std=("행정동_월_1인가구수", "std")
    )
)

single_scale_feature["single_household_range"] = (
    single_scale_feature["single_household_max"]
    - single_scale_feature["single_household_min"]
)

print("Feature Table 크기:", single_scale_feature.shape)

print("\n결측값:")
print(single_scale_feature.isna().sum())

display(
    single_scale_feature
    .sort_values("single_household_mean", ascending=False)
    .round(2)
)

Feature Table 크기: (22, 7)

결측값:
행정동코드                     0
행정동명                      0
single_household_mean     0
single_household_min      0
single_household_max      0
single_household_std      0
single_household_range    0
dtype: int64

,행정동코드,행정동명,single_household_mean,single_household_min,single_household_max,single_household_std,single_household_range
7,1123064,역삼1동,17897.13,17682.18,18184.35,188.25,502.17
1,1123052,논현1동,9136.04,9052.18,9203.37,59.70,151.19
17,1123076,세곡동,5942.30,5886.02,5999.45,47.41,113.43
2,1123053,논현2동,5832.84,5784.66,5901.33,48.05,116.67
8,1123065,역삼2동,5405.84,5389.71,5416.95,9.43,27.24
6,1123063,대치4동,5122.60,5085.12,5178.83,34.51,93.71
4,1123059,삼성2동,4737.71,4723.38,4756.55,11.29,33.17
16,1123075,수서동,3961.79,3924.24,3994.52,27.30,70.28
19,1123078,청담동,3867.86,3809.50,3936.73,46.49,127.23
14,1123073,일원1동,3339.69,3316.21,3374.40,20.48,58.19
21,1123080,개포2동,3104.14,3082.13,3122.09,16.65,39.96
12,1123071,개포4동,2828.36,2793.84,2857.87,25.88,64.03
11,1123068,개포1동,2736.02,2693.70,2761.32,26.83,67.62
18,1123077,압구정동,2439.30,2416.99,2452.08,13.76,35.09
0,1123051,신사동,2430.55,2417.03,2440.18,8.34,23.15
15,1123074,개포3동,2398.87,2378.89,2431.63,20.65,52.74
9,1123066,도곡1동,2041.38,2031.84,2050.10,7.37,18.26
10,1123067,도곡2동,1832.64,1817.65,1846.88,12.69,29.23
3,1123058,삼성1동,1790.74,1763.93,1822.02,23.05,58.09
20,1123079,대치2동,1732.42,1717.27,1749.45,12.75,32.18
13,1123072,일원본동,1566.08,1554.68,1579.48,11.29,24.80
5,1123060,대치1동,543.31,534.50,554.34,8.13,19.84

In [33]:
# ========================================
# 공식 1인세대 규모 Feature
# ========================================

official_single_feature = gangnam_household.copy()

official_single_feature["official_single_household_mean"] = (
    official_single_feature[
        ["2025_Q3_1인세대", "2025_Q4_1인세대"]
    ].mean(axis=1)
)

official_single_feature["official_single_household_change"] = (
    official_single_feature["2025_Q4_1인세대"]
    - official_single_feature["2025_Q3_1인세대"]
)

official_single_feature["official_single_household_change_rate"] = (
    official_single_feature["official_single_household_change"]
    / official_single_feature["2025_Q3_1인세대"]
)

print("Feature Table 크기:", official_single_feature.shape)

print("\n결측값:")
print(official_single_feature.isna().sum())

display(
    official_single_feature
    .sort_values(
        "official_single_household_mean",
        ascending=False
    )
    .round(4)
)

Feature Table 크기: (22, 6)

결측값:
행정동명                                     0
2025_Q3_1인세대                             0
2025_Q4_1인세대                             0
official_single_household_mean           0
official_single_household_change         0
official_single_household_change_rate    0
dtype: int64

,행정동명,2025_Q3_1인세대,2025_Q4_1인세대,official_single_household_mean,official_single_household_change,official_single_household_change_rate
10,역삼1동,17855,17783,17819.0,-72,-0.0040
1,논현1동,9372,9306,9339.0,-66,-0.0070
18,세곡동,7853,7847,7850.0,-6,-0.0008
2,논현2동,6502,6434,6468.0,-68,-0.0105
11,역삼2동,6379,6328,6353.5,-51,-0.0080
6,삼성2동,6047,6014,6030.5,-33,-0.0055
9,대치4동,5461,5293,5377.0,-168,-0.0308
4,청담동,4176,4265,4220.5,89,0.0213
21,수서동,4053,4002,4027.5,-51,-0.0126
20,일원1동,3700,3678,3689.0,-22,-0.0059
17,개포4동,3697,3676,3686.5,-21,-0.0057
12,도곡1동,2689,2698,2693.5,9,0.0033
3,압구정동,2680,2663,2671.5,-17,-0.0063
15,개포2동,2579,2559,2569.0,-20,-0.0078
16,개포3동,2554,2543,2548.5,-11,-0.0043
8,대치2동,2560,2485,2522.5,-75,-0.0293
0,신사동,2451,2444,2447.5,-7,-0.0029
13,도곡2동,2171,2184,2177.5,13,0.0060
5,삼성1동,1967,1981,1974.0,14,0.0071
19,일원본동,1472,1473,1472.5,1,0.0007
14,개포1동,1336,1316,1326.0,-20,-0.0150
7,대치1동,551,547,549.0,-4,-0.0073

In [34]:
# ========================================
# 최종 1인가구 Feature Table 생성
# ========================================

single_household_feature = (
    single_demographic_feature

    # 통신 기반 규모
    .merge(
        single_scale_feature[
            [
                "행정동코드",
                "행정동명",
                "single_household_mean"
            ]
        ],
        on=["행정동코드", "행정동명"],
        how="left",
        validate="one_to_one"
    )

    # 공식 1인세대 규모
    .merge(
        official_single_feature[
            [
                "행정동명",
                "2025_Q3_1인세대",
                "2025_Q4_1인세대",
                "official_single_household_mean",
                "official_single_household_change",
                "official_single_household_change_rate"
            ]
        ],
        on="행정동명",
        how="left",
        validate="one_to_one"
    )
)

# ========================================
# 검증
# ========================================

print("최종 크기:", single_household_feature.shape)

print("\n행정동 수:")
print(single_household_feature["행정동명"].nunique())

print("\n결측값:")
print(single_household_feature.isna().sum())

print("\n중복 행정동:")
print(single_household_feature["행정동명"].duplicated().sum())

display(single_household_feature.head().round(4))

최종 크기: (22, 15)

행정동 수:
22

결측값:
행정동코드                                    0
행정동명                                     0
single_age_20_gap                        0
single_age_30_gap                        0
single_age_40_gap                        0
single_age_50_gap                        0
single_age_60_plus_gap                   0
single_gender_1_ratio                    0
single_gender_2_ratio                    0
single_household_mean                    0
2025_Q3_1인세대                             0
2025_Q4_1인세대                             0
official_single_household_mean           0
official_single_household_change         0
official_single_household_change_rate    0
dtype: int64

중복 행정동:
0

,행정동코드,행정동명,single_age_20_gap,single_age_30_gap,single_age_40_gap,single_age_50_gap,single_age_60_plus_gap,single_gender_1_ratio,single_gender_2_ratio,single_household_mean,2025_Q3_1인세대,2025_Q4_1인세대,official_single_household_mean,official_single_household_change,official_single_household_change_rate
0,1123051,신사동,0.0570,0.1212,-0.0528,-0.1076,-0.0177,0.4562,0.5438,2430.5467,2451,2444,2447.5,-7,-0.0029
1,1123052,논현1동,0.0619,0.0825,0.0259,-0.0721,-0.0982,0.4672,0.5328,9136.0450,9372,9306,9339.0,-66,-0.0070
2,1123053,논현2동,0.0431,0.1218,0.0117,-0.0792,-0.0974,0.4740,0.5260,5832.8367,6502,6434,6468.0,-68,-0.0105
3,1123058,삼성1동,-0.0233,0.0774,-0.0021,-0.0729,0.0209,0.4952,0.5048,1790.7367,1967,1981,1974.0,14,0.0071
4,1123059,삼성2동,0.0403,0.1384,-0.0515,-0.0892,-0.0379,0.4592,0.5408,4737.7100,6047,6014,6030.5,-33,-0.0055

In [35]:
# ========================================
# 1인가구 분석 결과 저장
# ========================================

# 1. 상세 데이터
# 행정동 × 월 × 성별 × 5세 단위 연령
single_household.to_csv(
    "gangnam_single_household_detail_2025_07_12.csv",
    index=False,
    encoding="utf-8-sig"
)

# 2. 연령구조 비교 데이터
# 행정동 × 월 × 5개 연령그룹
single_age_compare.to_csv(
    "gangnam_single_household_age_compare_2025_07_12.csv",
    index=False,
    encoding="utf-8-sig"
)

# 3. 최종 행정동 Feature Table
# 행정동 × 1행
single_household_feature.to_csv(
    "gangnam_single_household_features_2025.csv",
    index=False,
    encoding="utf-8-sig"
)

print("저장 완료")

print(
    "detail:",
    single_household.shape
)

print(
    "age compare:",
    single_age_compare.shape
)

print(
    "feature:",
    single_household_feature.shape
)

저장 완료
detail: (3168, 10)
age compare: (660, 14)
feature: (22, 15)

In [36]:
from google.colab import files

files.download("gangnam_single_household_detail_2025_07_12.csv")
files.download("gangnam_single_household_age_compare_2025_07_12.csv")
files.download("gangnam_single_household_features_2025.csv")