In [1]:
import pandas as pd
from google.colab import files

# 파일 업로드
uploaded = files.upload()

# 업로드된 파일명 확인
print(list(uploaded.keys()))

Saving 신한카드_빅콘테스트2026_데이터2.csv to 신한카드_빅콘테스트2026_데이터2.csv
['신한카드_빅콘테스트2026_데이터2.csv']

In [2]:
file_name = list(uploaded.keys())[0]

# 인코딩이 utf-8인 경우
try:
    df = pd.read_csv(file_name, encoding="utf-8")
except:
    # 국내 공공/기업 데이터에서 자주 사용하는 인코딩
    df = pd.read_csv(file_name, encoding="cp949")

print("shape:", df.shape)

print("\n[컬럼]")
print(df.columns.tolist())

print("\n[앞 5행]")
display(df.head())

print("\n[데이터 타입]")
print(df.dtypes)

print("\n[결측치]")
print(df.isna().sum())

print("\n[컬럼별 고유값 수]")
print(df.nunique())

shape: (1806800, 9)

[컬럼]
['Unnamed: 0', 'TA_YMD', 'MCT_SGG_CD', 'MCT_RY_CD', 'CLN_SGG_CD', 'SEX_CCD', 'AGE_CCD', 'TS_AT', 'USE_CNT']

[앞 5행]

,Unnamed: 0,TA_YMD,MCT_SGG_CD,MCT_RY_CD,CLN_SGG_CD,SEX_CCD,AGE_CCD,TS_AT,USE_CNT
0,0,20250714,강원 춘천시,가구,강원,남성,50 대,77544,18
1,1,20250723,서울 강남구,가구,서울,여성,30 대,651570,13
2,2,20250711,강원 춘천시,가전,강원,여성,30 대,4239967,16
3,3,20250719,강원 춘천시,가전,강원,남성,30 대,828641,18
4,4,20250723,강원 춘천시,가전,강원,여성,30 대,443864,11

[데이터 타입]
Unnamed: 0     int64
TA_YMD         int64
MCT_SGG_CD    object
MCT_RY_CD     object
CLN_SGG_CD    object
SEX_CCD       object
AGE_CCD       object
TS_AT          int64
USE_CNT        int64
dtype: object

[결측치]
Unnamed: 0    0
TA_YMD        0
MCT_SGG_CD    0
MCT_RY_CD     0
CLN_SGG_CD    0
SEX_CCD       0
AGE_CCD       0
TS_AT         0
USE_CNT       0
dtype: int64

[컬럼별 고유값 수]
Unnamed: 0    1806800
TA_YMD            184
MCT_SGG_CD          2
MCT_RY_CD          90
CLN_SGG_CD         17
SEX_CCD             2
AGE_CCD             9
TS_AT          978730
USE_CNT         16499
dtype: int64

In [3]:
# 1. 가맹점 지역
print("=== MCT_SGG_CD ===")
print(df["MCT_SGG_CD"].value_counts())

# 2. 고객 지역
print("\n=== CLN_SGG_CD ===")
print(df["CLN_SGG_CD"].value_counts())

# 3. 연령대
print("\n=== AGE_CCD ===")
print(df["AGE_CCD"].value_counts())

# 4. 업종 전체 목록
print("\n=== MCT_RY_CD ===")
industry_list = sorted(df["MCT_RY_CD"].unique())

for i, x in enumerate(industry_list, 1):
    print(f"{i:2d}. {x}")

=== MCT_SGG_CD ===
MCT_SGG_CD
서울 강남구    1366189
강원 춘천시     440611
Name: count, dtype: int64

=== CLN_SGG_CD ===
CLN_SGG_CD
서울      271570
경기      243517
강원      219625
인천      135151
충북       92037
부산       90588
충남       89767
전남광주     88835
경남       82180
대구       80198
경북       79573
대전       78258
전북       67424
울산       58218
제주       55365
세종       54250
정보없음     20244
Name: count, dtype: int64

=== AGE_CCD ===
AGE_CCD
30 대    319358
40 대    312364
50 대    311101
20 대    280601
60 대    239888
70 대    154013
10 대     97507
80 대     75176
90 대     16792
Name: count, dtype: int64

=== MCT_RY_CD ===
 1. LPG가스
 2. ZZ_나머지
 3. 가구
 4. 가전
 5. 게임방/오락실
 6. 결제대행(PG)
 7. 고속버스/철도/여객선
 8. 기타식품
 9. 기타요식
10. 기타유통
11. 기타의료
12. 노래방
13. 농수산물
14. 독서실
15. 동물병원
16. 면세점
17. 모텔,여관,기타숙박
18. 문화용품
19. 미용서비스
20. 미용실
21. 방문판매/다단계판매
22. 백화점
23. 법률/사무서비스
24. 보건소
25. 보험
26. 부동산중개
27. 사무기기/문구용품
28. 상품권/복권
29. 생활잡화/수입상품점
30. 서점
31. 세금공과금
32. 세탁소
33. 쇼핑몰
34. 수입자동차
35. 수제용품점
36. 스포츠/레저용품
37. 스포츠시설
38. 시계/귀금속
39. 실내/실외골프장
40. 싸우나/목욕탕
41. 악기/음반
42. 안마/마사지
43. 애완동물
44. 약국
45. 양식
46. 여행사/항공사
47. 연구/번역서비스
48. 영화/공연
49. 예식장/결혼서비스
50. 오토바이
51. 완구/아동용자전거
52. 유치원
53. 유흥업소
54. 의복/의류
55. 인테리어/건축자재/주방기구
56. 일반병원
57. 일식
58. 자동차서비스
59. 자동차용품
60. 장례식장/묘지/장의사
61. 전용매장
62. 정육점
63. 제과점
64. 종합레저타운/놀이동산
65. 종합병원
66. 주류판매
67. 주유소
68. 주차장
69. 중고차판매
70. 중고품판매점
71. 중식
72. 체인점
73. 치과병원
74. 커피전문점
75. 컴퓨터/소프트웨어
76. 택시
77. 통신요금(이동,시내전화)
78. 패션잡화
79. 패스트푸드
80. 편의점
81. 학교등록금
82. 학원/학습지
83. 한식
84. 한의원
85. 할인점/슈퍼마켓/양판점
86. 헬스장
87. 호텔/콘도
88. 화원
89. 화장품
90. 회계/변리서비스

In [4]:
import pandas as pd
import numpy as np
from google.colab import files

# 2022~2025 CSV 파일 4개를 한꺼번에 선택
uploaded = files.upload()

print("\n업로드된 파일")
for name in uploaded.keys():
    print("-", name)

Saving 서울시 상권분석서비스(추정매출-행정동)_2024년.csv to 서울시 상권분석서비스(추정매출-행정동)_2024년.csv
Saving 서울시 상권분석서비스(추정매출-행정동)_2025년.csv to 서울시 상권분석서비스(추정매출-행정동)_2025년.csv
Saving 서울시_상권분석서비스(추정매출-행정동)_2022년.csv to 서울시_상권분석서비스(추정매출-행정동)_2022년.csv
Saving 서울시_상권분석서비스(추정매출-행정동)_2023년.csv to 서울시_상권분석서비스(추정매출-행정동)_2023년.csv

업로드된 파일
- 서울시 상권분석서비스(추정매출-행정동)_2024년.csv
- 서울시 상권분석서비스(추정매출-행정동)_2025년.csv
- 서울시_상권분석서비스(추정매출-행정동)_2022년.csv
- 서울시_상권분석서비스(추정매출-행정동)_2023년.csv

In [5]:
# ============================================================
# 1. CSV 읽기
# ============================================================

dfs = {}

for filename in uploaded.keys():

    # 파일명에서 연도 추출
    year = None
    for y in range(2022, 2026):
        if str(y) in filename:
            year = y
            break

    if year is None:
        print(f"[주의] 연도를 찾을 수 없음: {filename}")
        continue

    # 인코딩 자동 시도
    try:
        temp = pd.read_csv(filename, encoding="utf-8")
    except UnicodeDecodeError:
        temp = pd.read_csv(filename, encoding="cp949")

    dfs[year] = temp

    print(f"{year}: {temp.shape}")

print("\n로드된 연도:", sorted(dfs.keys()))

2024: (67900, 53)
2025: (67113, 53)
2022: (69440, 53)
2023: (68643, 53)

로드된 연도: [2022, 2023, 2024, 2025]

In [6]:
# ============================================================
# 2. 연도별 기본 구조 확인
# ============================================================

for year in sorted(dfs):

    df = dfs[year]

    print("\n" + "=" * 70)
    print(f"{year}년")
    print("=" * 70)

    print("shape:", df.shape)

    print("\n분기")
    if "기준_년분기_코드" in df.columns:
        print(sorted(df["기준_년분기_코드"].dropna().unique()))

    print("\n행정동 수")
    if "행정동_코드" in df.columns:
        print(df["행정동_코드"].nunique())

    print("\n서비스 업종 수")
    if "서비스_업종_코드" in df.columns:
        print(df["서비스_업종_코드"].nunique())

    print("\n전체 결측치 수")
    print(int(df.isna().sum().sum()))

======================================================================
2022년
======================================================================
shape: (69440, 53)

분기
[np.int64(20221), np.int64(20222), np.int64(20223), np.int64(20224)]

행정동 수
424

서비스 업종 수
63

전체 결측치 수
0

======================================================================
2023년
======================================================================
shape: (68643, 53)

분기
[np.int64(20231), np.int64(20232), np.int64(20233), np.int64(20234)]

행정동 수
424

서비스 업종 수
63

전체 결측치 수
0

======================================================================
2024년
======================================================================
shape: (67900, 53)

분기
[np.int64(20241), np.int64(20242), np.int64(20243), np.int64(20244)]

행정동 수
424

서비스 업종 수
63

전체 결측치 수
0

======================================================================
2025년
======================================================================
shape: (67113, 53)

분기
[np.int64(20251), np.int64(20252), np.int64(20253), np.int64(20254)]

행정동 수
425

서비스 업종 수
63

전체 결측치 수
0

In [7]:
# ============================================================
# 4. 연령별 매출건수 컬럼 확인
# ============================================================

for year in sorted(dfs):

    age_count_cols = [
        c for c in dfs[year].columns
        if ("연령대" in c) and ("매출_건수" in c)
    ]

    print(f"\n[{year}] 연령별 매출건수")
    for c in age_count_cols:
        print("-", c)

[2022] 연령별 매출건수
- 연령대_10_매출_건수
- 연령대_20_매출_건수
- 연령대_30_매출_건수
- 연령대_40_매출_건수
- 연령대_50_매출_건수
- 연령대_60_이상_매출_건수

[2023] 연령별 매출건수
- 연령대_10_매출_건수
- 연령대_20_매출_건수
- 연령대_30_매출_건수
- 연령대_40_매출_건수
- 연령대_50_매출_건수
- 연령대_60_이상_매출_건수

[2024] 연령별 매출건수
- 연령대_10_매출_건수
- 연령대_20_매출_건수
- 연령대_30_매출_건수
- 연령대_40_매출_건수
- 연령대_50_매출_건수
- 연령대_60_이상_매출_건수

[2025] 연령별 매출건수
- 연령대_10_매출_건수
- 연령대_20_매출_건수
- 연령대_30_매출_건수
- 연령대_40_매출_건수
- 연령대_50_매출_건수
- 연령대_60_이상_매출_건수

In [8]:
# ============================================================
# 5. 지역 관련 컬럼 확인
# ============================================================

print([
    c for c in dfs[2025].columns
    if any(x in c for x in ["자치구", "행정동"])
])

['행정동_코드', '행정동_코드_명']

In [10]:
# 2025년 실제 전체 컬럼명 확인
for i, col in enumerate(dfs[2025].columns, 1):
    print(f"{i:2d}. {col}")

 1. 기준_년분기_코드
 2. 행정동_코드
 3. 행정동_코드_명
 4. 서비스_업종_코드
 5. 서비스_업종_코드_명
 6. 당월_매출_금액
 7. 당월_매출_건수
 8. 주중_매출_금액
 9. 주말_매출_금액
10. 월요일_매출_금액
11. 화요일_매출_금액
12. 수요일_매출_금액
13. 목요일_매출_금액
14. 금요일_매출_금액
15. 토요일_매출_금액
16. 일요일_매출_금액
17. 시간대_00~06_매출_금액
18. 시간대_06~11_매출_금액
19. 시간대_11~14_매출_금액
20. 시간대_14~17_매출_금액
21. 시간대_17~21_매출_금액
22. 시간대_21~24_매출_금액
23. 남성_매출_금액
24. 여성_매출_금액
25. 연령대_10_매출_금액
26. 연령대_20_매출_금액
27. 연령대_30_매출_금액
28. 연령대_40_매출_금액
29. 연령대_50_매출_금액
30. 연령대_60_이상_매출_금액
31. 주중_매출_건수
32. 주말_매출_건수
33. 월요일_매출_건수
34. 화요일_매출_건수
35. 수요일_매출_건수
36. 목요일_매출_건수
37. 금요일_매출_건수
38. 토요일_매출_건수
39. 일요일_매출_건수
40. 시간대_건수~06_매출_건수
41. 시간대_건수~11_매출_건수
42. 시간대_건수~14_매출_건수
43. 시간대_건수~17_매출_건수
44. 시간대_건수~21_매출_건수
45. 시간대_건수~24_매출_건수
46. 남성_매출_건수
47. 여성_매출_건수
48. 연령대_10_매출_건수
49. 연령대_20_매출_건수
50. 연령대_30_매출_건수
51. 연령대_40_매출_건수
52. 연령대_50_매출_건수
53. 연령대_60_이상_매출_건수

In [11]:
print("\n=== '강남구'라는 값이 들어 있는 컬럼 검색 ===")

for col in dfs[2025].columns:
    try:
        values = dfs[2025][col].astype(str)

        if values.str.contains("강남구", na=False).any():
            print(f"\n컬럼: {col}")
            print(
                dfs[2025].loc[
                    values.str.contains("강남구", na=False),
                    col
                ].value_counts().head(10)
            )

    except Exception:
        pass

=== '강남구'라는 값이 들어 있는 컬럼 검색 ===

In [12]:
# ============================================================
# 6. 강남구 22개 행정동 추출
# ============================================================

gangnam_codes = [
    1123051,  # 신사동
    1123052,  # 논현1동
    1123053,  # 논현2동
    1123058,  # 삼성1동
    1123059,  # 삼성2동
    1123060,  # 대치1동
    1123063,  # 대치4동
    1123064,  # 역삼1동
    1123065,  # 역삼2동
    1123066,  # 도곡1동
    1123067,  # 도곡2동
    1123068,  # 개포1동
    1123071,  # 개포4동
    1123072,  # 일원본동
    1123073,  # 일원1동
    1123074,  # 개포3동 (과거 일원2동 여부 확인 필요)
    1123075,  # 수서동
    1123076,  # 세곡동
    1123077,  # 압구정동
    1123078,  # 청담동
    1123079,  # 대치2동
    1123080   # 개포2동
]

gangnam_dfs = {}

for year in sorted(dfs):

    temp = dfs[year][
        dfs[year]["행정동_코드"].isin(gangnam_codes)
    ].copy()

    gangnam_dfs[year] = temp

    dong_table = (
        temp[["행정동_코드", "행정동_코드_명"]]
        .drop_duplicates()
        .sort_values("행정동_코드")
    )

    print("\n" + "=" * 60)
    print(f"{year}년")
    print("=" * 60)

    print("행 수:", len(temp))
    print("행정동 코드 수:", temp["행정동_코드"].nunique())
    print("행정동명 수:", temp["행정동_코드_명"].nunique())

    display(dong_table)

============================================================
2022년
============================================================
행 수: 0
행정동 코드 수: 0
행정동명 수: 0

Empty DataFrame
Columns: [행정동_코드, 행정동_코드_명]
Index: []

============================================================
2023년
============================================================
행 수: 0
행정동 코드 수: 0
행정동명 수: 0

Empty DataFrame
Columns: [행정동_코드, 행정동_코드_명]
Index: []

============================================================
2024년
============================================================
행 수: 0
행정동 코드 수: 0
행정동명 수: 0

Empty DataFrame
Columns: [행정동_코드, 행정동_코드_명]
Index: []

============================================================
2025년
============================================================
행 수: 0
행정동 코드 수: 0
행정동명 수: 0

Empty DataFrame
Columns: [행정동_코드, 행정동_코드_명]
Index: []

In [13]:
# ============================================================
# 7. 1123074 명칭 변화 확인
# ============================================================

for year in sorted(gangnam_dfs):

    check = gangnam_dfs[year][
        gangnam_dfs[year]["행정동_코드"] == 1123074
    ]

    print(
        year,
        check["행정동_코드_명"].unique().tolist()
    )

2022 []
2023 []
2024 []
2025 []

In [14]:
# ============================================================
# 8. 강남구 행정동 코드 일관성 확인
# ============================================================

base_codes = set(gangnam_dfs[2022]["행정동_코드"].unique())

for year in [2023, 2024, 2025]:

    current_codes = set(
        gangnam_dfs[year]["행정동_코드"].unique()
    )

    print(f"\n2022 vs {year}")
    print("2022에만 존재:", sorted(base_codes - current_codes))
    print(f"{year}에만 존재:", sorted(current_codes - base_codes))

2022 vs 2023
2022에만 존재: []
2023에만 존재: []

2022 vs 2024
2022에만 존재: []
2024에만 존재: []

2022 vs 2025
2022에만 존재: []
2025에만 존재: []

In [15]:
# ============================================================
# 서울 상권분석 데이터에서 강남구 22개 행정동명 검색
# ============================================================

gangnam_names = [
    "신사동", "논현1동", "논현2동",
    "삼성1동", "삼성2동",
    "대치1동", "대치2동", "대치4동",
    "역삼1동", "역삼2동",
    "도곡1동", "도곡2동",
    "개포1동", "개포2동", "개포3동", "개포4동",
    "일원본동", "일원1동",
    "수서동", "세곡동",
    "압구정동", "청담동"
]

for year in sorted(dfs):

    df_year = dfs[year]

    matched = (
        df_year.loc[
            df_year["행정동_코드_명"].isin(gangnam_names),
            ["행정동_코드", "행정동_코드_명"]
        ]
        .drop_duplicates()
        .sort_values(["행정동_코드_명", "행정동_코드"])
    )

    print("\n" + "=" * 60)
    print(year)
    print("=" * 60)

    print("일치 행정동 수:", matched["행정동_코드_명"].nunique())
    display(matched)

    missing = sorted(
        set(gangnam_names) -
        set(matched["행정동_코드_명"])
    )

    print("찾지 못한 행정동:", missing)

============================================================
2022
============================================================
일치 행정동 수: 21

         행정동_코드 행정동_코드_명
15321  11680660     개포1동
15325  11680670     개포2동
15362  11680690     개포4동
14664  11680521     논현1동
14722  11680531     논현2동
14977  11680600     대치1동
15019  11680610     대치2동
15065  11680630     대치4동
15232  11680655     도곡1동
15280  11680656     도곡2동
14878  11680580     삼성1동
14929  11680590     삼성2동
15417  11680700      세곡동
15531  11680750      수서동
13506  11620685      신사동
14607  11680510      신사동
14771  11680545     압구정동
15118  11680640     역삼1동
15178  11680650     역삼2동
15470  11680730     일원1동
15453  11680720     일원본동
14825  11680565      청담동

찾지 못한 행정동: ['개포3동']

============================================================
2023
============================================================
일치 행정동 수: 21

         행정동_코드 행정동_코드_명
15146  11680660     개포1동
15148  11680670     개포2동
15187  11680690     개포4동
14494  11680521     논현1동
14551  11680531     논현2동
14806  11680600     대치1동
14847  11680610     대치2동
14893  11680630     대치4동
15059  11680655     도곡1동
15104  11680656     도곡2동
14708  11680580     삼성1동
14757  11680590     삼성2동
15239  11680700      세곡동
15352  11680750      수서동
13350  11620685      신사동
14439  11680510      신사동
14602  11680545     압구정동
14946  11680640     역삼1동
15004  11680650     역삼2동
15291  11680730     일원1동
15274  11680720     일원본동
14655  11680565      청담동

찾지 못한 행정동: ['개포3동']

============================================================
2024
============================================================
일치 행정동 수: 21

         행정동_코드 행정동_코드_명
15000  11680660     개포1동
15006  11680670     개포2동
15048  11680690     개포4동
14355  11680521     논현1동
14413  11680531     논현2동
14665  11680600     대치1동
14705  11680610     대치2동
14751  11680630     대치4동
14913  11680655     도곡1동
14959  11680656     도곡2동
14569  11680580     삼성1동
14618  11680590     삼성2동
15098  11680700      세곡동
15211  11680750      수서동
13224  11620685      신사동
14298  11680510      신사동
14463  11680545     압구정동
14802  11680640     역삼1동
14859  11680650     역삼2동
15150  11680730     일원1동
15131  11680720     일원본동
14515  11680565      청담동

찾지 못한 행정동: ['개포3동']

============================================================
2025
============================================================
일치 행정동 수: 21

         행정동_코드 행정동_코드_명
14747  11680660     개포1동
14754  11680670     개포2동
14794  11680690     개포4동
14115  11680521     논현1동
14171  11680531     논현2동
14418  11680600     대치1동
14458  11680610     대치2동
14502  11680630     대치4동
14662  11680655     도곡1동
14707  11680656     도곡2동
14323  11680580     삼성1동
14372  11680590     삼성2동
14843  11680700      세곡동
14953  11680750      수서동
12983  11620685      신사동
14060  11680510      신사동
14220  11680545     압구정동
14553  11680640     역삼1동
14608  11680650     역삼2동
14893  11680730     일원1동
14876  11680720     일원본동
14271  11680565      청담동

찾지 못한 행정동: ['개포3동']

In [16]:
for year in sorted(dfs):

    check = (
        dfs[year]
        .loc[
            dfs[year]["행정동_코드_명"].isin(
                ["개포3동", "일원2동"]
            ),
            ["행정동_코드", "행정동_코드_명"]
        ]
        .drop_duplicates()
    )

    print(year)
    display(check)

2022

         행정동_코드 행정동_코드_명
15511  11680740     일원2동

2023

         행정동_코드 행정동_코드_명
15332  11680740     일원2동

2024

         행정동_코드 행정동_코드_명
15192  11680740     일원2동

2025

         행정동_코드 행정동_코드_명
14935  11680740     일원2동

In [17]:
# ============================================================
# 9. 서울 상권분석 기준 강남구 22개 행정동 추출
# ============================================================

gangnam_code_map = {
    11680510: "신사동",
    11680521: "논현1동",
    11680531: "논현2동",
    11680545: "압구정동",
    11680565: "청담동",
    11680580: "삼성1동",
    11680590: "삼성2동",
    11680600: "대치1동",
    11680610: "대치2동",
    11680630: "대치4동",
    11680640: "역삼1동",
    11680650: "역삼2동",
    11680655: "도곡1동",
    11680656: "도곡2동",
    11680660: "개포1동",
    11680670: "개포2동",
    11680690: "개포4동",
    11680700: "세곡동",
    11680720: "일원본동",
    11680730: "일원1동",

    # 서울 상권분석에서는 과거 명칭 유지
    11680740: "개포3동",

    11680750: "수서동"
}

gangnam_codes = list(gangnam_code_map.keys())

gangnam_dfs = {}

for year in sorted(dfs):

    temp = dfs[year][
        dfs[year]["행정동_코드"].isin(gangnam_codes)
    ].copy()

    # 이름 표준화
    temp["행정동명_표준"] = (
        temp["행정동_코드"]
        .map(gangnam_code_map)
    )

    gangnam_dfs[year] = temp

    print(
        year,
        "행 수:", len(temp),
        "| 동:", temp["행정동_코드"].nunique(),
        "| 분기:", temp["기준_년분기_코드"].nunique(),
        "| 업종:", temp["서비스_업종_코드"].nunique()
    )

2022 행 수: 3842 | 동: 22 | 분기: 4 | 업종: 63
2023 행 수: 3805 | 동: 22 | 분기: 4 | 업종: 63
2024 행 수: 3775 | 동: 22 | 분기: 4 | 업종: 62
2025 행 수: 3742 | 동: 22 | 분기: 4 | 업종: 62

In [18]:
# ============================================================
# 10. 동 × 분기 × 업종 관측 완전성 검사
# ============================================================

for year in sorted(gangnam_dfs):

    temp = gangnam_dfs[year]

    print("\n" + "=" * 65)
    print(year)
    print("=" * 65)

    # 분석 key 중복
    dup = temp.duplicated(
        subset=[
            "기준_년분기_코드",
            "행정동_코드",
            "서비스_업종_코드"
        ]
    ).sum()

    print("key 중복:", dup)

    # 동×분기별 관측 업종 수
    coverage = (
        temp
        .groupby([
            "기준_년분기_코드",
            "행정동명_표준"
        ])["서비스_업종_코드"]
        .nunique()
        .reset_index(name="업종수")
    )

    print("동×분기 관측 수:", len(coverage))
    print("예상 동×분기 수:", 22 * 4)

    print(
        "업종수 min / median / max:",
        coverage["업종수"].min(),
        coverage["업종수"].median(),
        coverage["업종수"].max()
    )

    print("\n업종수가 63개 미만인 동×분기:")
    display(
        coverage[
            coverage["업종수"] < 63
        ].sort_values(
            ["업종수", "기준_년분기_코드"]
        )
    )

=================================================================
2022
=================================================================
key 중복: 0
동×분기 관측 수: 88
예상 동×분기 수: 88
업종수 min / median / max: 2 48.0 61

업종수가 63개 미만인 동×분기:

    기준_년분기_코드 행정동명_표준  업종수
66      20224    개포1동    2
22      20222    개포1동    3
44      20223    개포1동    3
0       20221    개포1동    4
20      20221    일원본동   17
..        ...     ...  ...
70      20224    논현1동   58
61      20223    역삼1동   59
83      20224    역삼1동   59
17      20221    역삼1동   60
39      20222    역삼1동   61

[88 rows x 3 columns]

=================================================================
2023
=================================================================
key 중복: 0
동×분기 관측 수: 88
예상 동×분기 수: 88
업종수 min / median / max: 2 47.0 59

업종수가 63개 미만인 동×분기:

    기준_년분기_코드 행정동명_표준  업종수
0       20231    개포1동    2
22      20232    개포1동    2
66      20234    개포1동    2
44      20233    개포1동    3
64      20233    일원본동   16
..        ...     ...  ...
26      20232    논현1동   58
48      20233    논현1동   58
83      20234    역삼1동   58
39      20232    역삼1동   59
61      20233    역삼1동   59

[88 rows x 3 columns]

=================================================================
2024
=================================================================
key 중복: 0
동×분기 관측 수: 88
예상 동×분기 수: 88
업종수 min / median / max: 6 46.5 58

업종수가 63개 미만인 동×분기:

    기준_년분기_코드 행정동명_표준  업종수
0       20241    개포1동    6
22      20242    개포1동    7
66      20244    개포1동    7
44      20243    개포1동    8
42      20242    일원본동   18
..        ...     ...  ...
15      20241     신사동   57
17      20241    역삼1동   57
26      20242    논현1동   57
39      20242    역삼1동   57
4       20241    논현1동   58

[88 rows x 3 columns]

=================================================================
2025
=================================================================
key 중복: 0
동×분기 관측 수: 88
예상 동×분기 수: 88
업종수 min / median / max: 7 46.0 57

업종수가 63개 미만인 동×분기:

    기준_년분기_코드 행정동명_표준  업종수
0       20251    개포1동    7
44      20253    개포1동    7
66      20254    개포1동    7
22      20252    개포1동    8
20      20251    일원본동   17
..        ...     ...  ...
59      20253     신사동   56
70      20254    논현1동   56
39      20252    역삼1동   57
61      20253    역삼1동   57
83      20254    역삼1동   57

[88 rows x 3 columns]

In [19]:
# ============================================================
# 11. 연도별 업종 목록 및 사라진/추가된 업종 확인
# ============================================================

industry_sets = {}

for year in sorted(gangnam_dfs):

    temp = gangnam_dfs[year]

    industry_table = (
        temp[
            ["서비스_업종_코드", "서비스_업종_코드_명"]
        ]
        .drop_duplicates()
        .sort_values("서비스_업종_코드")
    )

    industry_sets[year] = set(
        industry_table["서비스_업종_코드"]
    )

    print(f"\n[{year}] 업종 수: {len(industry_table)}")
    display(industry_table)


# 연도 간 차이
for year in [2023, 2024, 2025]:

    removed = industry_sets[2022] - industry_sets[year]
    added = industry_sets[year] - industry_sets[2022]

    print(f"\n=== 2022 vs {year} ===")

    print("2022에는 있지만 해당 연도에는 없는 업종:")

    display(
        gangnam_dfs[2022][
            gangnam_dfs[2022]["서비스_업종_코드"].isin(removed)
        ][
            ["서비스_업종_코드", "서비스_업종_코드_명"]
        ].drop_duplicates()
    )

    print("해당 연도에 새로 존재하는 업종:")

    display(
        gangnam_dfs[year][
            gangnam_dfs[year]["서비스_업종_코드"].isin(added)
        ][
            ["서비스_업종_코드", "서비스_업종_코드_명"]
        ].drop_duplicates()
    )

[2022] 업종 수: 63

      서비스_업종_코드 서비스_업종_코드_명
14607  CS100001       한식음식점
14608  CS100002       중식음식점
14609  CS100003       일식음식점
14610  CS100004       양식음식점
14611  CS100005         제과점
...         ...         ...
14660  CS300032        가전제품
14661  CS300033         철물점
14662  CS300035        인테리어
14720  CS300036        조명용품
14663  CS300043      전자상거래업

[63 rows x 2 columns]

[2023] 업종 수: 63

      서비스_업종_코드 서비스_업종_코드_명
14439  CS100001       한식음식점
14440  CS100002       중식음식점
14441  CS100003       일식음식점
14442  CS100004       양식음식점
14443  CS100005         제과점
...         ...         ...
14490  CS300032        가전제품
14491  CS300033         철물점
14492  CS300035        인테리어
14549  CS300036        조명용품
14493  CS300043      전자상거래업

[63 rows x 2 columns]

[2024] 업종 수: 62

      서비스_업종_코드 서비스_업종_코드_명
14298  CS100001       한식음식점
14299  CS100002       중식음식점
14300  CS100003       일식음식점
14301  CS100004       양식음식점
14302  CS100005         제과점
...         ...         ...
14351  CS300032        가전제품
14352  CS300033         철물점
14353  CS300035        인테리어
14411  CS300036        조명용품
14354  CS300043      전자상거래업

[62 rows x 2 columns]

[2025] 업종 수: 62

      서비스_업종_코드 서비스_업종_코드_명
14060  CS100001       한식음식점
14061  CS100002       중식음식점
14062  CS100003       일식음식점
14063  CS100004       양식음식점
14064  CS100005         제과점
...         ...         ...
14112  CS300032        가전제품
14113  CS300033         철물점
14168  CS300035        인테리어
14169  CS300036        조명용품
14114  CS300043      전자상거래업

[62 rows x 2 columns]

=== 2022 vs 2023 ===
2022에는 있지만 해당 연도에는 없는 업종:

Empty DataFrame
Columns: [서비스_업종_코드, 서비스_업종_코드_명]
Index: []

해당 연도에 새로 존재하는 업종:

Empty DataFrame
Columns: [서비스_업종_코드, 서비스_업종_코드_명]
Index: []

=== 2022 vs 2024 ===
2022에는 있지만 해당 연도에는 없는 업종:

      서비스_업종_코드 서비스_업종_코드_명
15147  CS200036         고시원

해당 연도에 새로 존재하는 업종:

Empty DataFrame
Columns: [서비스_업종_코드, 서비스_업종_코드_명]
Index: []

=== 2022 vs 2025 ===
2022에는 있지만 해당 연도에는 없는 업종:

      서비스_업종_코드 서비스_업종_코드_명
15147  CS200036         고시원

해당 연도에 새로 존재하는 업종:

Empty DataFrame
Columns: [서비스_업종_코드, 서비스_업종_코드_명]
Index: []

In [20]:
# ============================================================
# 12. 주요 행동신호 지역의 업종 관측 안정성
# ============================================================

target_dongs = [
    "개포3동",
    "일원본동",
    "일원1동",
    "신사동"
]

all_gangnam = pd.concat(
    gangnam_dfs.values(),
    ignore_index=True
)

coverage_target = (
    all_gangnam[
        all_gangnam["행정동명_표준"].isin(target_dongs)
    ]
    .groupby([
        "행정동명_표준",
        "기준_년분기_코드"
    ])["서비스_업종_코드"]
    .nunique()
    .reset_index(name="관측업종수")
)

pivot_target = coverage_target.pivot(
    index="기준_년분기_코드",
    columns="행정동명_표준",
    values="관측업종수"
)

display(pivot_target)

행정동명_표준    개포3동  신사동  일원1동  일원본동
기준_년분기_코드
20221        20   57    41    17
20222        20   55    42    17
20223        20   55    41    17
20224        20   55    40    17
20231        20   55    41    17
20232        20   56    42    17
20233        19   55    42    16
20234        19   56    41    20
20241        19   57    42    19
20242        19   55    42    18
20243        19   56    42    18
20244        18   55    42    18
20251        18   55    42    17
20252        18   54    41    18
20253        18   56    42    18
20254        19   55    41    18

In [21]:
# ============================================================
# 13. 주요 4개 동 업종의 16분기 관측 지속성 확인
# ============================================================

target_dongs = [
    "개포3동",
    "일원본동",
    "일원1동",
    "신사동"
]

# 업종별로 16개 분기 중 몇 개 분기에 관측됐는지 계산
industry_persistence = (
    all_gangnam[
        all_gangnam["행정동명_표준"].isin(target_dongs)
    ]
    .groupby([
        "행정동명_표준",
        "서비스_업종_코드",
        "서비스_업종_코드_명"
    ])["기준_년분기_코드"]
    .nunique()
    .reset_index(name="관측분기수")
)

# 각 동별 분포
for dong in target_dongs:

    temp = industry_persistence[
        industry_persistence["행정동명_표준"] == dong
    ].sort_values(
        ["관측분기수", "서비스_업종_코드"],
        ascending=[False, True]
    )

    print("\n" + "=" * 65)
    print(dong)
    print("=" * 65)

    print("한 번이라도 등장한 업종:", len(temp))
    print("16분기 모두 관측:", (temp["관측분기수"] == 16).sum())
    print("12분기 이상 관측:", (temp["관측분기수"] >= 12).sum())
    print("8분기 이상 관측:", (temp["관측분기수"] >= 8).sum())

    display(temp)

=================================================================
개포3동
=================================================================
한 번이라도 등장한 업종: 21
16분기 모두 관측: 18
12분기 이상 관측: 18
8분기 이상 관측: 19

   행정동명_표준 서비스_업종_코드 서비스_업종_코드_명  관측분기수
0     개포3동  CS100001       한식음식점     16
1     개포3동  CS100002       중식음식점     16
2     개포3동  CS100003       일식음식점     16
4     개포3동  CS100008       분식전문점     16
6     개포3동  CS100010       커피-음료     16
7     개포3동  CS200001      일반교습학원     16
8     개포3동  CS200003        예술학원     16
9     개포3동  CS200005      스포츠 강습     16
10    개포3동  CS200007        치과의원     16
11    개포3동  CS200008         한의원     16
12    개포3동  CS200028         미용실     16
13    개포3동  CS200031         세탁소     16
14    개포3동  CS300001        슈퍼마켓     16
15    개포3동  CS300002         편의점     16
16    개포3동  CS300007        육류판매     16
18    개포3동  CS300021          문구     16
19    개포3동  CS300022         화장품     16
20    개포3동  CS300028          화초     16
17    개포3동  CS300011        일반의류     11
5     개포3동  CS100009     호프-간이주점      6
3     개포3동  CS100005         제과점      1

=================================================================
일원본동
=================================================================
한 번이라도 등장한 업종: 20
16분기 모두 관측: 15
12분기 이상 관측: 16
8분기 이상 관측: 18

    행정동명_표준 서비스_업종_코드 서비스_업종_코드_명  관측분기수
123    일원본동  CS100001       한식음식점     16
124    일원본동  CS100006      패스트푸드점     16
125    일원본동  CS100007       치킨전문점     16
126    일원본동  CS100010       커피-음료     16
127    일원본동  CS200001      일반교습학원     16
129    일원본동  CS200003        예술학원     16
130    일원본동  CS200007        치과의원     16
131    일원본동  CS200017       골프연습장     16
133    일원본동  CS200028         미용실     16
135    일원본동  CS200031         세탁소     16
136    일원본동  CS300001        슈퍼마켓     16
137    일원본동  CS300002         편의점     16
140    일원본동  CS300016          안경     16
141    일원본동  CS300019        의료기기     16
142    일원본동  CS300028          화초     16
139    일원본동  CS300011        일반의류     15
132    일원본동  CS200024       스포츠클럽      9
138    일원본동  CS300010        반찬가게      8
134    일원본동  CS200030       피부관리실      7
128    일원본동  CS200002       외국어학원      3

=================================================================
일원1동
=================================================================
한 번이라도 등장한 업종: 44
16분기 모두 관측: 38
12분기 이상 관측: 40
8분기 이상 관측: 42

    행정동명_표준 서비스_업종_코드 서비스_업종_코드_명  관측분기수
79     일원1동  CS100001       한식음식점     16
80     일원1동  CS100002       중식음식점     16
81     일원1동  CS100003       일식음식점     16
82     일원1동  CS100004       양식음식점     16
83     일원1동  CS100005         제과점     16
84     일원1동  CS100006      패스트푸드점     16
85     일원1동  CS100007       치킨전문점     16
86     일원1동  CS100008       분식전문점     16
87     일원1동  CS100009     호프-간이주점     16
88     일원1동  CS100010       커피-음료     16
89     일원1동  CS200001      일반교습학원     16
90     일원1동  CS200003        예술학원     16
91     일원1동  CS200005      스포츠 강습     16
92     일원1동  CS200006        일반의원     16
93     일원1동  CS200007        치과의원     16
94     일원1동  CS200008         한의원     16
95     일원1동  CS200016         당구장     16
96     일원1동  CS200019         PC방     16
98     일원1동  CS200025       자동차수리     16
100    일원1동  CS200028         미용실     16
102    일원1동  CS200031         세탁소     16
103    일원1동  CS200032      가전제품수리     16
104    일원1동  CS200037         노래방     16
105    일원1동  CS300001        슈퍼마켓     16
106    일원1동  CS300002         편의점     16
107    일원1동  CS300004         핸드폰     16
108    일원1동  CS300007        육류판매     16
109    일원1동  CS300009         청과상     16
110    일원1동  CS300010        반찬가게     16
111    일원1동  CS300011        일반의류     16
112    일원1동  CS300016          안경     16
113    일원1동  CS300017      시계및귀금속     16
114    일원1동  CS300018         의약품     16
115    일원1동  CS300019        의료기기     16
117    일원1동  CS300021          문구     16
118    일원1동  CS300022         화장품     16
120    일원1동  CS300028          화초     16
121    일원1동  CS300033         철물점     16
101    일원1동  CS200030       피부관리실     14
122    일원1동  CS300035        인테리어     13
119    일원1동  CS300024     운동/경기용품     11
99     일원1동  CS200026       자동차미용     10
116    일원1동  CS300020          서적      6
97     일원1동  CS200024       스포츠클럽      2

=================================================================
신사동
=================================================================
한 번이라도 등장한 업종: 58
16분기 모두 관측: 52
12분기 이상 관측: 53
8분기 이상 관측: 57

   행정동명_표준 서비스_업종_코드   서비스_업종_코드_명  관측분기수
21     신사동  CS100001         한식음식점     16
22     신사동  CS100002         중식음식점     16
23     신사동  CS100003         일식음식점     16
24     신사동  CS100004         양식음식점     16
25     신사동  CS100005           제과점     16
26     신사동  CS100006        패스트푸드점     16
27     신사동  CS100007         치킨전문점     16
28     신사동  CS100008         분식전문점     16
29     신사동  CS100009       호프-간이주점     16
30     신사동  CS100010         커피-음료     16
31     신사동  CS200001        일반교습학원     16
32     신사동  CS200002         외국어학원     16
33     신사동  CS200003          예술학원     16
34     신사동  CS200005        스포츠 강습     16
35     신사동  CS200006          일반의원     16
36     신사동  CS200007          치과의원     16
37     신사동  CS200008           한의원     16
38     신사동  CS200016           당구장     16
39     신사동  CS200017         골프연습장     16
40     신사동  CS200019           PC방     16
41     신사동  CS200024         스포츠클럽     16
42     신사동  CS200025         자동차수리     16
43     신사동  CS200028           미용실     16
44     신사동  CS200029           네일숍     16
45     신사동  CS200030         피부관리실     16
46     신사동  CS200031           세탁소     16
48     신사동  CS200034            여관     16
49     신사동  CS200037           노래방     16
50     신사동  CS300001          슈퍼마켓     16
51     신사동  CS300002           편의점     16
53     신사동  CS300004           핸드폰     16
54     신사동  CS300006          미곡판매     16
55     신사동  CS300007          육류판매     16
56     신사동  CS300008         수산물판매     16
58     신사동  CS300010          반찬가게     16
59     신사동  CS300011          일반의류     16
60     신사동  CS300014            신발     16
62     신사동  CS300016            안경     16
63     신사동  CS300017        시계및귀금속     16
64     신사동  CS300018           의약품     16
65     신사동  CS300020            서적     16
66     신사동  CS300021            문구     16
67     신사동  CS300022           화장품     16
68     신사동  CS300024       운동/경기용품     16
69     신사동  CS300025  자전거 및 기타운송장비     16
71     신사동  CS300027          섬유제품     16
72     신사동  CS300028            화초     16
73     신사동  CS300029          애완동물     16
74     신사동  CS300031            가구     16
75     신사동  CS300032          가전제품     16
76     신사동  CS300033           철물점     16
78     신사동  CS300043        전자상거래업     16
61     신사동  CS300015            가방     15
70     신사동  CS300026            완구     10
77     신사동  CS300035          인테리어     10
47     신사동  CS200033        부동산중개업      9
52     신사동  CS300003    컴퓨터및주변장치판매      8
57     신사동  CS300009           청과상      3

In [22]:
# ============================================================
# 14. 주요 지역 업종 지속성 요약
# ============================================================

summary = []

for dong in target_dongs:

    temp = industry_persistence[
        industry_persistence["행정동명_표준"] == dong
    ]

    summary.append({
        "행정동": dong,
        "등장업종수": len(temp),
        "16분기_모두관측": (temp["관측분기수"] == 16).sum(),
        "12분기이상": (temp["관측분기수"] >= 12).sum(),
        "8분기이상": (temp["관측분기수"] >= 8).sum(),
        "4분기미만": (temp["관측분기수"] < 4).sum()
    })

persistence_summary = pd.DataFrame(summary)

display(persistence_summary)

    행정동  등장업종수  16분기_모두관측  12분기이상  8분기이상  4분기미만
0  개포3동     21         18      18     19      1
1  일원본동     20         15      16     18      1
2  일원1동     44         38      40     42      1
3   신사동     58         52      53     57      1

In [23]:
# ============================================================
# 15. 2025년 62개 업종 전체 목록 확인
# ============================================================

industry_2025 = (
    gangnam_dfs[2025][
        ["서비스_업종_코드", "서비스_업종_코드_명"]
    ]
    .drop_duplicates()
    .sort_values("서비스_업종_코드")
    .reset_index(drop=True)
)

pd.set_option("display.max_rows", None)

display(industry_2025)

   서비스_업종_코드   서비스_업종_코드_명
0   CS100001         한식음식점
1   CS100002         중식음식점
2   CS100003         일식음식점
3   CS100004         양식음식점
4   CS100005           제과점
5   CS100006        패스트푸드점
6   CS100007         치킨전문점
7   CS100008         분식전문점
8   CS100009       호프-간이주점
9   CS100010         커피-음료
10  CS200001        일반교습학원
11  CS200002         외국어학원
12  CS200003          예술학원
13  CS200005        스포츠 강습
14  CS200006          일반의원
15  CS200007          치과의원
16  CS200008           한의원
17  CS200016           당구장
18  CS200017         골프연습장
19  CS200019           PC방
20  CS200024         스포츠클럽
21  CS200025         자동차수리
22  CS200026         자동차미용
23  CS200028           미용실
24  CS200029           네일숍
25  CS200030         피부관리실
26  CS200031           세탁소
27  CS200032        가전제품수리
28  CS200033        부동산중개업
29  CS200034            여관
30  CS200037           노래방
31  CS300001          슈퍼마켓
32  CS300002           편의점
33  CS300003    컴퓨터및주변장치판매
34  CS300004           핸드폰
35  CS300006          미곡판매
36  CS300007          육류판매
37  CS300008         수산물판매
38  CS300009           청과상
39  CS300010          반찬가게
40  CS300011          일반의류
41  CS300014            신발
42  CS300015            가방
43  CS300016            안경
44  CS300017        시계및귀금속
45  CS300018           의약품
46  CS300019          의료기기
47  CS300020            서적
48  CS300021            문구
49  CS300022           화장품
50  CS300024       운동/경기용품
51  CS300025  자전거 및 기타운송장비
52  CS300026            완구
53  CS300027          섬유제품
54  CS300028            화초
55  CS300029          애완동물
56  CS300031            가구
57  CS300032          가전제품
58  CS300033           철물점
59  CS300035          인테리어
60  CS300036          조명용품
61  CS300043        전자상거래업

In [24]:
# ============================================================
# 16. 전체 매출건수 vs 연령별 매출건수 합 검증
# ============================================================

age_count_cols = [
    "연령대_10_매출_건수",
    "연령대_20_매출_건수",
    "연령대_30_매출_건수",
    "연령대_40_매출_건수",
    "연령대_50_매출_건수",
    "연령대_60_이상_매출_건수"
]

check_df = all_gangnam.copy()

check_df["연령별_매출건수_합"] = (
    check_df[age_count_cols].sum(axis=1)
)

check_df["연령합_대비_전체_비율"] = (
    check_df["연령별_매출건수_합"]
    / check_df["당월_매출_건수"].replace(0, pd.NA)
)

print("전체 행:", len(check_df))

print("\n[연령별 합 / 전체 매출건수]")
print(
    check_df["연령합_대비_전체_비율"]
    .describe(
        percentiles=[0.01, 0.05, 0.25, 0.5, 0.75, 0.95, 0.99]
    )
)

print("\n전체 매출건수 0인 행:",
      (check_df["당월_매출_건수"] == 0).sum())

print("연령별 합이 전체보다 큰 행:",
      (
          check_df["연령별_매출건수_합"]
          > check_df["당월_매출_건수"]
      ).sum())

전체 행: 15164

[연령별 합 / 전체 매출건수]
count    15164.000000
mean         0.919311
std          0.108591
min          0.049515
1%           0.514695
5%           0.709142
25%          0.878355
50%          0.964087
75%          0.997469
95%          1.000000
99%          1.000000
max          1.111111
Name: 연령합_대비_전체_비율, dtype: float64

전체 매출건수 0인 행: 0
연령별 합이 전체보다 큰 행: 25

In [25]:
check_df["연도"] = (
    check_df["기준_년분기_코드"]
    .astype(str)
    .str[:4]
    .astype(int)
)

year_check = (
    check_df
    .groupby("연도")
    .agg(
        전체매출건수=("당월_매출_건수", "sum"),
        연령별매출건수합=("연령별_매출건수_합", "sum")
    )
)

year_check["연령포착비율"] = (
    year_check["연령별매출건수합"]
    / year_check["전체매출건수"]
)

display(year_check)

         전체매출건수   연령별매출건수합    연령포착비율
연도
2022  390097864  362542682  0.929363
2023  394731966  366248410  0.927841
2024  376181238  347657835  0.924176
2025  355628746  328142062  0.922710

In [26]:
# ============================================================
# 17. Analysis 3-A 소비영역 분류
# ============================================================

consumption_domain = {

    # A. 외식·카페
    "CS100001": "A_외식카페",
    "CS100002": "A_외식카페",
    "CS100003": "A_외식카페",
    "CS100004": "A_외식카페",
    "CS100005": "A_외식카페",
    "CS100006": "A_외식카페",
    "CS100007": "A_외식카페",
    "CS100008": "A_외식카페",
    "CS100009": "A_외식카페",
    "CS100010": "A_외식카페",

    # B. 여가·운동
    "CS200005": "B_여가운동",
    "CS200016": "B_여가운동",
    "CS200017": "B_여가운동",
    "CS200019": "B_여가운동",
    "CS200024": "B_여가운동",
    "CS200037": "B_여가운동",

    # C. 대면 생활서비스
    "CS200028": "C_대면생활서비스",
    "CS200029": "C_대면생활서비스",
    "CS200030": "C_대면생활서비스",
    "CS200031": "C_대면생활서비스",

    # D. 생활필수 소비
    "CS300001": "D_생활필수",
    "CS300002": "D_생활필수",
    "CS300006": "D_생활필수",
    "CS300007": "D_생활필수",
    "CS300008": "D_생활필수",
    "CS300009": "D_생활필수",
    "CS300010": "D_생활필수",

    # E. 의료·건강
    "CS200006": "E_의료건강",
    "CS200007": "E_의료건강",
    "CS200008": "E_의료건강",
    "CS300018": "E_의료건강",
    "CS300019": "E_의료건강"
}

analysis3 = all_gangnam.copy()

analysis3["소비영역"] = (
    analysis3["서비스_업종_코드"]
    .map(consumption_domain)
)

print("전체 행:", len(analysis3))
print("Core 영역 포함 행:", analysis3["소비영역"].notna().sum())
print("분석 제외/보조 행:", analysis3["소비영역"].isna().sum())

print("\n영역별 업종 수")
display(
    analysis3[
        analysis3["소비영역"].notna()
    ]
    .groupby("소비영역")["서비스_업종_코드"]
    .nunique()
)

전체 행: 15164
Core 영역 포함 행: 9268
분석 제외/보조 행: 5896

영역별 업종 수

소비영역
A_외식카페       10
B_여가운동        6
C_대면생활서비스     4
D_생활필수        7
E_의료건강        5
Name: 서비스_업종_코드, dtype: int64

In [27]:
# ============================================================
# 18. 주요 4개 동 × 소비영역 관측 지속성
# ============================================================

core = analysis3[
    analysis3["소비영역"].notna()
].copy()

domain_coverage = (
    core[
        core["행정동명_표준"].isin(
            ["개포3동", "일원본동", "일원1동", "신사동"]
        )
    ]
    .groupby([
        "행정동명_표준",
        "기준_년분기_코드",
        "소비영역"
    ])["서비스_업종_코드"]
    .nunique()
    .reset_index(name="관측업종수")
)

for dong in ["개포3동", "일원본동", "일원1동", "신사동"]:

    print("\n" + "=" * 65)
    print(dong)
    print("=" * 65)

    temp = domain_coverage[
        domain_coverage["행정동명_표준"] == dong
    ]

    pivot = temp.pivot(
        index="기준_년분기_코드",
        columns="소비영역",
        values="관측업종수"
    )

    display(pivot)

=================================================================
개포3동
=================================================================

소비영역       A_외식카페  B_여가운동  C_대면생활서비스  D_생활필수  E_의료건강
기준_년분기_코드
20221           6       1          2       3       2
20222           6       1          2       3       2
20223           6       1          2       3       2
20224           6       1          2       3       2
20231           6       1          2       3       2
20232           6       1          2       3       2
20233           5       1          2       3       2
20234           5       1          2       3       2
20241           5       1          2       3       2
20242           5       1          2       3       2
20243           5       1          2       3       2
20244           5       1          2       3       2
20251           5       1          2       3       2
20252           5       1          2       3       2
20253           5       1          2       3       2
20254           6       1          2       3       2

=================================================================
일원본동
=================================================================

소비영역       A_외식카페  B_여가운동  C_대면생활서비스  D_생활필수  E_의료건강
기준_년분기_코드
20221           4       1          2       3       2
20222           4       1          2       3       2
20223           4       1          2       3       2
20224           4       1          2       3       2
20231           4       1          2       3       2
20232           4       1          2       3       2
20233           4       1          2       3       2
20234           4       2          3       3       2
20241           4       2          3       2       2
20242           4       2          2       2       2
20243           4       2          3       2       2
20244           4       2          3       2       2
20251           4       2          2       2       2
20252           4       2          3       2       2
20253           4       2          3       2       2
20254           4       2          3       2       2

=================================================================
일원1동
=================================================================

소비영역       A_외식카페  B_여가운동  C_대면생활서비스  D_생활필수  E_의료건강
기준_년분기_코드
20221          10       4          3       5       5
20222          10       4          3       5       5
20223          10       4          3       5       5
20224          10       4          2       5       5
20231          10       4          3       5       5
20232          10       4          3       5       5
20233          10       4          3       5       5
20234          10       4          2       5       5
20241          10       4          3       5       5
20242          10       4          3       5       5
20243          10       4          3       5       5
20244          10       4          3       5       5
20251          10       4          3       5       5
20252          10       4          3       5       5
20253          10       5          3       5       5
20254          10       5          3       5       5

=================================================================
신사동
=================================================================

소비영역       A_외식카페  B_여가운동  C_대면생활서비스  D_생활필수  E_의료건강
기준_년분기_코드
20221          10       6          4       7       4
20222          10       6          4       6       4
20223          10       6          4       6       4
20224          10       6          4       6       4
20231          10       6          4       6       4
20232          10       6          4       6       4
20233          10       6          4       6       4
20234          10       6          4       6       4
20241          10       6          4       6       4
20242          10       6          4       6       4
20243          10       6          4       6       4
20244          10       6          4       6       4
20251          10       6          4       6       4
20252          10       6          4       6       4
20253          10       6          4       7       4
20254          10       6          4       7       4

In [28]:
# ============================================================
# 19. Analysis 3-A
# 행정동 × 분기 × 연령 × 소비영역 Feature Table 생성
# ============================================================

age_map = {
    "연령대_10_매출_건수": "10대",
    "연령대_20_매출_건수": "20대",
    "연령대_30_매출_건수": "30대",
    "연령대_40_매출_건수": "40대",
    "연령대_50_매출_건수": "50대",
    "연령대_60_이상_매출_건수": "60대이상"
}

# Core 소비영역만
core = analysis3[
    analysis3["소비영역"].notna()
].copy()

# wide → long
age_long = core.melt(
    id_vars=[
        "기준_년분기_코드",
        "행정동_코드",
        "행정동명_표준",
        "서비스_업종_코드",
        "서비스_업종_코드_명",
        "소비영역"
    ],
    value_vars=list(age_map.keys()),
    var_name="연령컬럼",
    value_name="매출건수"
)

age_long["연령대"] = (
    age_long["연령컬럼"].map(age_map)
)

# 영역 단위 집계
age_domain = (
    age_long
    .groupby([
        "기준_년분기_코드",
        "행정동_코드",
        "행정동명_표준",
        "연령대",
        "소비영역"
    ], as_index=False)
    .agg(
        매출건수=("매출건수", "sum"),
        관측업종수=("서비스_업종_코드", "nunique")
    )
)

print("shape:", age_domain.shape)
print("행정동:", age_domain["행정동명_표준"].nunique())
print("분기:", age_domain["기준_년분기_코드"].nunique())
print("연령대:", age_domain["연령대"].nunique())
print("소비영역:", age_domain["소비영역"].nunique())

print(
    "key 중복:",
    age_domain.duplicated(
        subset=[
            "기준_년분기_코드",
            "행정동_코드",
            "연령대",
            "소비영역"
        ]
    ).sum()
)

print("결측:", age_domain.isna().sum().sum())

shape: (10320, 7)
행정동: 22
분기: 16
연령대: 6
소비영역: 5
key 중복: 0
결측: 0

In [29]:
# ============================================================
# 20. 주요 지역 2025 Q3/Q4 데이터 확인
# ============================================================

target_check = age_domain[
    (age_domain["행정동명_표준"].isin(
        ["개포3동", "일원본동", "일원1동", "신사동"]
    ))
    &
    (age_domain["기준_년분기_코드"].isin(
        [20253, 20254]
    ))
].copy()

print("행 수:", len(target_check))

display(
    target_check.sort_values([
        "행정동명_표준",
        "기준_년분기_코드",
        "연령대",
        "소비영역"
    ])
)

행 수: 240

       기준_년분기_코드    행정동_코드 행정동명_표준    연령대       소비영역    매출건수  관측업종수
9612       20253  11680740    개포3동    10대     A_외식카페     149      5
9613       20253  11680740    개포3동    10대     B_여가운동       0      1
9614       20253  11680740    개포3동    10대  C_대면생활서비스       0      2
9615       20253  11680740    개포3동    10대     D_생활필수    3440      3
9616       20253  11680740    개포3동    10대     E_의료건강       0      2
9617       20253  11680740    개포3동    20대     A_외식카페    4448      5
9618       20253  11680740    개포3동    20대     B_여가운동       0      1
9619       20253  11680740    개포3동    20대  C_대면생활서비스     143      2
9620       20253  11680740    개포3동    20대     D_생활필수   23181      3
9621       20253  11680740    개포3동    20대     E_의료건강     112      2
9622       20253  11680740    개포3동    30대     A_외식카페   13498      5
9623       20253  11680740    개포3동    30대     B_여가운동      51      1
9624       20253  11680740    개포3동    30대  C_대면생활서비스     369      2
9625       20253  11680740    개포3동    30대     D_생활필수   70184      3
9626       20253  11680740    개포3동    30대     E_의료건강     531      2
9627       20253  11680740    개포3동    40대     A_외식카페   10133      5
9628       20253  11680740    개포3동    40대     B_여가운동     430      1
9629       20253  11680740    개포3동    40대  C_대면생활서비스     488      2
9630       20253  11680740    개포3동    40대     D_생활필수   72934      3
9631       20253  11680740    개포3동    40대     E_의료건강    1459      2
9632       20253  11680740    개포3동    50대     A_외식카페    8107      5
9633       20253  11680740    개포3동    50대     B_여가운동      49      1
9634       20253  11680740    개포3동    50대  C_대면생활서비스     670      2
9635       20253  11680740    개포3동    50대     D_생활필수   47141      3
9636       20253  11680740    개포3동    50대     E_의료건강    1438      2
9637       20253  11680740    개포3동  60대이상     A_외식카페    5952      5
9638       20253  11680740    개포3동  60대이상     B_여가운동       5      1
9639       20253  11680740    개포3동  60대이상  C_대면생활서비스     588      2
9640       20253  11680740    개포3동  60대이상     D_생활필수   41709      3
9641       20253  11680740    개포3동  60대이상     E_의료건강    1797      2
10260      20254  11680740    개포3동    10대     A_외식카페     183      6
10261      20254  11680740    개포3동    10대     B_여가운동       0      1
10262      20254  11680740    개포3동    10대  C_대면생활서비스       7      2
10263      20254  11680740    개포3동    10대     D_생활필수    3215      3
10264      20254  11680740    개포3동    10대     E_의료건강      18      2
10265      20254  11680740    개포3동    20대     A_외식카페    3807      6
10266      20254  11680740    개포3동    20대     B_여가운동       0      1
10267      20254  11680740    개포3동    20대  C_대면생활서비스     212      2
10268      20254  11680740    개포3동    20대     D_생활필수   20700      3
10269      20254  11680740    개포3동    20대     E_의료건강     147      2
10270      20254  11680740    개포3동    30대     A_외식카페   10680      6
10271      20254  11680740    개포3동    30대     B_여가운동      19      1
10272      20254  11680740    개포3동    30대  C_대면생활서비스     278      2
10273      20254  11680740    개포3동    30대     D_생활필수   60292      3
10274      20254  11680740    개포3동    30대     E_의료건강     620      2
10275      20254  11680740    개포3동    40대     A_외식카페    8351      6
10276      20254  11680740    개포3동    40대     B_여가운동     309      1
10277      20254  11680740    개포3동    40대  C_대면생활서비스     504      2
10278      20254  11680740    개포3동    40대     D_생활필수   61844      3
10279      20254  11680740    개포3동    40대     E_의료건강    1217      2
10280      20254  11680740    개포3동    50대     A_외식카페    6845      6
10281      20254  11680740    개포3동    50대     B_여가운동      28      1
10282      20254  11680740    개포3동    50대  C_대면생활서비스     862      2
10283      20254  11680740    개포3동    50대     D_생활필수   43400      3
10284      20254  11680740    개포3동    50대     E_의료건강     944      2
10285      20254  11680740    개포3동  60대이상     A_외식카페    5131      6
10286      20254  11680740    개포3동  60대이상     B_여가운동       5      1
10287      20254  11680740    개포3동  60대이상  C_대면생활서비스     599      2
10288      20254  11680740    개포3동  60대이상     D_생활필수   37038      3
10289      20254  11680740    개포3동  60대이상     E_의료건강     995      2
9024       20253  11680510     신사동    10대     A_외식카페   29423     10
9025       20253  11680510     신사동    10대     B_여가운동   33861      6
9026       20253  11680510     신사동    10대  C_대면생활서비스     820      4
9027       20253  11680510     신사동    10대     D_생활필수   21859      7
9028       20253  11680510     신사동    10대     E_의료건강    3180      4
9029       20253  11680510     신사동    20대     A_외식카페  387147     10
9030       20253  11680510     신사동    20대     B_여가운동  154358      6
9031       20253  11680510     신사동    20대  C_대면생활서비스   12072      4
9032       20253  11680510     신사동    20대     D_생활필수  181054      7
9033       20253  11680510     신사동    20대     E_의료건강   80008      4
9034       20253  11680510     신사동    30대     A_외식카페  508431     10
9035       20253  11680510     신사동    30대     B_여가운동   76633      6
9036       20253  11680510     신사동    30대  C_대면생활서비스   13660      4
9037       20253  11680510     신사동    30대     D_생활필수  245326      7
9038       20253  11680510     신사동    30대     E_의료건강  122496      4
9039       20253  11680510     신사동    40대     A_외식카페  301538     10
9040       20253  11680510     신사동    40대     B_여가운동   42878      6
9041       20253  11680510     신사동    40대  C_대면생활서비스   10858      4
9042       20253  11680510     신사동    40대     D_생활필수  165996      7
9043       20253  11680510     신사동    40대     E_의료건강  102200      4
9044       20253  11680510     신사동    50대     A_외식카페  253073     10
9045       20253  11680510     신사동    50대     B_여가운동   44262      6
9046       20253  11680510     신사동    50대  C_대면생활서비스   10176      4
9047       20253  11680510     신사동    50대     D_생활필수  140434      7
9048       20253  11680510     신사동    50대     E_의료건강  102332      4
9049       20253  11680510     신사동  60대이상     A_외식카페  153316     10
9050       20253  11680510     신사동  60대이상     B_여가운동    6592      6
9051       20253  11680510     신사동  60대이상  C_대면생활서비스    7254      4
9052       20253  11680510     신사동  60대이상     D_생활필수   85339      7
9053       20253  11680510     신사동  60대이상     E_의료건강  109366      4
9672       20254  11680510     신사동    10대     A_외식카페   24126     10
9673       20254  11680510     신사동    10대     B_여가운동   24778      6
9674       20254  11680510     신사동    10대  C_대면생활서비스     878      4
9675       20254  11680510     신사동    10대     D_생활필수   18457      7
9676       20254  11680510     신사동    10대     E_의료건강    2570      4
9677       20254  11680510     신사동    20대     A_외식카페  364491     10
9678       20254  11680510     신사동    20대     B_여가운동  131201      6
9679       20254  11680510     신사동    20대  C_대면생활서비스   12689      4
9680       20254  11680510     신사동    20대     D_생활필수  159677      7
9681       20254  11680510     신사동    20대     E_의료건강   74943      4
9682       20254  11680510     신사동    30대     A_외식카페  481578     10
9683       20254  11680510     신사동    30대     B_여가운동   67479      6
9684       20254  11680510     신사동    30대  C_대면생활서비스   14542      4
9685       20254  11680510     신사동    30대     D_생활필수  211398      7
9686       20254  11680510     신사동    30대     E_의료건강  116730      4
9687       20254  11680510     신사동    40대     A_외식카페  284526     10
9688       20254  11680510     신사동    40대     B_여가운동   31160      6
9689       20254  11680510     신사동    40대  C_대면생활서비스    9602      4
9690       20254  11680510     신사동    40대     D_생활필수  145277      7
9691       20254  11680510     신사동    40대     E_의료건강  104182      4
9692       20254  11680510     신사동    50대     A_외식카페  241823     10
9693       20254  11680510     신사동    50대     B_여가운동   34575      6
9694       20254  11680510     신사동    50대  C_대면생활서비스   10145      4
9695       20254  11680510     신사동    50대     D_생활필수  125214      7
9696       20254  11680510     신사동    50대     E_의료건강  104703      4
9697       20254  11680510     신사동  60대이상     A_외식카페  146454     10
9698       20254  11680510     신사동  60대이상     B_여가운동    6349      6
9699       20254  11680510     신사동  60대이상  C_대면생활서비스    7453      4
9700       20254  11680510     신사동  60대이상     D_생활필수   76848      7
9701       20254  11680510     신사동  60대이상     E_의료건강  113108      4
9582       20253  11680730    일원1동    10대     A_외식카페    5010     10
9583       20253  11680730    일원1동    10대     B_여가운동   10958      5
9584       20253  11680730    일원1동    10대  C_대면생활서비스     119      3
9585       20253  11680730    일원1동    10대     D_생활필수    2164      5
9586       20253  11680730    일원1동    10대     E_의료건강    1303      5
9587       20253  11680730    일원1동    20대     A_외식카페   46077     10
9588       20253  11680730    일원1동    20대     B_여가운동   29436      5
9589       20253  11680730    일원1동    20대  C_대면생활서비스    1715      3
9590       20253  11680730    일원1동    20대     D_생활필수   38687      5
9591       20253  11680730    일원1동    20대     E_의료건강   15774      5
9592       20253  11680730    일원1동    30대     A_외식카페   91007     10
9593       20253  11680730    일원1동    30대     B_여가운동   22237      5
9594       20253  11680730    일원1동    30대  C_대면생활서비스    3477      3
9595       20253  11680730    일원1동    30대     D_생활필수   65546      5
9596       20253  11680730    일원1동    30대     E_의료건강   49746      5
9597       20253  11680730    일원1동    40대     A_외식카페  108756     10
9598       20253  11680730    일원1동    40대     B_여가운동   13569      5
9599       20253  11680730    일원1동    40대  C_대면생활서비스    5038      3
9600       20253  11680730    일원1동    40대     D_생활필수   66126      5
9601       20253  11680730    일원1동    40대     E_의료건강   77837      5
9602       20253  11680730    일원1동    50대     A_외식카페   99770     10
9603       20253  11680730    일원1동    50대     B_여가운동   10583      5
9604       20253  11680730    일원1동    50대  C_대면생활서비스    4023      3
9605       20253  11680730    일원1동    50대     D_생활필수   55136      5
9606       20253  11680730    일원1동    50대     E_의료건강   66925      5
9607       20253  11680730    일원1동  60대이상     A_외식카페  106966     10
9608       20253  11680730    일원1동  60대이상     B_여가운동    3790      5
9609       20253  11680730    일원1동  60대이상  C_대면생활서비스    3322      3
9610       20253  11680730    일원1동  60대이상     D_생활필수   36554      5
9611       20253  11680730    일원1동  60대이상     E_의료건강  117162      5
10230      20254  11680730    일원1동    10대     A_외식카페    5642     10
10231      20254  11680730    일원1동    10대     B_여가운동    9754      5
10232      20254  11680730    일원1동    10대  C_대면생활서비스      95      3
10233      20254  11680730    일원1동    10대     D_생활필수    2701      5
10234      20254  11680730    일원1동    10대     E_의료건강    1453      5
10235      20254  11680730    일원1동    20대     A_외식카페   41890     10
10236      20254  11680730    일원1동    20대     B_여가운동   22771      5
10237      20254  11680730    일원1동    20대  C_대면생활서비스    1558      3
10238      20254  11680730    일원1동    20대     D_생활필수   33044      5
10239      20254  11680730    일원1동    20대     E_의료건강   19168      5
10240      20254  11680730    일원1동    30대     A_외식카페   83838     10
10241      20254  11680730    일원1동    30대     B_여가운동   22012      5
10242      20254  11680730    일원1동    30대  C_대면생활서비스    2925      3
10243      20254  11680730    일원1동    30대     D_생활필수   57842      5
10244      20254  11680730    일원1동    30대     E_의료건강   51765      5
10245      20254  11680730    일원1동    40대     A_외식카페   98011     10
10246      20254  11680730    일원1동    40대     B_여가운동   16025      5
10247      20254  11680730    일원1동    40대  C_대면생활서비스    4621      3
10248      20254  11680730    일원1동    40대     D_생활필수   57071      5
10249      20254  11680730    일원1동    40대     E_의료건강   86722      5
10250      20254  11680730    일원1동    50대     A_외식카페   90518     10
10251      20254  11680730    일원1동    50대     B_여가운동   12237      5
10252      20254  11680730    일원1동    50대  C_대면생활서비스    4540      3
10253      20254  11680730    일원1동    50대     D_생활필수   50912      5
10254      20254  11680730    일원1동    50대     E_의료건강   68994      5
10255      20254  11680730    일원1동  60대이상     A_외식카페   99960     10
10256      20254  11680730    일원1동  60대이상     B_여가운동    6876      5
10257      20254  11680730    일원1동  60대이상  C_대면생활서비스    3299      3
10258      20254  11680730    일원1동  60대이상     D_생활필수   39065      5
10259      20254  11680730    일원1동  60대이상     E_의료건강  127908      5
9552       20253  11680720    일원본동    10대     A_외식카페     494      4
9553       20253  11680720    일원본동    10대     B_여가운동     110      2
9554       20253  11680720    일원본동    10대  C_대면생활서비스     144      3
9555       20253  11680720    일원본동    10대     D_생활필수    6075      2
9556       20253  11680720    일원본동    10대     E_의료건강      17      2
9557       20253  11680720    일원본동    20대     A_외식카페    7937      4
9558       20253  11680720    일원본동    20대     B_여가운동     235      2
9559       20253  11680720    일원본동    20대  C_대면생활서비스     452      3
9560       20253  11680720    일원본동    20대     D_생활필수  148519      2
9561       20253  11680720    일원본동    20대     E_의료건강     272      2
9562       20253  11680720    일원본동    30대     A_외식카페   15365      4
9563       20253  11680720    일원본동    30대     B_여가운동     979      2
9564       20253  11680720    일원본동    30대  C_대면생활서비스     942      3
9565       20253  11680720    일원본동    30대     D_생활필수  332713      2
9566       20253  11680720    일원본동    30대     E_의료건강    1432      2
9567       20253  11680720    일원본동    40대     A_외식카페   24867      4
9568       20253  11680720    일원본동    40대     B_여가운동    2034      2
9569       20253  11680720    일원본동    40대  C_대면생활서비스    2949      3
9570       20253  11680720    일원본동    40대     D_생활필수  333858      2
9571       20253  11680720    일원본동    40대     E_의료건강    3579      2
9572       20253  11680720    일원본동    50대     A_외식카페   23536      4
9573       20253  11680720    일원본동    50대     B_여가운동    2416      2
9574       20253  11680720    일원본동    50대  C_대면생활서비스    2968      3
9575       20253  11680720    일원본동    50대     D_생활필수  275139      2
9576       20253  11680720    일원본동    50대     E_의료건강    3256      2
9577       20253  11680720    일원본동  60대이상     A_외식카페   28169      4
9578       20253  11680720    일원본동  60대이상     B_여가운동    2812      2
9579       20253  11680720    일원본동  60대이상  C_대면생활서비스    2263      3
9580       20253  11680720    일원본동  60대이상     D_생활필수  259758      2
9581       20253  11680720    일원본동  60대이상     E_의료건강    6178      2
10200      20254  11680720    일원본동    10대     A_외식카페     725      4
10201      20254  11680720    일원본동    10대     B_여가운동     190      2
10202      20254  11680720    일원본동    10대  C_대면생활서비스     102      3
10203      20254  11680720    일원본동    10대     D_생활필수    4892      2
10204      20254  11680720    일원본동    10대     E_의료건강       8      2
10205      20254  11680720    일원본동    20대     A_외식카페    6182      4
10206      20254  11680720    일원본동    20대     B_여가운동     173      2
10207      20254  11680720    일원본동    20대  C_대면생활서비스     343      3
10208      20254  11680720    일원본동    20대     D_생활필수  153674      2
10209      20254  11680720    일원본동    20대     E_의료건강     389      2
10210      20254  11680720    일원본동    30대     A_외식카페   15586      4
10211      20254  11680720    일원본동    30대     B_여가운동     358      2
10212      20254  11680720    일원본동    30대  C_대면생활서비스     836      3
10213      20254  11680720    일원본동    30대     D_생활필수  304082      2
10214      20254  11680720    일원본동    30대     E_의료건강    1312      2
10215      20254  11680720    일원본동    40대     A_외식카페   21210      4
10216      20254  11680720    일원본동    40대     B_여가운동    1134      2
10217      20254  11680720    일원본동    40대  C_대면생활서비스    2260      3
10218      20254  11680720    일원본동    40대     D_생활필수  308150      2
10219      20254  11680720    일원본동    40대     E_의료건강    3026      2
10220      20254  11680720    일원본동    50대     A_외식카페   23629      4
10221      20254  11680720    일원본동    50대     B_여가운동    1762      2
10222      20254  11680720    일원본동    50대  C_대면생활서비스    3009      3
10223      20254  11680720    일원본동    50대     D_생활필수  265332      2
10224      20254  11680720    일원본동    50대     E_의료건강    3668      2
10225      20254  11680720    일원본동  60대이상     A_외식카페   24210      4
10226      20254  11680720    일원본동  60대이상     B_여가운동    1566      2
10227      20254  11680720    일원본동  60대이상  C_대면생활서비스    2228      3
10228      20254  11680720    일원본동  60대이상     D_생활필수  244234      2
10229      20254  11680720    일원본동  60대이상     E_의료건강    5869      2

In [30]:
# ============================================================
# 21. 2025 Q3/Q4 vs 2022~2024 동일분기 baseline
# ============================================================

compare = age_domain.copy()

# 연도 / 분기 분리
compare["연도"] = (
    compare["기준_년분기_코드"]
    .astype(str)
    .str[:4]
    .astype(int)
)

compare["분기"] = (
    compare["기준_년분기_코드"]
    .astype(str)
    .str[-1]
    .astype(int)
)

keys = [
    "행정동_코드",
    "행정동명_표준",
    "연령대",
    "소비영역",
    "분기"
]

# ------------------------------------------------------------
# 2022~2024 historical baseline
# ------------------------------------------------------------

baseline = (
    compare[
        (compare["연도"].between(2022, 2024))
        &
        (compare["분기"].isin([3, 4]))
    ]
    .groupby(keys, as_index=False)
    .agg(
        baseline_mean=("매출건수", "mean"),
        baseline_median=("매출건수", "median"),
        baseline_std=("매출건수", "std"),
        baseline_n=("매출건수", "count"),
        baseline_min=("매출건수", "min"),
        baseline_max=("매출건수", "max")
    )
)

# ------------------------------------------------------------
# 2025 Q3/Q4
# ------------------------------------------------------------

current = (
    compare[
        (compare["연도"] == 2025)
        &
        (compare["분기"].isin([3, 4]))
    ][
        keys
        + [
            "기준_년분기_코드",
            "매출건수",
            "관측업종수"
        ]
    ]
    .rename(
        columns={
            "매출건수": "current_count",
            "관측업종수": "current_industry_count"
        }
    )
)

# baseline 결합
card_detection = current.merge(
    baseline,
    on=keys,
    how="left",
    validate="one_to_one"
)

# ------------------------------------------------------------
# 변화량
# ------------------------------------------------------------

card_detection["change_from_mean"] = (
    card_detection["current_count"]
    - card_detection["baseline_mean"]
)

card_detection["change_rate_pct"] = (
    card_detection["change_from_mean"]
    / card_detection["baseline_mean"].replace(0, pd.NA)
    * 100
)

# 과거 범위보다 낮거나 높은지도 확인
card_detection["below_historical_min"] = (
    card_detection["current_count"]
    < card_detection["baseline_min"]
)

card_detection["above_historical_max"] = (
    card_detection["current_count"]
    > card_detection["baseline_max"]
)

print("shape:", card_detection.shape)

print(
    "baseline 3개 연도 모두 존재:",
    (card_detection["baseline_n"] == 3).sum(),
    "/",
    len(card_detection)
)

print(
    "baseline 결측:",
    card_detection["baseline_mean"].isna().sum()
)

print(
    "과거 3개년 최소보다 낮음:",
    card_detection["below_historical_min"].sum()
)

print(
    "과거 3개년 최대보다 높음:",
    card_detection["above_historical_max"].sum()
)

shape: (1296, 18)
baseline 3개 연도 모두 존재: 1284 / 1296
baseline 결측: 0
과거 3개년 최소보다 낮음: 586
과거 3개년 최대보다 높음: 269

In [31]:
# ============================================================
# 22. 주요 4개 지역 baseline 비교 상태 확인
# ============================================================

target_detection = card_detection[
    card_detection["행정동명_표준"].isin(
        ["개포3동", "일원본동", "일원1동", "신사동"]
    )
].copy()

print("주요 4개 지역 행 수:", len(target_detection))

print(
    "baseline_n 분포:"
)
print(
    target_detection["baseline_n"]
    .value_counts(dropna=False)
    .sort_index()
)

print(
    "\n변화율 계산 불가:",
    target_detection["change_rate_pct"].isna().sum()
)

display(
    target_detection[
        [
            "기준_년분기_코드",
            "행정동명_표준",
            "연령대",
            "소비영역",
            "current_count",
            "baseline_mean",
            "baseline_min",
            "baseline_max",
            "baseline_n",
            "change_rate_pct",
            "below_historical_min",
            "above_historical_max"
        ]
    ]
    .sort_values([
        "행정동명_표준",
        "기준_년분기_코드",
        "연령대",
        "소비영역"
    ])
)

주요 4개 지역 행 수: 240
baseline_n 분포:
baseline_n
3    240
Name: count, dtype: int64

변화율 계산 불가: 7

,기준_년분기_코드,행정동명_표준,연령대,소비영역,current_count,baseline_mean,baseline_min,baseline_max,baseline_n,change_rate_pct,below_historical_min,above_historical_max
588,20253,개포3동,10대,A_외식카페,149,286.000000,156,439,3,-47.902098,True,False
589,20253,개포3동,10대,B_여가운동,0,0.000000,0,0,3,<NA>,False,False
590,20253,개포3동,10대,C_대면생활서비스,0,0.000000,0,0,3,<NA>,False,False
591,20253,개포3동,10대,D_생활필수,3440,5617.333333,4421,7309,3,-38.760978,True,False
592,20253,개포3동,10대,E_의료건강,0,15.000000,0,36,3,-100.0,False,False
593,20253,개포3동,20대,A_외식카페,4448,7425.000000,5161,10931,3,-40.094276,True,False
594,20253,개포3동,20대,B_여가운동,0,0.000000,0,0,3,<NA>,False,False
595,20253,개포3동,20대,C_대면생활서비스,143,111.333333,63,187,3,28.443114,False,False
596,20253,개포3동,20대,D_생활필수,23181,32850.666667,28662,37290,3,-29.435222,True,False
597,20253,개포3동,20대,E_의료건강,112,257.666667,161,358,3,-56.532988,True,False
598,20253,개포3동,30대,A_외식카페,13498,16662.666667,13828,21189,3,-18.992558,True,False
599,20253,개포3동,30대,B_여가운동,51,81.666667,56,105,3,-37.55102,True,False
600,20253,개포3동,30대,C_대면생활서비스,369,374.000000,353,398,3,-1.336898,False,False
601,20253,개포3동,30대,D_생활필수,70184,73581.666667,68060,77492,3,-4.617545,False,False
602,20253,개포3동,30대,E_의료건강,531,773.000000,584,1038,3,-31.306598,True,False
603,20253,개포3동,40대,A_외식카페,10133,13325.333333,9382,19446,3,-23.956874,False,False
604,20253,개포3동,40대,B_여가운동,430,376.000000,208,569,3,14.361702,False,False
605,20253,개포3동,40대,C_대면생활서비스,488,682.333333,346,879,3,-28.480703,False,False
606,20253,개포3동,40대,D_생활필수,72934,69570.000000,65399,74689,3,4.835418,False,False
607,20253,개포3동,40대,E_의료건강,1459,1395.000000,1128,1794,3,4.587814,False,False
608,20253,개포3동,50대,A_외식카페,8107,11278.333333,8708,15881,3,-28.118812,True,False
609,20253,개포3동,50대,B_여가운동,49,64.666667,47,80,3,-24.226804,False,False
610,20253,개포3동,50대,C_대면생활서비스,670,876.333333,836,925,3,-23.545074,True,False
611,20253,개포3동,50대,D_생활필수,47141,47860.666667,43613,53515,3,-1.50367,False,False
612,20253,개포3동,50대,E_의료건강,1438,1529.666667,1147,1996,3,-5.992591,False,False
613,20253,개포3동,60대이상,A_외식카페,5952,5954.333333,5159,7330,3,-0.039187,False,False
614,20253,개포3동,60대이상,B_여가운동,5,1.666667,0,5,3,200.0,False,False
615,20253,개포3동,60대이상,C_대면생활서비스,588,414.333333,406,424,3,41.914722,False,True
616,20253,개포3동,60대이상,D_생활필수,41709,29459.666667,20799,37993,3,41.580013,False,True
617,20253,개포3동,60대이상,E_의료건강,1797,2081.666667,1445,2837,3,-13.67494,False,False
1236,20254,개포3동,10대,A_외식카페,183,577.666667,196,1254,3,-68.320831,True,False
1237,20254,개포3동,10대,B_여가운동,0,0.000000,0,0,3,<NA>,False,False
1238,20254,개포3동,10대,C_대면생활서비스,7,0.000000,0,0,3,<NA>,False,True
1239,20254,개포3동,10대,D_생활필수,3215,5448.333333,3926,7206,3,-40.991129,True,False
1240,20254,개포3동,10대,E_의료건강,18,0.000000,0,0,3,<NA>,False,True
1241,20254,개포3동,20대,A_외식카페,3807,6764.333333,3734,10959,3,-43.719509,False,False
1242,20254,개포3동,20대,B_여가운동,0,0.000000,0,0,3,<NA>,False,False
1243,20254,개포3동,20대,C_대면생활서비스,212,181.666667,157,197,3,16.697248,False,True
1244,20254,개포3동,20대,D_생활필수,20700,29672.000000,27195,34050,3,-30.237261,True,False
1245,20254,개포3동,20대,E_의료건강,147,251.666667,173,401,3,-41.589404,True,False
1246,20254,개포3동,30대,A_외식카페,10680,15070.666667,13122,18813,3,-29.133858,True,False
1247,20254,개포3동,30대,B_여가운동,19,94.000000,59,128,3,-79.787234,True,False
1248,20254,개포3동,30대,C_대면생활서비스,278,348.000000,203,474,3,-20.114943,False,False
1249,20254,개포3동,30대,D_생활필수,60292,67286.666667,65151,68547,3,-10.395323,True,False
1250,20254,개포3동,30대,E_의료건강,620,698.333333,496,967,3,-11.217184,False,False
1251,20254,개포3동,40대,A_외식카페,8351,11347.333333,8527,16794,3,-26.405617,True,False
1252,20254,개포3동,40대,B_여가운동,309,410.333333,311,549,3,-24.69537,True,False
1253,20254,개포3동,40대,C_대면생활서비스,504,655.333333,422,868,3,-23.092574,False,False
1254,20254,개포3동,40대,D_생활필수,61844,63086.333333,61357,64570,3,-1.969259,False,False
1255,20254,개포3동,40대,E_의료건강,1217,1284.333333,1105,1638,3,-5.242668,False,False
1256,20254,개포3동,50대,A_외식카페,6845,10827.333333,8120,16050,3,-36.780371,True,False
1257,20254,개포3동,50대,B_여가운동,28,33.333333,24,44,3,-16.0,False,False
1258,20254,개포3동,50대,C_대면생활서비스,862,799.000000,591,989,3,7.884856,False,False
1259,20254,개포3동,50대,D_생활필수,43400,42205.333333,40085,46438,3,2.830606,False,False
1260,20254,개포3동,50대,E_의료건강,944,1169.666667,1006,1279,3,-19.293246,True,False
1261,20254,개포3동,60대이상,A_외식카페,5131,6641.000000,4258,9908,3,-22.73754,False,False
1262,20254,개포3동,60대이상,B_여가운동,5,7.000000,0,16,3,-28.571429,False,False
1263,20254,개포3동,60대이상,C_대면생활서비스,599,421.666667,346,484,3,42.055336,False,True
1264,20254,개포3동,60대이상,D_생활필수,37038,26061.666667,20294,32724,3,42.116774,False,True
1265,20254,개포3동,60대이상,E_의료건강,995,2141.333333,2049,2274,3,-53.533624,True,False
0,20253,신사동,10대,A_외식카페,29423,40173.333333,33910,47759,3,-26.759874,True,False
1,20253,신사동,10대,B_여가운동,33861,25283.333333,16944,37343,3,33.92617,False,False
2,20253,신사동,10대,C_대면생활서비스,820,633.000000,584,672,3,29.541864,False,True
3,20253,신사동,10대,D_생활필수,21859,29310.000000,26054,31297,3,-25.421358,True,False
4,20253,신사동,10대,E_의료건강,3180,3504.666667,3067,4190,3,-9.263839,False,False
5,20253,신사동,20대,A_외식카페,387147,618093.000000,474934,773519,3,-37.36428,True,False
6,20253,신사동,20대,B_여가운동,154358,159373.333333,142562,171111,3,-3.146909,False,False
7,20253,신사동,20대,C_대면생활서비스,12072,12083.333333,10934,13399,3,-0.093793,False,False
8,20253,신사동,20대,D_생활필수,181054,274011.000000,230403,309916,3,-33.92455,True,False
9,20253,신사동,20대,E_의료건강,80008,101384.000000,86491,121805,3,-21.084195,True,False
10,20253,신사동,30대,A_외식카페,508431,595895.333333,532565,649375,3,-14.677801,True,False
11,20253,신사동,30대,B_여가운동,76633,65940.666667,60927,73632,3,16.215082,False,True
12,20253,신사동,30대,C_대면생활서비스,13660,13977.333333,12893,15369,3,-2.270342,False,False
13,20253,신사동,30대,D_생활필수,245326,278221.666667,265608,293191,3,-11.823546,True,False
14,20253,신사동,30대,E_의료건강,122496,135757.333333,127700,147524,3,-9.76841,True,False
15,20253,신사동,40대,A_외식카페,301538,337878.666667,311824,356779,3,-10.755537,True,False
16,20253,신사동,40대,B_여가운동,42878,21653.000000,18931,27001,3,98.023369,False,True
17,20253,신사동,40대,C_대면생활서비스,10858,10805.333333,10214,11977,3,0.487414,False,False
18,20253,신사동,40대,D_생활필수,165996,183984.000000,174836,196429,3,-9.776937,True,False
19,20253,신사동,40대,E_의료건강,102200,112000.000000,103079,119776,3,-8.75,True,False
20,20253,신사동,50대,A_외식카페,253073,270494.666667,259005,276889,3,-6.440669,True,False
21,20253,신사동,50대,B_여가운동,44262,27600.000000,26673,28165,3,60.369565,False,True
22,20253,신사동,50대,C_대면생활서비스,10176,9430.333333,9037,9757,3,7.907108,False,True
23,20253,신사동,50대,D_생활필수,140434,142399.000000,133804,149079,3,-1.379925,False,False
24,20253,신사동,50대,E_의료건강,102332,108693.333333,106461,111340,3,-5.852552,True,False
25,20253,신사동,60대이상,A_외식카페,153316,148149.666667,146100,151114,3,3.487239,False,True
26,20253,신사동,60대이상,B_여가운동,6592,4369.000000,4231,4609,3,50.881209,False,True
27,20253,신사동,60대이상,C_대면생활서비스,7254,6222.666667,5651,6582,3,16.573816,False,True
28,20253,신사동,60대이상,D_생활필수,85339,77948.666667,72386,81372,3,9.481026,False,True
29,20253,신사동,60대이상,E_의료건강,109366,102206.333333,97850,105819,3,7.005111,False,True
648,20254,신사동,10대,A_외식카페,24126,36829.000000,31760,42485,3,-34.491841,True,False
649,20254,신사동,10대,B_여가운동,24778,22577.000000,16908,33766,3,9.748859,False,False
650,20254,신사동,10대,C_대면생활서비스,878,747.000000,671,803,3,17.536814,False,True
651,20254,신사동,10대,D_생활필수,18457,23081.333333,20990,24703,3,-20.034949,True,False
652,20254,신사동,10대,E_의료건강,2570,3848.333333,3322,4325,3,-33.217843,True,False
653,20254,신사동,20대,A_외식카페,364491,597187.333333,463096,736272,3,-38.965383,True,False
654,20254,신사동,20대,B_여가운동,131201,148612.000000,124098,172435,3,-11.715743,False,False
655,20254,신사동,20대,C_대면생활서비스,12689,11546.000000,10441,12824,3,9.899532,False,False
656,20254,신사동,20대,D_생활필수,159677,234474.333333,186452,270612,3,-31.900009,True,False
657,20254,신사동,20대,E_의료건강,74943,97119.333333,84361,111080,3,-22.834108,True,False
658,20254,신사동,30대,A_외식카페,481578,583223.333333,523793,634264,3,-17.428201,True,False
659,20254,신사동,30대,B_여가운동,67479,68432.333333,59196,74793,3,-1.393104,False,False
660,20254,신사동,30대,C_대면생활서비스,14542,13669.666667,12812,14915,3,6.381526,False,False
661,20254,신사동,30대,D_생활필수,211398,248265.333333,235774,255444,3,-14.849972,True,False
662,20254,신사동,30대,E_의료건강,116730,134060.000000,128764,142045,3,-12.927048,True,False
663,20254,신사동,40대,A_외식카페,284526,320306.666667,296426,341972,3,-11.170753,True,False
664,20254,신사동,40대,B_여가운동,31160,20555.333333,18561,24279,3,51.590828,False,True
665,20254,신사동,40대,C_대면생활서비스,9602,10731.000000,9313,12512,3,-10.520921,False,False
666,20254,신사동,40대,D_생활필수,145277,160312.000000,154400,165954,3,-9.378587,True,False
667,20254,신사동,40대,E_의료건강,104182,115585.666667,110183,122003,3,-9.865987,True,False
668,20254,신사동,50대,A_외식카페,241823,253715.666667,236701,264042,3,-4.687399,False,False
669,20254,신사동,50대,B_여가운동,34575,23804.000000,21508,26091,3,45.248698,False,True
670,20254,신사동,50대,C_대면생활서비스,10145,8971.000000,8756,9118,3,13.086612,False,True
671,20254,신사동,50대,D_생활필수,125214,123665.000000,120644,126856,3,1.252578,False,False
672,20254,신사동,50대,E_의료건강,104703,109709.666667,108677,110681,3,-4.56356,True,False
673,20254,신사동,60대이상,A_외식카페,146454,142750.000000,139814,145946,3,2.594746,False,True
674,20254,신사동,60대이상,B_여가운동,6349,5226.333333,4281,5760,3,21.480962,False,True
675,20254,신사동,60대이상,C_대면생활서비스,7453,6192.000000,5833,6583,3,20.364987,False,True
676,20254,신사동,60대이상,D_생활필수,76848,71845.666667,66006,78257,3,6.96261,False,False
677,20254,신사동,60대이상,E_의료건강,113108,107376.666667,104758,109814,3,5.337597,False,True
558,20253,일원1동,10대,A_외식카페,5010,4937.333333,4641,5089,3,1.47178,False,False
559,20253,일원1동,10대,B_여가운동,10958,14355.333333,13187,16113,3,-23.666001,True,False
560,20253,일원1동,10대,C_대면생활서비스,119,227.333333,160,305,3,-47.653959,True,False
561,20253,일원1동,10대,D_생활필수,2164,4741.000000,3732,5522,3,-54.355621,True,False
562,20253,일원1동,10대,E_의료건강,1303,1864.666667,1238,2273,3,-30.121559,False,False
563,20253,일원1동,20대,A_외식카페,46077,61511.000000,50738,69583,3,-25.091447,True,False
564,20253,일원1동,20대,B_여가운동,29436,40283.666667,37405,44512,3,-26.928201,True,False
565,20253,일원1동,20대,C_대면생활서비스,1715,2323.000000,2086,2616,3,-26.173052,True,False
566,20253,일원1동,20대,D_생활필수,38687,52925.000000,47667,57349,3,-26.90222,True,False
567,20253,일원1동,20대,E_의료건강,15774,24388.666667,21860,27937,3,-35.322418,True,False
568,20253,일원1동,30대,A_외식카페,91007,98598.666667,92869,104476,3,-7.699563,True,False
569,20253,일원1동,30대,B_여가운동,22237,19429.000000,17688,21830,3,14.452622,False,True
570,20253,일원1동,30대,C_대면생활서비스,3477,3762.333333,3732,3785,3,-7.583946,True,False
571,20253,일원1동,30대,D_생활필수,65546,71145.666667,65785,73997,3,-7.870707,True,False
572,20253,일원1동,30대,E_의료건강,49746,58202.333333,55658,61920,3,-14.5292,True,False
573,20253,일원1동,40대,A_외식카페,108756,107785.333333,98962,116278,3,0.900555,False,False
574,20253,일원1동,40대,B_여가운동,13569,14282.666667,8877,18184,3,-4.996733,False,False
575,20253,일원1동,40대,C_대면생활서비스,5038,5470.666667,5031,5807,3,-7.908847,False,False
576,20253,일원1동,40대,D_생활필수,66126,62480.666667,57338,66093,3,5.834338,False,True
577,20253,일원1동,40대,E_의료건강,77837,78855.000000,77670,79805,3,-1.290977,False,False
578,20253,일원1동,50대,A_외식카페,99770,99111.666667,92233,106149,3,0.664234,False,False
579,20253,일원1동,50대,B_여가운동,10583,10806.333333,8220,14128,3,-2.066689,False,False
580,20253,일원1동,50대,C_대면생활서비스,4023,5184.000000,4814,5682,3,-22.395833,True,False
581,20253,일원1동,50대,D_생활필수,55136,44695.666667,39336,52973,3,23.358715,False,True
582,20253,일원1동,50대,E_의료건강,66925,70220.000000,68334,71738,3,-4.692395,True,False
583,20253,일원1동,60대이상,A_외식카페,106966,100678.666667,88034,108638,3,6.244951,False,False
584,20253,일원1동,60대이상,B_여가운동,3790,2626.666667,1862,3467,3,44.28934,False,True
585,20253,일원1동,60대이상,C_대면생활서비스,3322,2551.000000,2201,2915,3,30.223442,False,True
586,20253,일원1동,60대이상,D_생활필수,36554,33175.000000,23429,42156,3,10.185381,False,False
587,20253,일원1동,60대이상,E_의료건강,117162,103116.000000,95777,113883,3,13.621552,False,True
1206,20254,일원1동,10대,A_외식카페,5642,6293.666667,5206,7096,3,-10.354324,False,False
1207,20254,일원1동,10대,B_여가운동,9754,14394.333333,12215,18136,3,-32.237223,True,False
1208,20254,일원1동,10대,C_대면생활서비스,95,151.000000,138,164,3,-37.086093,True,False
1209,20254,일원1동,10대,D_생활필수,2701,3845.333333,3382,4568,3,-29.759015,True,False
1210,20254,일원1동,10대,E_의료건강,1453,1864.666667,1640,2075,3,-22.077226,True,False
1211,20254,일원1동,20대,A_외식카페,41890,63555.666667,52807,70415,3,-34.089276,True,False
1212,20254,일원1동,20대,B_여가운동,22771,33308.000000,25970,39982,3,-31.635043,True,False
1213,20254,일원1동,20대,C_대면생활서비스,1558,2102.666667,2054,2193,3,-25.903614,True,False
1214,20254,일원1동,20대,D_생활필수,33044,54664.000000,47152,60039,3,-39.55071,True,False
1215,20254,일원1동,20대,E_의료건강,19168,25269.000000,22332,28345,3,-24.144208,True,False
1216,20254,일원1동,30대,A_외식카페,83838,101649.666667,92123,111101,3,-17.522602,True,False
1217,20254,일원1동,30대,B_여가운동,22012,17769.333333,15098,19152,3,23.876341,False,True
1218,20254,일원1동,30대,C_대면생활서비스,2925,4088.666667,3835,4565,3,-28.460786,True,False
1219,20254,일원1동,30대,D_생활필수,57842,72383.333333,65676,79115,3,-20.089339,True,False
1220,20254,일원1동,30대,E_의료건강,51765,61664.666667,57215,69106,3,-16.054034,True,False
1221,20254,일원1동,40대,A_외식카페,98011,109753.666667,102411,121211,3,-10.699111,True,False
1222,20254,일원1동,40대,B_여가운동,16025,15712.000000,12666,20092,3,1.992108,False,False
1223,20254,일원1동,40대,C_대면생활서비스,4621,5278.000000,4318,5847,3,-12.447897,False,False
1224,20254,일원1동,40대,D_생활필수,57071,61877.333333,57008,68328,3,-7.767519,False,False
1225,20254,일원1동,40대,E_의료건강,86722,89341.666667,83405,97461,3,-2.932189,False,False
1226,20254,일원1동,50대,A_외식카페,90518,99324.666667,92903,108641,3,-8.866545,True,False
1227,20254,일원1동,50대,B_여가운동,12237,13718.000000,11383,15319,3,-10.796034,False,False
1228,20254,일원1동,50대,C_대면생활서비스,4540,4935.666667,4415,5404,3,-8.016479,False,False
1229,20254,일원1동,50대,D_생활필수,50912,44423.666667,35021,53003,3,14.605578,False,False
1230,20254,일원1동,50대,E_의료건강,68994,75262.666667,72674,78311,3,-8.329052,True,False
1231,20254,일원1동,60대이상,A_외식카페,99960,100417.666667,94317,103620,3,-0.455763,False,False
1232,20254,일원1동,60대이상,B_여가운동,6876,3127.333333,1993,5122,3,119.867832,False,True
1233,20254,일원1동,60대이상,C_대면생활서비스,3299,2665.333333,2465,2774,3,23.774387,False,True
1234,20254,일원1동,60대이상,D_생활필수,39065,33725.333333,23666,38850,3,15.832806,False,True
1235,20254,일원1동,60대이상,E_의료건강,127908,107979.666667,101587,115527,3,18.455635,False,True
528,20253,일원본동,10대,A_외식카페,494,379.333333,97,883,3,30.228471,False,False
529,20253,일원본동,10대,B_여가운동,110,24.000000,0,72,3,358.333333,False,True
530,20253,일원본동,10대,C_대면생활서비스,144,95.000000,41,149,3,51.578947,False,False
531,20253,일원본동,10대,D_생활필수,6075,4851.666667,3553,6478,3,25.214703,False,False
532,20253,일원본동,10대,E_의료건강,17,61.333333,8,112,3,-72.282609,False,False
533,20253,일원본동,20대,A_외식카페,7937,8429.000000,7192,9779,3,-5.836991,False,False
534,20253,일원본동,20대,B_여가운동,235,157.000000,6,459,3,49.681529,False,False
535,20253,일원본동,20대,C_대면생활서비스,452,317.000000,198,439,3,42.586751,False,True
536,20253,일원본동,20대,D_생활필수,148519,189133.000000,147403,240008,3,-21.473778,False,False
537,20253,일원본동,20대,E_의료건강,272,631.666667,432,778,3,-56.939314,True,False
538,20253,일원본동,30대,A_외식카페,15365,18350.333333,16260,19982,3,-16.268551,True,False
539,20253,일원본동,30대,B_여가운동,979,374.000000,66,966,3,161.764706,False,True
540,20253,일원본동,30대,C_대면생활서비스,942,1013.333333,843,1186,3,-7.039474,False,False
541,20253,일원본동,30대,D_생활필수,332713,354866.000000,305166,423221,3,-6.242638,False,False
542,20253,일원본동,30대,E_의료건강,1432,2255.666667,1600,2626,3,-36.515443,True,False
543,20253,일원본동,40대,A_외식카페,24867,27595.000000,25080,32308,3,-9.885849,True,False
544,20253,일원본동,40대,B_여가운동,2034,721.000000,30,2079,3,182.108183,False,False
545,20253,일원본동,40대,C_대면생활서비스,2949,2523.333333,2377,2717,3,16.869221,False,True
546,20253,일원본동,40대,D_생활필수,333858,335523.666667,301076,370712,3,-0.496438,False,False
547,20253,일원본동,40대,E_의료건강,3579,4044.333333,3302,4711,3,-11.505811,False,False
548,20253,일원본동,50대,A_외식카페,23536,21852.333333,18522,24341,3,7.704745,False,False
549,20253,일원본동,50대,B_여가운동,2416,841.000000,48,2367,3,187.277051,False,True
550,20253,일원본동,50대,C_대면생활서비스,2968,2235.333333,2091,2350,3,32.776618,False,True
551,20253,일원본동,50대,D_생활필수,275139,257112.000000,238024,273122,3,7.011341,False,True
552,20253,일원본동,50대,E_의료건강,3256,4550.333333,3145,5602,3,-28.444803,False,False
553,20253,일원본동,60대이상,A_외식카페,28169,24567.333333,16331,29458,3,14.660389,False,False
554,20253,일원본동,60대이상,B_여가운동,2812,869.000000,0,2601,3,223.590334,False,True
555,20253,일원본동,60대이상,C_대면생활서비스,2263,1627.333333,1570,1725,3,39.06186,False,True
556,20253,일원본동,60대이상,D_생활필수,259758,226167.000000,204919,237511,3,14.852299,False,True
557,20253,일원본동,60대이상,E_의료건강,6178,6766.000000,5734,7494,3,-8.690511,False,False
1176,20254,일원본동,10대,A_외식카페,725,502.000000,415,669,3,44.422311,False,True
1177,20254,일원본동,10대,B_여가운동,190,113.333333,0,231,3,67.647059,False,False
1178,20254,일원본동,10대,C_대면생활서비스,102,97.666667,69,126,3,4.43686,False,False
1179,20254,일원본동,10대,D_생활필수,4892,5215.000000,3419,6628,3,-6.193672,False,False
1180,20254,일원본동,10대,E_의료건강,8,24.666667,0,74,3,-67.567568,False,False
1181,20254,일원본동,20대,A_외식카페,6182,8613.000000,8424,8850,3,-28.224777,True,False
1182,20254,일원본동,20대,B_여가운동,173,205.666667,0,334,3,-15.883306,False,False
1183,20254,일원본동,20대,C_대면생활서비스,343,379.666667,291,431,3,-9.657594,False,False
1184,20254,일원본동,20대,D_생활필수,153674,183770.333333,142855,243997,3,-16.377145,False,False
1185,20254,일원본동,20대,E_의료건강,389,468.666667,337,609,3,-16.998578,False,False
1186,20254,일원본동,30대,A_외식카페,15586,16830.666667,15643,17864,3,-7.395231,True,False
1187,20254,일원본동,30대,B_여가운동,358,503.666667,24,791,3,-28.921244,False,False
1188,20254,일원본동,30대,C_대면생활서비스,836,951.666667,853,1050,3,-12.154116,True,False
1189,20254,일원본동,30대,D_생활필수,304082,330872.000000,296666,391131,3,-8.096787,False,False
1190,20254,일원본동,30대,E_의료건강,1312,2030.666667,1559,2579,3,-35.390676,True,False
1191,20254,일원본동,40대,A_외식카페,21210,27398.666667,24666,31634,3,-22.587474,True,False
1192,20254,일원본동,40대,B_여가운동,1134,1178.333333,12,1780,3,-3.762376,False,False
1193,20254,일원본동,40대,C_대면생활서비스,2260,2645.333333,2228,3021,3,-14.566532,False,False
1194,20254,일원본동,40대,D_생활필수,308150,314282.333333,286192,348882,3,-1.951218,False,False
1195,20254,일원본동,40대,E_의료건강,3026,3778.666667,3068,4369,3,-19.918843,True,False
1196,20254,일원본동,50대,A_외식카페,23629,23977.666667,21565,26029,3,-1.454131,False,False
1197,20254,일원본동,50대,B_여가운동,1762,1379.333333,96,2211,3,27.742871,False,False
1198,20254,일원본동,50대,C_대면생활서비스,3009,2460.666667,2206,2613,3,22.283934,False,True
1199,20254,일원본동,50대,D_생활필수,265332,233369.000000,221988,248576,3,13.696335,False,True
1200,20254,일원본동,50대,E_의료건강,3668,4107.000000,3378,4682,3,-10.689067,False,False
1201,20254,일원본동,60대이상,A_외식카페,24210,23719.000000,18905,26636,3,2.07007,False,False
1202,20254,일원본동,60대이상,B_여가운동,1566,1596.666667,6,2432,3,-1.920668,False,False
1203,20254,일원본동,60대이상,C_대면생활서비스,2228,1862.666667,1707,1947,3,19.613457,False,True
1204,20254,일원본동,60대이상,D_생활필수,244234,210126.666667,204724,219713,3,16.231797,False,True
1205,20254,일원본동,60대이상,E_의료건강,5869,6304.333333,5406,6949,3,-6.905303,False,False

In [32]:
# ============================================================
# 23. 강남구 내 상대적 변화 위치 계산
# 동 × 연령 × 소비영역의 변화가
# 강남구 다른 동과 비교해 어느 위치인지 확인
# ============================================================

valid = card_detection[
    card_detection["change_rate_pct"].notna()
].copy()

# 동일 분기 × 연령 × 소비영역 내 percentile rank
valid["gangnam_change_percentile"] = (
    valid
    .groupby([
        "기준_년분기_코드",
        "연령대",
        "소비영역"
    ])["change_rate_pct"]
    .rank(
        method="average",
        pct=True
    )
)

# 비교집단 크기도 보존
group_n = (
    valid
    .groupby([
        "기준_년분기_코드",
        "연령대",
        "소비영역"
    ])
    .size()
    .rename("gangnam_compare_n")
    .reset_index()
)

valid = valid.merge(
    group_n,
    on=[
        "기준_년분기_코드",
        "연령대",
        "소비영역"
    ],
    how="left",
    validate="many_to_one"
)

print("분석 가능 행:", len(valid))

print("\n비교집단 크기 분포")
print(
    valid["gangnam_compare_n"]
    .value_counts()
    .sort_index()
)

print("\npercentile 요약")
print(
    valid["gangnam_change_percentile"]
    .describe()
)

분석 가능 행: 1287

비교집단 크기 분포
gangnam_compare_n
20    120
21    441
22    726
Name: count, dtype: int64

percentile 요약
count    1287.000000
mean        0.523310
std         0.288474
min         0.045455
25%         0.272727
50%         0.523810
75%         0.772727
max         1.000000
Name: gangnam_change_percentile, dtype: float64

In [33]:
# ============================================================
# 24. 주요 4개 동의 강남구 내 상대 위치
# ============================================================

target_relative = valid[
    valid["행정동명_표준"].isin(
        ["개포3동", "일원본동", "일원1동", "신사동"]
    )
].copy()

display(
    target_relative[
        [
            "기준_년분기_코드",
            "행정동명_표준",
            "연령대",
            "소비영역",
            "current_count",
            "baseline_mean",
            "change_rate_pct",
            "gangnam_change_percentile",
            "gangnam_compare_n",
            "below_historical_min",
            "above_historical_max"
        ]
    ]
    .sort_values([
        "기준_년분기_코드",
        "행정동명_표준",
        "연령대",
        "소비영역"
    ])
)

,기준_년분기_코드,행정동명_표준,연령대,소비영역,current_count,baseline_mean,change_rate_pct,gangnam_change_percentile,gangnam_compare_n,below_historical_min,above_historical_max
586,20253,개포3동,10대,A_외식카페,149,286.000000,-47.902098,0.047619,21,True,False
587,20253,개포3동,10대,D_생활필수,3440,5617.333333,-38.760978,0.227273,22,True,False
588,20253,개포3동,10대,E_의료건강,0,15.000000,-100.0,0.047619,21,False,False
589,20253,개포3동,20대,A_외식카페,4448,7425.000000,-40.094276,0.136364,22,True,False
590,20253,개포3동,20대,C_대면생활서비스,143,111.333333,28.443114,0.954545,22,False,False
591,20253,개포3동,20대,D_생활필수,23181,32850.666667,-29.435222,0.500000,22,True,False
592,20253,개포3동,20대,E_의료건강,112,257.666667,-56.532988,0.095238,21,True,False
593,20253,개포3동,30대,A_외식카페,13498,16662.666667,-18.992558,0.136364,22,True,False
594,20253,개포3동,30대,B_여가운동,51,81.666667,-37.55102,0.333333,21,True,False
595,20253,개포3동,30대,C_대면생활서비스,369,374.000000,-1.336898,0.727273,22,False,False
596,20253,개포3동,30대,D_생활필수,70184,73581.666667,-4.617545,0.727273,22,False,False
597,20253,개포3동,30대,E_의료건강,531,773.000000,-31.306598,0.142857,21,True,False
598,20253,개포3동,40대,A_외식카페,10133,13325.333333,-23.956874,0.045455,22,False,False
599,20253,개포3동,40대,B_여가운동,430,376.000000,14.361702,0.761905,21,False,False
600,20253,개포3동,40대,C_대면생활서비스,488,682.333333,-28.480703,0.136364,22,False,False
601,20253,개포3동,40대,D_생활필수,72934,69570.000000,4.835418,0.863636,22,False,False
602,20253,개포3동,40대,E_의료건강,1459,1395.000000,4.587814,0.952381,21,False,False
603,20253,개포3동,50대,A_외식카페,8107,11278.333333,-28.118812,0.090909,22,True,False
604,20253,개포3동,50대,B_여가운동,49,64.666667,-24.226804,0.333333,21,False,False
605,20253,개포3동,50대,C_대면생활서비스,670,876.333333,-23.545074,0.045455,22,True,False
606,20253,개포3동,50대,D_생활필수,47141,47860.666667,-1.50367,0.363636,22,False,False
607,20253,개포3동,50대,E_의료건강,1438,1529.666667,-5.992591,0.333333,21,False,False
608,20253,개포3동,60대이상,A_외식카페,5952,5954.333333,-0.039187,0.090909,22,False,False
609,20253,개포3동,60대이상,B_여가운동,5,1.666667,200.0,0.904762,21,False,False
610,20253,개포3동,60대이상,C_대면생활서비스,588,414.333333,41.914722,0.863636,22,False,True
611,20253,개포3동,60대이상,D_생활필수,41709,29459.666667,41.580013,0.863636,22,False,True
612,20253,개포3동,60대이상,E_의료건강,1797,2081.666667,-13.67494,0.047619,21,False,False
0,20253,신사동,10대,A_외식카페,29423,40173.333333,-26.759874,0.428571,21,True,False
1,20253,신사동,10대,B_여가운동,33861,25283.333333,33.92617,0.850000,20,False,False
2,20253,신사동,10대,C_대면생활서비스,820,633.000000,29.541864,0.750000,20,False,True
3,20253,신사동,10대,D_생활필수,21859,29310.000000,-25.421358,0.454545,22,True,False
4,20253,신사동,10대,E_의료건강,3180,3504.666667,-9.263839,0.666667,21,False,False
5,20253,신사동,20대,A_외식카페,387147,618093.000000,-37.36428,0.227273,22,True,False
6,20253,신사동,20대,B_여가운동,154358,159373.333333,-3.146909,0.800000,20,False,False
7,20253,신사동,20대,C_대면생활서비스,12072,12083.333333,-0.093793,0.772727,22,False,False
8,20253,신사동,20대,D_생활필수,181054,274011.000000,-33.92455,0.227273,22,True,False
9,20253,신사동,20대,E_의료건강,80008,101384.000000,-21.084195,0.714286,21,True,False
10,20253,신사동,30대,A_외식카페,508431,595895.333333,-14.677801,0.227273,22,True,False
11,20253,신사동,30대,B_여가운동,76633,65940.666667,16.215082,0.761905,21,False,True
12,20253,신사동,30대,C_대면생활서비스,13660,13977.333333,-2.270342,0.681818,22,False,False
13,20253,신사동,30대,D_생활필수,245326,278221.666667,-11.823546,0.363636,22,True,False
14,20253,신사동,30대,E_의료건강,122496,135757.333333,-9.76841,0.619048,21,True,False
15,20253,신사동,40대,A_외식카페,301538,337878.666667,-10.755537,0.181818,22,True,False
16,20253,신사동,40대,B_여가운동,42878,21653.000000,98.023369,0.904762,21,False,True
17,20253,신사동,40대,C_대면생활서비스,10858,10805.333333,0.487414,0.863636,22,False,False
18,20253,신사동,40대,D_생활필수,165996,183984.000000,-9.776937,0.272727,22,True,False
19,20253,신사동,40대,E_의료건강,102200,112000.000000,-8.75,0.571429,21,True,False
20,20253,신사동,50대,A_외식카페,253073,270494.666667,-6.440669,0.227273,22,True,False
21,20253,신사동,50대,B_여가운동,44262,27600.000000,60.369565,0.904762,21,False,True
22,20253,신사동,50대,C_대면생활서비스,10176,9430.333333,7.907108,0.772727,22,False,True
23,20253,신사동,50대,D_생활필수,140434,142399.000000,-1.379925,0.409091,22,False,False
24,20253,신사동,50대,E_의료건강,102332,108693.333333,-5.852552,0.380952,21,True,False
25,20253,신사동,60대이상,A_외식카페,153316,148149.666667,3.487239,0.181818,22,False,True
26,20253,신사동,60대이상,B_여가운동,6592,4369.000000,50.881209,0.714286,21,False,True
27,20253,신사동,60대이상,C_대면생활서비스,7254,6222.666667,16.573816,0.500000,22,False,True
28,20253,신사동,60대이상,D_생활필수,85339,77948.666667,9.481026,0.181818,22,False,True
29,20253,신사동,60대이상,E_의료건강,109366,102206.333333,7.005111,0.523810,21,False,True
556,20253,일원1동,10대,A_외식카페,5010,4937.333333,1.47178,0.761905,21,False,False
557,20253,일원1동,10대,B_여가운동,10958,14355.333333,-23.666001,0.600000,20,True,False
558,20253,일원1동,10대,C_대면생활서비스,119,227.333333,-47.653959,0.100000,20,True,False
559,20253,일원1동,10대,D_생활필수,2164,4741.000000,-54.355621,0.136364,22,True,False
560,20253,일원1동,10대,E_의료건강,1303,1864.666667,-30.121559,0.238095,21,False,False
561,20253,일원1동,20대,A_외식카페,46077,61511.000000,-25.091447,0.681818,22,True,False
562,20253,일원1동,20대,B_여가운동,29436,40283.666667,-26.928201,0.600000,20,True,False
563,20253,일원1동,20대,C_대면생활서비스,1715,2323.000000,-26.173052,0.363636,22,True,False
564,20253,일원1동,20대,D_생활필수,38687,52925.000000,-26.90222,0.590909,22,True,False
565,20253,일원1동,20대,E_의료건강,15774,24388.666667,-35.322418,0.142857,21,True,False
566,20253,일원1동,30대,A_외식카페,91007,98598.666667,-7.699563,0.590909,22,True,False
567,20253,일원1동,30대,B_여가운동,22237,19429.000000,14.452622,0.714286,21,False,True
568,20253,일원1동,30대,C_대면생활서비스,3477,3762.333333,-7.583946,0.545455,22,True,False
569,20253,일원1동,30대,D_생활필수,65546,71145.666667,-7.870707,0.545455,22,True,False
570,20253,일원1동,30대,E_의료건강,49746,58202.333333,-14.5292,0.333333,21,True,False
571,20253,일원1동,40대,A_외식카페,108756,107785.333333,0.900555,0.681818,22,False,False
572,20253,일원1동,40대,B_여가운동,13569,14282.666667,-4.996733,0.666667,21,False,False
573,20253,일원1동,40대,C_대면생활서비스,5038,5470.666667,-7.908847,0.681818,22,False,False
574,20253,일원1동,40대,D_생활필수,66126,62480.666667,5.834338,0.909091,22,False,True
575,20253,일원1동,40대,E_의료건강,77837,78855.000000,-1.290977,0.857143,21,False,False
576,20253,일원1동,50대,A_외식카페,99770,99111.666667,0.664234,0.545455,22,False,False
577,20253,일원1동,50대,B_여가운동,10583,10806.333333,-2.066689,0.619048,21,False,False
578,20253,일원1동,50대,C_대면생활서비스,4023,5184.000000,-22.395833,0.090909,22,True,False
579,20253,일원1동,50대,D_생활필수,55136,44695.666667,23.358715,1.000000,22,False,True
580,20253,일원1동,50대,E_의료건강,66925,70220.000000,-4.692395,0.523810,21,True,False
581,20253,일원1동,60대이상,A_외식카페,106966,100678.666667,6.244951,0.272727,22,False,False
582,20253,일원1동,60대이상,B_여가운동,3790,2626.666667,44.28934,0.619048,21,False,True
583,20253,일원1동,60대이상,C_대면생활서비스,3322,2551.000000,30.223442,0.727273,22,False,True
584,20253,일원1동,60대이상,D_생활필수,36554,33175.000000,10.185381,0.272727,22,False,False
585,20253,일원1동,60대이상,E_의료건강,117162,103116.000000,13.621552,0.809524,21,False,True
526,20253,일원본동,10대,A_외식카페,494,379.333333,30.228471,0.952381,21,False,False
527,20253,일원본동,10대,B_여가운동,110,24.000000,358.333333,1.000000,20,False,True
528,20253,일원본동,10대,C_대면생활서비스,144,95.000000,51.578947,0.900000,20,False,False
529,20253,일원본동,10대,D_생활필수,6075,4851.666667,25.214703,0.954545,22,False,False
530,20253,일원본동,10대,E_의료건강,17,61.333333,-72.282609,0.095238,21,False,False
531,20253,일원본동,20대,A_외식카페,7937,8429.000000,-5.836991,0.954545,22,False,False
532,20253,일원본동,20대,B_여가운동,235,157.000000,49.681529,0.900000,20,False,False
533,20253,일원본동,20대,C_대면생활서비스,452,317.000000,42.586751,1.000000,22,False,True
534,20253,일원본동,20대,D_생활필수,148519,189133.000000,-21.473778,0.772727,22,False,False
535,20253,일원본동,20대,E_의료건강,272,631.666667,-56.939314,0.047619,21,True,False
536,20253,일원본동,30대,A_외식카페,15365,18350.333333,-16.268551,0.181818,22,True,False
537,20253,일원본동,30대,B_여가운동,979,374.000000,161.764706,0.952381,21,False,True
538,20253,일원본동,30대,C_대면생활서비스,942,1013.333333,-7.039474,0.590909,22,False,False
539,20253,일원본동,30대,D_생활필수,332713,354866.000000,-6.242638,0.636364,22,False,False
540,20253,일원본동,30대,E_의료건강,1432,2255.666667,-36.515443,0.047619,21,True,False
541,20253,일원본동,40대,A_외식카페,24867,27595.000000,-9.885849,0.318182,22,True,False
542,20253,일원본동,40대,B_여가운동,2034,721.000000,182.108183,1.000000,21,False,False
543,20253,일원본동,40대,C_대면생활서비스,2949,2523.333333,16.869221,0.909091,22,False,True
544,20253,일원본동,40대,D_생활필수,333858,335523.666667,-0.496438,0.681818,22,False,False
545,20253,일원본동,40대,E_의료건강,3579,4044.333333,-11.505811,0.428571,21,False,False
546,20253,일원본동,50대,A_외식카페,23536,21852.333333,7.704745,0.681818,22,False,False
547,20253,일원본동,50대,B_여가운동,2416,841.000000,187.277051,1.000000,21,False,True
548,20253,일원본동,50대,C_대면생활서비스,2968,2235.333333,32.776618,0.954545,22,False,True
549,20253,일원본동,50대,D_생활필수,275139,257112.000000,7.011341,0.636364,22,False,True
550,20253,일원본동,50대,E_의료건강,3256,4550.333333,-28.444803,0.047619,21,False,False
551,20253,일원본동,60대이상,A_외식카페,28169,24567.333333,14.660389,0.454545,22,False,False
552,20253,일원본동,60대이상,B_여가운동,2812,869.000000,223.590334,0.952381,21,False,True
553,20253,일원본동,60대이상,C_대면생활서비스,2263,1627.333333,39.06186,0.818182,22,False,True
554,20253,일원본동,60대이상,D_생활필수,259758,226167.000000,14.852299,0.454545,22,False,True
555,20253,일원본동,60대이상,E_의료건강,6178,6766.000000,-8.690511,0.190476,21,False,False
1231,20254,개포3동,10대,A_외식카페,183,577.666667,-68.320831,0.090909,22,True,False
1232,20254,개포3동,10대,D_생활필수,3215,5448.333333,-40.991129,0.181818,22,True,False
1233,20254,개포3동,20대,A_외식카페,3807,6764.333333,-43.719509,0.136364,22,False,False
1234,20254,개포3동,20대,C_대면생활서비스,212,181.666667,16.697248,0.954545,22,False,True
1235,20254,개포3동,20대,D_생활필수,20700,29672.000000,-30.237261,0.500000,22,True,False
1236,20254,개포3동,20대,E_의료건강,147,251.666667,-41.589404,0.095238,21,True,False
1237,20254,개포3동,30대,A_외식카페,10680,15070.666667,-29.133858,0.045455,22,True,False
1238,20254,개포3동,30대,B_여가운동,19,94.000000,-79.787234,0.095238,21,True,False
1239,20254,개포3동,30대,C_대면생활서비스,278,348.000000,-20.114943,0.363636,22,False,False
1240,20254,개포3동,30대,D_생활필수,60292,67286.666667,-10.395323,0.590909,22,True,False
1241,20254,개포3동,30대,E_의료건강,620,698.333333,-11.217184,0.761905,21,False,False
1242,20254,개포3동,40대,A_외식카페,8351,11347.333333,-26.405617,0.045455,22,True,False
1243,20254,개포3동,40대,B_여가운동,309,410.333333,-24.69537,0.523810,21,True,False
1244,20254,개포3동,40대,C_대면생활서비스,504,655.333333,-23.092574,0.272727,22,False,False
1245,20254,개포3동,40대,D_생활필수,61844,63086.333333,-1.969259,0.727273,22,False,False
1246,20254,개포3동,40대,E_의료건강,1217,1284.333333,-5.242668,0.857143,21,False,False
1247,20254,개포3동,50대,A_외식카페,6845,10827.333333,-36.780371,0.045455,22,True,False
1248,20254,개포3동,50대,B_여가운동,28,33.333333,-16.0,0.333333,21,False,False
1249,20254,개포3동,50대,C_대면생활서비스,862,799.000000,7.884856,0.772727,22,False,False
1250,20254,개포3동,50대,D_생활필수,43400,42205.333333,2.830606,0.636364,22,False,False
1251,20254,개포3동,50대,E_의료건강,944,1169.666667,-19.293246,0.095238,21,True,False
1252,20254,개포3동,60대이상,A_외식카페,5131,6641.000000,-22.73754,0.045455,22,False,False
1253,20254,개포3동,60대이상,B_여가운동,5,7.000000,-28.571429,0.142857,21,False,False
1254,20254,개포3동,60대이상,C_대면생활서비스,599,421.666667,42.055336,0.909091,22,False,True
1255,20254,개포3동,60대이상,D_생활필수,37038,26061.666667,42.116774,0.863636,22,False,True
1256,20254,개포3동,60대이상,E_의료건강,995,2141.333333,-53.533624,0.047619,21,True,False
643,20254,신사동,10대,A_외식카페,24126,36829.000000,-34.491841,0.318182,22,True,False
644,20254,신사동,10대,B_여가운동,24778,22577.000000,9.748859,0.800000,20,False,False
645,20254,신사동,10대,C_대면생활서비스,878,747.000000,17.536814,0.809524,21,False,True
646,20254,신사동,10대,D_생활필수,18457,23081.333333,-20.034949,0.500000,22,True,False
647,20254,신사동,10대,E_의료건강,2570,3848.333333,-33.217843,0.300000,20,True,False
648,20254,신사동,20대,A_외식카페,364491,597187.333333,-38.965383,0.181818,22,True,False
649,20254,신사동,20대,B_여가운동,131201,148612.000000,-11.715743,0.700000,20,False,False
650,20254,신사동,20대,C_대면생활서비스,12689,11546.000000,9.899532,0.863636,22,False,False
651,20254,신사동,20대,D_생활필수,159677,234474.333333,-31.900009,0.454545,22,True,False
652,20254,신사동,20대,E_의료건강,74943,97119.333333,-22.834108,0.761905,21,True,False
653,20254,신사동,30대,A_외식카페,481578,583223.333333,-17.428201,0.272727,22,True,False
654,20254,신사동,30대,B_여가운동,67479,68432.333333,-1.393104,0.666667,21,False,False
655,20254,신사동,30대,C_대면생활서비스,14542,13669.666667,6.381526,0.863636,22,False,False
656,20254,신사동,30대,D_생활필수,211398,248265.333333,-14.849972,0.500000,22,True,False
657,20254,신사동,30대,E_의료건강,116730,134060.000000,-12.927048,0.571429,21,True,False
658,20254,신사동,40대,A_외식카페,284526,320306.666667,-11.170753,0.409091,22,True,False
659,20254,신사동,40대,B_여가운동,31160,20555.333333,51.590828,0.904762,21,False,True
660,20254,신사동,40대,C_대면생활서비스,9602,10731.000000,-10.520921,0.727273,22,False,False
661,20254,신사동,40대,D_생활필수,145277,160312.000000,-9.378587,0.409091,22,True,False
662,20254,신사동,40대,E_의료건강,104182,115585.666667,-9.865987,0.619048,21,True,False
663,20254,신사동,50대,A_외식카페,241823,253715.666667,-4.687399,0.318182,22,False,False
664,20254,신사동,50대,B_여가운동,34575,23804.000000,45.248698,0.904762,21,False,True
665,20254,신사동,50대,C_대면생활서비스,10145,8971.000000,13.086612,0.818182,22,False,True
666,20254,신사동,50대,D_생활필수,125214,123665.000000,1.252578,0.500000,22,False,False
667,20254,신사동,50대,E_의료건강,104703,109709.666667,-4.56356,0.571429,21,True,False
668,20254,신사동,60대이상,A_외식카페,146454,142750.000000,2.594746,0.272727,22,False,True
669,20254,신사동,60대이상,B_여가운동,6349,5226.333333,21.480962,0.571429,21,False,True
670,20254,신사동,60대이상,C_대면생활서비스,7453,6192.000000,20.364987,0.636364,22,False,True
671,20254,신사동,60대이상,D_생활필수,76848,71845.666667,6.96261,0.318182,22,False,False
672,20254,신사동,60대이상,E_의료건강,113108,107376.666667,5.337597,0.666667,21,False,True
1201,20254,일원1동,10대,A_외식카페,5642,6293.666667,-10.354324,0.863636,22,False,False
1202,20254,일원1동,10대,B_여가운동,9754,14394.333333,-32.237223,0.550000,20,True,False
1203,20254,일원1동,10대,C_대면생활서비스,95,151.000000,-37.086093,0.190476,21,True,False
1204,20254,일원1동,10대,D_생활필수,2701,3845.333333,-29.759015,0.272727,22,True,False
1205,20254,일원1동,10대,E_의료건강,1453,1864.666667,-22.077226,0.600000,20,True,False
1206,20254,일원1동,20대,A_외식카페,41890,63555.666667,-34.089276,0.409091,22,True,False
1207,20254,일원1동,20대,B_여가운동,22771,33308.000000,-31.635043,0.550000,20,True,False
1208,20254,일원1동,20대,C_대면생활서비스,1558,2102.666667,-25.903614,0.363636,22,True,False
1209,20254,일원1동,20대,D_생활필수,33044,54664.000000,-39.55071,0.318182,22,True,False
1210,20254,일원1동,20대,E_의료건강,19168,25269.000000,-24.144208,0.619048,21,True,False
1211,20254,일원1동,30대,A_외식카페,83838,101649.666667,-17.522602,0.227273,22,True,False
1212,20254,일원1동,30대,B_여가운동,22012,17769.333333,23.876341,0.809524,21,False,True
1213,20254,일원1동,30대,C_대면생활서비스,2925,4088.666667,-28.460786,0.272727,22,True,False
1214,20254,일원1동,30대,D_생활필수,57842,72383.333333,-20.089339,0.318182,22,True,False
1215,20254,일원1동,30대,E_의료건강,51765,61664.666667,-16.054034,0.428571,21,True,False
1216,20254,일원1동,40대,A_외식카페,98011,109753.666667,-10.699111,0.454545,22,True,False
1217,20254,일원1동,40대,B_여가운동,16025,15712.000000,1.992108,0.761905,21,False,False
1218,20254,일원1동,40대,C_대면생활서비스,4621,5278.000000,-12.447897,0.681818,22,False,False
1219,20254,일원1동,40대,D_생활필수,57071,61877.333333,-7.767519,0.545455,22,False,False
1220,20254,일원1동,40대,E_의료건강,86722,89341.666667,-2.932189,0.952381,21,False,False
1221,20254,일원1동,50대,A_외식카페,90518,99324.666667,-8.866545,0.181818,22,True,False
1222,20254,일원1동,50대,B_여가운동,12237,13718.000000,-10.796034,0.428571,21,False,False
1223,20254,일원1동,50대,C_대면생활서비스,4540,4935.666667,-8.016479,0.318182,22,False,False
1224,20254,일원1동,50대,D_생활필수,50912,44423.666667,14.605578,0.909091,22,False,False
1225,20254,일원1동,50대,E_의료건강,68994,75262.666667,-8.329052,0.380952,21,True,False
1226,20254,일원1동,60대이상,A_외식카페,99960,100417.666667,-0.455763,0.136364,22,False,False
1227,20254,일원1동,60대이상,B_여가운동,6876,3127.333333,119.867832,0.952381,21,False,True
1228,20254,일원1동,60대이상,C_대면생활서비스,3299,2665.333333,23.774387,0.772727,22,False,True
1229,20254,일원1동,60대이상,D_생활필수,39065,33725.333333,15.832806,0.500000,22,False,True
1230,20254,일원1동,60대이상,E_의료건강,127908,107979.666667,18.455635,1.000000,21,False,True
1171,20254,일원본동,10대,A_외식카페,725,502.000000,44.422311,0.954545,22,False,True
1172,20254,일원본동,10대,B_여가운동,190,113.333333,67.647059,0.900000,20,False,False
1173,20254,일원본동,10대,C_대면생활서비스,102,97.666667,4.43686,0.761905,21,False,False
1174,20254,일원본동,10대,D_생활필수,4892,5215.000000,-6.193672,0.772727,22,False,False
1175,20254,일원본동,10대,E_의료건강,8,24.666667,-67.567568,0.050000,20,False,False
1176,20254,일원본동,20대,A_외식카페,6182,8613.000000,-28.224777,0.681818,22,True,False
1177,20254,일원본동,20대,B_여가운동,173,205.666667,-15.883306,0.650000,20,False,False
1178,20254,일원본동,20대,C_대면생활서비스,343,379.666667,-9.657594,0.636364,22,False,False
1179,20254,일원본동,20대,D_생활필수,153674,183770.333333,-16.377145,0.863636,22,False,False
1180,20254,일원본동,20대,E_의료건강,389,468.666667,-16.998578,0.857143,21,False,False
1181,20254,일원본동,30대,A_외식카페,15586,16830.666667,-7.395231,0.818182,22,True,False
1182,20254,일원본동,30대,B_여가운동,358,503.666667,-28.921244,0.428571,21,False,False
1183,20254,일원본동,30대,C_대면생활서비스,836,951.666667,-12.154116,0.500000,22,True,False
1184,20254,일원본동,30대,D_생활필수,304082,330872.000000,-8.096787,0.727273,22,False,False
1185,20254,일원본동,30대,E_의료건강,1312,2030.666667,-35.390676,0.047619,21,True,False
1186,20254,일원본동,40대,A_외식카페,21210,27398.666667,-22.587474,0.090909,22,True,False
1187,20254,일원본동,40대,B_여가운동,1134,1178.333333,-3.762376,0.714286,21,False,False
1188,20254,일원본동,40대,C_대면생활서비스,2260,2645.333333,-14.566532,0.545455,22,False,False
1189,20254,일원본동,40대,D_생활필수,308150,314282.333333,-1.951218,0.772727,22,False,False
1190,20254,일원본동,40대,E_의료건강,3026,3778.666667,-19.918843,0.190476,21,True,False
1191,20254,일원본동,50대,A_외식카페,23629,23977.666667,-1.454131,0.454545,22,False,False
1192,20254,일원본동,50대,B_여가운동,1762,1379.333333,27.742871,0.809524,21,False,False
1193,20254,일원본동,50대,C_대면생활서비스,3009,2460.666667,22.283934,0.954545,22,False,True
1194,20254,일원본동,50대,D_생활필수,265332,233369.000000,13.696335,0.818182,22,False,True
1195,20254,일원본동,50대,E_의료건강,3668,4107.000000,-10.689067,0.238095,21,False,False
1196,20254,일원본동,60대이상,A_외식카페,24210,23719.000000,2.07007,0.227273,22,False,False
1197,20254,일원본동,60대이상,B_여가운동,1566,1596.666667,-1.920668,0.428571,21,False,False
1198,20254,일원본동,60대이상,C_대면생활서비스,2228,1862.666667,19.613457,0.545455,22,False,True
1199,20254,일원본동,60대이상,D_생활필수,244234,210126.666667,16.231797,0.545455,22,False,True
1200,20254,일원본동,60대이상,E_의료건강,5869,6304.333333,-6.905303,0.142857,21,False,False

In [34]:
# ============================================================
# 25. Historical × Relative 이중 변화신호 확인
# ============================================================

signal = valid.copy()

# 상대적 하위/상위 20%
signal["relative_low"] = (
    signal["gangnam_change_percentile"] <= 0.20
)

signal["relative_high"] = (
    signal["gangnam_change_percentile"] >= 0.80
)

# 자기 과거 + 강남구 상대비교가 같은 방향인 경우
signal["dual_low_signal"] = (
    signal["below_historical_min"]
    & signal["relative_low"]
)

signal["dual_high_signal"] = (
    signal["above_historical_max"]
    & signal["relative_high"]
)

print("전체 분석 가능 행:", len(signal))

print("\n이중 감소신호:", signal["dual_low_signal"].sum())
print("이중 증가신호:", signal["dual_high_signal"].sum())

print("\n분기별 이중 변화신호")
print(
    signal.groupby("기준_년분기_코드")[
        ["dual_low_signal", "dual_high_signal"]
    ].sum()
)

print("\n소비영역별 이중 변화신호")
print(
    signal.groupby("소비영역")[
        ["dual_low_signal", "dual_high_signal"]
    ].sum()
)

전체 분석 가능 행: 1287

이중 감소신호: 180
이중 증가신호: 159

분기별 이중 변화신호
           dual_low_signal  dual_high_signal
기준_년분기_코드
20253                   90                91
20254                   90                68

소비영역별 이중 변화신호
           dual_low_signal  dual_high_signal
소비영역
A_외식카페                  34                31
B_여가운동                  31                46
C_대면생활서비스               37                41
D_생활필수                  40                27
E_의료건강                  38                14

In [35]:
print("\n연령대별 이중 변화신호")

print(
    signal.groupby("연령대")[
        ["dual_low_signal", "dual_high_signal"]
    ].sum()
)

연령대별 이중 변화신호
       dual_low_signal  dual_high_signal
연령대
10대                 29                21
20대                 36                 9
30대                 39                23
40대                 35                23
50대                 32                36
60대이상                9                47

In [36]:
# ============================================================
# 26. 동 × 분기 × 연령별 소비영역 변화 패턴 요약
# ============================================================

age_signal_summary = (
    signal
    .groupby([
        "기준_년분기_코드",
        "행정동_코드",
        "행정동명_표준",
        "연령대"
    ], as_index=False)
    .agg(
        observed_domains=("소비영역", "nunique"),
        dual_low_domains=("dual_low_signal", "sum"),
        dual_high_domains=("dual_high_signal", "sum")
    )
)

print("shape:", age_signal_summary.shape)

print("\n이중 감소 영역 수 분포")
print(
    age_signal_summary["dual_low_domains"]
    .value_counts()
    .sort_index()
)

print("\n이중 증가 영역 수 분포")
print(
    age_signal_summary["dual_high_domains"]
    .value_counts()
    .sort_index()
)

shape: (264, 7)

이중 감소 영역 수 분포
dual_low_domains
0    134
1     89
2     33
3      7
4      1
Name: count, dtype: int64

이중 증가 영역 수 분포
dual_high_domains
0    144
1     85
2     31
3      4
Name: count, dtype: int64

In [37]:
target_age_signal = (
    age_signal_summary[
        age_signal_summary["행정동명_표준"].isin(
            ["개포3동", "일원본동", "일원1동", "신사동"]
        )
    ]
    .sort_values([
        "기준_년분기_코드",
        "행정동명_표준",
        "연령대"
    ])
)

display(target_age_signal)

,기준_년분기_코드,행정동_코드,행정동명_표준,연령대,observed_domains,dual_low_domains,dual_high_domains
120,20253,11680740,개포3동,10대,3,1,0
121,20253,11680740,개포3동,20대,4,2,0
122,20253,11680740,개포3동,30대,5,2,0
123,20253,11680740,개포3동,40대,5,0,0
124,20253,11680740,개포3동,50대,5,2,0
125,20253,11680740,개포3동,60대이상,5,0,2
0,20253,11680510,신사동,10대,5,0,0
1,20253,11680510,신사동,20대,5,0,0
2,20253,11680510,신사동,30대,5,0,0
3,20253,11680510,신사동,40대,5,1,1
4,20253,11680510,신사동,50대,5,0,1
5,20253,11680510,신사동,60대이상,5,0,0
114,20253,11680730,일원1동,10대,5,2,0
115,20253,11680730,일원1동,20대,5,1,0
116,20253,11680730,일원1동,30대,5,0,0
117,20253,11680730,일원1동,40대,5,0,1
118,20253,11680730,일원1동,50대,5,1,1
119,20253,11680730,일원1동,60대이상,5,0,1
108,20253,11680720,일원본동,10대,5,0,1
109,20253,11680720,일원본동,20대,5,1,1
110,20253,11680720,일원본동,30대,5,2,1
111,20253,11680720,일원본동,40대,5,0,1
112,20253,11680720,일원본동,50대,5,0,2
113,20253,11680720,일원본동,60대이상,5,0,2
252,20254,11680740,개포3동,10대,2,2,0
253,20254,11680740,개포3동,20대,4,1,1
254,20254,11680740,개포3동,30대,5,2,0
255,20254,11680740,개포3동,40대,5,1,0
256,20254,11680740,개포3동,50대,5,2,0
257,20254,11680740,개포3동,60대이상,5,1,2
132,20254,11680510,신사동,10대,5,0,1
133,20254,11680510,신사동,20대,5,1,0
134,20254,11680510,신사동,30대,5,0,0
135,20254,11680510,신사동,40대,5,0,1
136,20254,11680510,신사동,50대,5,0,2
137,20254,11680510,신사동,60대이상,5,0,0
246,20254,11680730,일원1동,10대,5,1,0
247,20254,11680730,일원1동,20대,5,0,0
248,20254,11680730,일원1동,30대,5,0,1
249,20254,11680730,일원1동,40대,5,0,0
250,20254,11680730,일원1동,50대,5,1,0
251,20254,11680730,일원1동,60대이상,5,0,2
240,20254,11680720,일원본동,10대,5,0,1
241,20254,11680720,일원본동,20대,5,0,0
242,20254,11680720,일원본동,30대,5,1,0
243,20254,11680720,일원본동,40대,5,2,0
244,20254,11680720,일원본동,50대,5,0,2
245,20254,11680720,일원본동,60대이상,5,0,0

In [38]:
# ============================================================
# 27. Analysis 3-A 소비변화 요약 Feature 생성
# ============================================================

age_signal_summary["dual_low_domain_ratio"] = (
    age_signal_summary["dual_low_domains"]
    / age_signal_summary["observed_domains"]
)

age_signal_summary["dual_high_domain_ratio"] = (
    age_signal_summary["dual_high_domains"]
    / age_signal_summary["observed_domains"]
)

# 다영역 변화 여부
# 주의: 위험/고립 판정이 아니라 기술적 패턴 플래그
age_signal_summary["multi_domain_low"] = (
    age_signal_summary["dual_low_domains"] >= 2
)

age_signal_summary["multi_domain_high"] = (
    age_signal_summary["dual_high_domains"] >= 2
)

print("다영역 감소:", age_signal_summary["multi_domain_low"].sum())
print("다영역 증가:", age_signal_summary["multi_domain_high"].sum())

print("\n다영역 감소 비율:")
print(
    age_signal_summary["multi_domain_low"].mean()
)

display(
    age_signal_summary[
        age_signal_summary["multi_domain_low"]
    ]
    .sort_values(
        [
            "기준_년분기_코드",
            "dual_low_domain_ratio"
        ],
        ascending=[True, False]
    )
)

다영역 감소: 41
다영역 증가: 35

다영역 감소 비율:
0.1553030303030303

,기준_년분기_코드,행정동_코드,행정동명_표준,연령대,observed_domains,dual_low_domains,dual_high_domains,dual_low_domain_ratio,dual_high_domain_ratio,multi_domain_low,multi_domain_high
99,20253,11680690,개포4동,40대,5,4,0,0.800000,0.0,True,False
78,20253,11680656,도곡2동,10대,5,3,0,0.600000,0.0,True,False
79,20253,11680656,도곡2동,20대,5,3,0,0.600000,0.0,True,False
100,20253,11680690,개포4동,50대,5,3,1,0.600000,0.2,True,False
121,20253,11680740,개포3동,20대,4,2,0,0.500000,0.0,True,False
19,20253,11680545,압구정동,20대,5,2,0,0.400000,0.0,True,False
20,20253,11680545,압구정동,30대,5,2,0,0.400000,0.0,True,False
30,20253,11680580,삼성1동,10대,5,2,0,0.400000,0.0,True,False
44,20253,11680600,대치1동,30대,5,2,2,0.400000,0.4,True,True
46,20253,11680600,대치1동,50대,5,2,2,0.400000,0.4,True,True
68,20253,11680650,역삼2동,30대,5,2,0,0.400000,0.0,True,False
69,20253,11680650,역삼2동,40대,5,2,0,0.400000,0.0,True,False
80,20253,11680656,도곡2동,30대,5,2,1,0.400000,0.2,True,False
97,20253,11680690,개포4동,20대,5,2,0,0.400000,0.0,True,False
98,20253,11680690,개포4동,30대,5,2,0,0.400000,0.0,True,False
103,20253,11680700,세곡동,20대,5,2,0,0.400000,0.0,True,False
110,20253,11680720,일원본동,30대,5,2,1,0.400000,0.2,True,False
114,20253,11680730,일원1동,10대,5,2,0,0.400000,0.0,True,False
122,20253,11680740,개포3동,30대,5,2,0,0.400000,0.0,True,False
124,20253,11680740,개포3동,50대,5,2,0,0.400000,0.0,True,False
252,20254,11680740,개포3동,10대,2,2,0,1.000000,0.0,True,False
218,20254,11680660,개포1동,30대,3,2,0,0.666667,0.0,True,False
200,20254,11680650,역삼2동,30대,5,3,0,0.600000,0.0,True,False
201,20254,11680650,역삼2동,40대,5,3,0,0.600000,0.0,True,False
211,20254,11680656,도곡2동,20대,5,3,0,0.600000,0.0,True,False
228,20254,11680690,개포4동,10대,5,3,0,0.600000,0.0,True,False
148,20254,11680531,논현2동,50대,5,2,0,0.400000,0.0,True,False
152,20254,11680545,압구정동,30대,5,2,0,0.400000,0.0,True,False
166,20254,11680580,삼성1동,50대,5,2,0,0.400000,0.0,True,False
176,20254,11680600,대치1동,30대,5,2,0,0.400000,0.0,True,False
181,20254,11680610,대치2동,20대,5,2,0,0.400000,0.0,True,False
198,20254,11680650,역삼2동,10대,5,2,0,0.400000,0.0,True,False
199,20254,11680650,역삼2동,20대,5,2,0,0.400000,0.0,True,False
210,20254,11680656,도곡2동,10대,5,2,0,0.400000,0.0,True,False
229,20254,11680690,개포4동,20대,5,2,0,0.400000,0.0,True,False
231,20254,11680690,개포4동,40대,5,2,0,0.400000,0.0,True,False
232,20254,11680690,개포4동,50대,5,2,0,0.400000,0.0,True,False
243,20254,11680720,일원본동,40대,5,2,0,0.400000,0.0,True,False
254,20254,11680740,개포3동,30대,5,2,0,0.400000,0.0,True,False
256,20254,11680740,개포3동,50대,5,2,0,0.400000,0.0,True,False
260,20254,11680750,수서동,30대,5,2,2,0.400000,0.4,True,True

In [39]:
# ============================================================
# 28. Analysis 2 월별 행동신호 → 분기 단위 요약
# ============================================================

analysis2_events = pd.DataFrame({
    "행정동명_표준": [
        "개포3동",
        "개포4동",
        "대치2동",
        "신사동",
        "신사동",

        "개포3동",
        "개포3동",
        "대치4동",
        "도곡1동",
        "일원1동",
        "일원1동",
        "일원본동",
        "일원본동",
        "일원본동"
    ],
    "기준연월": [
        202508,
        202509,
        202508,
        202508,
        202509,

        202510,
        202511,
        202510,
        202512,
        202511,
        202512,
        202510,
        202511,
        202512
    ]
})

# 월 → 분기
analysis2_events["기준_년분기_코드"] = (
    analysis2_events["기준연월"] // 100 * 10
    + ((analysis2_events["기준연월"] % 100 - 1) // 3 + 1)
)

# 동 × 분기 단위 요약
analysis2_quarter = (
    analysis2_events
    .groupby(
        ["행정동명_표준", "기준_년분기_코드"],
        as_index=False
    )
    .agg(
        behavior_signal_months=("기준연월", "nunique"),
        behavior_signal_month_list=(
            "기준연월",
            lambda x: ", ".join(
                sorted(x.astype(str))
            )
        )
    )
)

print("월별 행동신호:", len(analysis2_events))
print("동 × 분기 행동신호:", len(analysis2_quarter))

display(
    analysis2_quarter.sort_values(
        ["기준_년분기_코드", "행정동명_표준"]
    )
)

월별 행동신호: 14
동 × 분기 행동신호: 9

  행정동명_표준  기준_년분기_코드  behavior_signal_months behavior_signal_month_list
0    개포3동      20253                       1                     202508
2    개포4동      20253                       1                     202509
3    대치2동      20253                       1                     202508
6     신사동      20253                       2             202508, 202509
1    개포3동      20254                       2             202510, 202511
4    대치4동      20254                       1                     202510
5    도곡1동      20254                       1                     202512
7    일원1동      20254                       2             202511, 202512
8    일원본동      20254                       3     202510, 202511, 202512

In [41]:
# ============================================================
# 29. 현재 Colab 세션의 신한카드 관련 파일 확인
# ============================================================

import os

files_in_colab = os.listdir("/content")

print("=== /content 전체 파일 ===")
for f in sorted(files_in_colab):
    print(f)

print("\n=== 카드 관련 가능성이 있는 파일 ===")
keywords = [
    "card", "shinhan", "신한",
    "contest", "공모전",
    "gangnam"
]

card_candidates = [
    f for f in files_in_colab
    if any(k.lower() in f.lower() for k in keywords)
]

for f in sorted(card_candidates):
    path = os.path.join("/content", f)

    if os.path.isfile(path):
        size_mb = os.path.getsize(path) / (1024 ** 2)
        print(f"{f}  |  {size_mb:.2f} MB")

=== /content 전체 파일 ===
.config
sample_data
서울시 상권분석서비스(추정매출-행정동)_2024년.csv
서울시 상권분석서비스(추정매출-행정동)_2025년.csv
서울시_상권분석서비스(추정매출-행정동)_2022년.csv
서울시_상권분석서비스(추정매출-행정동)_2023년.csv
신한카드_빅콘테스트2026_데이터2.csv

=== 카드 관련 가능성이 있는 파일 ===
신한카드_빅콘테스트2026_데이터2.csv  |  113.96 MB

In [42]:
import pandas as pd
import os

print("=== CSV 파일 구조 확인 ===")

for f in sorted(files_in_colab):

    if not f.lower().endswith(".csv"):
        continue

    path = os.path.join("/content", f)

    try:
        # 전체 파일을 읽지 않고 헤더와 일부 행만 확인
        sample = pd.read_csv(path, nrows=5)

        print("\n----------------------------------------")
        print("파일:", f)
        print("컬럼 수:", len(sample.columns))
        print("컬럼:", sample.columns.tolist())

        # 신한카드 공모전 원본의 핵심 컬럼 확인
        required = {
            "TA_YMD",
            "MCT_SGG_CD",
            "MCT_RY_CD",
            "SEX_CCD",
            "AGE_CCD",
            "TS_AT",
            "USE_CNT"
        }

        if required.issubset(set(sample.columns)):
            print(">>> ★ 신한카드 공모전 원본 후보")

    except Exception as e:
        print(f"\n{f} 읽기 실패: {e}")

=== CSV 파일 구조 확인 ===

서울시 상권분석서비스(추정매출-행정동)_2024년.csv 읽기 실패: 'utf-8' codec can't decode byte 0xb1 in position 1: invalid start byte

서울시 상권분석서비스(추정매출-행정동)_2025년.csv 읽기 실패: 'utf-8' codec can't decode byte 0xb1 in position 1: invalid start byte

서울시_상권분석서비스(추정매출-행정동)_2022년.csv 읽기 실패: 'utf-8' codec can't decode byte 0xb1 in position 1: invalid start byte

서울시_상권분석서비스(추정매출-행정동)_2023년.csv 읽기 실패: 'utf-8' codec can't decode byte 0xb1 in position 1: invalid start byte

신한카드_빅콘테스트2026_데이터2.csv 읽기 실패: 'utf-8' codec can't decode byte 0xb0 in position 81: invalid start byte

In [43]:
# ============================================================
# 30. 신한카드 공모전 원본 불러오기
# ============================================================

import pandas as pd

shinhan_path = "/content/신한카드_빅콘테스트2026_데이터2.csv"

shinhan_raw = pd.read_csv(
    shinhan_path,
    encoding="cp949"
)

print("shape:", shinhan_raw.shape)

print("\n컬럼:")
print(shinhan_raw.columns.tolist())

print("\n지역:")
print(shinhan_raw["MCT_SGG_CD"].value_counts())

print("\n기간:")
print(
    shinhan_raw["TA_YMD"].min(),
    "~",
    shinhan_raw["TA_YMD"].max()
)

print("\n날짜 수:", shinhan_raw["TA_YMD"].nunique())
print("업종 수:", shinhan_raw["MCT_RY_CD"].nunique())
print("연령대 수:", shinhan_raw["AGE_CCD"].nunique())

print("\n결측치:")
print(shinhan_raw.isna().sum())

shape: (1806800, 9)

컬럼:
['Unnamed: 0', 'TA_YMD', 'MCT_SGG_CD', 'MCT_RY_CD', 'CLN_SGG_CD', 'SEX_CCD', 'AGE_CCD', 'TS_AT', 'USE_CNT']

지역:
MCT_SGG_CD
서울 강남구    1366189
강원 춘천시     440611
Name: count, dtype: int64

기간:
20250701 ~ 20251231

날짜 수: 184
업종 수: 90
연령대 수: 9

결측치:
Unnamed: 0    0
TA_YMD        0
MCT_SGG_CD    0
MCT_RY_CD     0
CLN_SGG_CD    0
SEX_CCD       0
AGE_CCD       0
TS_AT         0
USE_CNT       0
dtype: int64

In [44]:
# ============================================================
# 31. Analysis 3-B
# 강남구 × 월 × 연령 × 업종 Feature Table 생성
# ============================================================

# 강남구만 추출
shinhan_gangnam = shinhan_raw[
    shinhan_raw["MCT_SGG_CD"] == "서울 강남구"
].copy()

# 날짜형 변환
shinhan_gangnam["TA_YMD"] = pd.to_datetime(
    shinhan_gangnam["TA_YMD"].astype(str),
    format="%Y%m%d"
)

# 월 생성
shinhan_gangnam["기준연월"] = (
    shinhan_gangnam["TA_YMD"]
    .dt.strftime("%Y%m")
    .astype(int)
)

# 월 × 연령 × 업종 집계
shinhan_month_age_industry = (
    shinhan_gangnam
    .groupby(
        [
            "기준연월",
            "AGE_CCD",
            "MCT_RY_CD"
        ],
        as_index=False
    )
    .agg(
        이용건수=("USE_CNT", "sum"),
        이용금액=("TS_AT", "sum"),
        관측일수=("TA_YMD", "nunique")
    )
)

print("shape:", shinhan_month_age_industry.shape)

print(
    "월:",
    sorted(shinhan_month_age_industry["기준연월"].unique())
)

print(
    "연령대:",
    sorted(shinhan_month_age_industry["AGE_CCD"].unique())
)

print(
    "업종 수:",
    shinhan_month_age_industry["MCT_RY_CD"].nunique()
)

print(
    "key 중복:",
    shinhan_month_age_industry.duplicated(
        ["기준연월", "AGE_CCD", "MCT_RY_CD"]
    ).sum()
)

print(
    "결측:",
    shinhan_month_age_industry.isna().sum().sum()
)

print("\n관측일수 분포:")
print(
    shinhan_month_age_industry["관측일수"]
    .value_counts()
    .sort_index()
)

shape: (4502, 6)
월: [np.int64(202507), np.int64(202508), np.int64(202509), np.int64(202510), np.int64(202511), np.int64(202512)]
연령대: ['10 대', '20 대', '30 대', '40 대', '50 대', '60 대', '70 대', '80 대', '90 대']
업종 수: 88
key 중복: 0
결측: 0

관측일수 분포:
관측일수
1       89
2       69
3       51
4       33
5       44
6       38
7       40
8       39
9       39
10      29
11      41
12      25
13      23
14      35
15      23
16      24
17      26
18      46
19      54
20      49
21      53
22      44
23      50
24      58
25      59
26      72
27      85
28      80
29     137
30    1101
31    1946
Name: count, dtype: int64

In [45]:
# ============================================================
# 32. 전체 90개 업종 vs 강남구 88개 업종 확인
# ============================================================

all_industries = set(
    shinhan_raw["MCT_RY_CD"].unique()
)

gangnam_industries = set(
    shinhan_gangnam["MCT_RY_CD"].unique()
)

chuncheon_industries = set(
    shinhan_raw.loc[
        shinhan_raw["MCT_SGG_CD"] == "강원 춘천시",
        "MCT_RY_CD"
    ].unique()
)

print("전체 업종:", len(all_industries))
print("강남구 업종:", len(gangnam_industries))
print("춘천시 업종:", len(chuncheon_industries))

print("\n=== 전체에는 있지만 강남구에는 없는 업종 ===")
print(sorted(all_industries - gangnam_industries))

print("\n=== 강남구에는 있지만 춘천시에는 없는 업종 ===")
print(sorted(gangnam_industries - chuncheon_industries))

print("\n=== 춘천시에만 존재하는 업종 ===")
print(sorted(chuncheon_industries - gangnam_industries))

전체 업종: 90
강남구 업종: 88
춘천시 업종: 85

=== 전체에는 있지만 강남구에는 없는 업종 ===
['종합레저타운/놀이동산', '학교등록금']

=== 강남구에는 있지만 춘천시에는 없는 업종 ===
['결제대행(PG)', '면세점', '백화점', '수입자동차', '통신요금(이동,시내전화)']

=== 춘천시에만 존재하는 업종 ===
['종합레저타운/놀이동산', '학교등록금']

In [46]:
print("\n=== 강남구 월별 관측 업종 수 ===")
print(
    shinhan_gangnam
    .groupby("기준연월")["MCT_RY_CD"]
    .nunique()
)

print("\n=== 강남구 연령별 관측 업종 수 ===")
print(
    shinhan_gangnam
    .groupby("AGE_CCD")["MCT_RY_CD"]
    .nunique()
    .sort_index()
)

print("\n=== 월 × 연령별 관측 업종 수 ===")
display(
    shinhan_gangnam
    .groupby(
        ["기준연월", "AGE_CCD"]
    )["MCT_RY_CD"]
    .nunique()
    .unstack()
)

=== 강남구 월별 관측 업종 수 ===
기준연월
202507    88
202508    88
202509    88
202510    88
202511    88
202512    87
Name: MCT_RY_CD, dtype: int64

=== 강남구 연령별 관측 업종 수 ===
AGE_CCD
10 대    82
20 대    87
30 대    87
40 대    88
50 대    88
60 대    87
70 대    87
80 대    87
90 대    77
Name: MCT_RY_CD, dtype: int64

=== 월 × 연령별 관측 업종 수 ===

AGE_CCD  10 대  20 대  30 대  40 대  50 대  60 대  70 대  80 대  90 대
기준연월
202507     80    87    87    87    88    87    87    84    67
202508     80    87    87    88    88    86    86    85    65
202509     77    86    87    88    88    86    86    83    62
202510     80    86    87    87    87    87    86    84    69
202511     77    86    87    88    87    87    86    83    69
202512     80    86    87    87    87    86    86    83    68

In [47]:
# ============================================================
# 33. Analysis 3-B
# 월 길이를 보정한 일평균 이용건수 생성
# ============================================================

import calendar

shinhan_month_age_industry["연도"] = (
    shinhan_month_age_industry["기준연월"] // 100
)

shinhan_month_age_industry["월"] = (
    shinhan_month_age_industry["기준연월"] % 100
)

# 실제 달력 일수
shinhan_month_age_industry["월일수"] = (
    shinhan_month_age_industry.apply(
        lambda x: calendar.monthrange(
            int(x["연도"]),
            int(x["월"])
        )[1],
        axis=1
    )
)

# 월 전체 일수 기준 일평균
shinhan_month_age_industry["일평균_이용건수"] = (
    shinhan_month_age_industry["이용건수"]
    / shinhan_month_age_industry["월일수"]
)

# 검증
print(
    shinhan_month_age_industry[
        ["기준연월", "월일수"]
    ]
    .drop_duplicates()
    .sort_values("기준연월")
)

print("\n일평균 이용건수 결측:",
      shinhan_month_age_industry["일평균_이용건수"].isna().sum())

print(
    "일평균 이용건수 <= 0:",
    (shinhan_month_age_industry["일평균_이용건수"] <= 0).sum()
)

        기준연월  월일수
0     202507   31
754   202508   31
1506  202509   30
2249  202510   31
3002  202511   30
3752  202512   31

일평균 이용건수 결측: 0
일평균 이용건수 <= 0: 0

In [48]:
# ============================================================
# 34. Analysis 3-B
# 연령대 × 월 전체 소비활동 기준선 생성
# ============================================================

age_month_baseline = (
    shinhan_month_age_industry
    .groupby(
        ["기준연월", "AGE_CCD"],
        as_index=False
    )
    .agg(
        월이용건수=("이용건수", "sum")
    )
)

# 월 일수
days_map = {
    202507: 31,
    202508: 31,
    202509: 30,
    202510: 31,
    202511: 30,
    202512: 31
}

age_month_baseline["월일수"] = (
    age_month_baseline["기준연월"].map(days_map)
)

age_month_baseline["일평균_전체이용건수"] = (
    age_month_baseline["월이용건수"]
    / age_month_baseline["월일수"]
)

# 전월 대비 변화율
age_month_baseline = age_month_baseline.sort_values(
    ["AGE_CCD", "기준연월"]
)

age_month_baseline["전월대비_pct"] = (
    age_month_baseline
    .groupby("AGE_CCD")["일평균_전체이용건수"]
    .pct_change(fill_method=None)
    * 100
)

print("shape:", age_month_baseline.shape)
print(
    "key 중복:",
    age_month_baseline.duplicated(
        ["기준연월", "AGE_CCD"]
    ).sum()
)

display(
    age_month_baseline.pivot(
        index="AGE_CCD",
        columns="기준연월",
        values="전월대비_pct"
    ).round(2)
)

shape: (54, 6)
key 중복: 0

기준연월     202507  202508  202509  202510  202511  202512
AGE_CCD
10 대        NaN   -2.78   -1.08   -1.56    0.73    3.50
20 대        NaN    0.31    1.89   -5.16    5.31   -0.93
30 대        NaN   -1.38    3.65   -5.17    4.78   -1.68
40 대        NaN   -2.94    3.04   -5.04    3.86   -0.44
50 대        NaN   -3.77    3.43   -5.51    3.56    1.03
60 대        NaN   -4.46    7.32   -8.63    3.76    2.10
70 대        NaN   -6.51   11.83  -11.61    3.18    2.46
80 대        NaN   -7.04   12.28  -13.68    3.20    0.30
90 대        NaN   -9.27    4.88  -13.06   -0.78    6.49

In [49]:
# ============================================================
# 35. Analysis 3-B
# 연령 전체 기준선 대비 개별 업종의 상대적 월 변화 계산
# ============================================================

industry_change = shinhan_month_age_industry.copy()

industry_change = industry_change.sort_values(
    ["AGE_CCD", "MCT_RY_CD", "기준연월"]
)

# 개별 연령 × 업종의 일평균 이용건수 전월 대비 변화율
industry_change["업종_전월대비_pct"] = (
    industry_change
    .groupby(
        ["AGE_CCD", "MCT_RY_CD"]
    )["일평균_이용건수"]
    .pct_change(fill_method=None)
    * 100
)

# 연령 전체 기준선 결합
industry_change = industry_change.merge(
    age_month_baseline[
        [
            "기준연월",
            "AGE_CCD",
            "전월대비_pct"
        ]
    ].rename(
        columns={
            "전월대비_pct": "연령전체_전월대비_pct"
        }
    ),
    on=["기준연월", "AGE_CCD"],
    how="left",
    validate="many_to_one"
)

# 연령 전체 변화와 비교한 업종의 상대 변화
industry_change["업종_상대변화_pp"] = (
    industry_change["업종_전월대비_pct"]
    - industry_change["연령전체_전월대비_pct"]
)

print("shape:", industry_change.shape)

print(
    "key 중복:",
    industry_change.duplicated(
        ["기준연월", "AGE_CCD", "MCT_RY_CD"]
    ).sum()
)

# 7월은 전월 자료가 없으므로 제외
valid_industry_change = industry_change[
    industry_change["기준연월"] >= 202508
].copy()

print("\n상대변화 계산 가능:",
      valid_industry_change["업종_상대변화_pp"].notna().sum())

print(
    "상대변화 계산 불가:",
    valid_industry_change["업종_상대변화_pp"].isna().sum()
)

print("\n상대변화 분포:")
print(
    valid_industry_change["업종_상대변화_pp"]
    .describe()
)

shape: (4502, 13)
key 중복: 0

상대변화 계산 가능: 3732
상대변화 계산 불가: 16

상대변화 분포:
count    3732.000000
mean        5.830377
std        46.135826
min       -93.490021
25%        -8.111623
50%         0.338745
75%         9.379905
max       888.815125
Name: 업종_상대변화_pp, dtype: float64

In [50]:
# ============================================================
# 36. Analysis 3-B
# 변화율 계산불가 원인 + 저빈도 업종 규모 확인
# ============================================================

# ① 상대변화 계산 불가 사례
invalid_change = valid_industry_change[
    valid_industry_change["업종_상대변화_pp"].isna()
].copy()

print("=== 상대변화 계산 불가 사례 ===")
display(
    invalid_change[
        [
            "기준연월",
            "AGE_CCD",
            "MCT_RY_CD",
            "이용건수",
            "일평균_이용건수",
            "업종_전월대비_pct",
            "연령전체_전월대비_pct"
        ]
    ].sort_values(
        ["AGE_CCD", "MCT_RY_CD", "기준연월"]
    )
)


# ② 이용건수 분포
print("\n=== 월 × 연령 × 업종 이용건수 분포 ===")
print(
    valid_industry_change["이용건수"]
    .describe(
        percentiles=[
            .01, .05, .10, .25,
            .50, .75, .90, .95, .99
        ]
    )
)


# ③ 상대변화 극단값의 실제 이용건수 확인
print("\n=== 상대변화 절댓값 상위 20건 ===")

extreme_change = (
    valid_industry_change[
        valid_industry_change["업종_상대변화_pp"].notna()
    ]
    .assign(
        abs_relative_change=lambda x:
        x["업종_상대변화_pp"].abs()
    )
    .nlargest(
        20,
        "abs_relative_change"
    )
)

display(
    extreme_change[
        [
            "기준연월",
            "AGE_CCD",
            "MCT_RY_CD",
            "이용건수",
            "일평균_이용건수",
            "업종_전월대비_pct",
            "연령전체_전월대비_pct",
            "업종_상대변화_pp"
        ]
    ]
)

=== 상대변화 계산 불가 사례 ===

        기준연월 AGE_CCD    MCT_RY_CD  이용건수  일평균_이용건수  업종_전월대비_pct  연령전체_전월대비_pct
127   202510    10 대     법률/사무서비스     5  0.161290          NaN      -1.557235
317   202509    10 대        자동차용품     6  0.200000          NaN      -1.080223
1916  202508    40 대        중고차판매    15  0.483871          NaN      -2.944928
3748  202508    80 대        부동산중개     5  0.161290          NaN      -7.038553
3897  202508    80 대         유흥업소     5  0.161290          NaN      -7.038553
4023  202508    80 대           택시     5  0.161290          NaN      -7.038553
4182  202508    90 대        미용서비스    10  0.322581          NaN      -9.267155
4203  202511    90 대     법률/사무서비스     5  0.166667          NaN      -0.776187
4211  202511    90 대        부동산중개     5  0.166667          NaN      -0.776187
4272  202509    90 대     실내/실외골프장     6  0.200000          NaN       4.879348
4281  202510    90 대       안마/마사지     5  0.161290          NaN     -13.061519
4299  202508    90 대      여행사/항공사    10  0.322581          NaN      -9.267155
4314  202508    90 대    예식장/결혼서비스     5  0.161290          NaN      -9.267155
4315  202510    90 대    완구/아동용자전거     6  0.193548          NaN     -13.061519
4353  202508    90 대  장례식장/묘지/장의사    12  0.387097          NaN      -9.267155
4381  202509    90 대         주류판매     5  0.166667          NaN       4.879348

=== 월 × 연령 × 업종 이용건수 분포 ===
count    3.748000e+03
mean     1.152610e+05
std      4.590164e+05
min      5.000000e+00
1%       5.000000e+00
5%       2.600000e+01
10%      7.100000e+01
25%      5.210000e+02
50%      4.859000e+03
75%      2.868825e+04
90%      1.508842e+05
95%      5.016345e+05
99%      2.882073e+06
max      4.369689e+06
Name: 이용건수, dtype: float64

=== 상대변화 절댓값 상위 20건 ===

,기준연월,AGE_CCD,MCT_RY_CD,이용건수,일평균_이용건수,업종_전월대비_pct,연령전체_전월대비_pct,업종_상대변화_pp
3291,202511,70 대,수제용품점,48,1.600000,892.000000,3.184875,888.815125
3118,202512,70 대,결제대행(PG),51,1.645161,887.096774,2.461326,884.635448
1758,202511,40 대,악기/음반,5538,184.600000,668.134228,3.855534,664.278694
3289,202509,70 대,수제용품점,36,1.200000,520.000000,11.831669,508.168331
3898,202509,80 대,유흥업소,30,1.000000,520.000000,12.277900,507.722100
211,202512,10 대,실내/실외골프장,37,1.193548,496.774194,3.503469,493.270724
4308,202512,90 대,연구/번역서비스,58,1.870968,461.290323,6.488117,454.802206
1433,202510,30 대,택시,27,0.870968,422.580645,-5.173707,427.754353
3325,202509,70 대,악기/음반,333,11.100000,398.695652,11.831669,386.863983
3681,202510,80 대,독서실,28,0.903226,351.612903,-13.682471,365.295374
3235,202509,70 대,부동산중개,68,2.266667,339.166667,11.831669,327.334998
222,202511,10 대,악기/음반,868,28.933333,327.111111,0.725651,326.385460
4306,202510,90 대,연구/번역서비스,21,0.677419,306.451613,-13.061519,319.513132
363,202510,10 대,중고품판매점,25,0.806452,316.666667,-1.557235,318.223902
89,202508,10 대,면세점,24,0.774194,300.000000,-2.784252,302.784252
3750,202512,80 대,부동산중개,20,0.645161,287.096774,0.296649,286.800125
718,202511,20 대,악기/음반,7529,250.966667,287.255683,5.309455,281.946227
1236,202511,30 대,악기/음반,7147,238.233333,285.249522,4.775616,280.473906
4407,202508,90 대,체인점,37,1.193548,270.000000,-9.267155,279.267155
1007,202510,30 대,가구,3760,121.290323,256.386844,-5.173707,261.560551

In [51]:
# ============================================================
# 37. Analysis 3-B
# 신한카드 업종 → 5개 소비영역 분류
# ============================================================

domain_map = {

    # A. 외식·카페
    "한식": "A_외식카페",
    "중식": "A_외식카페",
    "일식": "A_외식카페",
    "양식": "A_외식카페",
    "기타요식": "A_외식카페",
    "커피전문점": "A_외식카페",
    "제과점": "A_외식카페",
    "패스트푸드": "A_외식카페",

    # B. 여가·운동
    "영화/공연": "B_여가운동",
    "노래방": "B_여가운동",
    "게임방/오락실": "B_여가운동",
    "스포츠시설": "B_여가운동",
    "실내/실외골프장": "B_여가운동",
    "헬스장": "B_여가운동",

    # C. 대면 생활서비스
    "미용실": "C_대면생활서비스",
    "미용서비스": "C_대면생활서비스",
    "세탁소": "C_대면생활서비스",
    "싸우나/목욕탕": "C_대면생활서비스",

    # D. 생활필수
    "편의점": "D_생활필수",
    "할인점/슈퍼마켓/양판점": "D_생활필수",
    "농수산물": "D_생활필수",
    "정육점": "D_생활필수",
    "기타식품": "D_생활필수",

    # E. 의료·건강
    "약국": "E_의료건강",
    "일반병원": "E_의료건강",
    "종합병원": "E_의료건강",
    "치과병원": "E_의료건강",
    "한의원": "E_의료건강",
    "보건소": "E_의료건강"
}

# 분류 적용
shinhan_domain = shinhan_gangnam.copy()

shinhan_domain["소비영역"] = (
    shinhan_domain["MCT_RY_CD"].map(domain_map)
)

# 핵심 5개 영역만 추출
shinhan_domain_core = shinhan_domain[
    shinhan_domain["소비영역"].notna()
].copy()

print("전체 강남구 행:", len(shinhan_domain))
print("5개 영역 포함 행:", len(shinhan_domain_core))
print(
    "포함 비율:",
    round(len(shinhan_domain_core) / len(shinhan_domain) * 100, 2),
    "%"
)

print("\n=== 영역별 업종 수 ===")
print(
    shinhan_domain_core
    .groupby("소비영역")["MCT_RY_CD"]
    .nunique()
)

print("\n=== 실제 포함 업종 ===")
for domain, g in shinhan_domain_core.groupby("소비영역"):
    print(f"\n{domain}")
    print(sorted(g["MCT_RY_CD"].unique()))

전체 강남구 행: 1366189
5개 영역 포함 행: 591167
포함 비율: 43.27 %

=== 영역별 업종 수 ===
소비영역
A_외식카페       8
B_여가운동       6
C_대면생활서비스    4
D_생활필수       5
E_의료건강       6
Name: MCT_RY_CD, dtype: int64

=== 실제 포함 업종 ===

A_외식카페
['기타요식', '양식', '일식', '제과점', '중식', '커피전문점', '패스트푸드', '한식']

B_여가운동
['게임방/오락실', '노래방', '스포츠시설', '실내/실외골프장', '영화/공연', '헬스장']

C_대면생활서비스
['미용서비스', '미용실', '세탁소', '싸우나/목욕탕']

D_생활필수
['기타식품', '농수산물', '정육점', '편의점', '할인점/슈퍼마켓/양판점']

E_의료건강
['보건소', '약국', '일반병원', '종합병원', '치과병원', '한의원']

In [52]:
# ============================================================
# 38. Analysis 3-B
# 월 × 연령 × 소비영역 이용건수 집계 및 변화율 계산
# ============================================================

import calendar

# 월 × 연령 × 소비영역 집계
age_domain_month = (
    shinhan_domain_core
    .groupby(
        ["기준연월", "AGE_CCD", "소비영역"],
        as_index=False
    )
    .agg(
        이용건수=("USE_CNT", "sum"),
        이용금액=("TS_AT", "sum"),
        포함업종수=("MCT_RY_CD", "nunique")
    )
)

# 월 일수
age_domain_month["연도"] = (
    age_domain_month["기준연월"] // 100
)

age_domain_month["월"] = (
    age_domain_month["기준연월"] % 100
)

age_domain_month["월일수"] = age_domain_month.apply(
    lambda x: calendar.monthrange(
        int(x["연도"]),
        int(x["월"])
    )[1],
    axis=1
)

# 월 길이 보정
age_domain_month["일평균_이용건수"] = (
    age_domain_month["이용건수"]
    / age_domain_month["월일수"]
)

# 정렬
age_domain_month = age_domain_month.sort_values(
    ["AGE_CCD", "소비영역", "기준연월"]
)

# 소비영역 자체의 전월 대비 변화율
age_domain_month["영역_전월대비_pct"] = (
    age_domain_month
    .groupby(
        ["AGE_CCD", "소비영역"]
    )["일평균_이용건수"]
    .pct_change(fill_method=None)
    * 100
)

# 앞에서 만든 연령 전체 소비 기준선 결합
age_domain_month = age_domain_month.merge(
    age_month_baseline[
        [
            "기준연월",
            "AGE_CCD",
            "전월대비_pct"
        ]
    ].rename(
        columns={
            "전월대비_pct":
            "연령전체_전월대비_pct"
        }
    ),
    on=["기준연월", "AGE_CCD"],
    how="left",
    validate="many_to_one"
)

# 연령 전체 흐름 대비 소비영역 상대변화
age_domain_month["영역_상대변화_pp"] = (
    age_domain_month["영역_전월대비_pct"]
    - age_domain_month["연령전체_전월대비_pct"]
)

# ------------------------------------------------------------
# 검증
# ------------------------------------------------------------

print("shape:", age_domain_month.shape)

print(
    "key 중복:",
    age_domain_month.duplicated(
        ["기준연월", "AGE_CCD", "소비영역"]
    ).sum()
)

print(
    "결측:",
    age_domain_month.isna().sum()
)

print("\n=== 월 × 연령별 소비영역 수 ===")
display(
    age_domain_month
    .groupby(
        ["기준연월", "AGE_CCD"]
    )["소비영역"]
    .nunique()
    .unstack()
)

print("\n=== 8~12월 영역 상대변화 분포 ===")

print(
    age_domain_month.loc[
        age_domain_month["기준연월"] >= 202508,
        "영역_상대변화_pp"
    ].describe()
)

shape: (270, 13)
key 중복: 0
결측: 기준연월              0
AGE_CCD           0
소비영역              0
이용건수              0
이용금액              0
포함업종수             0
연도                0
월                 0
월일수               0
일평균_이용건수          0
영역_전월대비_pct      45
연령전체_전월대비_pct    45
영역_상대변화_pp       45
dtype: int64

=== 월 × 연령별 소비영역 수 ===

AGE_CCD  10 대  20 대  30 대  40 대  50 대  60 대  70 대  80 대  90 대
기준연월
202507      5     5     5     5     5     5     5     5     5
202508      5     5     5     5     5     5     5     5     5
202509      5     5     5     5     5     5     5     5     5
202510      5     5     5     5     5     5     5     5     5
202511      5     5     5     5     5     5     5     5     5
202512      5     5     5     5     5     5     5     5     5

=== 8~12월 영역 상대변화 분포 ===
count    225.000000
mean       0.818447
std       19.550867
min      -74.349045
25%       -3.674680
50%       -0.181209
75%        4.014052
max      225.716605
Name: 영역_상대변화_pp, dtype: float64

In [53]:
# ============================================================
# 39. Analysis 2 행동신호 월
# × Analysis 3-B 신한카드 월별 소비맥락 연결
# ============================================================

behavior_card_context = analysis2_events.merge(
    age_domain_month[
        [
            "기준연월",
            "AGE_CCD",
            "소비영역",
            "이용건수",
            "일평균_이용건수",
            "영역_전월대비_pct",
            "연령전체_전월대비_pct",
            "영역_상대변화_pp"
        ]
    ],
    on="기준연월",
    how="left",
    validate="many_to_many"
)

print("Analysis 2 행동신호:", len(analysis2_events))
print("결합 후 행:", len(behavior_card_context))

print(
    "행동신호 동×월:",
    behavior_card_context[
        ["행정동명_표준", "기준연월"]
    ].drop_duplicates().shape[0]
)

print(
    "연령대 수:",
    behavior_card_context["AGE_CCD"].nunique()
)

print(
    "소비영역 수:",
    behavior_card_context["소비영역"].nunique()
)

print(
    "상대변화 결측:",
    behavior_card_context["영역_상대변화_pp"].isna().sum()
)

# 월별 행동신호 동 수 확인
print("\n=== 월별 행동신호 동 수 ===")
print(
    analysis2_events
    .groupby("기준연월")["행정동명_표준"]
    .nunique()
)

# 연결 결과 일부 확인
display(
    behavior_card_context[
        [
            "행정동명_표준",
            "기준연월",
            "AGE_CCD",
            "소비영역",
            "영역_전월대비_pct",
            "연령전체_전월대비_pct",
            "영역_상대변화_pp"
        ]
    ]
    .sort_values(
        [
            "기준연월",
            "행정동명_표준",
            "AGE_CCD",
            "소비영역"
        ]
    )
    .head(30)
)

Analysis 2 행동신호: 14
결합 후 행: 630
행동신호 동×월: 14
연령대 수: 9
소비영역 수: 5
상대변화 결측: 0

=== 월별 행동신호 동 수 ===
기준연월
202508    3
202509    2
202510    3
202511    3
202512    3
Name: 행정동명_표준, dtype: int64

   행정동명_표준    기준연월 AGE_CCD       소비영역  영역_전월대비_pct  연령전체_전월대비_pct  영역_상대변화_pp
0     개포3동  202508    10 대     A_외식카페    -0.461302      -2.784252    2.322951
1     개포3동  202508    10 대     B_여가운동   -26.133789      -2.784252  -23.349536
2     개포3동  202508    10 대  C_대면생활서비스    12.624886      -2.784252   15.409139
3     개포3동  202508    10 대     D_생활필수     0.714719      -2.784252    3.498972
4     개포3동  202508    10 대     E_의료건강    -3.147737      -2.784252   -0.363484
5     개포3동  202508    20 대     A_외식카페     0.689130       0.307033    0.382097
6     개포3동  202508    20 대     B_여가운동     6.295058       0.307033    5.988025
7     개포3동  202508    20 대  C_대면생활서비스     7.583206       0.307033    7.276173
8     개포3동  202508    20 대     D_생활필수     0.554331       0.307033    0.247298
9     개포3동  202508    20 대     E_의료건강    -1.317050       0.307033   -1.624083
10    개포3동  202508    30 대     A_외식카페    -2.072850      -1.378374   -0.694476
11    개포3동  202508    30 대     B_여가운동     0.537010      -1.378374    1.915385
12    개포3동  202508    30 대  C_대면생활서비스     2.351222      -1.378374    3.729596
13    개포3동  202508    30 대     D_생활필수    -1.526486      -1.378374   -0.148112
14    개포3동  202508    30 대     E_의료건강    -3.672134      -1.378374   -2.293759
15    개포3동  202508    40 대     A_외식카페    -3.127788      -2.944928   -0.182861
16    개포3동  202508    40 대     B_여가운동    -2.625999      -2.944928    0.318929
17    개포3동  202508    40 대  C_대면생활서비스    -1.885056      -2.944928    1.059872
18    개포3동  202508    40 대     D_생활필수    -1.938324      -2.944928    1.006604
19    개포3동  202508    40 대     E_의료건강    -6.928240      -2.944928   -3.983312
20    개포3동  202508    50 대     A_외식카페    -1.681308      -3.767228    2.085920
21    개포3동  202508    50 대     B_여가운동    -3.227838      -3.767228    0.539390
22    개포3동  202508    50 대  C_대면생활서비스    -1.240728      -3.767228    2.526501
23    개포3동  202508    50 대     D_생활필수    -1.593012      -3.767228    2.174216
24    개포3동  202508    50 대     E_의료건강    -5.608381      -3.767228   -1.841152
25    개포3동  202508    60 대     A_외식카페    -0.493812      -4.458532    3.964720
26    개포3동  202508    60 대     B_여가운동    -2.475381      -4.458532    1.983151
27    개포3동  202508    60 대  C_대면생활서비스     1.874065      -4.458532    6.332597
28    개포3동  202508    60 대     D_생활필수    -2.954717      -4.458532    1.503816
29    개포3동  202508    60 대     E_의료건강    -6.849036      -4.458532   -2.390504

In [55]:
# ============================================================
# 40-1. dual_low_signal이 저장된 데이터프레임 확인
# ============================================================

candidate_dfs = [
    "card_detection",
    "valid",
    "age_signal_summary",
    "behavior_card_context"
]

for name in candidate_dfs:
    if name in globals():
        df = globals()[name]

        print(f"\n=== {name} ===")
        print("shape:", df.shape)

        signal_cols = [
            c for c in df.columns
            if any(
                keyword in c.lower()
                for keyword in [
                    "dual",
                    "historical",
                    "percentile",
                    "signal"
                ]
            )
        ]

        print("관련 컬럼:")
        print(signal_cols)

print("\n=== card_detection 전체 컬럼 ===")
if "card_detection" in globals():
    print(card_detection.columns.tolist())

=== card_detection ===
shape: (1296, 18)
관련 컬럼:
['below_historical_min', 'above_historical_max']

=== valid ===
shape: (1287, 20)
관련 컬럼:
['below_historical_min', 'above_historical_max', 'gangnam_change_percentile']

=== age_signal_summary ===
shape: (264, 11)
관련 컬럼:
['dual_low_domains', 'dual_high_domains', 'dual_low_domain_ratio', 'dual_high_domain_ratio']

=== behavior_card_context ===
shape: (630, 10)
관련 컬럼:
[]

=== card_detection 전체 컬럼 ===
['행정동_코드', '행정동명_표준', '연령대', '소비영역', '분기', '기준_년분기_코드', 'current_count', 'current_industry_count', 'baseline_mean', 'baseline_median', 'baseline_std', 'baseline_n', 'baseline_min', 'baseline_max', 'change_from_mean', 'change_rate_pct', 'below_historical_min', 'above_historical_max']

In [56]:
# ============================================================
# 40. dual signal 복원 후
# Analysis 2 행동신호 × Analysis 3-A 연결
# ============================================================

# ------------------------------------------------------------
# 1) 기존 정의 그대로 dual signal 복원
# ------------------------------------------------------------

valid = valid.copy()

valid["dual_low_signal"] = (
    valid["below_historical_min"]
    & (valid["gangnam_change_percentile"] <= 0.20)
)

valid["dual_high_signal"] = (
    valid["above_historical_max"]
    & (valid["gangnam_change_percentile"] >= 0.80)
)

print("=== dual signal 복원 검증 ===")
print("dual-low :", valid["dual_low_signal"].sum())
print("dual-high:", valid["dual_high_signal"].sum())


# ------------------------------------------------------------
# 2) Analysis 2의 동 × 분기 key
# ------------------------------------------------------------

behavior_quarter_keys = (
    analysis2_quarter[
        [
            "행정동명_표준",
            "기준_년분기_코드",
            "behavior_signal_months",
            "behavior_signal_month_list"
        ]
    ]
    .drop_duplicates()
)

print("\nAnalysis 2 동×분기 사례:",
      len(behavior_quarter_keys))


# ------------------------------------------------------------
# 3) Analysis 3-A dual-low만 추출
# ------------------------------------------------------------

card_3a_low = valid[
    valid["dual_low_signal"]
].copy()


# ------------------------------------------------------------
# 4) Analysis 2 발생 동×분기와 연결
# ------------------------------------------------------------

behavior_3a_low = behavior_quarter_keys.merge(
    card_3a_low,
    on=[
        "행정동명_표준",
        "기준_년분기_코드"
    ],
    how="inner",
    validate="one_to_many"
)

print(
    "3-A dual-low 연결 행:",
    len(behavior_3a_low)
)

print(
    "dual-low가 하나 이상 있는 동×분기:",
    behavior_3a_low[
        [
            "행정동명_표준",
            "기준_년분기_코드"
        ]
    ].drop_duplicates().shape[0]
)


# ------------------------------------------------------------
# 5) 결과 확인
# ------------------------------------------------------------

show_cols = [
    "행정동명_표준",
    "기준_년분기_코드",
    "behavior_signal_months",
    "behavior_signal_month_list",
    "연령대",
    "소비영역",
    "change_rate_pct",
    "gangnam_change_percentile",
    "dual_low_signal"
]

display(
    behavior_3a_low[show_cols]
    .sort_values(
        [
            "기준_년분기_코드",
            "행정동명_표준",
            "연령대",
            "소비영역"
        ]
    )
)

=== dual signal 복원 검증 ===
dual-low : 180
dual-high: 159

Analysis 2 동×분기 사례: 9
3-A dual-low 연결 행: 36
dual-low가 하나 이상 있는 동×분기: 7

,행정동명_표준,기준_년분기_코드,behavior_signal_months,behavior_signal_month_list,연령대,소비영역,change_rate_pct,gangnam_change_percentile,dual_low_signal
0,개포3동,20253,1,202508,10대,A_외식카페,-47.902098,0.047619,True
1,개포3동,20253,1,202508,20대,A_외식카페,-40.094276,0.136364,True
2,개포3동,20253,1,202508,20대,E_의료건강,-56.532988,0.095238,True
3,개포3동,20253,1,202508,30대,A_외식카페,-18.992558,0.136364,True
4,개포3동,20253,1,202508,30대,E_의료건강,-31.306598,0.142857,True
5,개포3동,20253,1,202508,50대,A_외식카페,-28.118812,0.090909,True
6,개포3동,20253,1,202508,50대,C_대면생활서비스,-23.545074,0.045455,True
16,개포4동,20253,1,202509,20대,B_여가운동,-91.583945,0.100000,True
17,개포4동,20253,1,202509,20대,C_대면생활서비스,-43.04579,0.136364,True
18,개포4동,20253,1,202509,30대,B_여가운동,-71.219627,0.095238,True
19,개포4동,20253,1,202509,30대,E_의료건강,-28.233622,0.190476,True
20,개포4동,20253,1,202509,40대,B_여가운동,-61.306348,0.047619,True
21,개포4동,20253,1,202509,40대,C_대면생활서비스,-30.188929,0.090909,True
22,개포4동,20253,1,202509,40대,D_생활필수,-23.215114,0.090909,True
23,개포4동,20253,1,202509,40대,E_의료건강,-32.428256,0.047619,True
24,개포4동,20253,1,202509,50대,C_대면생활서비스,-13.07626,0.181818,True
25,개포4동,20253,1,202509,50대,D_생활필수,-9.042918,0.090909,True
26,개포4동,20253,1,202509,50대,E_의료건강,-18.289025,0.142857,True
27,개포4동,20253,1,202509,60대이상,E_의료건강,-9.149871,0.142857,True
30,신사동,20253,2,"202508, 202509",40대,A_외식카페,-10.755537,0.181818,True
7,개포3동,20254,2,"202510, 202511",10대,A_외식카페,-68.320831,0.090909,True
8,개포3동,20254,2,"202510, 202511",10대,D_생활필수,-40.991129,0.181818,True
9,개포3동,20254,2,"202510, 202511",20대,E_의료건강,-41.589404,0.095238,True
10,개포3동,20254,2,"202510, 202511",30대,A_외식카페,-29.133858,0.045455,True
11,개포3동,20254,2,"202510, 202511",30대,B_여가운동,-79.787234,0.095238,True
12,개포3동,20254,2,"202510, 202511",40대,A_외식카페,-26.405617,0.045455,True
13,개포3동,20254,2,"202510, 202511",50대,A_외식카페,-36.780371,0.045455,True
14,개포3동,20254,2,"202510, 202511",50대,E_의료건강,-19.293246,0.095238,True
15,개포3동,20254,2,"202510, 202511",60대이상,E_의료건강,-53.533624,0.047619,True
28,도곡1동,20254,1,202512,20대,C_대면생활서비스,-36.437167,0.181818,True
29,도곡1동,20254,1,202512,30대,C_대면생활서비스,-35.370058,0.181818,True
31,일원1동,20254,2,"202511, 202512",10대,C_대면생활서비스,-37.086093,0.190476,True
32,일원1동,20254,2,"202511, 202512",50대,A_외식카페,-8.866545,0.181818,True
33,일원본동,20254,3,"202510, 202511, 202512",30대,E_의료건강,-35.390676,0.047619,True
34,일원본동,20254,3,"202510, 202511, 202512",40대,A_외식카페,-22.587474,0.090909,True
35,일원본동,20254,3,"202510, 202511, 202512",40대,E_의료건강,-19.918843,0.190476,True

In [57]:
# ============================================================
# 41. Analysis 2 × 3-A × 3-B 연결
# 우선 연령 정의가 동일한 10~50대
# ============================================================

# 1) 행동신호 발생월을 실제 행으로 펼치기
behavior_3a_month = behavior_3a_low.copy()

behavior_3a_month["기준연월"] = (
    behavior_3a_month["behavior_signal_month_list"]
    .str.split(", ")
)

behavior_3a_month = behavior_3a_month.explode("기준연월")

behavior_3a_month["기준연월"] = (
    behavior_3a_month["기준연월"].astype(int)
)

# 2) 3-A와 3-B에서 연령 정의가 동일한 연령만
same_age = ["10대", "20대", "30대", "40대", "50대"]

behavior_3a_month_same_age = behavior_3a_month[
    behavior_3a_month["연령대"].isin(same_age)
].copy()

# 신한카드는 '10 대'처럼 공백이 있으므로 표준화
card_3b = age_domain_month.copy()

card_3b["연령대"] = (
    card_3b["AGE_CCD"]
    .str.replace(" ", "", regex=False)
)

# 3) 실제 행동신호 월 × 동일 연령 × 동일 소비영역으로 연결
analysis_2_3a_3b = behavior_3a_month_same_age.merge(
    card_3b[
        [
            "기준연월",
            "연령대",
            "소비영역",
            "영역_전월대비_pct",
            "연령전체_전월대비_pct",
            "영역_상대변화_pp"
        ]
    ],
    on=[
        "기준연월",
        "연령대",
        "소비영역"
    ],
    how="left",
    validate="many_to_one"
)

print("연결 결과:", len(analysis_2_3a_3b))

print(
    "3-B 상대변화 결측:",
    analysis_2_3a_3b["영역_상대변화_pp"].isna().sum()
)

print(
    "포함 동:",
    analysis_2_3a_3b["행정동명_표준"].nunique()
)

print("\n=== 연결 결과 ===")

display(
    analysis_2_3a_3b[
        [
            "행정동명_표준",
            "기준_년분기_코드",
            "기준연월",
            "연령대",
            "소비영역",
            "change_rate_pct",
            "gangnam_change_percentile",
            "영역_전월대비_pct",
            "연령전체_전월대비_pct",
            "영역_상대변화_pp"
        ]
    ].sort_values(
        [
            "기준연월",
            "행정동명_표준",
            "연령대",
            "소비영역"
        ]
    )
)

연결 결과: 51
3-B 상대변화 결측: 0
포함 동: 6

=== 연결 결과 ===

,행정동명_표준,기준_년분기_코드,기준연월,연령대,소비영역,change_rate_pct,gangnam_change_percentile,영역_전월대비_pct,연령전체_전월대비_pct,영역_상대변화_pp
0,개포3동,20253,202508,10대,A_외식카페,-47.902098,0.047619,-0.461302,-2.784252,2.322951
1,개포3동,20253,202508,20대,A_외식카페,-40.094276,0.136364,0.689130,0.307033,0.382097
2,개포3동,20253,202508,20대,E_의료건강,-56.532988,0.095238,-1.317050,0.307033,-1.624083
3,개포3동,20253,202508,30대,A_외식카페,-18.992558,0.136364,-2.072850,-1.378374,-0.694476
4,개포3동,20253,202508,30대,E_의료건강,-31.306598,0.142857,-3.672134,-1.378374,-2.293759
5,개포3동,20253,202508,50대,A_외식카페,-28.118812,0.090909,-1.681308,-3.767228,2.085920
6,개포3동,20253,202508,50대,C_대면생활서비스,-23.545074,0.045455,-1.240728,-3.767228,2.526501
36,신사동,20253,202508,40대,A_외식카페,-10.755537,0.181818,-3.127788,-2.944928,-0.182861
23,개포4동,20253,202509,20대,B_여가운동,-91.583945,0.100000,-21.628854,1.894875,-23.523728
24,개포4동,20253,202509,20대,C_대면생활서비스,-43.04579,0.136364,-4.306367,1.894875,-6.201242
25,개포4동,20253,202509,30대,B_여가운동,-71.219627,0.095238,-7.932848,3.646146,-11.578994
26,개포4동,20253,202509,30대,E_의료건강,-28.233622,0.190476,11.704984,3.646146,8.058838
27,개포4동,20253,202509,40대,B_여가운동,-61.306348,0.047619,-16.530886,3.042175,-19.573061
28,개포4동,20253,202509,40대,C_대면생활서비스,-30.188929,0.090909,-0.712264,3.042175,-3.754438
29,개포4동,20253,202509,40대,D_생활필수,-23.215114,0.090909,0.878778,3.042175,-2.163397
30,개포4동,20253,202509,40대,E_의료건강,-32.428256,0.047619,12.727679,3.042175,9.685504
31,개포4동,20253,202509,50대,C_대면생활서비스,-13.07626,0.181818,2.051714,3.425333,-1.373620
32,개포4동,20253,202509,50대,D_생활필수,-9.042918,0.090909,0.692818,3.425333,-2.732515
33,개포4동,20253,202509,50대,E_의료건강,-18.289025,0.142857,8.348158,3.425333,4.922825
37,신사동,20253,202509,40대,A_외식카페,-10.755537,0.181818,0.933617,3.042175,-2.108558
7,개포3동,20254,202510,10대,A_외식카페,-68.320831,0.090909,2.353787,-1.557235,3.911022
9,개포3동,20254,202510,10대,D_생활필수,-40.991129,0.181818,-11.257263,-1.557235,-9.700027
11,개포3동,20254,202510,20대,E_의료건강,-41.589404,0.095238,-8.837288,-5.162608,-3.674680
13,개포3동,20254,202510,30대,A_외식카페,-29.133858,0.045455,-8.983812,-5.173707,-3.810104
15,개포3동,20254,202510,30대,B_여가운동,-79.787234,0.095238,6.706432,-5.173707,11.880139
17,개포3동,20254,202510,40대,A_외식카페,-26.405617,0.045455,-8.081365,-5.035541,-3.045824
19,개포3동,20254,202510,50대,A_외식카페,-36.780371,0.045455,-5.691032,-5.509823,-0.181209
21,개포3동,20254,202510,50대,E_의료건강,-19.293246,0.095238,-11.017444,-5.509823,-5.507621
42,일원본동,20254,202510,30대,E_의료건강,-35.390676,0.047619,-10.869776,-5.173707,-5.696069
45,일원본동,20254,202510,40대,A_외식카페,-22.587474,0.090909,-8.081365,-5.035541,-3.045824
48,일원본동,20254,202510,40대,E_의료건강,-19.918843,0.190476,-11.019957,-5.035541,-5.984416
8,개포3동,20254,202511,10대,A_외식카페,-68.320831,0.090909,-4.890109,0.725651,-5.615760
10,개포3동,20254,202511,10대,D_생활필수,-40.991129,0.181818,1.803514,0.725651,1.077863
12,개포3동,20254,202511,20대,E_의료건강,-41.589404,0.095238,5.614766,5.309455,0.305310
14,개포3동,20254,202511,30대,A_외식카페,-29.133858,0.045455,3.580913,4.775616,-1.194702
16,개포3동,20254,202511,30대,B_여가운동,-79.787234,0.095238,-13.766406,4.775616,-18.542021
18,개포3동,20254,202511,40대,A_외식카페,-26.405617,0.045455,3.783028,3.855534,-0.072506
20,개포3동,20254,202511,50대,A_외식카페,-36.780371,0.045455,1.815668,3.559106,-1.743438
22,개포3동,20254,202511,50대,E_의료건강,-19.293246,0.095238,10.406642,3.559106,6.847536
38,일원1동,20254,202511,10대,C_대면생활서비스,-37.086093,0.190476,-4.255476,0.725651,-4.981127
40,일원1동,20254,202511,50대,A_외식카페,-8.866545,0.181818,1.815668,3.559106,-1.743438
43,일원본동,20254,202511,30대,E_의료건강,-35.390676,0.047619,9.130686,4.775616,4.355070
46,일원본동,20254,202511,40대,A_외식카페,-22.587474,0.090909,3.783028,3.855534,-0.072506
49,일원본동,20254,202511,40대,E_의료건강,-19.918843,0.190476,15.117314,3.855534,11.261780
34,도곡1동,20254,202512,20대,C_대면생활서비스,-36.437167,0.181818,2.318662,-0.929990,3.248652
35,도곡1동,20254,202512,30대,C_대면생활서비스,-35.370058,0.181818,-6.465745,-1.680904,-4.784840
39,일원1동,20254,202512,10대,C_대면생활서비스,-37.086093,0.190476,9.779307,3.503469,6.275838
41,일원1동,20254,202512,50대,A_외식카페,-8.866545,0.181818,0.534878,1.033487,-0.498608
44,일원본동,20254,202512,30대,E_의료건강,-35.390676,0.047619,-1.152221,-1.680904,0.528683
47,일원본동,20254,202512,40대,A_외식카페,-22.587474,0.090909,-0.022545,-0.438062,0.415517
50,일원본동,20254,202512,40대,E_의료건강,-19.918843,0.190476,-1.083550,-0.438062,-0.645488

In [58]:
# ============================================================
# 42. Analysis 3-B
# 신한카드 60·70·80·90대 → 60대이상 재집계
# ============================================================

senior_ages = ["60 대", "70 대", "80 대", "90 대"]

# 5개 핵심 소비영역 중 60대 이상만
senior_raw = shinhan_domain_core[
    shinhan_domain_core["AGE_CCD"].isin(senior_ages)
].copy()

# 월 × 소비영역으로 원자료부터 합산
senior_domain_month = (
    senior_raw
    .groupby(
        ["기준연월", "소비영역"],
        as_index=False
    )
    .agg(
        이용건수=("USE_CNT", "sum"),
        이용금액=("TS_AT", "sum")
    )
)

senior_domain_month["연령대"] = "60대이상"

# 월 일수
senior_domain_month["월일수"] = (
    senior_domain_month["기준연월"]
    .map({
        202507: 31,
        202508: 31,
        202509: 30,
        202510: 31,
        202511: 30,
        202512: 31
    })
)

senior_domain_month["일평균_이용건수"] = (
    senior_domain_month["이용건수"]
    / senior_domain_month["월일수"]
)

# ------------------------------------------------------------
# 60대 이상 전체 소비 기준선
# 핵심 5개 영역이 아니라 원본 88개 업종 전체 USE_CNT 사용
# ------------------------------------------------------------

senior_total_month = (
    shinhan_gangnam[
        shinhan_gangnam["AGE_CCD"].isin(senior_ages)
    ]
    .groupby(
        "기준연월",
        as_index=False
    )
    .agg(
        연령전체_이용건수=("USE_CNT", "sum")
    )
)

senior_total_month["월일수"] = (
    senior_total_month["기준연월"]
    .map({
        202507: 31,
        202508: 31,
        202509: 30,
        202510: 31,
        202511: 30,
        202512: 31
    })
)

senior_total_month["연령전체_일평균"] = (
    senior_total_month["연령전체_이용건수"]
    / senior_total_month["월일수"]
)

# 전월 대비
senior_domain_month = senior_domain_month.sort_values(
    ["소비영역", "기준연월"]
)

senior_domain_month["영역_전월대비_pct"] = (
    senior_domain_month
    .groupby("소비영역")["일평균_이용건수"]
    .pct_change(fill_method=None)
    * 100
)

senior_total_month = senior_total_month.sort_values("기준연월")

senior_total_month["연령전체_전월대비_pct"] = (
    senior_total_month["연령전체_일평균"]
    .pct_change(fill_method=None)
    * 100
)

# 결합
senior_domain_month = senior_domain_month.merge(
    senior_total_month[
        [
            "기준연월",
            "연령전체_전월대비_pct"
        ]
    ],
    on="기준연월",
    how="left",
    validate="many_to_one"
)

senior_domain_month["영역_상대변화_pp"] = (
    senior_domain_month["영역_전월대비_pct"]
    - senior_domain_month["연령전체_전월대비_pct"]
)

# 검증
print("shape:", senior_domain_month.shape)

print(
    "월별 소비영역 수:"
)
print(
    senior_domain_month
    .groupby("기준연월")["소비영역"]
    .nunique()
)

print("\n결측:")
print(senior_domain_month.isna().sum())

print("\n=== 60대이상 월별 영역 변화 ===")

display(
    senior_domain_month[
        [
            "기준연월",
            "연령대",
            "소비영역",
            "영역_전월대비_pct",
            "연령전체_전월대비_pct",
            "영역_상대변화_pp"
        ]
    ].sort_values(
        ["기준연월", "소비영역"]
    )
)

shape: (30, 10)
월별 소비영역 수:
기준연월
202507    5
202508    5
202509    5
202510    5
202511    5
202512    5
Name: 소비영역, dtype: int64

결측:
기준연월             0
소비영역             0
이용건수             0
이용금액             0
연령대              0
월일수              0
일평균_이용건수         0
영역_전월대비_pct      5
연령전체_전월대비_pct    5
영역_상대변화_pp       5
dtype: int64

=== 60대이상 월별 영역 변화 ===

      기준연월    연령대       소비영역  영역_전월대비_pct  연령전체_전월대비_pct  영역_상대변화_pp
0   202507  60대이상     A_외식카페          NaN            NaN         NaN
6   202507  60대이상     B_여가운동          NaN            NaN         NaN
12  202507  60대이상  C_대면생활서비스          NaN            NaN         NaN
18  202507  60대이상     D_생활필수          NaN            NaN         NaN
24  202507  60대이상     E_의료건강          NaN            NaN         NaN
1   202508  60대이상     A_외식카페    -0.856185      -5.120745    4.264560
7   202508  60대이상     B_여가운동    -1.895704      -5.120745    3.225041
13  202508  60대이상  C_대면생활서비스     1.447687      -5.120745    6.568432
19  202508  60대이상     D_생활필수    -3.012891      -5.120745    2.107854
25  202508  60대이상     E_의료건강    -7.517732      -5.120745   -2.396987
2   202509  60대이상     A_외식카페     1.785810       8.662145   -6.876335
8   202509  60대이상     B_여가운동     3.114724       8.662145   -5.547421
14  202509  60대이상  C_대면생활서비스     5.771410       8.662145   -2.890735
20  202509  60대이상     D_생활필수     4.341539       8.662145   -4.320605
26  202509  60대이상     E_의료건강    16.582699       8.662145    7.920554
3   202510  60대이상     A_외식카페    -8.050882      -9.658554    1.607672
9   202510  60대이상     B_여가운동   -17.576186      -9.658554   -7.917632
15  202510  60대이상  C_대면생활서비스     3.391003      -9.658554   13.049557
21  202510  60대이상     D_생활필수    -2.065846      -9.658554    7.592709
27  202510  60대이상     E_의료건강   -12.724295      -9.658554   -3.065741
4   202511  60대이상     A_외식카페     3.337703       3.571712   -0.234009
10  202511  60대이상     B_여가운동   -23.279238       3.571712  -26.850950
16  202511  60대이상  C_대면생활서비스     3.272449       3.571712   -0.299263
22  202511  60대이상     D_생활필수     2.021174       3.571712   -1.550538
28  202511  60대이상     E_의료건강     7.925747       3.571712    4.354035
5   202512  60대이상     A_외식카페     3.001444       2.114977    0.886466
11  202512  60대이상     B_여가운동     3.378066       2.114977    1.263089
17  202512  60대이상  C_대면생활서비스    -4.501116       2.114977   -6.616093
23  202512  60대이상     D_생활필수    -0.981511       2.114977   -3.096488
29  202512  60대이상     E_의료건강     3.661400       2.114977    1.546423

In [59]:
# ============================================================
# 43. Analysis 2 + 3-A + 3-B 최종 연결
# 10~50대 + 60대이상 통합
# ============================================================

import pandas as pd

# ------------------------------------------------------------
# 1) 3-A의 60대이상 dual-low 사례
# ------------------------------------------------------------

behavior_3a_senior = behavior_3a_low[
    behavior_3a_low["연령대"] == "60대이상"
].copy()

print("3-A 60대이상 dual-low:", len(behavior_3a_senior))


# ------------------------------------------------------------
# 2) 행동신호 발생 월로 펼치기
# ------------------------------------------------------------

behavior_3a_senior["기준연월"] = (
    behavior_3a_senior["behavior_signal_month_list"]
    .str.split(", ")
)

behavior_3a_senior = behavior_3a_senior.explode("기준연월")

behavior_3a_senior["기준연월"] = (
    behavior_3a_senior["기준연월"].astype(int)
)


# ------------------------------------------------------------
# 3) 60대이상 신한카드 월별 Context 연결
# ------------------------------------------------------------

senior_context_cols = [
    "기준연월",
    "연령대",
    "소비영역",
    "영역_전월대비_pct",
    "연령전체_전월대비_pct",
    "영역_상대변화_pp"
]

analysis_senior = behavior_3a_senior.merge(
    senior_domain_month[senior_context_cols],
    on=[
        "기준연월",
        "연령대",
        "소비영역"
    ],
    how="left",
    validate="many_to_one"
)

print(
    "60대이상 월 단위 연결:",
    len(analysis_senior)
)

print(
    "60대이상 3-B 결측:",
    analysis_senior["영역_상대변화_pp"].isna().sum()
)


# ------------------------------------------------------------
# 4) 10~50대 + 60대이상 통합
# ------------------------------------------------------------

common_cols = [
    "행정동명_표준",
    "기준_년분기_코드",
    "기준연월",
    "behavior_signal_months",
    "behavior_signal_month_list",
    "연령대",
    "소비영역",
    "change_rate_pct",
    "gangnam_change_percentile",
    "dual_low_signal",
    "영역_전월대비_pct",
    "연령전체_전월대비_pct",
    "영역_상대변화_pp"
]

analysis_2_3a_3b_final = pd.concat(
    [
        analysis_2_3a_3b[common_cols],
        analysis_senior[common_cols]
    ],
    ignore_index=True
)

analysis_2_3a_3b_final = (
    analysis_2_3a_3b_final
    .sort_values(
        [
            "기준연월",
            "행정동명_표준",
            "연령대",
            "소비영역"
        ]
    )
    .reset_index(drop=True)
)


# ------------------------------------------------------------
# 5) 검증
# ------------------------------------------------------------

print("\n=== 최종 연결 검증 ===")

print(
    "최종 행:",
    len(analysis_2_3a_3b_final)
)

print(
    "포함 동:",
    analysis_2_3a_3b_final["행정동명_표준"].nunique()
)

print(
    "동×분기:",
    analysis_2_3a_3b_final[
        ["행정동명_표준", "기준_년분기_코드"]
    ].drop_duplicates().shape[0]
)

print(
    "동×행동신호월:",
    analysis_2_3a_3b_final[
        ["행정동명_표준", "기준연월"]
    ].drop_duplicates().shape[0]
)

print(
    "3-B 상대변화 결측:",
    analysis_2_3a_3b_final[
        "영역_상대변화_pp"
    ].isna().sum()
)

print("\n=== 동별 연결 행 수 ===")

print(
    analysis_2_3a_3b_final[
        "행정동명_표준"
    ].value_counts()
)

3-A 60대이상 dual-low: 2
60대이상 월 단위 연결: 3
60대이상 3-B 결측: 0

=== 최종 연결 검증 ===
최종 행: 54
포함 동: 6
동×분기: 7
동×행동신호월: 12
3-B 상대변화 결측: 0

=== 동별 연결 행 수 ===
행정동명_표준
개포3동    25
개포4동    12
일원본동     9
일원1동     4
신사동      2
도곡1동     2
Name: count, dtype: int64