In [ ]:
from google.colab import files

uploaded = files.upload()

Saving gangnam_db1_dong_month_behavior_mart_2025_07_12.csv to gangnam_db1_dong_month_behavior_mart_2025_07_12.csv
Saving gangnam_disability_features_2025.csv to gangnam_disability_features_2025.csv
Saving gangnam_resident_population_features_2025Q3_Q4.csv to gangnam_resident_population_features_2025Q3_Q4.csv
Saving gangnam_single_household_features_2025.csv to gangnam_single_household_features_2025.csv
Saving gangnam_welfare_economic_features_2024_05.csv to gangnam_welfare_economic_features_2024_05.csv

In [ ]:
import pandas as pd

# 1. Dong-Month Behavior Mart
behavior = pd.read_csv(
    "gangnam_db1_dong_month_behavior_mart_2025_07_12.csv",
    encoding="utf-8-sig"
)

# 2. 주민등록인구
resident = pd.read_csv(
    "gangnam_resident_population_features_2025Q3_Q4.csv",
    encoding="utf-8-sig"
)

# 3. 1인가구
single = pd.read_csv(
    "gangnam_single_household_features_2025.csv",
    encoding="utf-8-sig"
)

# 4. 경제취약
welfare = pd.read_csv(
    "gangnam_welfare_economic_features_2024_05.csv",
    encoding="utf-8-sig"
)

# 5. 장애인
disability = pd.read_csv(
    "gangnam_disability_features_2025.csv",
    encoding="utf-8-sig"
)

print("[Behavior]", behavior.shape)
print("[Resident]", resident.shape)
print("[Single Household]", single.shape)
print("[Welfare]", welfare.shape)
print("[Disability]", disability.shape)

[Behavior] (132, 39)
[Resident] (44, 27)
[Single Household] (22, 15)
[Welfare] (22, 7)
[Disability] (22, 14)

In [ ]:
datasets = {
    "Behavior": behavior,
    "Resident": resident,
    "Single Household": single,
    "Welfare": welfare,
    "Disability": disability
}

for name, df in datasets.items():
    print(f"\n===== {name} =====")
    print("shape:", df.shape)

    for i, col in enumerate(df.columns, 1):
        print(f"{i:2d}. {col}")

===== Behavior =====
shape: (132, 39)
 1. 행정동코드
 2. 행정동명
 3. 기준연월
 4. total_flow
 5. flow_per_point
 6. male_ratio
 7. age_20_ratio
 8. age_30_ratio
 9. age_40_ratio
10. age_50_ratio
11. age_60_plus_ratio
12. morning_ratio
13. daytime_ratio
14. evening_ratio
15. peak_hour_ratio
16. weekend_weekday_index
17. peak_day_ratio
18. low_comm_ratio
19. low_weekday_outing_ratio
20. low_holiday_outing_ratio
21. high_worktime_ratio
22. high_video_ratio
23. high_life_service_ratio
24. financial_interest_ratio
25. very_low_outing_ratio
26. very_low_outing_comm_ratio
27. 야간상주지 변경횟수 평균
28. 평균 근무시간 평균
29. 평일 총 이동 횟수
30. 휴일 총 이동 횟수 평균
31. 집 추정 위치 평일 총 체류시간
32. 집 추정 위치 휴일 총 체류시간
33. 금융 서비스 사용일수
34. 쇼핑 서비스 사용일수
35. 배달 서비스 사용일수
36. 최근 3개월 내 요금 연체 비율
37. 평균 통화대상자 수
38. 데이터 사용량
39. 카카오톡_비사용비율

===== Resident =====
shape: (44, 27)
 1. dong_name
 2. quarter
 3. resident_total
 4. resident_korean
 5. resident_foreigner
 6. foreigner_ratio
 7. resident_age_10
 8. resident_age_20
 9. resident_age_30
10. resident_age_40
11. resident_age_50
12. resident_age_60_plus
13. resident_age_65_plus
14. resident_age_10_ratio
15. resident_age_20_ratio
16. resident_age_30_ratio
17. resident_age_40_ratio
18. resident_age_50_ratio
19. resident_age_60_plus_ratio
20. resident_age_65_plus_ratio
21. resident_10plus
22. resident_age_10_ratio_10plus
23. resident_age_20_ratio_10plus
24. resident_age_30_ratio_10plus
25. resident_age_40_ratio_10plus
26. resident_age_50_ratio_10plus
27. resident_age_60_plus_ratio_10plus

===== Single Household =====
shape: (22, 15)
 1. 행정동코드
 2. 행정동명
 3. single_age_20_gap
 4. single_age_30_gap
 5. single_age_40_gap
 6. single_age_50_gap
 7. single_age_60_plus_gap
 8. single_gender_1_ratio
 9. single_gender_2_ratio
10. single_household_mean
11. 2025_Q3_1인세대
12. 2025_Q4_1인세대
13. official_single_household_mean
14. official_single_household_change
15. official_single_household_change_rate

===== Welfare =====
shape: (22, 7)
 1. dong_name
 2. livelihood_per_1000
 3. medical_per_1000
 4. housing_per_1000
 5. elderly_livelihood_per_1000
 6. elderly_medical_per_1000
 7. elderly_housing_per_1000

===== Disability =====
shape: (22, 14)
 1. dong_name
 2. disabled_total
 3. disabled_per_1000
 4. disabled_male_ratio
 5. disabled_female_ratio
 6. brain_lesion_ratio
 7. visual_ratio
 8. kidney_ratio
 9. autism_ratio
10. mental_ratio
11. intellectual_ratio
12. physical_ratio
13. hearing_ratio
14. other_disability_ratio

In [ ]:
# ==========================================
# 1. Behavior에서 22개 행정동 마스터 생성
# ==========================================

dong_master = (
    behavior[
        ["행정동코드", "행정동명"]
    ]
    .drop_duplicates()
    .sort_values("행정동코드")
    .reset_index(drop=True)
)

print("[Dong Master]")
print("행정동 수:", len(dong_master))
print(
    "코드 중복:",
    dong_master["행정동코드"].duplicated().sum()
)
print(
    "동명 중복:",
    dong_master["행정동명"].duplicated().sum()
)

display(dong_master)


# ==========================================
# 2. 각 데이터의 행정동 목록
# ==========================================

dong_sets = {
    "Behavior": set(behavior["행정동명"].unique()),
    "Resident": set(resident["dong_name"].unique()),
    "Single Household": set(single["행정동명"].unique()),
    "Welfare": set(welfare["dong_name"].unique()),
    "Disability": set(disability["dong_name"].unique())
}

print("\n[행정동 수]")
for name, dong_set in dong_sets.items():
    print(name, len(dong_set))


# ==========================================
# 3. Behavior를 기준으로 차이 확인
# ==========================================

base = dong_sets["Behavior"]

for name, dong_set in dong_sets.items():

    if name == "Behavior":
        continue

    print(f"\n===== {name} =====")

    print(
        "Behavior에는 있고 해당 데이터에는 없음:",
        sorted(base - dong_set)
    )

    print(
        "해당 데이터에는 있고 Behavior에는 없음:",
        sorted(dong_set - base)
    )

[Dong Master]
행정동 수: 22
코드 중복: 0
동명 중복: 0

      행정동코드  행정동명
0   1123051   신사동
1   1123052  논현1동
2   1123053  논현2동
3   1123058  삼성1동
4   1123059  삼성2동
5   1123060  대치1동
6   1123063  대치4동
7   1123064  역삼1동
8   1123065  역삼2동
9   1123066  도곡1동
10  1123067  도곡2동
11  1123068  개포1동
12  1123071  개포4동
13  1123072  일원본동
14  1123073  일원1동
15  1123074  개포3동
16  1123075   수서동
17  1123076   세곡동
18  1123077  압구정동
19  1123078   청담동
20  1123079  대치2동
21  1123080  개포2동

[행정동 수]
Behavior 22
Resident 22
Single Household 22
Welfare 22
Disability 22

===== Resident =====
Behavior에는 있고 해당 데이터에는 없음: []
해당 데이터에는 있고 Behavior에는 없음: []

===== Single Household =====
Behavior에는 있고 해당 데이터에는 없음: []
해당 데이터에는 있고 Behavior에는 없음: []

===== Welfare =====
Behavior에는 있고 해당 데이터에는 없음: []
해당 데이터에는 있고 Behavior에는 없음: []

===== Disability =====
Behavior에는 있고 해당 데이터에는 없음: []
해당 데이터에는 있고 Behavior에는 없음: []

In [ ]:
# 확인할 주민등록인구 구조 변수
resident_check_cols = [
    "resident_total",
    "foreigner_ratio",
    "resident_age_10_ratio_10plus",
    "resident_age_20_ratio_10plus",
    "resident_age_30_ratio_10plus",
    "resident_age_40_ratio_10plus",
    "resident_age_50_ratio_10plus",
    "resident_age_60_plus_ratio_10plus"
]

# Q3 / Q4를 가로로 펼치기
resident_compare = resident.pivot(
    index="dong_name",
    columns="quarter",
    values=resident_check_cols
)

print("quarter 값:", resident["quarter"].unique())
print("비교 테이블 shape:", resident_compare.shape)

# 분기별 기술통계
for col in resident_check_cols:
    print(f"\n===== {col} =====")

    temp = resident.pivot(
        index="dong_name",
        columns="quarter",
        values=col
    )

    q3 = temp.iloc[:, 0]
    q4 = temp.iloc[:, 1]

    diff = q4 - q3

    print("Q3 평균:", round(q3.mean(), 6))
    print("Q4 평균:", round(q4.mean(), 6))
    print("평균 변화:", round(diff.mean(), 6))
    print("평균 절대 변화:", round(diff.abs().mean(), 6))
    print("최대 절대 변화:", round(diff.abs().max(), 6))

quarter 값: ['2025Q3' '2025Q4']
비교 테이블 shape: (22, 16)

===== resident_total =====
Q3 평균: 25562.818182
Q4 평균: 25568.545455
평균 변화: 5.727273
평균 절대 변화: 142.363636
최대 절대 변화: 1348

===== foreigner_ratio =====
Q3 평균: 0.011362
Q4 평균: 0.011515
평균 변화: 0.000153
평균 절대 변화: 0.000415
최대 절대 변화: 0.001208

===== resident_age_10_ratio_10plus =====
Q3 평균: 0.115313
Q4 평균: 0.115209
평균 변화: -0.000104
평균 절대 변화: 0.000879
최대 절대 변화: 0.004555

===== resident_age_20_ratio_10plus =====
Q3 평균: 0.123032
Q4 평균: 0.121377
평균 변화: -0.001655
평균 절대 변화: 0.001688
최대 절대 변화: 0.005199

===== resident_age_30_ratio_10plus =====
Q3 평균: 0.155408
Q4 평균: 0.155167
평균 변화: -0.000242
평균 절대 변화: 0.001518
최대 절대 변화: 0.004286

===== resident_age_40_ratio_10plus =====
Q3 평균: 0.185831
Q4 평균: 0.185684
평균 변화: -0.000147
평균 절대 변화: 0.001147
최대 절대 변화: 0.002706

===== resident_age_50_ratio_10plus =====
Q3 평균: 0.167089
Q4 평균: 0.166989
평균 변화: -0.0001
평균 절대 변화: 0.000899
최대 절대 변화: 0.002776

===== resident_age_60_plus_ratio_10plus =====
Q3 평균: 0.253326
Q4 평균: 0.255574
평균 변화: 0.002248
평균 절대 변화: 0.002248
최대 절대 변화: 0.007368

In [ ]:
resident_feature_cols = [
    "resident_total",
    "foreigner_ratio",
    "resident_age_10_ratio_10plus",
    "resident_age_20_ratio_10plus",
    "resident_age_30_ratio_10plus",
    "resident_age_40_ratio_10plus",
    "resident_age_50_ratio_10plus",
    "resident_age_60_plus_ratio_10plus"
]

resident_dong = (
    resident
    .groupby("dong_name")[resident_feature_cols]
    .mean()
    .reset_index()
)

# 이름 정리
resident_dong = resident_dong.rename(
    columns={
        "dong_name": "행정동명",
        "resident_total": "resident_total_mean",
        "foreigner_ratio": "foreigner_ratio_mean",
        "resident_age_10_ratio_10plus": "resident_age_10_ratio",
        "resident_age_20_ratio_10plus": "resident_age_20_ratio",
        "resident_age_30_ratio_10plus": "resident_age_30_ratio",
        "resident_age_40_ratio_10plus": "resident_age_40_ratio",
        "resident_age_50_ratio_10plus": "resident_age_50_ratio",
        "resident_age_60_plus_ratio_10plus": "resident_age_60_plus_ratio"
    }
)

# Behavior의 Dong Master에서 행정동코드 부여
resident_dong = (
    dong_master
    .merge(
        resident_dong,
        on="행정동명",
        how="left",
        validate="one_to_one"
    )
)

print("Resident Dong Feature shape:", resident_dong.shape)
print("행정동 수:", resident_dong["행정동코드"].nunique())
print("결측값:", resident_dong.isna().sum().sum())
print("행정동코드 중복:", resident_dong["행정동코드"].duplicated().sum())

display(resident_dong.head())

Resident Dong Feature shape: (22, 10)
행정동 수: 22
결측값: 0
행정동코드 중복: 0

,행정동코드,행정동명,resident_total_mean,foreigner_ratio_mean,resident_age_10_ratio,resident_age_20_ratio,resident_age_30_ratio,resident_age_40_ratio,resident_age_50_ratio,resident_age_60_plus_ratio
0,1123051,신사동,15309.0,0.013815,0.100617,0.124995,0.137736,0.166386,0.182156,0.288110
1,1123052,논현1동,21535.5,0.039261,0.041166,0.177929,0.261331,0.175555,0.136385,0.207635
2,1123053,논현2동,20508.5,0.019236,0.061135,0.149945,0.215139,0.183938,0.160016,0.229827
3,1123058,삼성1동,13036.5,0.024469,0.094189,0.124413,0.152825,0.162349,0.174132,0.292092
4,1123059,삼성2동,30596.0,0.010410,0.120186,0.131546,0.162511,0.204351,0.183396,0.198011

In [ ]:
import numpy as np

# ------------------------------------------
# 1. 연령 gap 합
# ------------------------------------------

age_gap_cols = [
    "single_age_20_gap",
    "single_age_30_gap",
    "single_age_40_gap",
    "single_age_50_gap",
    "single_age_60_plus_gap"
]

single["age_gap_sum"] = single[age_gap_cols].sum(axis=1)

print("[연령 gap 합]")
print(single["age_gap_sum"].describe())


# ------------------------------------------
# 2. 성별 비율 합
# ------------------------------------------

single["gender_ratio_sum"] = (
    single["single_gender_1_ratio"]
    + single["single_gender_2_ratio"]
)

print("\n[성별 비율 합]")
print(single["gender_ratio_sum"].describe())


# ------------------------------------------
# 3. 규모/변화 변수 상관관계
# ------------------------------------------

single_scale_cols = [
    "single_household_mean",
    "2025_Q3_1인세대",
    "2025_Q4_1인세대",
    "official_single_household_mean",
    "official_single_household_change",
    "official_single_household_change_rate"
]

print("\n[규모·변화 변수 상관관계]")
display(
    single[single_scale_cols]
    .corr()
    .round(3)
)


# ------------------------------------------
# 4. 기본 검증
# ------------------------------------------

print("\n[기본 검증]")
print("행정동 수:", single["행정동코드"].nunique())
print(
    "key 중복:",
    single["행정동코드"].duplicated().sum()
)
print(
    "원본 결측값:",
    single.drop(
        columns=["age_gap_sum", "gender_ratio_sum"]
    ).isna().sum().sum()
)

[연령 gap 합]
count    2.200000e+01
mean     3.731627e-17
std      7.239205e-17
min     -1.110223e-16
25%     -2.602085e-18
50%      5.204170e-17
75%      1.023487e-16
max      1.110223e-16
Name: age_gap_sum, dtype: float64

[성별 비율 합]
count    2.200000e+01
mean     1.000000e+00
std      5.934392e-17
min      1.000000e+00
25%      1.000000e+00
50%      1.000000e+00
75%      1.000000e+00
max      1.000000e+00
Name: gender_ratio_sum, dtype: float64

[규모·변화 변수 상관관계]

,single_household_mean,2025_Q3_1인세대,2025_Q4_1인세대,official_single_household_mean,official_single_household_change,official_single_household_change_rate
single_household_mean,1.000,0.985,0.985,0.985,-0.393,-0.044
2025_Q3_1인세대,0.985,1.000,1.000,1.000,-0.393,-0.033
2025_Q4_1인세대,0.985,1.000,1.000,1.000,-0.382,-0.022
official_single_household_mean,0.985,1.000,1.000,1.000,-0.388,-0.027
official_single_household_change,-0.393,-0.393,-0.382,-0.388,1.000,0.870
official_single_household_change_rate,-0.044,-0.033,-0.022,-0.027,0.870,1.000

[기본 검증]
행정동 수: 22
key 중복: 0
원본 결측값: 0

In [ ]:
single_feature_cols = [
    # 연령구조 gap
    "single_age_20_gap",
    "single_age_30_gap",
    "single_age_40_gap",
    "single_age_50_gap",
    "single_age_60_plus_gap",

    # 성별구조
    "single_gender_1_ratio",
    "single_gender_2_ratio",

    # 규모
    "single_household_mean",
    "official_single_household_mean",

    # 변화
    "official_single_household_change_rate"
]

single_dong = single[
    [
        "행정동코드",
        "행정동명"
    ] + single_feature_cols
].copy()

print("Single Household Feature shape:", single_dong.shape)
print("Feature 수:", len(single_feature_cols))
print("행정동 수:", single_dong["행정동코드"].nunique())
print("결측값:", single_dong.isna().sum().sum())
print(
    "행정동코드 중복:",
    single_dong["행정동코드"].duplicated().sum()
)

display(single_dong.head())

Single Household Feature shape: (22, 12)
Feature 수: 10
행정동 수: 22
결측값: 0
행정동코드 중복: 0

,행정동코드,행정동명,single_age_20_gap,single_age_30_gap,single_age_40_gap,single_age_50_gap,single_age_60_plus_gap,single_gender_1_ratio,single_gender_2_ratio,single_household_mean,official_single_household_mean,official_single_household_change_rate
0,1123051,신사동,0.056955,0.121174,-0.052816,-0.107611,-0.017703,0.456150,0.543850,2430.546667,2447.5,-0.002856
1,1123052,논현1동,0.061908,0.082458,0.025895,-0.072081,-0.098180,0.467232,0.532768,9136.045000,9339.0,-0.007042
2,1123053,논현2동,0.043139,0.121755,0.011741,-0.079243,-0.097392,0.474023,0.525977,5832.836667,6468.0,-0.010458
3,1123058,삼성1동,-0.023253,0.077436,-0.002115,-0.072925,0.020857,0.495165,0.504835,1790.736667,1974.0,0.007117
4,1123059,삼성2동,0.040319,0.138350,-0.051526,-0.089197,-0.037945,0.459228,0.540772,4737.710000,6030.5,-0.005457

In [ ]:
welfare_cols = [
    "livelihood_per_1000",
    "medical_per_1000",
    "housing_per_1000",
    "elderly_livelihood_per_1000",
    "elderly_medical_per_1000",
    "elderly_housing_per_1000"
]

print("[기본 구조]")
print("shape:", welfare.shape)
print("행정동 수:", welfare["dong_name"].nunique())
print("중복:", welfare["dong_name"].duplicated().sum())

print("\n[컬럼별 결측값]")
print(welfare[welfare_cols].isna().sum())

print("\n[상관관계]")
display(
    welfare[welfare_cols]
    .corr()
    .round(3)
)

# |r| >= 0.8인 조합 추출
corr = welfare[welfare_cols].corr()

high_corr = []

for i in range(len(welfare_cols)):
    for j in range(i + 1, len(welfare_cols)):
        r = corr.iloc[i, j]

        if abs(r) >= 0.8:
            high_corr.append({
                "Feature_1": welfare_cols[i],
                "Feature_2": welfare_cols[j],
                "상관계수": r
            })

high_corr = pd.DataFrame(high_corr)

if len(high_corr) > 0:
    high_corr["절대상관"] = high_corr["상관계수"].abs()
    high_corr = (
        high_corr
        .sort_values("절대상관", ascending=False)
        .drop(columns="절대상관")
        .reset_index(drop=True)
    )

print("\n[|r| >= 0.8]")
print("관계 수:", len(high_corr))
display(high_corr)

[기본 구조]
shape: (22, 7)
행정동 수: 22
중복: 0

[컬럼별 결측값]
livelihood_per_1000            0
medical_per_1000               1
housing_per_1000               0
elderly_livelihood_per_1000    0
elderly_medical_per_1000       1
elderly_housing_per_1000       0
dtype: int64

[상관관계]

,livelihood_per_1000,medical_per_1000,housing_per_1000,elderly_livelihood_per_1000,elderly_medical_per_1000,elderly_housing_per_1000
livelihood_per_1000,1.000,0.982,0.937,0.980,0.920,0.881
medical_per_1000,0.982,1.000,0.967,0.978,0.964,0.915
housing_per_1000,0.937,0.967,1.000,0.957,0.955,0.947
elderly_livelihood_per_1000,0.980,0.978,0.957,1.000,0.962,0.944
elderly_medical_per_1000,0.920,0.964,0.955,0.962,1.000,0.948
elderly_housing_per_1000,0.881,0.915,0.947,0.944,0.948,1.000

[|r| >= 0.8]
관계 수: 15

                      Feature_1                    Feature_2      상관계수
0           livelihood_per_1000             medical_per_1000  0.982130
1           livelihood_per_1000  elderly_livelihood_per_1000  0.979502
2              medical_per_1000  elderly_livelihood_per_1000  0.977511
3              medical_per_1000             housing_per_1000  0.967492
4              medical_per_1000     elderly_medical_per_1000  0.964497
5   elderly_livelihood_per_1000     elderly_medical_per_1000  0.961845
6              housing_per_1000  elderly_livelihood_per_1000  0.957435
7              housing_per_1000     elderly_medical_per_1000  0.954607
8      elderly_medical_per_1000     elderly_housing_per_1000  0.947531
9              housing_per_1000     elderly_housing_per_1000  0.947349
10  elderly_livelihood_per_1000     elderly_housing_per_1000  0.943987
11          livelihood_per_1000             housing_per_1000  0.937088
12          livelihood_per_1000     elderly_medical_per_1000  0.920078
13             medical_per_1000     elderly_housing_per_1000  0.915392
14          livelihood_per_1000     elderly_housing_per_1000  0.880987

In [ ]:
welfare_dong = (
    dong_master
    .merge(
        welfare.rename(
            columns={"dong_name": "행정동명"}
        ),
        on="행정동명",
        how="left",
        validate="one_to_one"
    )
)

print("Welfare Dong Feature shape:", welfare_dong.shape)
print("행정동 수:", welfare_dong["행정동코드"].nunique())
print(
    "행정동코드 중복:",
    welfare_dong["행정동코드"].duplicated().sum()
)

print("\n[결측값]")
print(welfare_dong.isna().sum())

display(welfare_dong.head())

Welfare Dong Feature shape: (22, 8)
행정동 수: 22
행정동코드 중복: 0

[결측값]
행정동코드                          0
행정동명                           0
livelihood_per_1000            0
medical_per_1000               1
housing_per_1000               0
elderly_livelihood_per_1000    0
elderly_medical_per_1000       1
elderly_housing_per_1000       0
dtype: int64

,행정동코드,행정동명,livelihood_per_1000,medical_per_1000,housing_per_1000,elderly_livelihood_per_1000,elderly_medical_per_1000,elderly_housing_per_1000
0,1123051,신사동,7.7732,0.8492,5.6829,16.3808,2.7816,8.3449
1,1123052,논현1동,29.8112,1.1609,12.1660,67.2660,2.7898,18.9089
2,1123053,논현2동,15.8958,1.2190,9.8008,30.8514,2.3732,11.5693
3,1123058,삼성1동,6.8270,0.5370,3.2217,11.5910,0.3739,6.3563
4,1123059,삼성2동,11.0799,0.8171,5.5563,34.4908,1.4078,8.9160

In [ ]:
disability_type_cols = [
    "brain_lesion_ratio",
    "visual_ratio",
    "kidney_ratio",
    "autism_ratio",
    "mental_ratio",
    "intellectual_ratio",
    "physical_ratio",
    "hearing_ratio",
    "other_disability_ratio"
]

# ==========================================
# 1. 성별 구성비 합
# ==========================================

disability["gender_ratio_sum"] = (
    disability["disabled_male_ratio"]
    + disability["disabled_female_ratio"]
)

print("[장애인 성별 비율 합]")
print(
    disability["gender_ratio_sum"]
    .describe()
)


# ==========================================
# 2. 장애유형 구성비 합
# ==========================================

disability["type_ratio_sum"] = (
    disability[disability_type_cols]
    .sum(axis=1)
)

print("\n[장애유형 비율 합]")
print(
    disability["type_ratio_sum"]
    .describe()
)


# ==========================================
# 3. 전체 Feature 상관관계
# ==========================================

disability_feature_cols = [
    "disabled_total",
    "disabled_per_1000",
    "disabled_male_ratio",
    "disabled_female_ratio"
] + disability_type_cols

corr = disability[
    disability_feature_cols
].corr()

high_corr = []

for i in range(len(disability_feature_cols)):
    for j in range(i + 1, len(disability_feature_cols)):

        r = corr.iloc[i, j]

        if abs(r) >= 0.8:
            high_corr.append({
                "Feature_1": disability_feature_cols[i],
                "Feature_2": disability_feature_cols[j],
                "상관계수": r
            })

high_corr = pd.DataFrame(high_corr)

if len(high_corr) > 0:
    high_corr["절대상관"] = (
        high_corr["상관계수"].abs()
    )

    high_corr = (
        high_corr
        .sort_values(
            "절대상관",
            ascending=False
        )
        .drop(columns="절대상관")
        .reset_index(drop=True)
    )

print("\n[|r| >= 0.8]")
print("관계 수:", len(high_corr))
display(high_corr.round(3))


# ==========================================
# 4. 기본 검증
# ==========================================

print("\n[기본 검증]")
print(
    "행정동 수:",
    disability["dong_name"].nunique()
)
print(
    "중복:",
    disability["dong_name"].duplicated().sum()
)
print(
    "원본 결측값:",
    disability[
        ["dong_name"] + disability_feature_cols
    ].isna().sum().sum()
)

[장애인 성별 비율 합]
count    22.0
mean      1.0
std       0.0
min       1.0
25%       1.0
50%       1.0
75%       1.0
max       1.0
Name: gender_ratio_sum, dtype: float64

[장애유형 비율 합]
count    2.200000e+01
mean     1.000000e+00
std      7.516216e-07
min      9.999990e-01
25%      1.000000e+00
50%      1.000000e+00
75%      1.000001e+00
max      1.000001e+00
Name: type_ratio_sum, dtype: float64

[|r| >= 0.8]
관계 수: 1

             Feature_1              Feature_2  상관계수
0  disabled_male_ratio  disabled_female_ratio  -1.0

[기본 검증]
행정동 수: 22
중복: 0
원본 결측값: 0

In [ ]:
disability_feature_cols = [
    "disabled_total",
    "disabled_per_1000",
    "disabled_male_ratio",
    "disabled_female_ratio",
    "brain_lesion_ratio",
    "visual_ratio",
    "kidney_ratio",
    "autism_ratio",
    "mental_ratio",
    "intellectual_ratio",
    "physical_ratio",
    "hearing_ratio",
    "other_disability_ratio"
]

disability_dong = (
    dong_master
    .merge(
        disability[
            ["dong_name"] + disability_feature_cols
        ].rename(
            columns={"dong_name": "행정동명"}
        ),
        on="행정동명",
        how="left",
        validate="one_to_one"
    )
)

print(
    "Disability Dong Feature shape:",
    disability_dong.shape
)

print(
    "행정동 수:",
    disability_dong["행정동코드"].nunique()
)

print(
    "행정동코드 중복:",
    disability_dong["행정동코드"].duplicated().sum()
)

print(
    "결측값:",
    disability_dong.isna().sum().sum()
)

display(disability_dong.head())

Disability Dong Feature shape: (22, 15)
행정동 수: 22
행정동코드 중복: 0
결측값: 0

,행정동코드,행정동명,disabled_total,disabled_per_1000,disabled_male_ratio,disabled_female_ratio,brain_lesion_ratio,visual_ratio,kidney_ratio,autism_ratio,mental_ratio,intellectual_ratio,physical_ratio,hearing_ratio,other_disability_ratio
0,1123051,신사동,356,23.254295,0.595506,0.404494,0.115169,0.089888,0.070225,0.042135,0.016854,0.042135,0.396067,0.174157,0.053371
1,1123052,논현1동,547,25.399921,0.590494,0.409506,0.098720,0.140768,0.049360,0.027422,0.036563,0.078611,0.383912,0.138940,0.045704
2,1123053,논현2동,452,22.039642,0.612832,0.387168,0.079646,0.117257,0.059735,0.028761,0.022124,0.068584,0.418142,0.172566,0.033186
3,1123058,삼성1동,283,21.708281,0.643110,0.356890,0.116608,0.109541,0.045936,0.063604,0.017668,0.053004,0.413428,0.155477,0.024735
4,1123059,삼성2동,586,19.152830,0.607509,0.392491,0.100683,0.119454,0.064846,0.073379,0.029010,0.042662,0.353242,0.175768,0.040956

In [ ]:
# ID를 제외한 Behavior Feature
behavior_cols = [
    col for col in behavior.columns
    if col not in [
        "행정동코드",
        "행정동명",
        "기준연월"
    ]
]

print("Behavior Feature 수:", len(behavior_cols))


# ==========================================
# 6개월 평균
# ==========================================

behavior_dong = (
    behavior
    .groupby(
        ["행정동코드", "행정동명"]
    )[behavior_cols]
    .mean()
    .reset_index()
)

# 출처/의미가 명확하도록 suffix 부여
behavior_dong = behavior_dong.rename(
    columns={
        col: f"{col}_mean"
        for col in behavior_cols
    }
)

print(
    "Behavior Dong Feature shape:",
    behavior_dong.shape
)

print(
    "행정동 수:",
    behavior_dong["행정동코드"].nunique()
)

print(
    "행정동코드 중복:",
    behavior_dong["행정동코드"]
    .duplicated()
    .sum()
)

print(
    "결측값:",
    behavior_dong.isna().sum().sum()
)

display(behavior_dong.head())

Behavior Feature 수: 36
Behavior Dong Feature shape: (22, 38)
행정동 수: 22
행정동코드 중복: 0
결측값: 0

,행정동코드,행정동명,total_flow_mean,flow_per_point_mean,male_ratio_mean,age_20_ratio_mean,age_30_ratio_mean,age_40_ratio_mean,age_50_ratio_mean,age_60_plus_ratio_mean,...,휴일 총 이동 횟수 평균_mean,집 추정 위치 평일 총 체류시간_mean,집 추정 위치 휴일 총 체류시간_mean,금융 서비스 사용일수_mean,쇼핑 서비스 사용일수_mean,배달 서비스 사용일수_mean,최근 3개월 내 요금 연체 비율_mean,평균 통화대상자 수_mean,데이터 사용량_mean,카카오톡_비사용비율_mean
0,1123051,신사동,424182.530000,607.269840,0.503033,0.167233,0.198218,0.194927,0.172209,0.193282,...,11.479739,728659.028810,143352.409854,160.255972,230.970833,12.117335,6.713968,13.609471,7.085193,5.379185
1,1123052,논현1동,344618.113333,696.198209,0.522369,0.196942,0.234957,0.203438,0.156841,0.161290,...,10.655411,741194.162129,154031.397491,183.079588,253.910655,15.589859,15.054549,13.908236,9.664360,5.057882
2,1123053,논현2동,403971.858333,698.913250,0.517462,0.178522,0.231816,0.208925,0.162009,0.167636,...,11.213517,772140.799248,151892.156642,174.178081,246.094061,13.790640,10.156000,14.559950,8.282585,5.512393
3,1123058,삼성1동,594872.323333,809.740536,0.524113,0.170581,0.221924,0.214355,0.170481,0.151670,...,12.058403,723835.401832,147806.180840,160.696258,229.455030,11.455841,6.207129,14.232888,6.919258,5.158283
4,1123059,삼성2동,354758.653333,705.285593,0.520436,0.157192,0.211135,0.214164,0.171410,0.171061,...,11.059072,772810.516814,153492.571184,180.771692,253.719725,12.986152,8.211461,14.121990,7.747843,4.057728

In [ ]:
# ==========================================
# DB1 Dong Feature Mart 생성
# ==========================================

dong_feature_mart = (
    behavior_dong

    .merge(
        resident_dong,
        on=["행정동코드", "행정동명"],
        how="left",
        validate="one_to_one"
    )

    .merge(
        single_dong,
        on=["행정동코드", "행정동명"],
        how="left",
        validate="one_to_one"
    )

    .merge(
        welfare_dong,
        on=["행정동코드", "행정동명"],
        how="left",
        validate="one_to_one"
    )

    .merge(
        disability_dong,
        on=["행정동코드", "행정동명"],
        how="left",
        validate="one_to_one"
    )
)


# ==========================================
# 최종 구조 검증
# ==========================================

print(
    "Dong Feature Mart shape:",
    dong_feature_mart.shape
)

print(
    "행정동 수:",
    dong_feature_mart["행정동코드"].nunique()
)

print(
    "행정동코드 중복:",
    dong_feature_mart["행정동코드"]
    .duplicated()
    .sum()
)

print(
    "전체 Feature 수:",
    dong_feature_mart.shape[1] - 2
)

print(
    "\n[결측값이 있는 컬럼]"
)

missing = (
    dong_feature_mart
    .isna()
    .sum()
)

print(
    missing[missing > 0]
)

display(dong_feature_mart.head())

Dong Feature Mart shape: (22, 75)
행정동 수: 22
행정동코드 중복: 0
전체 Feature 수: 73

[결측값이 있는 컬럼]
medical_per_1000            1
elderly_medical_per_1000    1
dtype: int64

,행정동코드,행정동명,total_flow_mean,flow_per_point_mean,male_ratio_mean,age_20_ratio_mean,age_30_ratio_mean,age_40_ratio_mean,age_50_ratio_mean,age_60_plus_ratio_mean,...,disabled_female_ratio,brain_lesion_ratio,visual_ratio,kidney_ratio,autism_ratio,mental_ratio,intellectual_ratio,physical_ratio,hearing_ratio,other_disability_ratio
0,1123051,신사동,424182.530000,607.269840,0.503033,0.167233,0.198218,0.194927,0.172209,0.193282,...,0.404494,0.115169,0.089888,0.070225,0.042135,0.016854,0.042135,0.396067,0.174157,0.053371
1,1123052,논현1동,344618.113333,696.198209,0.522369,0.196942,0.234957,0.203438,0.156841,0.161290,...,0.409506,0.098720,0.140768,0.049360,0.027422,0.036563,0.078611,0.383912,0.138940,0.045704
2,1123053,논현2동,403971.858333,698.913250,0.517462,0.178522,0.231816,0.208925,0.162009,0.167636,...,0.387168,0.079646,0.117257,0.059735,0.028761,0.022124,0.068584,0.418142,0.172566,0.033186
3,1123058,삼성1동,594872.323333,809.740536,0.524113,0.170581,0.221924,0.214355,0.170481,0.151670,...,0.356890,0.116608,0.109541,0.045936,0.063604,0.017668,0.053004,0.413428,0.155477,0.024735
4,1123059,삼성2동,354758.653333,705.285593,0.520436,0.157192,0.211135,0.214164,0.171410,0.171061,...,0.392491,0.100683,0.119454,0.064846,0.073379,0.029010,0.042662,0.353242,0.175768,0.040956

In [ ]:
output_file = "gangnam_db1_dong_feature_mart_2025.csv"

dong_feature_mart.to_csv(
    output_file,
    index=False,
    encoding="utf-8-sig"
)

print("저장 완료:", output_file)
print("shape:", dong_feature_mart.shape)

저장 완료: gangnam_db1_dong_feature_mart_2025.csv
shape: (22, 75)

In [ ]:
from google.colab import files

files.download(
    "gangnam_db1_dong_feature_mart_2025.csv"
)

In [ ]:
import numpy as np
import pandas as pd

# ==========================================
# 1. ML 후보 Feature
# ==========================================

id_cols = [
    "행정동코드",
    "행정동명"
]

feature_cols = [
    col for col in dong_feature_mart.columns
    if col not in id_cols
]

X = dong_feature_mart[feature_cols].copy()

print("[기본 구조]")
print("행정동 수:", len(X))
print("Feature 수:", X.shape[1])


# ==========================================
# 2. 결측값
# ==========================================

missing = X.isna().sum()
missing = missing[missing > 0]

print("\n[결측값]")
print(missing)


# ==========================================
# 3. 분산 확인
# ==========================================

std_values = X.std()

zero_variance = std_values[
    np.isclose(std_values, 0)
]

print("\n[분산이 0에 가까운 Feature]")
print("개수:", len(zero_variance))

if len(zero_variance) > 0:
    display(zero_variance)


# ==========================================
# 4. 전체 상관관계
# ==========================================

corr = X.corr()

corr_pairs = []

for i in range(len(feature_cols)):
    for j in range(i + 1, len(feature_cols)):

        r = corr.iloc[i, j]

        if pd.notna(r) and abs(r) >= 0.8:
            corr_pairs.append({
                "Feature_1": feature_cols[i],
                "Feature_2": feature_cols[j],
                "상관계수": r,
                "절대상관": abs(r)
            })

corr_pairs = pd.DataFrame(corr_pairs)

if len(corr_pairs) > 0:
    corr_pairs = (
        corr_pairs
        .sort_values(
            "절대상관",
            ascending=False
        )
        .reset_index(drop=True)
    )


# ==========================================
# 5. 강도별 요약
# ==========================================

print("\n[고상관 관계 요약]")

if len(corr_pairs) == 0:
    print("|r| >= 0.8 관계 없음")

else:
    print(
        "|r| >= 0.8 :",
        (corr_pairs["절대상관"] >= 0.8).sum()
    )

    print(
        "|r| >= 0.9 :",
        (corr_pairs["절대상관"] >= 0.9).sum()
    )

    print(
        "|r| >= 0.95:",
        (corr_pairs["절대상관"] >= 0.95).sum()
    )

    print("\n[|r| >= 0.9 관계]")

    display(
        corr_pairs[
            corr_pairs["절대상관"] >= 0.9
        ][
            ["Feature_1", "Feature_2", "상관계수"]
        ].round(3)
    )

[기본 구조]
행정동 수: 22
Feature 수: 73

[결측값]
medical_per_1000            1
elderly_medical_per_1000    1
dtype: int64

[분산이 0에 가까운 Feature]
개수: 0

[고상관 관계 요약]
|r| >= 0.8 : 81
|r| >= 0.9 : 32
|r| >= 0.95: 16

[|r| >= 0.9 관계]

                        Feature_1                       Feature_2   상관계수
0           single_gender_1_ratio           single_gender_2_ratio -1.000
1             disabled_male_ratio           disabled_female_ratio -1.000
2           single_household_mean  official_single_household_mean  0.985
3             livelihood_per_1000                medical_per_1000  0.982
4             livelihood_per_1000               disabled_per_1000  0.982
5             livelihood_per_1000     elderly_livelihood_per_1000  0.980
6                medical_per_1000               disabled_per_1000  0.978
7                medical_per_1000     elderly_livelihood_per_1000  0.978
8     elderly_livelihood_per_1000               disabled_per_1000  0.971
9        high_worktime_ratio_mean           high_video_ratio_mean  0.969
10               medical_per_1000                housing_per_1000  0.967
11               medical_per_1000        elderly_medical_per_1000  0.964
12    elderly_livelihood_per_1000        elderly_medical_per_1000  0.962
13               housing_per_1000     elderly_livelihood_per_1000  0.957
14               housing_per_1000        elderly_medical_per_1000  0.955
15               금융 서비스 사용일수_mean                쇼핑 서비스 사용일수_mean  0.952
16       elderly_medical_per_1000        elderly_housing_per_1000  0.948
17               housing_per_1000        elderly_housing_per_1000  0.947
18              age_20_ratio_mean               age_30_ratio_mean  0.947
19    elderly_livelihood_per_1000        elderly_housing_per_1000  0.944
20            livelihood_per_1000                housing_per_1000  0.937
21               배달 서비스 사용일수_mean                    데이터 사용량_mean  0.936
22  low_weekday_outing_ratio_mean        high_worktime_ratio_mean  0.934
23       elderly_medical_per_1000               disabled_per_1000  0.932
24               배달 서비스 사용일수_mean           resident_age_20_ratio  0.925
25               housing_per_1000               disabled_per_1000  0.924
26               배달 서비스 사용일수_mean          최근 3개월 내 요금 연체 비율_mean  0.921
27            livelihood_per_1000        elderly_medical_per_1000  0.920
28               medical_per_1000        elderly_housing_per_1000  0.915
29         최근 3개월 내 요금 연체 비율_mean                    데이터 사용량_mean  0.914
30         최근 3개월 내 요금 연체 비율_mean            foreigner_ratio_mean  0.913
31       elderly_housing_per_1000               disabled_per_1000  0.902

In [ ]:
# ==========================================
# ML Feature Matrix - 1차 정리
# 완전 종속 성별 변수 제거
# ==========================================

drop_exact_dependency = [
    "single_gender_2_ratio",
    "disabled_female_ratio"
]

ml_feature_v1 = dong_feature_mart.drop(
    columns=drop_exact_dependency
).copy()

print("[ML Feature Matrix V1]")
print("shape:", ml_feature_v1.shape)
print(
    "Feature 수:",
    ml_feature_v1.shape[1] - 2
)

print("\n[제거한 Feature]")
for col in drop_exact_dependency:
    print("-", col)

print("\n[결측값]")
missing_v1 = ml_feature_v1.isna().sum()
print(
    missing_v1[
        missing_v1 > 0
    ]
)

[ML Feature Matrix V1]
shape: (22, 73)
Feature 수: 71

[제거한 Feature]
- single_gender_2_ratio
- disabled_female_ratio

[결측값]
medical_per_1000            1
elderly_medical_per_1000    1
dtype: int64

In [ ]:
from sklearn.preprocessing import StandardScaler
from sklearn.decomposition import PCA
from sklearn.impute import SimpleImputer
import pandas as pd
import numpy as np

welfare_cols = [
    "livelihood_per_1000",
    "medical_per_1000",
    "housing_per_1000",
    "elderly_livelihood_per_1000",
    "elderly_medical_per_1000",
    "elderly_housing_per_1000"
]

# ==========================================
# 1. PCA 검증용 데이터
# ==========================================

X_welfare = ml_feature_v1[welfare_cols].copy()

# PCA 검증을 위해서만 결측값 중앙값 대체
imputer = SimpleImputer(strategy="median")
X_welfare_imputed = imputer.fit_transform(X_welfare)

# 변수별 단위/분포 차이를 제거하기 위해 표준화
scaler = StandardScaler()
X_welfare_scaled = scaler.fit_transform(
    X_welfare_imputed
)


# ==========================================
# 2. PCA
# ==========================================

pca = PCA()
X_welfare_pca = pca.fit_transform(
    X_welfare_scaled
)

explained = pd.DataFrame({
    "PC": [
        f"PC{i+1}"
        for i in range(len(welfare_cols))
    ],
    "설명분산비": pca.explained_variance_ratio_,
    "누적설명분산비":
        np.cumsum(
            pca.explained_variance_ratio_
        )
})

print("[Welfare PCA 설명분산]")
display(explained.round(4))


# ==========================================
# 3. PC1 Loading
# ==========================================

pc1_loading = pd.DataFrame({
    "Feature": welfare_cols,
    "PC1_Loading": pca.components_[0]
})

pc1_loading["절대Loading"] = (
    pc1_loading["PC1_Loading"].abs()
)

pc1_loading = (
    pc1_loading
    .sort_values(
        "절대Loading",
        ascending=False
    )
    .reset_index(drop=True)
)

print("\n[PC1 Loading]")
display(
    pc1_loading[
        ["Feature", "PC1_Loading"]
    ].round(4)
)

[Welfare PCA 설명분산]

    PC   설명분산비  누적설명분산비
0  PC1  0.9564   0.9564
1  PC2  0.0242   0.9806
2  PC3  0.0094   0.9899
3  PC4  0.0077   0.9976
4  PC5  0.0021   0.9998
5  PC6  0.0002   1.0000

[PC1 Loading]

                       Feature  PC1_Loading
0  elderly_livelihood_per_1000       0.4138
1             medical_per_1000       0.4122
2             housing_per_1000       0.4093
3     elderly_medical_per_1000       0.4083
4          livelihood_per_1000       0.4055
5     elderly_housing_per_1000       0.4003

In [ ]:
from sklearn.impute import SimpleImputer
from sklearn.preprocessing import StandardScaler
from sklearn.decomposition import PCA

# ==========================================
# Welfare 6개 → PC1 1개
# ==========================================

welfare_cols = [
    "livelihood_per_1000",
    "medical_per_1000",
    "housing_per_1000",
    "elderly_livelihood_per_1000",
    "elderly_medical_per_1000",
    "elderly_housing_per_1000"
]

X_welfare = ml_feature_v1[welfare_cols].copy()

# Welfare 내부 결측 2개만 중앙값 대체
welfare_imputer = SimpleImputer(strategy="median")
X_welfare_imputed = welfare_imputer.fit_transform(
    X_welfare
)

# 표준화
welfare_scaler = StandardScaler()
X_welfare_scaled = welfare_scaler.fit_transform(
    X_welfare_imputed
)

# PC1 추출
welfare_pca = PCA(n_components=1)

welfare_pc1 = welfare_pca.fit_transform(
    X_welfare_scaled
).ravel()


# ==========================================
# PC1 방향 확인
# ==========================================

print("[PC1 Loading]")

for col, loading in zip(
    welfare_cols,
    welfare_pca.components_[0]
):
    print(
        f"{col}: {loading:.4f}"
    )


# 모든 loading이 음수라면 방향 반전
if welfare_pca.components_[0].mean() < 0:
    welfare_pc1 = -welfare_pc1


# ==========================================
# ML Feature Matrix V2
# ==========================================

ml_feature_v2 = (
    ml_feature_v1
    .drop(columns=welfare_cols)
    .copy()
)

ml_feature_v2[
    "welfare_vulnerability_pc1"
] = welfare_pc1


# ==========================================
# 검증
# ==========================================

print("\n[ML Feature Matrix V2]")
print(
    "shape:",
    ml_feature_v2.shape
)

print(
    "Feature 수:",
    ml_feature_v2.shape[1] - 2
)

print(
    "전체 결측값:",
    ml_feature_v2.isna().sum().sum()
)

print(
    "Welfare PC1 설명분산비:",
    round(
        welfare_pca.explained_variance_ratio_[0],
        4
    )
)

display(
    ml_feature_v2[
        [
            "행정동코드",
            "행정동명",
            "welfare_vulnerability_pc1"
        ]
    ]
    .sort_values(
        "welfare_vulnerability_pc1",
        ascending=False
    )
)

[PC1 Loading]
livelihood_per_1000: 0.4055
medical_per_1000: 0.4122
housing_per_1000: 0.4093
elderly_livelihood_per_1000: 0.4138
elderly_medical_per_1000: 0.4083
elderly_housing_per_1000: 0.4003

[ML Feature Matrix V2]
shape: (22, 68)
Feature 수: 66
전체 결측값: 0
Welfare PC1 설명분산비: 0.9564

      행정동코드  행정동명  welfare_vulnerability_pc1
16  1123075   수서동                   8.289593
14  1123073  일원1동                   4.416528
15  1123074  개포3동                   3.362253
17  1123076   세곡동                   1.632379
1   1123052  논현1동                   0.108801
12  1123071  개포4동                   0.074333
7   1123064  역삼1동                  -0.003555
6   1123063  대치4동                  -0.143657
2   1123053  논현2동                  -0.475732
0   1123051   신사동                  -0.864145
4   1123059  삼성2동                  -0.872530
8   1123065  역삼2동                  -0.922840
3   1123058  삼성1동                  -1.321390
11  1123068  개포1동                  -1.357620
21  1123080  개포2동                  -1.360161
19  1123078   청담동                  -1.388369
13  1123072  일원본동                  -1.430586
5   1123060  대치1동                  -1.474953
9   1123066  도곡1동                  -1.493888
20  1123079  대치2동                  -1.538844
18  1123077  압구정동                  -1.601086
10  1123067  도곡2동                  -1.634532

In [ ]:
# ==========================================
# 조성자료 종속성 검증
# ==========================================

resident_age_cols = [
    "resident_age_10_ratio",
    "resident_age_20_ratio",
    "resident_age_30_ratio",
    "resident_age_40_ratio",
    "resident_age_50_ratio",
    "resident_age_60_plus_ratio"
]

single_age_gap_cols = [
    "single_age_20_gap",
    "single_age_30_gap",
    "single_age_40_gap",
    "single_age_50_gap",
    "single_age_60_plus_gap"
]

disability_type_cols = [
    "brain_lesion_ratio",
    "visual_ratio",
    "kidney_ratio",
    "autism_ratio",
    "mental_ratio",
    "intellectual_ratio",
    "physical_ratio",
    "hearing_ratio",
    "other_disability_ratio"
]

# 합 계산
resident_sum = ml_feature_v2[resident_age_cols].sum(axis=1)
single_gap_sum = ml_feature_v2[single_age_gap_cols].sum(axis=1)
disability_sum = ml_feature_v2[disability_type_cols].sum(axis=1)

print("[주민 연령비율 합]")
print(resident_sum.describe())

print("\n[1인가구 연령 Gap 합]")
print(single_gap_sum.describe())

print("\n[장애유형 비율 합]")
print(disability_sum.describe())

print("\n[1 또는 0으로부터 최대 오차]")
print(
    "주민 연령:",
    abs(resident_sum - 1).max()
)
print(
    "1인가구 age gap:",
    abs(single_gap_sum).max()
)
print(
    "장애유형:",
    abs(disability_sum - 1).max()
)

[주민 연령비율 합]
count    2.200000e+01
mean     1.000000e+00
std      1.370489e-16
min      1.000000e+00
25%      1.000000e+00
50%      1.000000e+00
75%      1.000000e+00
max      1.000000e+00
dtype: float64

[1인가구 연령 Gap 합]
count    2.200000e+01
mean     3.731627e-17
std      7.239205e-17
min     -1.110223e-16
25%     -2.602085e-18
50%      5.204170e-17
75%      1.023487e-16
max      1.110223e-16
dtype: float64

[장애유형 비율 합]
count    2.200000e+01
mean     1.000000e+00
std      7.516216e-07
min      9.999990e-01
25%      1.000000e+00
50%      1.000000e+00
75%      1.000001e+00
max      1.000001e+00
dtype: float64

[1 또는 0으로부터 최대 오차]
주민 연령: 3.3306690738754696e-16
1인가구 age gap: 1.1102230246251565e-16
장애유형: 1.000000000139778e-06

In [ ]:
# ==========================================
# ML Feature Matrix V3
# 조성자료 reference category 제거
# ==========================================

composition_reference_cols = [
    "resident_age_10_ratio",
    "single_age_60_plus_gap",
    "other_disability_ratio"
]

ml_feature_v3 = (
    ml_feature_v2
    .drop(columns=composition_reference_cols)
    .copy()
)

print("[ML Feature Matrix V3]")
print("shape:", ml_feature_v3.shape)
print(
    "Feature 수:",
    ml_feature_v3.shape[1] - 2
)

print(
    "전체 결측값:",
    ml_feature_v3.isna().sum().sum()
)

print("\n[제거한 조성자료 기준범주]")
for col in composition_reference_cols:
    print("-", col)

[ML Feature Matrix V3]
shape: (22, 65)
Feature 수: 63
전체 결측값: 0

[제거한 조성자료 기준범주]
- resident_age_10_ratio
- single_age_60_plus_gap
- other_disability_ratio

In [ ]:
# ==========================================
# ML Feature Matrix V3
# 전체 Feature 목록 확인
# ==========================================

feature_cols_v3 = [
    col for col in ml_feature_v3.columns
    if col not in ["행정동코드", "행정동명"]
]

print("전체 Feature 수:", len(feature_cols_v3))

for i, col in enumerate(feature_cols_v3, start=1):
    print(f"{i:02d}. {col}")

전체 Feature 수: 63
01. total_flow_mean
02. flow_per_point_mean
03. male_ratio_mean
04. age_20_ratio_mean
05. age_30_ratio_mean
06. age_40_ratio_mean
07. age_50_ratio_mean
08. age_60_plus_ratio_mean
09. morning_ratio_mean
10. daytime_ratio_mean
11. evening_ratio_mean
12. peak_hour_ratio_mean
13. weekend_weekday_index_mean
14. peak_day_ratio_mean
15. low_comm_ratio_mean
16. low_weekday_outing_ratio_mean
17. low_holiday_outing_ratio_mean
18. high_worktime_ratio_mean
19. high_video_ratio_mean
20. high_life_service_ratio_mean
21. financial_interest_ratio_mean
22. very_low_outing_ratio_mean
23. very_low_outing_comm_ratio_mean
24. 야간상주지 변경횟수 평균_mean
25. 평균 근무시간 평균_mean
26. 평일 총 이동 횟수_mean
27. 휴일 총 이동 횟수 평균_mean
28. 집 추정 위치 평일 총 체류시간_mean
29. 집 추정 위치 휴일 총 체류시간_mean
30. 금융 서비스 사용일수_mean
31. 쇼핑 서비스 사용일수_mean
32. 배달 서비스 사용일수_mean
33. 최근 3개월 내 요금 연체 비율_mean
34. 평균 통화대상자 수_mean
35. 데이터 사용량_mean
36. 카카오톡_비사용비율_mean
37. resident_total_mean
38. foreigner_ratio_mean
39. resident_age_20_ratio
40. resident_age_30_ratio
41. resident_age_40_ratio
42. resident_age_50_ratio
43. resident_age_60_plus_ratio
44. single_age_20_gap
45. single_age_30_gap
46. single_age_40_gap
47. single_age_50_gap
48. single_gender_1_ratio
49. single_household_mean
50. official_single_household_mean
51. official_single_household_change_rate
52. disabled_total
53. disabled_per_1000
54. disabled_male_ratio
55. brain_lesion_ratio
56. visual_ratio
57. kidney_ratio
58. autism_ratio
59. mental_ratio
60. intellectual_ratio
61. physical_ratio
62. hearing_ratio
63. welfare_vulnerability_pc1

In [ ]:
feature_groups = {
    "A_유동활동규모": [
        "total_flow_mean",
        "flow_per_point_mean"
    ],

    "B_유동인구구조": [
        "male_ratio_mean",
        "age_20_ratio_mean",
        "age_30_ratio_mean",
        "age_40_ratio_mean",
        "age_50_ratio_mean",
        "age_60_plus_ratio_mean"
    ],

    "C_시간요일활동": [
        "morning_ratio_mean",
        "daytime_ratio_mean",
        "evening_ratio_mean",
        "peak_hour_ratio_mean",
        "weekend_weekday_index_mean",
        "peak_day_ratio_mean"
    ],

    "D_시민생활관심집단": [
        "low_comm_ratio_mean",
        "low_weekday_outing_ratio_mean",
        "low_holiday_outing_ratio_mean",
        "high_worktime_ratio_mean",
        "high_video_ratio_mean",
        "high_life_service_ratio_mean",
        "financial_interest_ratio_mean",
        "very_low_outing_ratio_mean",
        "very_low_outing_comm_ratio_mean"
    ],

    "E_이동체류": [
        "야간상주지 변경횟수 평균_mean",
        "평균 근무시간 평균_mean",
        "평일 총 이동 횟수_mean",
        "휴일 총 이동 횟수 평균_mean",
        "집 추정 위치 평일 총 체류시간_mean",
        "집 추정 위치 휴일 총 체류시간_mean"
    ],

    "F_통신생활서비스금융": [
        "금융 서비스 사용일수_mean",
        "쇼핑 서비스 사용일수_mean",
        "배달 서비스 사용일수_mean",
        "최근 3개월 내 요금 연체 비율_mean",
        "평균 통화대상자 수_mean",
        "데이터 사용량_mean",
        "카카오톡_비사용비율_mean"
    ],

    "G_주민인구구조": [
        "resident_total_mean",
        "foreigner_ratio_mean",
        "resident_age_20_ratio",
        "resident_age_30_ratio",
        "resident_age_40_ratio",
        "resident_age_50_ratio",
        "resident_age_60_plus_ratio"
    ],

    "H_1인가구구조": [
        "single_age_20_gap",
        "single_age_30_gap",
        "single_age_40_gap",
        "single_age_50_gap",
        "single_gender_1_ratio",
        "single_household_mean",
        "official_single_household_mean",
        "official_single_household_change_rate"
    ],

    "I_장애관련구조": [
        "disabled_total",
        "disabled_per_1000",
        "disabled_male_ratio",
        "brain_lesion_ratio",
        "visual_ratio",
        "kidney_ratio",
        "autism_ratio",
        "mental_ratio",
        "intellectual_ratio",
        "physical_ratio",
        "hearing_ratio"
    ],

    "J_복지경제취약": [
        "welfare_vulnerability_pc1"
    ]
}


# ==========================================
# 도메인별 내부 고상관 관계 요약
# ==========================================

summary = []

for group_name, cols in feature_groups.items():

    if len(cols) == 1:
        summary.append({
            "도메인": group_name,
            "Feature수": 1,
            "|r|>=0.8": 0,
            "|r|>=0.9": 0,
            "최대|r|": np.nan
        })
        continue

    corr = ml_feature_v3[cols].corr().abs()

    upper = corr.where(
        np.triu(
            np.ones(corr.shape),
            k=1
        ).astype(bool)
    )

    values = upper.stack()

    summary.append({
        "도메인": group_name,
        "Feature수": len(cols),
        "|r|>=0.8": (values >= 0.8).sum(),
        "|r|>=0.9": (values >= 0.9).sum(),
        "최대|r|": values.max()
    })


domain_corr_summary = pd.DataFrame(summary)

display(
    domain_corr_summary.round(3)
)

           도메인  Feature수  |r|>=0.8  |r|>=0.9  최대|r|
0     A_유동활동규모         2         0         0  0.749
1     B_유동인구구조         6         2         1  0.947
2     C_시간요일활동         6         1         0  0.832
3   D_시민생활관심집단         9         6         2  0.969
4       E_이동체류         6         1         0  0.897
5  F_통신생활서비스금융         7         4         4  0.952
6     G_주민인구구조         7         3         0  0.886
7     H_1인가구구조         8         1         1  0.985
8     I_장애관련구조        11         0         0  0.790
9     J_복지경제취약         1         0         0    NaN

In [ ]:
# ==========================================
# 추가 검토가 필요한 도메인의 고상관 쌍 확인
# ==========================================

check_groups = [
    "B_유동인구구조",
    "D_시민생활관심집단",
    "F_통신생활서비스금융",
    "H_1인가구구조"
]

for group_name in check_groups:

    cols = feature_groups[group_name]
    corr = ml_feature_v3[cols].corr()

    pairs = []

    for i in range(len(cols)):
        for j in range(i + 1, len(cols)):

            r = corr.iloc[i, j]

            if abs(r) >= 0.8:
                pairs.append({
                    "Feature_1": cols[i],
                    "Feature_2": cols[j],
                    "상관계수": r,
                    "절대상관": abs(r)
                })

    pairs = pd.DataFrame(pairs)

    print("\n" + "=" * 70)
    print(group_name)
    print("=" * 70)

    if len(pairs) == 0:
        print("|r| >= 0.8 관계 없음")
    else:
        pairs = (
            pairs
            .sort_values(
                "절대상관",
                ascending=False
            )
            .drop(columns="절대상관")
            .reset_index(drop=True)
        )

        display(pairs.round(3))

======================================================================
B_유동인구구조
======================================================================

           Feature_1          Feature_2   상관계수
0  age_20_ratio_mean  age_30_ratio_mean  0.947
1  age_20_ratio_mean  age_50_ratio_mean -0.869

======================================================================
D_시민생활관심집단
======================================================================

                       Feature_1                      Feature_2   상관계수
0       high_worktime_ratio_mean          high_video_ratio_mean  0.969
1  low_weekday_outing_ratio_mean       high_worktime_ratio_mean  0.934
2  low_weekday_outing_ratio_mean          high_video_ratio_mean  0.889
3            low_comm_ratio_mean  financial_interest_ratio_mean  0.862
4            low_comm_ratio_mean          high_video_ratio_mean  0.848
5   high_life_service_ratio_mean  financial_interest_ratio_mean  0.836

======================================================================
F_통신생활서비스금융
======================================================================

                Feature_1               Feature_2   상관계수
0        금융 서비스 사용일수_mean        쇼핑 서비스 사용일수_mean  0.952
1        배달 서비스 사용일수_mean            데이터 사용량_mean  0.936
2        배달 서비스 사용일수_mean  최근 3개월 내 요금 연체 비율_mean  0.921
3  최근 3개월 내 요금 연체 비율_mean            데이터 사용량_mean  0.914

======================================================================
H_1인가구구조
======================================================================

               Feature_1                       Feature_2   상관계수
0  single_household_mean  official_single_household_mean  0.985

In [ ]:
# ==========================================
# ML Feature Matrix V4
# 중복된 1인가구 규모 Feature 정리
# ==========================================

drop_v4 = [
    "single_household_mean"
]

ml_feature_v4 = (
    ml_feature_v3
    .drop(columns=drop_v4)
    .copy()
)

print("[ML Feature Matrix V4]")
print("shape:", ml_feature_v4.shape)

print(
    "Feature 수:",
    ml_feature_v4.shape[1] - 2
)

print(
    "전체 결측값:",
    ml_feature_v4.isna().sum().sum()
)

print("\n[제거 Feature]")
for col in drop_v4:
    print("-", col)

[ML Feature Matrix V4]
shape: (22, 64)
Feature 수: 62
전체 결측값: 0

[제거 Feature]
- single_household_mean

In [ ]:
from sklearn.preprocessing import StandardScaler
from sklearn.decomposition import PCA
import numpy as np
import pandas as pd

# ==========================================
# V4 기준 Feature Group 수정
# ==========================================

feature_groups_v4 = {
    group: [
        col for col in cols
        if col in ml_feature_v4.columns
    ]
    for group, cols in feature_groups.items()
}

# Welfare는 이미 PCA 완료 → 이번 진단 제외
feature_groups_v4.pop(
    "J_복지경제취약",
    None
)


# ==========================================
# 도메인별 PCA 설명분산 진단
# ==========================================

pca_summary = []

for group_name, cols in feature_groups_v4.items():

    X_group = ml_feature_v4[cols].copy()

    # 표준화
    scaler = StandardScaler()
    X_scaled = scaler.fit_transform(X_group)

    # 전체 PCA
    pca = PCA()
    pca.fit(X_scaled)

    explained = pca.explained_variance_ratio_
    cumulative = np.cumsum(explained)

    # 80%, 90%, 95% 설명에 필요한 PC 수
    n80 = np.argmax(cumulative >= 0.80) + 1
    n90 = np.argmax(cumulative >= 0.90) + 1
    n95 = np.argmax(cumulative >= 0.95) + 1

    pca_summary.append({
        "도메인": group_name,
        "원본_Feature수": len(cols),
        "PC1_설명분산": explained[0],
        "PC1_PC2_누적": (
            cumulative[1]
            if len(cumulative) >= 2
            else cumulative[0]
        ),
        "80%_PC수": n80,
        "90%_PC수": n90,
        "95%_PC수": n95
    })


pca_domain_summary = pd.DataFrame(
    pca_summary
)

display(
    pca_domain_summary.round(3)
)

           도메인  원본_Feature수  PC1_설명분산  PC1_PC2_누적  80%_PC수  90%_PC수  95%_PC수
0     A_유동활동규모            2     0.874       1.000        1        2        2
1     B_유동인구구조            6     0.686       0.864        2        3        3
2     C_시간요일활동            6     0.531       0.822        2        3        4
3   D_시민생활관심집단            9     0.680       0.853        2        3        4
4       E_이동체류            6     0.474       0.715        3        4        4
5  F_통신생활서비스금융            7     0.546       0.823        2        3        3
6     G_주민인구구조            7     0.454       0.818        2        3        4
7     H_1인가구구조            7     0.375       0.641        4        5        5
8     I_장애관련구조           11     0.377       0.603        4        6        7

In [ ]:
# ==========================================
# 행동 관련 A~F PCA Loading 확인
# ==========================================

behavior_groups = [
    "A_유동활동규모",
    "B_유동인구구조",
    "C_시간요일활동",
    "D_시민생활관심집단",
    "E_이동체류",
    "F_통신생활서비스금융"
]

for group_name in behavior_groups:

    cols = feature_groups_v4[group_name]

    X_group = ml_feature_v4[cols]

    scaler = StandardScaler()
    X_scaled = scaler.fit_transform(X_group)

    n_components = min(3, len(cols))

    pca = PCA(
        n_components=n_components
    )

    pca.fit(X_scaled)

    loading = pd.DataFrame(
        pca.components_.T,
        index=cols,
        columns=[
            f"PC{i+1}"
            for i in range(n_components)
        ]
    )

    print("\n" + "=" * 75)
    print(group_name)
    print("=" * 75)

    print(
        "설명분산:",
        np.round(
            pca.explained_variance_ratio_,
            3
        )
    )

    display(
        loading.round(3)
    )

===========================================================================
A_유동활동규모
===========================================================================
설명분산: [0.874 0.126]

                       PC1    PC2
total_flow_mean      0.707  0.707
flow_per_point_mean  0.707 -0.707

===========================================================================
B_유동인구구조
===========================================================================
설명분산: [0.686 0.178 0.091]

                          PC1    PC2    PC3
male_ratio_mean         0.341 -0.447  0.710
age_20_ratio_mean       0.470 -0.142 -0.228
age_30_ratio_mean       0.460 -0.217  0.093
age_40_ratio_mean       0.270  0.758  0.372
age_50_ratio_mean      -0.430  0.123  0.534
age_60_plus_ratio_mean -0.441 -0.379  0.111

===========================================================================
C_시간요일활동
===========================================================================
설명분산: [0.531 0.291 0.114]

                              PC1    PC2    PC3
morning_ratio_mean         -0.369  0.515 -0.247
daytime_ratio_mean          0.525 -0.190 -0.255
evening_ratio_mean         -0.355 -0.360  0.731
peak_hour_ratio_mean        0.445 -0.383  0.030
weekend_weekday_index_mean -0.357 -0.498 -0.283
peak_day_ratio_mean         0.369  0.418  0.509

===========================================================================
D_시민생활관심집단
===========================================================================
설명분산: [0.68  0.174 0.068]

                                   PC1    PC2    PC3
low_comm_ratio_mean              0.370  0.192 -0.169
low_weekday_outing_ratio_mean    0.362 -0.196 -0.284
low_holiday_outing_ratio_mean    0.227  0.582  0.352
high_worktime_ratio_mean         0.375 -0.210 -0.273
high_video_ratio_mean            0.376 -0.208 -0.204
high_life_service_ratio_mean     0.323  0.297  0.052
financial_interest_ratio_mean    0.345  0.365 -0.177
very_low_outing_ratio_mean       0.284 -0.496  0.298
very_low_outing_comm_ratio_mean  0.308 -0.180  0.727

===========================================================================
E_이동체류
===========================================================================
설명분산: [0.474 0.241 0.158]

                          PC1    PC2    PC3
야간상주지 변경횟수 평균_mean      0.258  0.500  0.500
평균 근무시간 평균_mean         0.014  0.748 -0.032
평일 총 이동 횟수_mean         0.507 -0.199  0.398
휴일 총 이동 횟수 평균_mean      0.507 -0.310  0.209
집 추정 위치 평일 총 체류시간_mean -0.501 -0.234  0.334
집 추정 위치 휴일 총 체류시간_mean -0.409 -0.005  0.660

===========================================================================
F_통신생활서비스금융
===========================================================================
설명분산: [0.546 0.276 0.147]

                          PC1    PC2    PC3
금융 서비스 사용일수_mean        0.354 -0.505 -0.069
쇼핑 서비스 사용일수_mean        0.375 -0.446 -0.215
배달 서비스 사용일수_mean        0.494  0.126  0.111
최근 3개월 내 요금 연체 비율_mean  0.449  0.310 -0.046
평균 통화대상자 수_mean         0.179  0.089  0.909
데이터 사용량_mean            0.493  0.112 -0.115
카카오톡_비사용비율_mean         0.114  0.644 -0.309

In [ ]:
# ==========================================
# 구조적 배경 G~I PCA Loading 확인
# ==========================================

structure_groups = [
    "G_주민인구구조",
    "H_1인가구구조",
    "I_장애관련구조"
]

for group_name in structure_groups:

    cols = feature_groups_v4[group_name]

    X_group = ml_feature_v4[cols]

    scaler = StandardScaler()
    X_scaled = scaler.fit_transform(X_group)

    # H, I는 정보가 더 분산되어 있으므로 최대 4개까지 확인
    n_components = min(4, len(cols))

    pca = PCA(
        n_components=n_components
    )

    pca.fit(X_scaled)

    loading = pd.DataFrame(
        pca.components_.T,
        index=cols,
        columns=[
            f"PC{i+1}"
            for i in range(n_components)
        ]
    )

    print("\n" + "=" * 75)
    print(group_name)
    print("=" * 75)

    print(
        "설명분산:",
        np.round(
            pca.explained_variance_ratio_,
            3
        )
    )

    print(
        "누적설명분산:",
        np.round(
            np.cumsum(
                pca.explained_variance_ratio_
            ),
            3
        )
    )

    display(
        loading.round(3)
    )

===========================================================================
G_주민인구구조
===========================================================================
설명분산: [0.454 0.364 0.119 0.039]
누적설명분산: [0.454 0.818 0.937 0.976]

                              PC1    PC2    PC3    PC4
resident_total_mean        -0.114 -0.400  0.768 -0.444
foreigner_ratio_mean        0.506 -0.163 -0.235 -0.049
resident_age_20_ratio       0.454 -0.332 -0.191 -0.228
resident_age_30_ratio       0.532 -0.105  0.161  0.025
resident_age_40_ratio      -0.290 -0.497 -0.005  0.597
resident_age_50_ratio      -0.396 -0.259 -0.522 -0.596
resident_age_60_plus_ratio -0.005  0.615  0.139 -0.190

===========================================================================
H_1인가구구조
===========================================================================
설명분산: [0.375 0.266 0.14  0.107]
누적설명분산: [0.375 0.641 0.781 0.888]

                                         PC1    PC2    PC3    PC4
single_age_20_gap                      0.499 -0.129 -0.176 -0.540
single_age_30_gap                      0.540 -0.223  0.070 -0.177
single_age_40_gap                      0.286  0.554 -0.077  0.158
single_age_50_gap                     -0.214  0.617 -0.234 -0.144
single_gender_1_ratio                  0.407  0.082  0.474  0.612
official_single_household_mean         0.393  0.398 -0.210 -0.041
official_single_household_change_rate -0.111  0.282  0.797 -0.505

===========================================================================
I_장애관련구조
===========================================================================
설명분산: [0.377 0.226 0.135 0.089]
누적설명분산: [0.377 0.603 0.737 0.826]

                       PC1    PC2    PC3    PC4
disabled_total       0.331 -0.219  0.161  0.529
disabled_per_1000    0.340 -0.265  0.321  0.329
disabled_male_ratio -0.370 -0.015 -0.283  0.463
brain_lesion_ratio  -0.290  0.245  0.325  0.427
visual_ratio        -0.083 -0.425 -0.455 -0.128
kidney_ratio        -0.359  0.189  0.164  0.083
autism_ratio         0.082  0.550 -0.239  0.022
mental_ratio         0.443  0.146  0.058 -0.117
intellectual_ratio   0.365  0.011 -0.243  0.084
physical_ratio      -0.244 -0.504 -0.063  0.056
hearing_ratio       -0.147 -0.164  0.573 -0.409

In [ ]:
from sklearn.preprocessing import StandardScaler
from sklearn.decomposition import PCA
import pandas as pd
import numpy as np

# ==========================================
# 도메인별 사용할 PC 개수
# ==========================================

domain_n_components = {
    "A_유동활동규모": 1,
    "B_유동인구구조": 2,
    "C_시간요일활동": 2,
    "D_시민생활관심집단": 2,
    "E_이동체류": 2,
    "F_통신생활서비스금융": 3,
    "G_주민인구구조": 3,
    "H_1인가구구조": 3,
    "I_장애관련구조": 4
}

domain_pc_parts = []

# ==========================================
# A~I 도메인별 PCA
# ==========================================

for group_name, n_pc in domain_n_components.items():

    cols = feature_groups_v4[group_name]

    X_group = ml_feature_v4[cols].copy()

    scaler = StandardScaler()
    X_scaled = scaler.fit_transform(X_group)

    pca = PCA(n_components=n_pc)
    X_pca = pca.fit_transform(X_scaled)

    pc_cols = [
        f"{group_name}_PC{i+1}"
        for i in range(n_pc)
    ]

    pc_df = pd.DataFrame(
        X_pca,
        columns=pc_cols,
        index=ml_feature_v4.index
    )

    domain_pc_parts.append(pc_df)


# ==========================================
# A~I 결합
# ==========================================

domain_pc_matrix = pd.concat(
    domain_pc_parts,
    axis=1
)


# ==========================================
# J. 기존 Welfare PC1 추가
# ==========================================

domain_pc_matrix[
    "J_복지경제취약_PC1"
] = ml_feature_v4[
    "welfare_vulnerability_pc1"
].values


# ==========================================
# ID 추가
# ==========================================

domain_feature_matrix = pd.concat(
    [
        ml_feature_v4[
            ["행정동코드", "행정동명"]
        ].reset_index(drop=True),

        domain_pc_matrix.reset_index(drop=True)
    ],
    axis=1
)


# ==========================================
# 검증
# ==========================================

print("[Domain Feature Matrix]")
print(
    "shape:",
    domain_feature_matrix.shape
)

print(
    "Feature 수:",
    domain_feature_matrix.shape[1] - 2
)

print(
    "결측값:",
    domain_feature_matrix.isna().sum().sum()
)

print("\n[도메인별 PC 수]")
for group, n_pc in domain_n_components.items():
    print(group, ":", n_pc)

print(
    "J_복지경제취약 : 1"
)

display(
    domain_feature_matrix.head()
)

[Domain Feature Matrix]
shape: (22, 25)
Feature 수: 23
결측값: 0

[도메인별 PC 수]
A_유동활동규모 : 1
B_유동인구구조 : 2
C_시간요일활동 : 2
D_시민생활관심집단 : 2
E_이동체류 : 2
F_통신생활서비스금융 : 3
G_주민인구구조 : 3
H_1인가구구조 : 3
I_장애관련구조 : 4
J_복지경제취약 : 1

,행정동코드,행정동명,A_유동활동규모_PC1,B_유동인구구조_PC1,B_유동인구구조_PC2,C_시간요일활동_PC1,C_시간요일활동_PC2,D_시민생활관심집단_PC1,D_시민생활관심집단_PC2,E_이동체류_PC1,...,G_주민인구구조_PC2,G_주민인구구조_PC3,H_1인가구구조_PC1,H_1인가구구조_PC2,H_1인가구구조_PC3,I_장애관련구조_PC1,I_장애관련구조_PC2,I_장애관련구조_PC3,I_장애관련구조_PC4,J_복지경제취약_PC1
0,1123051,신사동,0.408961,0.821199,-0.533824,0.506843,-1.544190,1.435323,-0.381605,-0.162593,...,0.847111,-1.320904,0.925320,-1.109823,0.182534,-1.681937,-0.200957,1.175394,-0.579243,-0.864145
1,1123052,논현1동,0.373265,3.183350,-0.698515,1.308908,-0.060109,3.364788,-0.613169,-2.261303,...,-0.928714,-0.237792,1.828492,1.239963,-0.703384,0.416875,-1.967311,-2.262683,-0.469895,0.108801
2,1123053,논현2동,0.556489,2.659018,-0.090081,2.062382,0.850516,2.386968,-1.362067,-2.039967,...,-0.438507,-0.443688,1.783356,0.495978,-0.419086,-0.536427,-2.169379,-0.920199,-1.325324,-0.475732
3,1123058,삼성1동,1.377319,2.486289,0.430788,3.630542,-0.663808,1.571483,-0.677547,0.238937,...,0.976356,-1.461459,0.278945,0.918323,1.878847,-1.333516,-0.629415,-0.954915,0.058828,-1.321390
4,1123059,삼성2동,0.424124,1.884657,0.483748,1.909553,1.076083,1.081723,-0.862931,-1.815479,...,-1.374895,-0.166242,1.217447,-0.376328,-0.198532,-0.942033,-0.180541,-0.233624,-0.992975,-0.872530

In [ ]:
# ==========================================
# Domain Feature의 실제 분산 기여도 확인
# ==========================================

domain_prefix_map = {
    "A": "A_유동활동규모",
    "B": "B_유동인구구조",
    "C": "C_시간요일활동",
    "D": "D_시민생활관심집단",
    "E": "E_이동체류",
    "F": "F_통신생활서비스금융",
    "G": "G_주민인구구조",
    "H": "H_1인가구구조",
    "I": "I_장애관련구조",
    "J": "J_복지경제취약"
}

pc_cols = [
    col for col in domain_feature_matrix.columns
    if col not in ["행정동코드", "행정동명"]
]

rows = []

for code, domain_name in domain_prefix_map.items():

    cols = [
        col for col in pc_cols
        if col.startswith(f"{code}_")
    ]

    variances = (
        domain_feature_matrix[cols]
        .var(ddof=0)
    )

    rows.append({
        "도메인": domain_name,
        "PC수": len(cols),
        "분산합": variances.sum(),
        "PC당_평균분산": variances.mean()
    })

domain_variance = pd.DataFrame(rows)

domain_variance["전체분산_기여율"] = (
    domain_variance["분산합"]
    / domain_variance["분산합"].sum()
)

print("[도메인별 현재 거리 기여 구조]")

display(
    domain_variance.round(4)
)

[도메인별 현재 거리 기여 구조]

           도메인  PC수     분산합  PC당_평균분산  전체분산_기여율
0     A_유동활동규모    1  1.7486    1.7486    0.0304
1     B_유동인구구조    2  5.1854    2.5927    0.0902
2     C_시간요일활동    2  4.9335    2.4668    0.0858
3   D_시민생활관심집단    2  7.6815    3.8407    0.1337
4       E_이동체류    2  4.2872    2.1436    0.0746
5  F_통신생활서비스금융    3  6.7875    2.2625    0.1181
6     G_주민인구구조    3  6.5590    2.1863    0.1141
7     H_1인가구구조    3  5.4657    1.8219    0.0951
8     I_장애관련구조    4  9.0871    2.2718    0.1581
9     J_복지경제취약    1  5.7382    5.7382    0.0998

In [ ]:
# ==========================================
# Domain-balanced Feature Matrix 생성
# 각 도메인의 총 분산 = 1
# ==========================================

balanced_pc_matrix = domain_pc_matrix.copy()

balance_info = []

for code, domain_name in domain_prefix_map.items():

    cols = [
        col for col in balanced_pc_matrix.columns
        if col.startswith(f"{code}_")
    ]

    # 현재 도메인의 총 분산
    current_variance = (
        balanced_pc_matrix[cols]
        .var(ddof=0)
        .sum()
    )

    # 총 분산을 1로 맞추기 위한 가중치
    weight = 1 / np.sqrt(current_variance)

    # 해당 도메인의 모든 PC에 동일한 가중치 적용
    balanced_pc_matrix[cols] = (
        balanced_pc_matrix[cols] * weight
    )

    new_variance = (
        balanced_pc_matrix[cols]
        .var(ddof=0)
        .sum()
    )

    balance_info.append({
        "도메인": domain_name,
        "PC수": len(cols),
        "기존_분산합": current_variance,
        "가중치": weight,
        "조정후_분산합": new_variance
    })


balance_info = pd.DataFrame(balance_info)


# ==========================================
# ID 결합
# ==========================================

balanced_domain_feature_matrix = pd.concat(
    [
        domain_feature_matrix[
            ["행정동코드", "행정동명"]
        ].reset_index(drop=True),

        balanced_pc_matrix.reset_index(drop=True)
    ],
    axis=1
)


# ==========================================
# 검증
# ==========================================

print("[Domain Balance 결과]")

display(
    balance_info.round(4)
)

print(
    "\nshape:",
    balanced_domain_feature_matrix.shape
)

print(
    "Feature 수:",
    balanced_domain_feature_matrix.shape[1] - 2
)

print(
    "결측값:",
    balanced_domain_feature_matrix.isna().sum().sum()
)


# ==========================================
# 실제 조정 후 기여율 확인
# ==========================================

check_rows = []

for code, domain_name in domain_prefix_map.items():

    cols = [
        col for col in balanced_pc_matrix.columns
        if col.startswith(f"{code}_")
    ]

    variance_sum = (
        balanced_pc_matrix[cols]
        .var(ddof=0)
        .sum()
    )

    check_rows.append({
        "도메인": domain_name,
        "조정후_분산합": variance_sum
    })

balance_check = pd.DataFrame(check_rows)

balance_check["전체분산_기여율"] = (
    balance_check["조정후_분산합"]
    / balance_check["조정후_분산합"].sum()
)

print("\n[조정 후 실제 기여율]")

display(
    balance_check.round(4)
)

[Domain Balance 결과]

           도메인  PC수  기존_분산합     가중치  조정후_분산합
0     A_유동활동규모    1  1.7486  0.7562      1.0
1     B_유동인구구조    2  5.1854  0.4391      1.0
2     C_시간요일활동    2  4.9335  0.4502      1.0
3   D_시민생활관심집단    2  7.6815  0.3608      1.0
4       E_이동체류    2  4.2872  0.4830      1.0
5  F_통신생활서비스금융    3  6.7875  0.3838      1.0
6     G_주민인구구조    3  6.5590  0.3905      1.0
7     H_1인가구구조    3  5.4657  0.4277      1.0
8     I_장애관련구조    4  9.0871  0.3317      1.0
9     J_복지경제취약    1  5.7382  0.4175      1.0

shape: (22, 25)
Feature 수: 23
결측값: 0

[조정 후 실제 기여율]

           도메인  조정후_분산합  전체분산_기여율
0     A_유동활동규모      1.0       0.1
1     B_유동인구구조      1.0       0.1
2     C_시간요일활동      1.0       0.1
3   D_시민생활관심집단      1.0       0.1
4       E_이동체류      1.0       0.1
5  F_통신생활서비스금융      1.0       0.1
6     G_주민인구구조      1.0       0.1
7     H_1인가구구조      1.0       0.1
8     I_장애관련구조      1.0       0.1
9     J_복지경제취약      1.0       0.1

In [ ]:
from sklearn.cluster import KMeans
from sklearn.metrics import silhouette_score
import pandas as pd

# ==========================================
# K-Means k 후보 진단
# ==========================================

X_cluster = balanced_domain_feature_matrix.drop(
    columns=["행정동코드", "행정동명"]
)

k_results = []

for k in range(2, 7):

    model = KMeans(
        n_clusters=k,
        random_state=42,
        n_init=50
    )

    labels = model.fit_predict(X_cluster)

    silhouette = silhouette_score(
        X_cluster,
        labels
    )

    cluster_sizes = (
        pd.Series(labels)
        .value_counts()
        .sort_index()
        .to_dict()
    )

    min_cluster_size = min(
        cluster_sizes.values()
    )

    k_results.append({
        "k": k,
        "silhouette_score": silhouette,
        "inertia": model.inertia_,
        "min_cluster_size": min_cluster_size,
        "cluster_sizes": cluster_sizes
    })


k_diagnostic = pd.DataFrame(k_results)

print("[K-Means k 후보 진단]")

display(
    k_diagnostic.round({
        "silhouette_score": 4,
        "inertia": 4
    })
)

[K-Means k 후보 진단]

,k,silhouette_score,inertia,min_cluster_size,cluster_sizes
0,2,0.2601,147.2516,11,"{0: 11, 1: 11}"
1,3,0.2365,114.3207,3,"{0: 3, 1: 12, 2: 7}"
2,4,0.1970,92.4161,3,"{0: 8, 1: 8, 2: 3, 3: 3}"
3,5,0.1876,79.0830,1,"{0: 7, 1: 2, 2: 4, 3: 8, 4: 1}"
4,6,0.1580,67.5947,1,"{0: 1, 1: 3, 2: 7, 3: 5, 4: 5, 5: 1}"

In [ ]:
# ==========================================
# k=2 / k=3 군집 구성 비교
# ==========================================

cluster_compare = balanced_domain_feature_matrix[
    ["행정동코드", "행정동명"]
].copy()

for k in [2, 3]:

    model = KMeans(
        n_clusters=k,
        random_state=42,
        n_init=50
    )

    cluster_compare[
        f"cluster_k{k}"
    ] = model.fit_predict(
        X_cluster
    )


# ==========================================
# 전체 비교표
# ==========================================

print("[k=2 / k=3 행정동 비교]")

display(
    cluster_compare.sort_values(
        ["cluster_k2", "cluster_k3", "행정동명"]
    )
)


# ==========================================
# 군집별 구성원
# ==========================================

for k in [2, 3]:

    print("\n" + "=" * 70)
    print(f"k={k}")
    print("=" * 70)

    for cluster_id in sorted(
        cluster_compare[f"cluster_k{k}"].unique()
    ):

        members = cluster_compare.loc[
            cluster_compare[f"cluster_k{k}"] == cluster_id,
            "행정동명"
        ].tolist()

        print(
            f"Cluster {cluster_id} "
            f"(n={len(members)}):"
        )

        print(", ".join(members))

[k=2 / k=3 행정동 비교]

      행정동코드  행정동명  cluster_k2  cluster_k3
20  1123079  대치2동           0           1
0   1123051   신사동           0           1
18  1123077  압구정동           0           1
19  1123078   청담동           0           1
1   1123052  논현1동           0           2
2   1123053  논현2동           0           2
6   1123063  대치4동           0           2
3   1123058  삼성1동           0           2
4   1123059  삼성2동           0           2
7   1123064  역삼1동           0           2
8   1123065  역삼2동           0           2
15  1123074  개포3동           1           0
16  1123075   수서동           1           0
14  1123073  일원1동           1           0
11  1123068  개포1동           1           1
21  1123080  개포2동           1           1
12  1123071  개포4동           1           1
5   1123060  대치1동           1           1
9   1123066  도곡1동           1           1
10  1123067  도곡2동           1           1
17  1123076   세곡동           1           1
13  1123072  일원본동           1           1

======================================================================
k=2
======================================================================
Cluster 0 (n=11):
신사동, 논현1동, 논현2동, 삼성1동, 삼성2동, 대치4동, 역삼1동, 역삼2동, 압구정동, 청담동, 대치2동
Cluster 1 (n=11):
대치1동, 도곡1동, 도곡2동, 개포1동, 개포4동, 일원본동, 일원1동, 개포3동, 수서동, 세곡동, 개포2동

======================================================================
k=3
======================================================================
Cluster 0 (n=3):
일원1동, 개포3동, 수서동
Cluster 1 (n=12):
신사동, 대치1동, 도곡1동, 도곡2동, 개포1동, 개포4동, 일원본동, 세곡동, 압구정동, 청담동, 대치2동, 개포2동
Cluster 2 (n=7):
논현1동, 논현2동, 삼성1동, 삼성2동, 대치4동, 역삼1동, 역삼2동

In [ ]:
from itertools import combinations
import numpy as np
import pandas as pd

# ==========================================
# 군집별 도메인 분리 정도 계산
# ==========================================

analysis_df = balanced_domain_feature_matrix.copy()

analysis_df["cluster_k2"] = cluster_compare["cluster_k2"].values
analysis_df["cluster_k3"] = cluster_compare["cluster_k3"].values


def domain_centroid_separation(df, cluster_col):

    results = []

    cluster_ids = sorted(
        df[cluster_col].unique()
    )

    for code, domain_name in domain_prefix_map.items():

        cols = [
            col for col in balanced_pc_matrix.columns
            if col.startswith(f"{code}_")
        ]

        centroids = (
            df.groupby(cluster_col)[cols]
            .mean()
        )

        distances = []

        for c1, c2 in combinations(cluster_ids, 2):

            v1 = centroids.loc[c1].values
            v2 = centroids.loc[c2].values

            distance = np.linalg.norm(v1 - v2)

            distances.append(distance)

        results.append({
            "도메인": domain_name,
            "평균_centroid거리": np.mean(distances),
            "최대_centroid거리": np.max(distances)
        })

    return (
        pd.DataFrame(results)
        .sort_values(
            "평균_centroid거리",
            ascending=False
        )
        .reset_index(drop=True)
    )


# ==========================================
# k=2
# ==========================================

k2_domain_sep = domain_centroid_separation(
    analysis_df,
    "cluster_k2"
)

print("=" * 70)
print("k=2 도메인별 군집 분리 정도")
print("=" * 70)

display(
    k2_domain_sep.round(4)
)


# ==========================================
# k=3
# ==========================================

k3_domain_sep = domain_centroid_separation(
    analysis_df,
    "cluster_k3"
)

print("=" * 70)
print("k=3 도메인별 군집 분리 정도")
print("=" * 70)

display(
    k3_domain_sep.round(4)
)

======================================================================
k=2 도메인별 군집 분리 정도
======================================================================

           도메인  평균_centroid거리  최대_centroid거리
0     B_유동인구구조         1.5866         1.5866
1     A_유동활동규모         1.4594         1.4594
2     C_시간요일활동         1.3848         1.3848
3   D_시민생활관심집단         1.2651         1.2651
4       E_이동체류         1.2014         1.2014
5  F_통신생활서비스금융         0.9726         0.9726
6     H_1인가구구조         0.9657         0.9657
7     I_장애관련구조         0.8146         0.8146
8     G_주민인구구조         0.7791         0.7791
9     J_복지경제취약         0.6849         0.6849

======================================================================
k=3 도메인별 군집 분리 정도
======================================================================

           도메인  평균_centroid거리  최대_centroid거리
0     J_복지경제취약         1.7791         2.6686
1     B_유동인구구조         1.4816         2.0440
2     G_주민인구구조         1.3918         1.6924
3     H_1인가구구조         1.2969         1.7165
4     I_장애관련구조         1.2643         1.4928
5  F_통신생활서비스금융         1.2441         1.4964
6     C_시간요일활동         1.2432         1.7473
7     A_유동활동규모         1.1906         1.7859
8   D_시민생활관심집단         1.0877         1.6106
9       E_이동체류         1.0500         1.3559

In [ ]:
# ==========================================
# k=3 Cluster 0이 다른 군집과
# 어떤 도메인에서 구별되는지 확인
# ==========================================

rows = []

for code, domain_name in domain_prefix_map.items():

    cols = [
        col for col in balanced_pc_matrix.columns
        if col.startswith(f"{code}_")
    ]

    centroids = (
        analysis_df
        .groupby("cluster_k3")[cols]
        .mean()
    )

    # Cluster 0 ↔ Cluster 1
    dist_01 = np.linalg.norm(
        centroids.loc[0].values
        - centroids.loc[1].values
    )

    # Cluster 0 ↔ Cluster 2
    dist_02 = np.linalg.norm(
        centroids.loc[0].values
        - centroids.loc[2].values
    )

    # Cluster 1 ↔ Cluster 2
    dist_12 = np.linalg.norm(
        centroids.loc[1].values
        - centroids.loc[2].values
    )

    rows.append({
        "도메인": domain_name,
        "C0_vs_C1": dist_01,
        "C0_vs_C2": dist_02,
        "C1_vs_C2": dist_12,
        "C0_평균거리": (dist_01 + dist_02) / 2
    })


k3_pairwise_domain = (
    pd.DataFrame(rows)
    .sort_values(
        "C0_평균거리",
        ascending=False
    )
    .reset_index(drop=True)
)

print(
    "[k=3 Cluster 0의 도메인별 분리 특성]"
)

display(
    k3_pairwise_domain.round(4)
)

[k=3 Cluster 0의 도메인별 분리 특성]

           도메인  C0_vs_C1  C0_vs_C2  C1_vs_C2  C0_평균거리
0     J_복지경제취약    2.6686    2.4525    0.2161   2.5606
1     G_주민인구구조    1.4068    1.6924    1.0762   1.5496
2     B_유동인구구조    0.9828    2.0440    1.4180   1.5134
3     I_장애관련구조    1.4799    1.4928    0.8201   1.4864
4     H_1인가구구조    1.1992    1.7165    0.9748   1.4579
5     C_시간요일활동    0.8041    1.7473    1.1781   1.2757
6  F_통신생활서비스금융    0.9771    1.4964    1.2589   1.2367
7     A_유동활동규모    0.3819    1.7859    1.4040   1.0839
8   D_시민생활관심집단    0.4160    1.6106    1.2364   1.0133
9       E_이동체류    0.6145    1.1795    1.3559   0.8970

In [ ]:
# ==========================================
# k=3 주요 구조 도메인의 군집별 PC 중심값
# ==========================================

important_domains = [
    "J",
    "G",
    "B",
    "I",
    "H"
]

important_cols = []

for code in important_domains:

    cols = [
        col for col in balanced_pc_matrix.columns
        if col.startswith(f"{code}_")
    ]

    important_cols.extend(cols)


k3_centroid_profile = (
    analysis_df
    .groupby("cluster_k3")[important_cols]
    .mean()
    .T
)

k3_centroid_profile.columns = [
    "Cluster_0",
    "Cluster_1",
    "Cluster_2"
]

# Cluster 0가 나머지 두 군집 평균과 얼마나 다른지도 계산
k3_centroid_profile[
    "C0_minus_C1C2_mean"
] = (
    k3_centroid_profile["Cluster_0"]
    -
    (
        k3_centroid_profile["Cluster_1"]
        + k3_centroid_profile["Cluster_2"]
    ) / 2
)

k3_centroid_profile[
    "abs_difference"
] = (
    k3_centroid_profile[
        "C0_minus_C1C2_mean"
    ].abs()
)

k3_centroid_profile = (
    k3_centroid_profile
    .sort_values(
        "abs_difference",
        ascending=False
    )
)

print(
    "[k=3 Cluster 0 주요 구조적 차이 방향]"
)

display(
    k3_centroid_profile.round(4)
)

[k=3 Cluster 0 주요 구조적 차이 방향]

,Cluster_0,Cluster_1,Cluster_2,C0_minus_C1C2_mean,abs_difference
J_복지경제취약_PC1,2.2360,-0.4327,-0.2165,2.5606,2.5606
G_주민인구구조_PC2,1.2060,-0.0620,-0.4106,1.4423,1.4423
H_1인가구구조_PC1,-0.9657,-0.1622,0.6920,-1.2305,1.2305
I_장애관련구조_PC1,1.0271,-0.0996,-0.2694,1.2116,1.2116
B_유동인구구조_PC1,-0.7910,-0.3972,1.0200,-1.1024,1.1024
B_유동인구구조_PC2,-0.7927,0.1077,0.1551,-0.9242,0.9242
I_장애관련구조_PC3,0.4700,0.0098,-0.2182,0.5742,0.5742
H_1인가구구조_PC3,-0.4917,0.1788,-0.0958,-0.5332,0.5332
I_장애관련구조_PC2,-0.4977,0.3437,-0.3759,-0.4816,0.4816
H_1인가구구조_PC2,0.3847,-0.2011,0.1799,0.3953,0.3953
G_주민인구구조_PC3,0.1529,0.0506,-0.1523,0.2037,0.2037
I_장애관련구조_PC4,0.0619,0.0904,-0.1815,0.1075,0.1075
G_주민인구구조_PC1,0.2013,-0.3994,0.5984,0.1018,0.1018

In [ ]:
from sklearn.cluster import KMeans
from sklearn.metrics import adjusted_rand_score
import pandas as pd
import numpy as np

# ==========================================
# K-Means 초기값 안정성 검증
# ==========================================

stability_results = []

for k in [2, 3]:

    # 기준 군집
    reference_model = KMeans(
        n_clusters=k,
        random_state=42,
        n_init=50
    )

    reference_labels = reference_model.fit_predict(
        X_cluster
    )

    ari_scores = []

    # 여러 random seed에서 반복
    for seed in range(100):

        model = KMeans(
            n_clusters=k,
            random_state=seed,
            n_init=50
        )

        labels = model.fit_predict(
            X_cluster
        )

        ari = adjusted_rand_score(
            reference_labels,
            labels
        )

        ari_scores.append(ari)

    stability_results.append({
        "k": k,
        "ARI_mean": np.mean(ari_scores),
        "ARI_min": np.min(ari_scores),
        "ARI_max": np.max(ari_scores),
        "ARI_std": np.std(ari_scores),
        "ARI_1.0_count": sum(
            np.isclose(ari_scores, 1.0)
        )
    })


stability_df = pd.DataFrame(
    stability_results
)

print(
    "[K-Means 초기화 안정성 검증]"
)

display(
    stability_df.round(4)
)

[K-Means 초기화 안정성 검증]

   k  ARI_mean  ARI_min  ARI_max  ARI_std  ARI_1.0_count
0  2     1.000   1.0000      1.0   0.0000            100
1  3     0.795   0.4495      1.0   0.2468             52

In [ ]:
# ==========================================
# 최종 후보 k=2
# 도메인별 군집 중심 방향 확인
# ==========================================

k2_profile_rows = []

for code, domain_name in domain_prefix_map.items():

    cols = [
        col for col in balanced_pc_matrix.columns
        if col.startswith(f"{code}_")
    ]

    centroids = (
        analysis_df
        .groupby("cluster_k2")[cols]
        .mean()
    )

    for col in cols:

        c0 = centroids.loc[0, col]
        c1 = centroids.loc[1, col]

        k2_profile_rows.append({
            "도메인": domain_name,
            "PC": col,
            "Cluster_0": c0,
            "Cluster_1": c1,
            "C0_minus_C1": c0 - c1,
            "abs_difference": abs(c0 - c1)
        })


k2_profile = (
    pd.DataFrame(k2_profile_rows)
    .sort_values(
        "abs_difference",
        ascending=False
    )
    .reset_index(drop=True)
)

print("[k=2 군집별 PC 중심 차이]")

display(
    k2_profile.round(4)
)

[k=2 군집별 PC 중심 차이]

,도메인,PC,Cluster_0,Cluster_1,C0_minus_C1,abs_difference
0,B_유동인구구조,B_유동인구구조_PC1,0.7888,-0.7888,1.5777,1.5777
1,A_유동활동규모,A_유동활동규모_PC1,0.7297,-0.7297,1.4594,1.4594
2,C_시간요일활동,C_시간요일활동_PC1,0.6803,-0.6803,1.3607,1.3607
3,D_시민생활관심집단,D_시민생활관심집단_PC1,0.5858,-0.5858,1.1716,1.1716
4,E_이동체류,E_이동체류_PC1,-0.5747,0.5747,-1.1493,1.1493
5,H_1인가구구조,H_1인가구구조_PC1,0.4812,-0.4812,0.9623,0.9623
6,F_통신생활서비스금융,F_통신생활서비스금융_PC1,0.3785,-0.3785,0.7570,0.7570
7,I_장애관련구조,I_장애관련구조_PC1,-0.3684,0.3684,-0.7367,0.7367
8,J_복지경제취약,J_복지경제취약_PC1,-0.3424,0.3424,-0.6849,0.6849
9,G_주민인구구조,G_주민인구구조_PC1,0.2678,-0.2678,0.5356,0.5356
10,F_통신생활서비스금융,F_통신생활서비스금융_PC2,0.2542,-0.2542,0.5084,0.5084
11,G_주민인구구조,G_주민인구구조_PC2,-0.2473,0.2473,-0.4947,0.4947
12,D_시민생활관심집단,D_시민생활관심집단_PC2,-0.2387,0.2387,-0.4774,0.4774
13,E_이동체류,E_이동체류_PC2,-0.1751,0.1751,-0.3501,0.3501
14,F_통신생활서비스금융,F_통신생활서비스금융_PC3,0.1692,-0.1692,0.3384,0.3384
15,I_장애관련구조,I_장애관련구조_PC2,-0.1443,0.1443,-0.2885,0.2885
16,G_주민인구구조,G_주민인구구조_PC3,-0.1374,0.1374,-0.2747,0.2747
17,C_시간요일활동,C_시간요일활동_PC2,-0.1285,0.1285,-0.2571,0.2571
18,I_장애관련구조,I_장애관련구조_PC4,-0.0950,0.0950,-0.1900,0.1900
19,B_유동인구구조,B_유동인구구조_PC2,0.0841,-0.0841,0.1681,0.1681
20,H_1인가구구조,H_1인가구구조_PC2,-0.0363,0.0363,-0.0727,0.0727
21,I_장애관련구조,I_장애관련구조_PC3,-0.0190,0.0190,-0.0380,0.0380
22,H_1인가구구조,H_1인가구구조_PC3,-0.0171,0.0171,-0.0343,0.0343

In [ ]:
# ==========================================
# k=2 주요 A~E 도메인
# 원변수 기준 군집 평균 비교
# ==========================================

main_domains = [
    "A_유동활동규모",
    "B_유동인구구조",
    "C_시간요일활동",
    "D_시민생활관심집단",
    "E_이동체류"
]

main_raw_cols = []

for group in main_domains:
    main_raw_cols.extend(
        feature_groups_v4[group]
    )


# V4 원변수 + 최종 k=2 cluster
raw_profile_df = ml_feature_v4[
    ["행정동코드", "행정동명"] + main_raw_cols
].copy()

raw_profile_df["cluster_k2"] = (
    cluster_compare["cluster_k2"].values
)


# ==========================================
# 원변수 표준화
# 단위가 서로 다르므로 군집 차이 비교용
# ==========================================

scaler_raw = StandardScaler()

raw_scaled = pd.DataFrame(
    scaler_raw.fit_transform(
        raw_profile_df[main_raw_cols]
    ),
    columns=main_raw_cols,
    index=raw_profile_df.index
)

raw_scaled["cluster_k2"] = (
    raw_profile_df["cluster_k2"].values
)


# ==========================================
# 군집별 표준화 평균
# ==========================================

cluster_raw_mean = (
    raw_scaled
    .groupby("cluster_k2")
    .mean()
    .T
)

cluster_raw_mean.columns = [
    "Cluster_0",
    "Cluster_1"
]

cluster_raw_mean["C0_minus_C1"] = (
    cluster_raw_mean["Cluster_0"]
    - cluster_raw_mean["Cluster_1"]
)

cluster_raw_mean["abs_difference"] = (
    cluster_raw_mean["C0_minus_C1"].abs()
)


# 도메인 정보 추가
feature_to_domain = {}

for group in main_domains:
    for col in feature_groups_v4[group]:
        feature_to_domain[col] = group

cluster_raw_mean["도메인"] = (
    cluster_raw_mean.index.map(
        feature_to_domain
    )
)


cluster_raw_mean = (
    cluster_raw_mean
    .sort_values(
        "abs_difference",
        ascending=False
    )
)


print(
    "[k=2 A~E 원변수 기준 군집 차이]"
)

display(
    cluster_raw_mean[
        [
            "도메인",
            "Cluster_0",
            "Cluster_1",
            "C0_minus_C1",
            "abs_difference"
        ]
    ].round(3)
)

[k=2 A~E 원변수 기준 군집 차이]

,도메인,Cluster_0,Cluster_1,C0_minus_C1,abs_difference
age_60_plus_ratio_mean,B_유동인구구조,-0.887,0.887,-1.774,1.774
very_low_outing_ratio_mean,D_시민생활관심집단,0.871,-0.871,1.743,1.743
daytime_ratio_mean,C_시간요일활동,0.845,-0.845,1.690,1.690
age_20_ratio_mean,B_유동인구구조,0.828,-0.828,1.657,1.657
age_30_ratio_mean,B_유동인구구조,0.801,-0.801,1.603,1.603
morning_ratio_mean,C_시간요일활동,-0.784,0.784,-1.568,1.568
high_video_ratio_mean,D_시민생활관심집단,0.765,-0.765,1.531,1.531
age_50_ratio_mean,B_유동인구구조,-0.717,0.717,-1.434,1.434
high_worktime_ratio_mean,D_시민생활관심집단,0.716,-0.716,1.432,1.432
peak_hour_ratio_mean,C_시간요일활동,0.704,-0.704,1.408,1.408
flow_per_point_mean,A_유동활동규모,0.696,-0.696,1.392,1.392
very_low_outing_comm_ratio_mean,D_시민생활관심집단,0.693,-0.693,1.385,1.385
평일 총 이동 횟수_mean,E_이동체류,-0.673,0.673,-1.345,1.345
total_flow_mean,A_유동활동규모,0.668,-0.668,1.337,1.337
야간상주지 변경횟수 평균_mean,E_이동체류,-0.619,0.619,-1.239,1.239
age_40_ratio_mean,B_유동인구구조,0.612,-0.612,1.225,1.225
집 추정 위치 평일 총 체류시간_mean,E_이동체류,0.605,-0.605,1.209,1.209
low_weekday_outing_ratio_mean,D_시민생활관심집단,0.587,-0.587,1.173,1.173
휴일 총 이동 횟수 평균_mean,E_이동체류,-0.524,0.524,-1.047,1.047
low_comm_ratio_mean,D_시민생활관심집단,0.516,-0.516,1.031,1.031
male_ratio_mean,B_유동인구구조,0.512,-0.512,1.024,1.024
peak_day_ratio_mean,C_시간요일활동,0.446,-0.446,0.893,0.893
weekend_weekday_index_mean,C_시간요일활동,-0.424,0.424,-0.849,0.849
evening_ratio_mean,C_시간요일활동,-0.418,0.418,-0.836,0.836
high_life_service_ratio_mean,D_시민생활관심집단,0.317,-0.317,0.634,0.634
집 추정 위치 휴일 총 체류시간_mean,E_이동체류,0.284,-0.284,0.568,0.568
평균 근무시간 평균_mean,E_이동체류,-0.276,0.276,-0.553,0.553
financial_interest_ratio_mean,D_시민생활관심집단,0.253,-0.253,0.507,0.507
low_holiday_outing_ratio_mean,D_시민생활관심집단,0.059,-0.059,0.119,0.119

In [ ]:
# ==========================================
# k=2 F~J 원변수 기준 군집 차이
# ==========================================

fj_domains = [
    "F_통신생활서비스금융",
    "G_주민인구구조",
    "H_1인가구구조",
    "I_장애관련구조"
]

fj_raw_cols = []

for group in fj_domains:
    fj_raw_cols.extend(
        feature_groups_v4[group]
    )

# J는 이미 PCA 축으로 압축되어 있으므로 추가
fj_raw_cols.append(
    "welfare_vulnerability_pc1"
)


# ==========================================
# 데이터 구성
# ==========================================

fj_profile_df = ml_feature_v4[
    ["행정동코드", "행정동명"] + fj_raw_cols
].copy()

fj_profile_df["cluster_k2"] = (
    cluster_compare["cluster_k2"].values
)


# ==========================================
# 비교를 위한 표준화
# ==========================================

scaler_fj = StandardScaler()

fj_scaled = pd.DataFrame(
    scaler_fj.fit_transform(
        fj_profile_df[fj_raw_cols]
    ),
    columns=fj_raw_cols,
    index=fj_profile_df.index
)

fj_scaled["cluster_k2"] = (
    fj_profile_df["cluster_k2"].values
)


# ==========================================
# 군집 평균
# ==========================================

fj_cluster_mean = (
    fj_scaled
    .groupby("cluster_k2")
    .mean()
    .T
)

fj_cluster_mean.columns = [
    "Cluster_0",
    "Cluster_1"
]

fj_cluster_mean["C0_minus_C1"] = (
    fj_cluster_mean["Cluster_0"]
    - fj_cluster_mean["Cluster_1"]
)

fj_cluster_mean["abs_difference"] = (
    fj_cluster_mean[
        "C0_minus_C1"
    ].abs()
)


# ==========================================
# 도메인 표시
# ==========================================

feature_to_domain_fj = {}

for group in fj_domains:
    for col in feature_groups_v4[group]:
        feature_to_domain_fj[col] = group

feature_to_domain_fj[
    "welfare_vulnerability_pc1"
] = "J_복지경제취약"

fj_cluster_mean["도메인"] = (
    fj_cluster_mean.index.map(
        feature_to_domain_fj
    )
)

fj_cluster_mean = (
    fj_cluster_mean
    .sort_values(
        "abs_difference",
        ascending=False
    )
)


print(
    "[k=2 F~J 원변수 기준 군집 차이]"
)

display(
    fj_cluster_mean[
        [
            "도메인",
            "Cluster_0",
            "Cluster_1",
            "C0_minus_C1",
            "abs_difference"
        ]
    ].round(3)
)

[k=2 F~J 원변수 기준 군집 차이]

,도메인,Cluster_0,Cluster_1,C0_minus_C1,abs_difference
single_age_30_gap,H_1인가구구조,0.659,-0.659,1.318,1.318
평균 통화대상자 수_mean,F_통신생활서비스금융,0.648,-0.648,1.296,1.296
foreigner_ratio_mean,G_주민인구구조,0.630,-0.630,1.260,1.260
배달 서비스 사용일수_mean,F_통신생활서비스금융,0.622,-0.622,1.245,1.245
intellectual_ratio,I_장애관련구조,-0.611,0.611,-1.222,1.222
최근 3개월 내 요금 연체 비율_mean,F_통신생활서비스금융,0.603,-0.603,1.206,1.206
single_age_20_gap,H_1인가구구조,0.597,-0.597,1.194,1.194
resident_age_20_ratio,G_주민인구구조,0.597,-0.597,1.194,1.194
데이터 사용량_mean,F_통신생활서비스금융,0.495,-0.495,0.991,0.991
카카오톡_비사용비율_mean,F_통신생활서비스금융,0.438,-0.438,0.876,0.876
physical_ratio,I_장애관련구조,0.436,-0.436,0.871,0.871
disabled_total,I_장애관련구조,-0.435,0.435,-0.870,0.870
visual_ratio,I_장애관련구조,0.430,-0.430,0.860,0.860
mental_ratio,I_장애관련구조,-0.419,0.419,-0.838,0.838
official_single_household_mean,H_1인가구구조,0.407,-0.407,0.813,0.813
disabled_per_1000,I_장애관련구조,-0.384,0.384,-0.768,0.768
resident_age_60_plus_ratio,G_주민인구구조,-0.369,0.369,-0.738,0.738
single_age_40_gap,H_1인가구구조,0.365,-0.365,0.730,0.730
autism_ratio,I_장애관련구조,-0.361,0.361,-0.723,0.723
single_age_50_gap,H_1인가구구조,-0.353,0.353,-0.705,0.705
welfare_vulnerability_pc1,J_복지경제취약,-0.342,0.342,-0.685,0.685
resident_age_30_ratio,G_주민인구구조,0.333,-0.333,0.666,0.666
single_gender_1_ratio,H_1인가구구조,0.293,-0.293,0.586,0.586
disabled_male_ratio,I_장애관련구조,0.263,-0.263,0.527,0.527
hearing_ratio,I_장애관련구조,0.237,-0.237,0.473,0.473
kidney_ratio,I_장애관련구조,0.212,-0.212,0.423,0.423
resident_age_50_ratio,G_주민인구구조,0.168,-0.168,0.336,0.336
brain_lesion_ratio,I_장애관련구조,0.161,-0.161,0.322,0.322
official_single_household_change_rate,H_1인가구구조,-0.112,0.112,-0.225,0.225
resident_age_40_ratio,G_주민인구구조,0.059,-0.059,0.117,0.117
쇼핑 서비스 사용일수_mean,F_통신생활서비스금융,-0.012,0.012,-0.023,0.023
금융 서비스 사용일수_mean,F_통신생활서비스금융,0.006,-0.006,0.011,0.011
resident_total_mean,G_주민인구구조,-0.005,0.005,-0.010,0.010

In [ ]:
# ==========================================
# DB1 최종 k=2 군집 결과 테이블 생성
# ==========================================

# 군집 해석용 대표 원변수
representative_features = [

    # A. 유동활동 규모
    "total_flow_mean",
    "flow_per_point_mean",

    # B. 유동인구 연령구조
    "age_20_ratio_mean",
    "age_30_ratio_mean",
    "age_50_ratio_mean",
    "age_60_plus_ratio_mean",

    # C. 시간대 활동
    "daytime_ratio_mean",
    "morning_ratio_mean",

    # D. 시민생활 관심집단
    "very_low_outing_ratio_mean",
    "very_low_outing_comm_ratio_mean",
    "low_comm_ratio_mean",

    # E. 이동·체류
    "평일 총 이동 횟수_mean",
    "집 추정 위치 평일 총 체류시간_mean",

    # F. 통신·생활서비스
    "평균 통화대상자 수_mean",
    "배달 서비스 사용일수_mean",

    # G. 주민 인구구조
    "foreigner_ratio_mean",
    "resident_age_20_ratio",
    "resident_age_60_plus_ratio",

    # H. 1인가구 구조
    "single_age_20_gap",
    "single_age_30_gap",

    # I. 장애 관련 구조
    "disabled_per_1000",

    # J. 복지·경제 구조
    "welfare_vulnerability_pc1"
]


# ==========================================
# 행정동 + 최종 군집 + 대표 변수
# ==========================================

final_cluster_result = ml_feature_v4[
    ["행정동코드", "행정동명"] + representative_features
].copy()

final_cluster_result["cluster_k2"] = (
    cluster_compare["cluster_k2"].values
)


# 보기 편하도록 cluster를 앞쪽으로 이동
column_order = [
    "행정동코드",
    "행정동명",
    "cluster_k2"
] + representative_features

final_cluster_result = (
    final_cluster_result[column_order]
    .sort_values(
        ["cluster_k2", "행정동명"]
    )
    .reset_index(drop=True)
)


# ==========================================
# 기본 검증
# ==========================================

print("[DB1 최종 k=2 군집 결과]")
print("shape :", final_cluster_result.shape)
print("행정동 수 :", final_cluster_result["행정동코드"].nunique())
print("중복 key :", final_cluster_result["행정동코드"].duplicated().sum())
print("결측치 :", final_cluster_result.isna().sum().sum())

print("\n[군집별 행정동 수]")
print(
    final_cluster_result[
        "cluster_k2"
    ].value_counts().sort_index()
)

print("\n[군집별 행정동]")
for cluster in sorted(
    final_cluster_result["cluster_k2"].unique()
):
    dongs = final_cluster_result.loc[
        final_cluster_result["cluster_k2"] == cluster,
        "행정동명"
    ].tolist()

    print(
        f"Cluster {cluster} ({len(dongs)}개): "
        + ", ".join(dongs)
    )


display(
    final_cluster_result
)

[DB1 최종 k=2 군집 결과]
shape : (22, 25)
행정동 수 : 22
중복 key : 0
결측치 : 0

[군집별 행정동 수]
cluster_k2
0    11
1    11
Name: count, dtype: int64

[군집별 행정동]
Cluster 0 (11개): 논현1동, 논현2동, 대치2동, 대치4동, 삼성1동, 삼성2동, 신사동, 압구정동, 역삼1동, 역삼2동, 청담동
Cluster 1 (11개): 개포1동, 개포2동, 개포3동, 개포4동, 대치1동, 도곡1동, 도곡2동, 세곡동, 수서동, 일원1동, 일원본동

,행정동코드,행정동명,cluster_k2,total_flow_mean,flow_per_point_mean,age_20_ratio_mean,age_30_ratio_mean,age_50_ratio_mean,age_60_plus_ratio_mean,daytime_ratio_mean,...,집 추정 위치 평일 총 체류시간_mean,평균 통화대상자 수_mean,배달 서비스 사용일수_mean,foreigner_ratio_mean,resident_age_20_ratio,resident_age_60_plus_ratio,single_age_20_gap,single_age_30_gap,disabled_per_1000,welfare_vulnerability_pc1
0,1123052,논현1동,0,3.446181e+05,696.198209,0.196942,0.234957,0.156841,0.161290,0.556443,...,741194.162129,13.908236,15.589859,0.039261,0.177929,0.207635,0.061908,0.082458,25.399921,0.108801
1,1123053,논현2동,0,4.039719e+05,698.913250,0.178522,0.231816,0.162009,0.167636,0.573830,...,772140.799248,14.559950,13.790640,0.019236,0.149945,0.229827,0.043139,0.121755,22.039642,-0.475732
2,1123079,대치2동,0,4.680830e+05,578.477477,0.130412,0.165530,0.173163,0.175425,0.568516,...,742797.397458,13.730482,11.503909,0.005189,0.099179,0.224144,0.036386,0.118626,15.374859,-1.538844
3,1123063,대치4동,0,3.498678e+05,1249.527774,0.129563,0.153679,0.172822,0.154212,0.568435,...,770012.422652,14.072894,13.736608,0.018446,0.157383,0.178707,0.005511,0.145572,19.391182,-0.143657
4,1123058,삼성1동,0,5.948723e+05,809.740536,0.170581,0.221924,0.170481,0.151670,0.622242,...,723835.401832,14.232888,11.455841,0.024469,0.124413,0.292092,-0.023253,0.077436,21.708281,-1.321390
5,1123059,삼성2동,0,3.547587e+05,705.285593,0.157192,0.211135,0.171410,0.171061,0.568812,...,772810.516814,14.121990,12.986152,0.010410,0.131546,0.198011,0.040319,0.138350,19.152830,-0.872530
6,1123051,신사동,0,4.241825e+05,607.269840,0.167233,0.198218,0.172209,0.193282,0.562115,...,728659.028810,13.609471,12.117335,0.013815,0.124995,0.288110,0.056955,0.121174,23.254295,-0.864145
7,1123077,압구정동,0,4.331283e+05,484.039463,0.166044,0.207442,0.168842,0.190738,0.576178,...,759201.320678,14.063492,11.193329,0.008376,0.110689,0.302293,-0.040508,0.015976,18.816105,-1.601086
8,1123064,역삼1동,0,1.224900e+06,1293.453156,0.207645,0.239373,0.154095,0.141759,0.576340,...,734976.137472,14.298480,15.805218,0.040072,0.194495,0.164408,0.022038,0.090726,20.526338,-0.003555
9,1123065,역삼2동,0,3.534588e+05,790.735492,0.142125,0.191634,0.175727,0.163632,0.563153,...,748683.626308,13.894082,13.618525,0.010360,0.126541,0.158126,0.077350,0.160998,18.061722,-0.922840
10,1123078,청담동,0,4.458611e+05,500.496460,0.153999,0.203549,0.177624,0.196207,0.557460,...,734712.794494,14.807509,12.394684,0.010221,0.127409,0.258235,0.007807,0.101868,21.098068,-1.388369
11,1123068,개포1동,1,8.043459e+04,126.025170,0.080906,0.123429,0.194586,0.261246,0.499427,...,701149.615499,14.036782,10.899747,0.002131,0.097471,0.254340,-0.012258,0.072449,19.551767,-1.357620
12,1123080,개포2동,1,2.257795e+05,356.119132,0.105102,0.127489,0.178920,0.255185,0.504530,...,708533.034733,13.022721,10.913003,0.003896,0.109873,0.221395,-0.064308,-0.006220,18.023139,-1.360161
13,1123074,개포3동,1,1.334290e+05,318.576966,0.105504,0.148431,0.182295,0.266654,0.508072,...,740024.198960,12.314647,11.346192,0.004667,0.092309,0.308731,-0.051338,-0.043107,68.550738,3.362253
14,1123071,개포4동,1,1.196803e+05,196.302898,0.105324,0.152602,0.195372,0.245508,0.524392,...,683678.771998,13.709344,11.700670,0.008009,0.121880,0.263441,-0.027017,0.065479,26.250459,0.074333
15,1123060,대치1동,1,2.280446e+05,708.213012,0.102701,0.101422,0.174515,0.203788,0.536543,...,723247.840325,14.200107,11.412779,0.001742,0.095491,0.180638,-0.016248,0.073888,12.718801,-1.474953
16,1123066,도곡1동,1,1.413241e+05,348.948350,0.139825,0.179653,0.176572,0.214788,0.550206,...,692421.407376,13.205669,12.011416,0.006310,0.121293,0.243456,0.031393,0.114971,16.986972,-1.493888
17,1123067,도곡2동,1,2.533768e+05,617.992240,0.107458,0.134483,0.187022,0.250251,0.537216,...,747952.315015,13.724331,11.333530,0.003273,0.108803,0.254974,-0.070110,0.009813,16.317920,-1.634532
18,1123076,세곡동,1,1.926526e+05,85.219930,0.097641,0.153545,0.175227,0.247617,0.509364,...,749736.712404,13.239290,11.626922,0.004291,0.120142,0.253984,0.013152,0.065581,43.019841,1.632379
19,1123075,수서동,1,2.425010e+05,388.739985,0.119782,0.166395,0.180065,0.293316,0.514934,...,700846.431456,11.476933,10.914513,0.005846,0.074823,0.505110,-0.038244,-0.065192,146.192595,8.289593
20,1123073,일원1동,1,9.888807e+04,264.406591,0.105210,0.143768,0.184799,0.288962,0.515539,...,733263.355290,12.440205,11.740834,0.010624,0.124871,0.357176,0.013191,-0.000259,76.510397,4.416528
21,1123072,일원본동,1,1.957077e+05,228.425693,0.099801,0.135234,0.185956,0.274679,0.530100,...,722652.236812,12.620623,11.108006,0.001003,0.097017,0.253072,-0.029788,-0.045125,30.671154,-1.430586

In [ ]:
# ==========================================
# 1. 행정동별 최종 군집 결과 저장
# ==========================================

cluster_output_file = (
    "gangnam_db1_final_k2_cluster_result_2025.csv"
)

final_cluster_result.to_csv(
    cluster_output_file,
    index=False,
    encoding="utf-8-sig"
)


# ==========================================
# 2. 군집별 대표변수 프로파일 생성
# ==========================================

cluster_profile = (
    final_cluster_result
    .groupby("cluster_k2")[representative_features]
    .mean()
    .reset_index()
)

profile_output_file = (
    "gangnam_db1_final_k2_cluster_profile_2025.csv"
)

cluster_profile.to_csv(
    profile_output_file,
    index=False,
    encoding="utf-8-sig"
)


# ==========================================
# 검증
# ==========================================

print("[저장 완료]")
print(cluster_output_file, final_cluster_result.shape)
print(profile_output_file, cluster_profile.shape)

display(cluster_profile)

[저장 완료]
gangnam_db1_final_k2_cluster_result_2025.csv (22, 25)
gangnam_db1_final_k2_cluster_profile_2025.csv (2, 23)

,cluster_k2,total_flow_mean,flow_per_point_mean,age_20_ratio_mean,age_30_ratio_mean,age_50_ratio_mean,age_60_plus_ratio_mean,daytime_ratio_mean,morning_ratio_mean,very_low_outing_ratio_mean,...,집 추정 위치 평일 총 체류시간_mean,평균 통화대상자 수_mean,배달 서비스 사용일수_mean,foreigner_ratio_mean,resident_age_20_ratio,resident_age_60_plus_ratio,single_age_20_gap,single_age_30_gap,disabled_per_1000,welfare_vulnerability_pc1
0,0,490700.231970,764.921568,0.163660,0.205387,0.168657,0.169719,0.572138,0.202926,2.592948,...,748093.055263,14.118134,13.108373,0.018169,0.138593,0.227417,0.026150,0.106813,20.438477,-0.820304
1,1,173801.659848,330.815452,0.106296,0.142405,0.183212,0.254727,0.520939,0.235762,1.472985,...,718500.538170,13.090059,11.364328,0.004708,0.105816,0.281483,-0.022871,0.022025,43.163071,0.820304

In [ ]:
from google.colab import files

files.download(
    "gangnam_db1_final_k2_cluster_result_2025.csv"
)

files.download(
    "gangnam_db1_final_k2_cluster_profile_2025.csv"
)