In [1]:
import pandas as pd
import numpy as np
from google.colab import files

uploaded = files.upload()

Saving 장애인 현황(장애유형별, 동별).csv to 장애인 현황(장애유형별, 동별).csv

In [5]:
disabled_raw = pd.read_csv(
    filename,
    encoding="utf-8-sig",
    sep=",",
    engine="python",
    on_bad_lines="skip"
)

print("크기:", disabled_raw.shape)

print("\n컬럼:")
print(disabled_raw.columns.tolist())

print("\n상위 5행:")
display(disabled_raw.head())

print("\n하위 5행:")
display(disabled_raw.tail())

print("\n동별 고유값 개수:")
print(disabled_raw["동별"].nunique())

print("\n동별 고유값 앞부분:")
print(disabled_raw["동별"].unique()[:50])

크기: (22943, 7)

컬럼:
['동별', '장애유형별', '성별', '항목', '단위', '2025 년', 'Unnamed: 6']

상위 5행:

   동별 장애유형별  성별                항목  단위  2025 년  Unnamed: 6
0  합계    합계   계  장애인 현황(장애유형별/동별) NaN  384934         NaN
1  합계    합계  남자  장애인 현황(장애유형별/동별) NaN  222453         NaN
2  합계    합계  여자  장애인 현황(장애유형별/동별) NaN  162481         NaN
3  합계    지체   계  장애인 현황(장애유형별/동별) NaN  152586         NaN
4  합계    지체  남자  장애인 현황(장애유형별/동별) NaN   85830         NaN

하위 5행:

       동별 장애유형별  성별                항목  단위 2025 년  Unnamed: 6
22938  기타  장루요루   계  장애인 현황(장애유형별/동별) NaN      -         NaN
22939  기타  장루요루  남자  장애인 현황(장애유형별/동별) NaN      -         NaN
22940  기타  장루요루  여자  장애인 현황(장애유형별/동별) NaN      -         NaN
22941  기타   뇌전증   계  장애인 현황(장애유형별/동별) NaN      -         NaN
22942  기타   뇌전증  남자  장애인 현황(장애유형별/동별) NaN      -         NaN

동별 고유값 개수:
453

동별 고유값 앞부분:
['합계' '종로구' '청운효자동' '사직동' '삼청동' '부암동' '평창동' '무악동' '교남동' '가회동'
 '종로1.2.3.4가동' '종로5.6가동' '이화동' '혜화동' '창신1동' '창신2동' '창신3동' '숭인1동' '숭인2동'
 '기타' '중구' '소공동' '회현동' '명동' '필동' '장충동' '광희동' '을지로동' '신당동' '다산동' '약수동'
 '청구동' '신당5동' '동화동' '황학동' '중림동' '용산구' '후암동' '용산2가동' '남영동' '청파동' '원효로1동'
 '원효로2동' '효창동' '용문동' '한강로동' '이촌1동' '이촌2동' '이태원1동' '이태원2동']

In [6]:
# '강남구'가 등장하는 위치 확인
gangnam_idx = disabled_raw.index[
    disabled_raw["동별"] == "강남구"
].tolist()

print("강남구 위치:", gangnam_idx)

# 강남구 전후의 동별 값 확인
if gangnam_idx:
    idx = gangnam_idx[0]

    display(
        disabled_raw.loc[
            idx - 3 : idx + 30,
            ["동별", "장애유형별", "성별", "2025 년"]
        ]
    )

강남구 위치: [19392, 19393, 19394, 19395, 19396, 19397, 19398, 19399, 19400, 19401, 19402, 19403, 19404, 19405, 19406, 19407, 19408, 19409, 19410, 19411, 19412, 19413, 19414, 19415, 19416, 19417, 19418, 19419, 19420, 19421, 19422, 19423, 19424, 19425, 19426, 19427, 19428, 19429, 19430, 19431, 19432, 19433, 19434, 19435, 19436, 19437, 19438, 19439]

        동별 장애유형별  성별 2025 년
19389   기타   뇌전증   계      -
19390   기타   뇌전증  남자      -
19391   기타   뇌전증  여자      -
19392  강남구    합계   계  15517
19393  강남구    합계  남자   9071
19394  강남구    합계  여자   6446
19395  강남구    지체   계   5645
19396  강남구    지체  남자   3263
19397  강남구    지체  여자   2382
19398  강남구   뇌병변   계   1666
19399  강남구   뇌병변  남자    978
19400  강남구   뇌병변  여자    688
19401  강남구    시각   계   1577
19402  강남구    시각  남자    936
19403  강남구    시각  여자    641
19404  강남구    청각   계   2430
19405  강남구    청각  남자   1279
19406  강남구    청각  여자   1151
19407  강남구    언어   계    124
19408  강남구    언어  남자     85
19409  강남구    언어  여자     39
19410  강남구  지적장애   계   1054
19411  강남구  지적장애  남자    602
19412  강남구  지적장애  여자    452
19413  강남구   자폐성   계    835
19414  강남구   자폐성  남자    688
19415  강남구   자폐성  여자    147
19416  강남구  정신장애   계    819
19417  강남구  정신장애  남자    367
19418  강남구  정신장애  여자    452
19419  강남구  신장장애   계    907
19420  강남구  신장장애  남자    568
19421  강남구  신장장애  여자    339
19422  강남구  심장장애   계     38

In [7]:
# 강남구 이후 등장하는 지역명의 순서를 중복 제거하여 확인
idx = gangnam_idx[0]

region_order = (
    disabled_raw.loc[idx:, "동별"]
    .drop_duplicates()
    .head(35)
    .tolist()
)

print(region_order)

['강남구', '신사동', '논현1동', '논현2동', '압구정동', '청담동', '삼성1동', '삼성2동', '대치1동', '대치2동', '대치4동', '역삼1동', '역삼2동', '도곡1동', '도곡2동', '개포1동', '개포2동', '개포3동', '개포4동', '세곡동', '일원본동', '일원1동', '수서동', '기타', '송파구', '풍납1동', '풍납2동', '거여1동', '거여2동', '마천1동', '마천2동', '방이1동', '방이2동', '오륜동', '오금동']

In [8]:
gangnam_dongs = [
    "신사동", "논현1동", "논현2동", "압구정동", "청담동",
    "삼성1동", "삼성2동", "대치1동", "대치2동", "대치4동",
    "역삼1동", "역삼2동", "도곡1동", "도곡2동",
    "개포1동", "개포2동", "개포3동", "개포4동",
    "세곡동", "일원본동", "일원1동", "수서동"
]

gangnam_disabled = disabled_raw[
    disabled_raw["동별"].isin(gangnam_dongs)
][
    ["동별", "장애유형별", "성별", "2025 년"]
].copy()

gangnam_disabled = gangnam_disabled.rename(
    columns={
        "동별": "dong_name",
        "장애유형별": "disability_type",
        "성별": "sex",
        "2025 년": "disabled_count"
    }
)

print("크기:", gangnam_disabled.shape)
print("행정동 수:", gangnam_disabled["dong_name"].nunique())

print("\n장애유형:")
print(gangnam_disabled["disability_type"].unique())

print("\n성별:")
print(gangnam_disabled["sex"].unique())

print("\n행정동별 행 개수:")
print(gangnam_disabled.groupby("dong_name").size())

print("\n'-' 개수:")
print((gangnam_disabled["disabled_count"] == "-").sum())

print("\n중복 조합 개수:")
print(
    gangnam_disabled.duplicated(
        ["dong_name", "disability_type", "sex"]
    ).sum()
)

크기: (1104, 4)
행정동 수: 22

장애유형:
['합계' '지체' '뇌병변' '시각' '청각' '언어' '지적장애' '자폐성' '정신장애' '신장장애' '심장장애' '호흡기'
 '간' '안면' '장루요루' '뇌전증']

성별:
['계' '남자' '여자']

행정동별 행 개수:
dong_name
개포1동    48
개포2동    48
개포3동    48
개포4동    48
논현1동    48
논현2동    48
대치1동    48
대치2동    48
대치4동    48
도곡1동    48
도곡2동    48
삼성1동    48
삼성2동    48
세곡동     48
수서동     48
신사동     96
압구정동    48
역삼1동    48
역삼2동    48
일원1동    48
일원본동    48
청담동     48
dtype: int64

'-' 개수:
124

중복 조합 개수:
48

In [9]:
sinsa_indices = disabled_raw.index[
    disabled_raw["동별"] == "신사동"
].tolist()

print("신사동 시작 위치들:")
print(sinsa_indices)

print("\n신사동 행 개수:")
print(len(sinsa_indices))

신사동 시작 위치들:
[18000, 18001, 18002, 18003, 18004, 18005, 18006, 18007, 18008, 18009, 18010, 18011, 18012, 18013, 18014, 18015, 18016, 18017, 18018, 18019, 18020, 18021, 18022, 18023, 18024, 18025, 18026, 18027, 18028, 18029, 18030, 18031, 18032, 18033, 18034, 18035, 18036, 18037, 18038, 18039, 18040, 18041, 18042, 18043, 18044, 18045, 18046, 18047, 19440, 19441, 19442, 19443, 19444, 19445, 19446, 19447, 19448, 19449, 19450, 19451, 19452, 19453, 19454, 19455, 19456, 19457, 19458, 19459, 19460, 19461, 19462, 19463, 19464, 19465, 19466, 19467, 19468, 19469, 19470, 19471, 19472, 19473, 19474, 19475, 19476, 19477, 19478, 19479, 19480, 19481, 19482, 19483, 19484, 19485, 19486, 19487]

신사동 행 개수:
96

In [10]:
for idx in sinsa_indices[::48]:
    print("\n====================")
    print("index:", idx)

    display(
        disabled_raw.loc[
            max(0, idx - 3): idx + 3,
            ["동별", "장애유형별", "성별", "2025 년"]
        ]
    )

====================
index: 18000

        동별 장애유형별  성별 2025 년
17997  서림동   뇌전증   계      4
17998  서림동   뇌전증  남자      1
17999  서림동   뇌전증  여자      3
18000  신사동    합계   계    941
18001  신사동    합계  남자    563
18002  신사동    합계  여자    378
18003  신사동    지체   계    355

====================
index: 19440

        동별 장애유형별  성별 2025 년
19437  강남구   뇌전증   계     57
19438  강남구   뇌전증  남자     29
19439  강남구   뇌전증  여자     28
19440  신사동    합계   계    356
19441  신사동    합계  남자    212
19442  신사동    합계  여자    144
19443  신사동    지체   계    141

In [11]:
# 강남구와 다음 자치구인 송파구 시작 위치
gangnam_start = disabled_raw.index[
    disabled_raw["동별"] == "강남구"
][0]

songpa_start = disabled_raw.index[
    disabled_raw["동별"] == "송파구"
][0]

print("강남구 시작:", gangnam_start)
print("송파구 시작:", songpa_start)

# 강남구 구간 전체 추출
gangnam_block = disabled_raw.loc[
    gangnam_start : songpa_start - 1
].copy()

print("강남구 구간 크기:", gangnam_block.shape)

print("\n지역 순서:")
print(gangnam_block["동별"].drop_duplicates().tolist())

강남구 시작: 19392
송파구 시작: 20544
강남구 구간 크기: (1152, 7)

지역 순서:
['강남구', '신사동', '논현1동', '논현2동', '압구정동', '청담동', '삼성1동', '삼성2동', '대치1동', '대치2동', '대치4동', '역삼1동', '역삼2동', '도곡1동', '도곡2동', '개포1동', '개포2동', '개포3동', '개포4동', '세곡동', '일원본동', '일원1동', '수서동', '기타']

In [12]:
gangnam_disabled = gangnam_block[
    ~gangnam_block["동별"].isin(["강남구", "기타"])
][
    ["동별", "장애유형별", "성별", "2025 년"]
].copy()

gangnam_disabled = gangnam_disabled.rename(
    columns={
        "동별": "dong_name",
        "장애유형별": "disability_type",
        "성별": "sex",
        "2025 년": "disabled_count"
    }
)

print("크기:", gangnam_disabled.shape)
print("행정동 수:", gangnam_disabled["dong_name"].nunique())

print("\n행정동별 행 개수:")
print(gangnam_disabled.groupby("dong_name").size())

print("\n중복 조합:")
print(
    gangnam_disabled.duplicated(
        ["dong_name", "disability_type", "sex"]
    ).sum()
)

print("\n'-' 개수:")
print((gangnam_disabled["disabled_count"] == "-").sum())

크기: (1056, 4)
행정동 수: 22

행정동별 행 개수:
dong_name
개포1동    48
개포2동    48
개포3동    48
개포4동    48
논현1동    48
논현2동    48
대치1동    48
대치2동    48
대치4동    48
도곡1동    48
도곡2동    48
삼성1동    48
삼성2동    48
세곡동     48
수서동     48
신사동     48
압구정동    48
역삼1동    48
역삼2동    48
일원1동    48
일원본동    48
청담동     48
dtype: int64

중복 조합:
0

'-' 개수:
118

In [13]:
# '-' 분포 확인
dash_rows = gangnam_disabled[
    gangnam_disabled["disabled_count"] == "-"
].copy()

print("장애유형별 '-' 개수:")
print(
    dash_rows.groupby("disability_type")
    .size()
    .sort_values(ascending=False)
)

print("\n성별 '-' 개수:")
print(
    dash_rows.groupby("sex")
    .size()
)

print("\n행정동별 '-' 개수:")
print(
    dash_rows.groupby("dong_name")
    .size()
    .sort_values(ascending=False)
)

장애유형별 '-' 개수:
disability_type
안면      36
심장장애    29
뇌전증     23
호흡기     15
간        6
언어       5
장루요루     4
dtype: int64

성별 '-' 개수:
sex
계     21
남자    36
여자    61
dtype: int64

행정동별 '-' 개수:
dong_name
도곡1동    12
삼성1동    11
논현2동    10
대치1동     9
청담동      8
신사동      7
도곡2동     7
역삼2동     7
일원본동     6
대치4동     6
압구정동     6
개포1동     5
삼성2동     5
개포2동     4
대치2동     3
개포4동     3
논현1동     3
일원1동     2
역삼1동     2
개포3동     1
세곡동      1
dtype: int64

In [14]:
# 강남구 구간에서 '합계 장애유형 × 계'만 추출
total_check = gangnam_block[
    (gangnam_block["장애유형별"] == "합계") &
    (gangnam_block["성별"] == "계")
][["동별", "2025 년"]].copy()

total_check["2025 년"] = pd.to_numeric(
    total_check["2025 년"],
    errors="coerce"
)

display(total_check)

# 강남구 전체
gangnam_total = total_check.loc[
    total_check["동별"] == "강남구",
    "2025 년"
].iloc[0]

# 22개 행정동 합
dong_total = total_check.loc[
    total_check["동별"].isin(gangnam_dongs),
    "2025 년"
].sum()

# 기타
etc_total = total_check.loc[
    total_check["동별"] == "기타",
    "2025 년"
].iloc[0]

print("강남구 전체:", gangnam_total)
print("22개 행정동 합:", dong_total)
print("기타:", etc_total)
print("22개 동 + 기타:", dong_total + etc_total)
print("강남구 전체와의 차이:", gangnam_total - (dong_total + etc_total))

         동별   2025 년
19392   강남구  15517.0
19440   신사동    356.0
19488  논현1동    547.0
19536  논현2동    452.0
19584  압구정동    483.0
19632   청담동    523.0
19680  삼성1동    283.0
19728  삼성2동    586.0
19776  대치1동    303.0
19824  대치2동    594.0
19872  대치4동    358.0
19920  역삼1동    732.0
19968  역삼2동    659.0
20016  도곡1동    354.0
20064  도곡2동    526.0
20112  개포1동    523.0
20160  개포2동    761.0
20208  개포3동   1117.0
20256  개포4동    608.0
20304   세곡동   1985.0
20352  일원본동    688.0
20400  일원1동   1091.0
20448   수서동   1988.0
20496    기타      NaN

강남구 전체: 15517.0
22개 행정동 합: 15517.0
기타: nan
22개 동 + 기타: nan
강남구 전체와의 차이: nan

In [15]:
# 분석용 복사본
dash_check = gangnam_disabled.copy()

# '-'는 우선 NaN으로 변환
dash_check["count_num"] = pd.to_numeric(
    dash_check["disabled_count"],
    errors="coerce"
)

# 행정동 × 장애유형별 성별 pivot
sex_check = dash_check.pivot(
    index=["dong_name", "disability_type"],
    columns="sex",
    values="count_num"
).reset_index()

display(sex_check.head(20))

# 계 / 남자 / 여자 중 결측이 있는 조합
missing_sex = sex_check[
    sex_check[["계", "남자", "여자"]].isna().any(axis=1)
].copy()

print("결측이 포함된 조합 수:", len(missing_sex))

display(missing_sex)

sex dong_name disability_type      계     남자     여자
0        개포1동               간    5.0    3.0    2.0
1        개포1동             뇌병변   57.0   33.0   24.0
2        개포1동             뇌전증    3.0    3.0    NaN
3        개포1동              시각   50.0   35.0   15.0
4        개포1동            신장장애   41.0   33.0    8.0
5        개포1동            심장장애    NaN    NaN    NaN
6        개포1동              안면    2.0    2.0    NaN
7        개포1동              언어    4.0    2.0    2.0
8        개포1동             자폐성   40.0   33.0    7.0
9        개포1동            장루요루    7.0    5.0    2.0
10       개포1동            정신장애   14.0    9.0    5.0
11       개포1동            지적장애   28.0   11.0   17.0
12       개포1동              지체  190.0  122.0   68.0
13       개포1동              청각   78.0   43.0   35.0
14       개포1동              합계  523.0  337.0  186.0
15       개포1동             호흡기    4.0    3.0    1.0
16       개포2동               간   13.0   11.0    2.0
17       개포2동             뇌병변   67.0   40.0   27.0
18       개포2동             뇌전증    NaN    NaN    NaN
19       개포2동              시각   92.0   61.0   31.0

결측이 포함된 조합 수: 76

sex dong_name disability_type    계   남자   여자
2        개포1동             뇌전증  3.0  3.0  NaN
5        개포1동            심장장애  NaN  NaN  NaN
6        개포1동              안면  2.0  2.0  NaN
18       개포2동             뇌전증  NaN  NaN  NaN
21       개포2동            심장장애  2.0  2.0  NaN
..        ...             ...  ...  ...  ...
335      일원본동             호흡기  2.0  NaN  2.0
338       청담동             뇌전증  NaN  NaN  NaN
341       청담동            심장장애  2.0  2.0  NaN
342       청담동              안면  NaN  NaN  NaN
343       청담동              언어  3.0  3.0  NaN

[76 rows x 5 columns]

In [16]:
sex_zero_test = sex_check.copy()

sex_zero_test[["계", "남자", "여자"]] = (
    sex_zero_test[["계", "남자", "여자"]]
    .fillna(0)
)

sex_zero_test["difference"] = (
    sex_zero_test["계"]
    - sex_zero_test["남자"]
    - sex_zero_test["여자"]
)

print("전체 조합 수:", len(sex_zero_test))

print(
    "'-'를 0으로 가정했을 때 불일치 조합:",
    (sex_zero_test["difference"] != 0).sum()
)

print("\n차이값 분포:")
print(
    sex_zero_test["difference"]
    .value_counts()
    .sort_index()
)

display(
    sex_zero_test[
        sex_zero_test["difference"] != 0
    ]
)

전체 조합 수: 352
'-'를 0으로 가정했을 때 불일치 조합: 0

차이값 분포:
difference
0.0    352
Name: count, dtype: int64

Empty DataFrame
Columns: [dong_name, disability_type, 계, 남자, 여자, difference]
Index: []

In [17]:
# '-' → 0 후 숫자형 변환
gangnam_disabled["disabled_count"] = (
    gangnam_disabled["disabled_count"]
    .replace("-", 0)
)

gangnam_disabled["disabled_count"] = pd.to_numeric(
    gangnam_disabled["disabled_count"],
    errors="coerce"
)

print("변환 후 결측치:")
print(gangnam_disabled["disabled_count"].isna().sum())

print("\n자료형:")
print(gangnam_disabled["disabled_count"].dtype)

변환 후 결측치:
0

자료형:
int64

In [18]:
type_check = gangnam_disabled[
    gangnam_disabled["sex"] == "계"
].copy()

# 각 동의 전체 장애인 수
dong_total = (
    type_check[
        type_check["disability_type"] == "합계"
    ]
    .set_index("dong_name")["disabled_count"]
)

# 합계를 제외한 15개 장애유형의 합
type_sum = (
    type_check[
        type_check["disability_type"] != "합계"
    ]
    .groupby("dong_name")["disabled_count"]
    .sum()
)

type_validation = pd.DataFrame({
    "disabled_total": dong_total,
    "disability_type_sum": type_sum
})

type_validation["difference"] = (
    type_validation["disabled_total"]
    - type_validation["disability_type_sum"]
)

display(type_validation)

print(
    "\n불일치 행정동 수:",
    (type_validation["difference"] != 0).sum()
)

print("\n차이값 분포:")
print(type_validation["difference"].value_counts().sort_index())

           disabled_total  disability_type_sum  difference
dong_name
개포1동                  523                  523           0
개포2동                  761                  761           0
개포3동                 1117                 1117           0
개포4동                  608                  608           0
논현1동                  547                  547           0
논현2동                  452                  452           0
대치1동                  303                  303           0
대치2동                  594                  594           0
대치4동                  358                  358           0
도곡1동                  354                  354           0
도곡2동                  526                  526           0
삼성1동                  283                  283           0
삼성2동                  586                  586           0
세곡동                  1985                 1985           0
수서동                  1988                 1988           0
신사동                   356                  356           0
압구정동                  483                  483           0
역삼1동                  732                  732           0
역삼2동                  659                  659           0
일원1동                 1091                 1091           0
일원본동                  688                  688           0
청담동                   523                  523           0

불일치 행정동 수: 0

차이값 분포:
difference
0    22
Name: count, dtype: int64

In [19]:
from google.colab import files

resident_uploaded = files.upload()

Saving gangnam_resident_population_features_2025Q3_Q4.csv to gangnam_resident_population_features_2025Q3_Q4.csv

In [20]:
resident_filename = list(resident_uploaded.keys())[0]

resident = pd.read_csv(
    resident_filename,
    encoding="utf-8-sig"
)

print("크기:", resident.shape)
print("컬럼:")
print(resident.columns.tolist())

print("\n분기:")
print(resident["quarter"].unique())

print("\n행정동 수:")
print(resident["dong_name"].nunique())

크기: (44, 27)
컬럼:
['dong_name', 'quarter', 'resident_total', 'resident_korean', 'resident_foreigner', 'foreigner_ratio', 'resident_age_10', 'resident_age_20', 'resident_age_30', 'resident_age_40', 'resident_age_50', 'resident_age_60_plus', 'resident_age_65_plus', 'resident_age_10_ratio', 'resident_age_20_ratio', 'resident_age_30_ratio', 'resident_age_40_ratio', 'resident_age_50_ratio', 'resident_age_60_plus_ratio', 'resident_age_65_plus_ratio', 'resident_10plus', 'resident_age_10_ratio_10plus', 'resident_age_20_ratio_10plus', 'resident_age_30_ratio_10plus', 'resident_age_40_ratio_10plus', 'resident_age_50_ratio_10plus', 'resident_age_60_plus_ratio_10plus']

분기:
['2025Q3' '2025Q4']

행정동 수:
22

In [21]:
# 2025 Q3/Q4 평균 등록인구
resident_mean = (
    resident
    .groupby("dong_name", as_index=False)
    .agg(
        resident_mean=("resident_total", "mean")
    )
)

print("크기:", resident_mean.shape)
display(resident_mean.head())

크기: (22, 2)

  dong_name  resident_mean
0      개포1동        26749.5
1      개포2동        42223.5
2      개포3동        16294.5
3      개포4동        23161.5
4      논현1동        21535.5

In [22]:
disabled_total = (
    gangnam_disabled[
        (gangnam_disabled["disability_type"] == "합계") &
        (gangnam_disabled["sex"] == "계")
    ][["dong_name", "disabled_count"]]
    .rename(columns={"disabled_count": "disabled_total"})
    .copy()
)

print("크기:", disabled_total.shape)
display(disabled_total.head())

크기: (22, 2)

      dong_name  disabled_total
19440       신사동             356
19488      논현1동             547
19536      논현2동             452
19584      압구정동             483
19632       청담동             523

In [23]:
disabled_scale = disabled_total.merge(
    resident_mean,
    on="dong_name",
    how="left"
)

disabled_scale["disabled_per_1000"] = (
    disabled_scale["disabled_total"]
    / disabled_scale["resident_mean"]
    * 1000
)

print("크기:", disabled_scale.shape)

print("\n결측치:")
print(disabled_scale.isna().sum())

print("\ndisabled_per_1000 분포:")
print(
    disabled_scale["disabled_per_1000"]
    .describe()
)

print("\n인구 1,000명당 등록장애인 규모:")
display(
    disabled_scale[
        ["dong_name", "disabled_total",
         "resident_mean", "disabled_per_1000"]
    ]
    .sort_values(
        "disabled_per_1000",
        ascending=False
    )
    .round(2)
)

크기: (22, 4)

결측치:
dong_name            0
disabled_total       0
resident_mean        0
disabled_per_1000    0
dtype: int64

disabled_per_1000 분포:
count     22.000000
mean      31.800774
std       30.276546
min       12.718801
25%       18.250318
50%       20.812203
75%       26.037824
max      146.192595
Name: disabled_per_1000, dtype: float64

인구 1,000명당 등록장애인 규모:

   dong_name  disabled_total  resident_mean  disabled_per_1000
21       수서동            1988        13598.5             146.19
20      일원1동            1091        14259.5              76.51
16      개포3동            1117        16294.5              68.55
18       세곡동            1985        46141.5              43.02
19      일원본동             688        22431.5              30.67
17      개포4동             608        23161.5              26.25
1       논현1동             547        21535.5              25.40
0        신사동             356        15309.0              23.25
2       논현2동             452        20508.5              22.04
5       삼성1동             283        13036.5              21.71
4        청담동             523        24789.0              21.10
10      역삼1동             732        35661.5              20.53
14      개포1동             523        26749.5              19.55
9       대치4동             358        18462.0              19.39
6       삼성2동             586        30596.0              19.15
3       압구정동             483        25669.5              18.82
11      역삼2동             659        36486.0              18.06
15      개포2동             761        42223.5              18.02
12      도곡1동             354        20839.5              16.99
13      도곡2동             526        32234.5              16.32
8       대치2동             594        38634.5              15.37
7       대치1동             303        23823.0              12.72

In [24]:
type_profile = (
    gangnam_disabled[
        (gangnam_disabled["sex"] == "계") &
        (gangnam_disabled["disability_type"] != "합계")
    ]
    .groupby("disability_type")
    .agg(
        total_count=("disabled_count", "sum"),
        mean_count=("disabled_count", "mean"),
        median_count=("disabled_count", "median"),
        zero_dongs=("disabled_count", lambda x: (x == 0).sum()),
        nonzero_dongs=("disabled_count", lambda x: (x > 0).sum())
    )
    .reset_index()
)

# 강남구 전체 등록장애인 15,517명 대비 유형별 비율
gangnam_disabled_total = disabled_total["disabled_total"].sum()

type_profile["share_pct"] = (
    type_profile["total_count"]
    / gangnam_disabled_total
    * 100
)

type_profile = type_profile.sort_values(
    "total_count",
    ascending=False
)

display(type_profile.round(2))

,disability_type,total_count,mean_count,median_count,zero_dongs,nonzero_dongs,share_pct
12,지체,5645,256.59,199.5,0,22,36.38
13,청각,2430,110.45,85.0,0,22,15.66
1,뇌병변,1666,75.73,63.0,0,22,10.74
3,시각,1577,71.68,54.5,0,22,10.16
11,지적장애,1054,47.91,30.0,0,22,6.79
4,신장장애,907,41.23,39.0,0,22,5.85
8,자폐성,835,37.95,28.0,0,22,5.38
10,정신장애,819,37.23,15.5,0,22,5.28
0,간,150,6.82,6.0,0,22,0.97
7,언어,124,5.64,4.0,0,22,0.80
9,장루요루,116,5.27,5.5,0,22,0.75
14,호흡기,77,3.50,3.0,2,20,0.50
2,뇌전증,57,2.59,2.0,5,17,0.37
5,심장장애,38,1.73,1.0,5,17,0.24
6,안면,22,1.00,1.0,9,13,0.14

In [25]:
print(
    "15개 장애유형 총합:",
    type_profile["total_count"].sum()
)

print(
    "강남구 등록장애인 총합:",
    gangnam_disabled_total
)

print(
    "장애유형 비율 합:",
    type_profile["share_pct"].sum()
)

15개 장애유형 총합: 15517
강남구 등록장애인 총합: 15517
장애유형 비율 합: 99.99999999999999

In [26]:
# 성별 '계', 전체 '합계' 제외
type_detail = gangnam_disabled[
    (gangnam_disabled["sex"] == "계") &
    (gangnam_disabled["disability_type"] != "합계")
].copy()

# 행정동별 전체 장애인 수 결합
type_detail = type_detail.merge(
    disabled_total,
    on="dong_name",
    how="left"
)

# 해당 동 등록장애인 중 각 장애유형의 비율
type_detail["type_ratio"] = (
    type_detail["disabled_count"]
    / type_detail["disabled_total"]
)

print("크기:", type_detail.shape)

print("\n행정동별 구성비 합 검증:")
ratio_check = (
    type_detail.groupby("dong_name")["type_ratio"]
    .sum()
)

print(ratio_check.describe())
print(
    "1과의 최대 오차:",
    (ratio_check - 1).abs().max()
)

크기: (330, 6)

행정동별 구성비 합 검증:
count    22.0
mean      1.0
std       0.0
min       1.0
25%       1.0
50%       1.0
75%       1.0
max       1.0
Name: type_ratio, dtype: float64
1과의 최대 오차: 0.0

In [27]:
main_types = [
    "지체",
    "청각",
    "뇌병변",
    "시각",
    "지적장애",
    "신장장애",
    "자폐성",
    "정신장애"
]

main_type_feature = (
    type_detail[
        type_detail["disability_type"].isin(main_types)
    ]
    .pivot(
        index="dong_name",
        columns="disability_type",
        values="type_ratio"
    )
    .reset_index()
)

main_type_feature = main_type_feature.rename(
    columns={
        "지체": "physical_ratio",
        "청각": "hearing_ratio",
        "뇌병변": "brain_lesion_ratio",
        "시각": "visual_ratio",
        "지적장애": "intellectual_ratio",
        "신장장애": "kidney_ratio",
        "자폐성": "autism_ratio",
        "정신장애": "mental_ratio"
    }
)

# 나머지 7개 유형을 other로 통합
other_feature = (
    type_detail[
        ~type_detail["disability_type"].isin(main_types)
    ]
    .groupby("dong_name", as_index=False)
    .agg(other_disability_ratio=("type_ratio", "sum"))
)

disability_type_feature = main_type_feature.merge(
    other_feature,
    on="dong_name",
    how="left"
)

print("크기:", disability_type_feature.shape)
print("\n결측치:")
print(disability_type_feature.isna().sum())

display(disability_type_feature.head().round(4))

크기: (22, 10)

결측치:
dong_name                 0
brain_lesion_ratio        0
visual_ratio              0
kidney_ratio              0
autism_ratio              0
mental_ratio              0
intellectual_ratio        0
physical_ratio            0
hearing_ratio             0
other_disability_ratio    0
dtype: int64

,dong_name,brain_lesion_ratio,visual_ratio,kidney_ratio,autism_ratio,mental_ratio,intellectual_ratio,physical_ratio,hearing_ratio,other_disability_ratio
0,개포1동,0.1090,0.0956,0.0784,0.0765,0.0268,0.0535,0.3633,0.1491,0.0478
1,개포2동,0.0880,0.1209,0.0539,0.0867,0.0223,0.0841,0.3679,0.1314,0.0447
2,개포3동,0.1021,0.1012,0.0403,0.0421,0.0725,0.0770,0.3339,0.2050,0.0260
3,개포4동,0.1135,0.0921,0.0724,0.0411,0.0477,0.0773,0.3536,0.1562,0.0461
4,논현1동,0.0987,0.1408,0.0494,0.0274,0.0366,0.0786,0.3839,0.1389,0.0457

In [28]:
ratio_cols = [
    "physical_ratio",
    "hearing_ratio",
    "brain_lesion_ratio",
    "visual_ratio",
    "intellectual_ratio",
    "kidney_ratio",
    "autism_ratio",
    "mental_ratio",
    "other_disability_ratio"
]

disability_type_feature["ratio_sum"] = (
    disability_type_feature[ratio_cols].sum(axis=1)
)

print(
    disability_type_feature["ratio_sum"].describe()
)

print(
    "1과의 최대 오차:",
    (disability_type_feature["ratio_sum"] - 1)
    .abs()
    .max()
)

count    2.200000e+01
mean     1.000000e+00
std      1.027867e-16
min      1.000000e+00
25%      1.000000e+00
50%      1.000000e+00
75%      1.000000e+00
max      1.000000e+00
Name: ratio_sum, dtype: float64
1과의 최대 오차: 2.220446049250313e-16

In [29]:
gender_disabled = gangnam_disabled[
    gangnam_disabled["disability_type"] == "합계"
].copy()

gender_pivot = (
    gender_disabled[
        gender_disabled["sex"].isin(["남자", "여자"])
    ]
    .pivot(
        index="dong_name",
        columns="sex",
        values="disabled_count"
    )
    .reset_index()
)

gender_pivot = gender_pivot.rename(
    columns={
        "남자": "disabled_male",
        "여자": "disabled_female"
    }
)

# 전체 장애인 수 결합
gender_pivot = gender_pivot.merge(
    disabled_total,
    on="dong_name",
    how="left"
)

# 성별 구성비
gender_pivot["disabled_male_ratio"] = (
    gender_pivot["disabled_male"]
    / gender_pivot["disabled_total"]
)

gender_pivot["disabled_female_ratio"] = (
    gender_pivot["disabled_female"]
    / gender_pivot["disabled_total"]
)

print("크기:", gender_pivot.shape)

print("\n결측치:")
print(gender_pivot.isna().sum())

display(gender_pivot.head().round(4))

크기: (22, 6)

결측치:
dong_name                0
disabled_male            0
disabled_female          0
disabled_total           0
disabled_male_ratio      0
disabled_female_ratio    0
dtype: int64

,dong_name,disabled_male,disabled_female,disabled_total,disabled_male_ratio,disabled_female_ratio
0,개포1동,337,186,523,0.6444,0.3556
1,개포2동,476,285,761,0.6255,0.3745
2,개포3동,539,578,1117,0.4825,0.5175
3,개포4동,367,241,608,0.6036,0.3964
4,논현1동,323,224,547,0.5905,0.4095

In [30]:
gender_pivot["gender_count_check"] = (
    gender_pivot["disabled_male"]
    + gender_pivot["disabled_female"]
    - gender_pivot["disabled_total"]
)

gender_pivot["gender_ratio_check"] = (
    gender_pivot["disabled_male_ratio"]
    + gender_pivot["disabled_female_ratio"]
)

print(
    "성별 인원 합계 불일치 동:",
    (gender_pivot["gender_count_check"] != 0).sum()
)

print(
    "성별 구성비 1과의 최대 오차:",
    (gender_pivot["gender_ratio_check"] - 1)
    .abs()
    .max()
)

print("\n성별 구성비 분포:")
print(
    gender_pivot[
        ["disabled_male_ratio", "disabled_female_ratio"]
    ].describe()
)

성별 인원 합계 불일치 동: 0
성별 구성비 1과의 최대 오차: 0.0

성별 구성비 분포:
       disabled_male_ratio  disabled_female_ratio
count            22.000000              22.000000
mean              0.594462               0.405538
std               0.045781               0.045781
min               0.479651               0.333333
25%               0.583225               0.383107
50%               0.598444               0.401556
75%               0.616893               0.416775
max               0.666667               0.520349

In [31]:
# 규모 Feature
scale_feature = disabled_scale[
    ["dong_name", "disabled_total", "disabled_per_1000"]
].copy()

# 성별 Feature
gender_feature = gender_pivot[
    [
        "dong_name",
        "disabled_male_ratio",
        "disabled_female_ratio"
    ]
].copy()

# 최종 결합
disabled_feature = (
    scale_feature
    .merge(
        gender_feature,
        on="dong_name",
        how="left"
    )
    .merge(
        disability_type_feature.drop(columns=["ratio_sum"]),
        on="dong_name",
        how="left"
    )
)

print("최종 크기:", disabled_feature.shape)

print("\n결측치:")
print(disabled_feature.isna().sum())

print("\n중복 행정동:")
print(disabled_feature["dong_name"].duplicated().sum())

display(disabled_feature.round(4))

최종 크기: (22, 14)

결측치:
dong_name                 0
disabled_total            0
disabled_per_1000         0
disabled_male_ratio       0
disabled_female_ratio     0
brain_lesion_ratio        0
visual_ratio              0
kidney_ratio              0
autism_ratio              0
mental_ratio              0
intellectual_ratio        0
physical_ratio            0
hearing_ratio             0
other_disability_ratio    0
dtype: int64

중복 행정동:
0

,dong_name,disabled_total,disabled_per_1000,disabled_male_ratio,disabled_female_ratio,brain_lesion_ratio,visual_ratio,kidney_ratio,autism_ratio,mental_ratio,intellectual_ratio,physical_ratio,hearing_ratio,other_disability_ratio
0,신사동,356,23.2543,0.5955,0.4045,0.1152,0.0899,0.0702,0.0421,0.0169,0.0421,0.3961,0.1742,0.0534
1,논현1동,547,25.3999,0.5905,0.4095,0.0987,0.1408,0.0494,0.0274,0.0366,0.0786,0.3839,0.1389,0.0457
2,논현2동,452,22.0396,0.6128,0.3872,0.0796,0.1173,0.0597,0.0288,0.0221,0.0686,0.4181,0.1726,0.0332
3,압구정동,483,18.8161,0.6004,0.3996,0.1284,0.0828,0.0704,0.0538,0.0145,0.0518,0.3602,0.1967,0.0414
4,청담동,523,21.0981,0.5870,0.4130,0.1338,0.0975,0.0880,0.0516,0.0268,0.0421,0.3576,0.1606,0.0421
5,삼성1동,283,21.7083,0.6431,0.3569,0.1166,0.1095,0.0459,0.0636,0.0177,0.0530,0.4134,0.1555,0.0247
6,삼성2동,586,19.1528,0.6075,0.3925,0.1007,0.1195,0.0648,0.0734,0.0290,0.0427,0.3532,0.1758,0.0410
7,대치1동,303,12.7188,0.6172,0.3828,0.1452,0.0924,0.0792,0.0924,0.0198,0.0561,0.3135,0.1584,0.0429
8,대치2동,594,15.3749,0.6667,0.3333,0.1347,0.0960,0.0758,0.0808,0.0168,0.0640,0.3316,0.1448,0.0556
9,대치4동,358,19.3912,0.5670,0.4330,0.1034,0.1061,0.0922,0.0251,0.0279,0.0531,0.3939,0.1564,0.0419
10,역삼1동,732,20.5263,0.5820,0.4180,0.1011,0.1189,0.0574,0.0232,0.0383,0.0492,0.4167,0.1530,0.0423
11,역삼2동,659,18.0617,0.6161,0.3839,0.1259,0.1123,0.0607,0.0455,0.0334,0.0440,0.3839,0.1578,0.0364
12,도곡1동,354,16.9870,0.5904,0.4096,0.1073,0.0819,0.0819,0.0593,0.0254,0.0791,0.3814,0.1582,0.0254
13,도곡2동,526,16.3179,0.6445,0.3555,0.1217,0.0932,0.0703,0.0703,0.0171,0.0475,0.3840,0.1559,0.0399
14,개포1동,523,19.5518,0.6444,0.3556,0.1090,0.0956,0.0784,0.0765,0.0268,0.0535,0.3633,0.1491,0.0478
15,개포2동,761,18.0231,0.6255,0.3745,0.0880,0.1209,0.0539,0.0867,0.0223,0.0841,0.3679,0.1314,0.0447
16,개포3동,1117,68.5507,0.4825,0.5175,0.1021,0.1012,0.0403,0.0421,0.0725,0.0770,0.3339,0.2050,0.0260
17,개포4동,608,26.2505,0.6036,0.3964,0.1135,0.0921,0.0724,0.0411,0.0477,0.0773,0.3536,0.1562,0.0461
18,세곡동,1985,43.0198,0.5965,0.4035,0.1144,0.1013,0.0509,0.0685,0.0327,0.0861,0.3627,0.1501,0.0332
19,일원본동,688,30.6712,0.4797,0.5203,0.0858,0.0727,0.0407,0.1381,0.1860,0.0872,0.2369,0.1206,0.0320
20,일원1동,1091,76.5104,0.5710,0.4290,0.0944,0.1008,0.0504,0.0467,0.0779,0.0788,0.3602,0.1613,0.0293
21,수서동,1988,146.1926,0.5543,0.4457,0.0981,0.0951,0.0463,0.0141,0.1142,0.0724,0.3813,0.1434,0.0352

In [32]:
# 성별 구성비
gender_sum = (
    disabled_feature["disabled_male_ratio"]
    + disabled_feature["disabled_female_ratio"]
)

# 장애유형 구성비
type_cols = [
    "physical_ratio",
    "hearing_ratio",
    "brain_lesion_ratio",
    "visual_ratio",
    "intellectual_ratio",
    "kidney_ratio",
    "autism_ratio",
    "mental_ratio",
    "other_disability_ratio"
]

type_sum = disabled_feature[type_cols].sum(axis=1)

print(
    "성별 구성비 최대 오차:",
    (gender_sum - 1).abs().max()
)

print(
    "장애유형 구성비 최대 오차:",
    (type_sum - 1).abs().max()
)

성별 구성비 최대 오차: 0.0
장애유형 구성비 최대 오차: 2.220446049250313e-16

In [33]:
output_file = "gangnam_disability_features_2025.csv"

disabled_feature.round(6).to_csv(
    output_file,
    index=False,
    encoding="utf-8-sig"
)

print("저장 완료:", output_file)
print("크기:", disabled_feature.shape)

저장 완료: gangnam_disability_features_2025.csv
크기: (22, 14)

In [34]:
from google.colab import files

files.download(
    "gangnam_disability_features_2025.csv"
)

In [35]:
from google.colab import files
import pandas as pd

uploaded = files.upload()

filename = list(uploaded.keys())[0]
print("업로드 파일:", filename)

Saving 장애인+현황(등급별_연령별)_20260923095357.csv to 장애인+현황(등급별_연령별)_20260923095357.csv
업로드 파일: 장애인+현황(등급별_연령별)_20260923095357.csv

In [36]:
disabled_age_raw = pd.read_csv(
    filename,
    encoding="utf-8-sig"
)

print("크기:", disabled_age_raw.shape)

print("\n컬럼:")
print(disabled_age_raw.columns.tolist())

print("\n상단 10행:")
display(disabled_age_raw.head(10))

print("\n하단 10행:")
display(disabled_age_raw.tail(10))

크기: (30, 38)

컬럼:
['자치구별(1)', '자치구별(2)', '2025', '2025.1', '2025.2', '2025.3', '2025.4', '2025.5', '2025.6', '2025.7', '2025.8', '2025.9', '2025.10', '2025.11', '2025.12', '2025.13', '2025.14', '2025.15', '2025.16', '2025.17', '2025.18', '2025.19', '2025.20', '2025.21', '2025.22', '2025.23', '2025.24', '2025.25', '2025.26', '2025.27', '2025.28', '2025.29', '2025.30', '2025.31', '2025.32', '2025.33', '2025.34', '2025.35']

상단 10행:

,자치구별(1),자치구별(2),2025,2025.1,2025.2,2025.3,2025.4,2025.5,2025.6,2025.7,...,2025.26,2025.27,2025.28,2025.29,2025.30,2025.31,2025.32,2025.33,2025.34,2025.35
0,자치구별(1),자치구별(2),합계,합계,합계,합계,합계,합계,합계,합계,...,합계,합계,합계,합계,합계,합계,합계,합계,합계,합계
1,자치구별(1),자치구별(2),소계,소계,소계,장애정도별,장애정도별,장애정도별,장애정도별,장애정도별,...,연령별,연령별,연령별,연령별,연령별,연령별,연령별,연령별,연령별,연령별
2,자치구별(1),자치구별(2),소계,소계,소계,심한 장애,심한 장애,심한 장애,심하지 않은 장애,심하지 않은 장애,...,50~59세,60~69세,60~69세,60~69세,70~79세,70~79세,70~79세,80세이상,80세이상,80세이상
3,자치구별(1),자치구별(2),계,남자,여자,계,남자,여자,계,남자,...,여자,계,남자,여자,계,남자,여자,계,남자,여자
4,서울시,소계,384934,222453,162481,135622,81905,53717,249312,140548,...,16441,85087,54483,30604,93730,51551,42179,82741,34858,47883
5,서울시,종로구,5538,3190,2348,1918,1154,764,3620,2036,...,229,1155,815,340,1214,655,559,1401,572,829
6,서울시,중구,5094,2896,2198,1688,1015,673,3406,1881,...,216,1123,733,390,1287,739,548,1267,494,773
7,서울시,용산구,6695,3951,2744,2310,1427,883,4385,2524,...,247,1420,939,481,1512,850,662,1580,659,921
8,서울시,성동구,10603,6114,4489,3483,2128,1355,7120,3986,...,473,2395,1615,780,2418,1361,1057,2510,978,1532
9,서울시,광진구,11981,6928,5053,3921,2363,1558,8060,4565,...,551,2684,1755,929,2835,1569,1266,2589,1104,1485

하단 10행:

,자치구별(1),자치구별(2),2025,2025.1,2025.2,2025.3,2025.4,2025.5,2025.6,2025.7,...,2025.26,2025.27,2025.28,2025.29,2025.30,2025.31,2025.32,2025.33,2025.34,2025.35
20,서울시,강서구,27618,15943,11675,10788,6431,4357,16830,9512,...,1210,6982,4363,2619,6930,3938,2992,5243,2138,3105
21,서울시,구로구,19579,11432,8147,6257,3780,2477,13322,7652,...,790,4458,2858,1600,5188,2899,2289,4072,1824,2248
22,서울시,금천구,12227,7224,5003,3891,2351,1540,8336,4873,...,560,3072,2030,1042,3147,1722,1425,2346,1038,1308
23,서울시,영등포구,14774,8709,6065,4582,2888,1694,10192,5821,...,542,3129,2104,1025,3796,2157,1639,3444,1482,1962
24,서울시,동작구,13911,7960,5951,4734,2823,1911,9177,5137,...,536,2880,1838,1042,3448,1815,1633,3197,1420,1777
25,서울시,관악구,20008,11608,8400,6645,4030,2615,13363,7578,...,868,4168,2656,1512,4984,2721,2263,4413,1928,2485
26,서울시,서초구,10179,5990,4189,3876,2349,1527,6303,3641,...,414,1836,1136,700,2403,1350,1053,2197,1003,1194
27,서울시,강남구,15517,9071,6446,6405,3874,2531,9112,5197,...,638,3153,1907,1246,3644,2013,1631,3178,1454,1724
28,서울시,송파구,20115,11967,8148,7269,4544,2725,12846,7423,...,847,4272,2706,1566,4634,2665,1969,3868,1644,2224
29,서울시,강동구,19453,11634,7819,6967,4357,2610,12486,7277,...,798,4332,2754,1578,4601,2644,1957,3603,1594,2009

In [37]:
# 원본의 4단 헤더 구조 확인
header_info = pd.DataFrame({
    "column": disabled_age_raw.columns,
    "level_1": disabled_age_raw.iloc[0].values,
    "level_2": disabled_age_raw.iloc[1].values,
    "level_3": disabled_age_raw.iloc[2].values,
    "level_4": disabled_age_raw.iloc[3].values
})

pd.set_option("display.max_rows", None)
display(header_info)

# 강남구 원자료 확인
gangnam_row = disabled_age_raw[
    disabled_age_raw["자치구별(2)"] == "강남구"
]

print("\n강남구 행 수:", len(gangnam_row))

     column  level_1  level_2    level_3  level_4
0   자치구별(1)  자치구별(1)  자치구별(1)    자치구별(1)  자치구별(1)
1   자치구별(2)  자치구별(2)  자치구별(2)    자치구별(2)  자치구별(2)
2      2025       합계       소계         소계        계
3    2025.1       합계       소계         소계       남자
4    2025.2       합계       소계         소계       여자
5    2025.3       합계    장애정도별      심한 장애        계
6    2025.4       합계    장애정도별      심한 장애       남자
7    2025.5       합계    장애정도별      심한 장애       여자
8    2025.6       합계    장애정도별  심하지 않은 장애        계
9    2025.7       합계    장애정도별  심하지 않은 장애       남자
10   2025.8       합계    장애정도별  심하지 않은 장애       여자
11   2025.9       합계      연령별       9세이하        계
12  2025.10       합계      연령별       9세이하       남자
13  2025.11       합계      연령별       9세이하       여자
14  2025.12       합계      연령별     10~19세        계
15  2025.13       합계      연령별     10~19세       남자
16  2025.14       합계      연령별     10~19세       여자
17  2025.15       합계      연령별     20~29세        계
18  2025.16       합계      연령별     20~29세       남자
19  2025.17       합계      연령별     20~29세       여자
20  2025.18       합계      연령별     30~39세        계
21  2025.19       합계      연령별     30~39세       남자
22  2025.20       합계      연령별     30~39세       여자
23  2025.21       합계      연령별     40~49세        계
24  2025.22       합계      연령별     40~49세       남자
25  2025.23       합계      연령별     40~49세       여자
26  2025.24       합계      연령별     50~59세        계
27  2025.25       합계      연령별     50~59세       남자
28  2025.26       합계      연령별     50~59세       여자
29  2025.27       합계      연령별     60~69세        계
30  2025.28       합계      연령별     60~69세       남자
31  2025.29       합계      연령별     60~69세       여자
32  2025.30       합계      연령별     70~79세        계
33  2025.31       합계      연령별     70~79세       남자
34  2025.32       합계      연령별     70~79세       여자
35  2025.33       합계      연령별      80세이상        계
36  2025.34       합계      연령별      80세이상       남자
37  2025.35       합계      연령별      80세이상       여자

강남구 행 수: 1

In [38]:
age_header = header_info[
    header_info["level_2"] == "연령별"
].copy()

display(age_header)

     column level_1 level_2 level_3 level_4
11   2025.9      합계     연령별    9세이하       계
12  2025.10      합계     연령별    9세이하      남자
13  2025.11      합계     연령별    9세이하      여자
14  2025.12      합계     연령별  10~19세       계
15  2025.13      합계     연령별  10~19세      남자
16  2025.14      합계     연령별  10~19세      여자
17  2025.15      합계     연령별  20~29세       계
18  2025.16      합계     연령별  20~29세      남자
19  2025.17      합계     연령별  20~29세      여자
20  2025.18      합계     연령별  30~39세       계
21  2025.19      합계     연령별  30~39세      남자
22  2025.20      합계     연령별  30~39세      여자
23  2025.21      합계     연령별  40~49세       계
24  2025.22      합계     연령별  40~49세      남자
25  2025.23      합계     연령별  40~49세      여자
26  2025.24      합계     연령별  50~59세       계
27  2025.25      합계     연령별  50~59세      남자
28  2025.26      합계     연령별  50~59세      여자
29  2025.27      합계     연령별  60~69세       계
30  2025.28      합계     연령별  60~69세      남자
31  2025.29      합계     연령별  60~69세      여자
32  2025.30      합계     연령별  70~79세       계
33  2025.31      합계     연령별  70~79세      남자
34  2025.32      합계     연령별  70~79세      여자
35  2025.33      합계     연령별   80세이상       계
36  2025.34      합계     연령별   80세이상      남자
37  2025.35      합계     연령별   80세이상      여자

In [39]:
gangnam = disabled_age_raw[
    disabled_age_raw["자치구별(2)"] == "강남구"
].iloc[0]

gangnam_disability_background = pd.DataFrame([{
    "region": "강남구",
    "year": 2025,

    # 전체
    "disabled_total": gangnam["2025"],
    "disabled_male": gangnam["2025.1"],
    "disabled_female": gangnam["2025.2"],

    # 장애정도
    "severe_total": gangnam["2025.3"],
    "severe_male": gangnam["2025.4"],
    "severe_female": gangnam["2025.5"],

    "nonsevere_total": gangnam["2025.6"],
    "nonsevere_male": gangnam["2025.7"],
    "nonsevere_female": gangnam["2025.8"],

    # 연령
    "age_0_9": gangnam["2025.9"],
    "age_10_19": gangnam["2025.12"],
    "age_20_29": gangnam["2025.15"],
    "age_30_39": gangnam["2025.18"],
    "age_40_49": gangnam["2025.21"],
    "age_50_59": gangnam["2025.24"],
    "age_60_69": gangnam["2025.27"],
    "age_70_79": gangnam["2025.30"],
    "age_80_plus": gangnam["2025.33"]
}])

# 숫자형 변환
numeric_cols = gangnam_disability_background.columns.difference(
    ["region"]
)

gangnam_disability_background[numeric_cols] = (
    gangnam_disability_background[numeric_cols]
    .apply(pd.to_numeric, errors="coerce")
)

display(gangnam_disability_background)

,region,year,disabled_total,disabled_male,disabled_female,severe_total,severe_male,severe_female,nonsevere_total,nonsevere_male,nonsevere_female,age_0_9,age_10_19,age_20_29,age_30_39,age_40_49,age_50_59,age_60_69,age_70_79,age_80_plus
0,강남구,2025,15517,9071,6446,6405,3874,2531,9112,5197,3915,329,651,625,773,1284,1880,3153,3644,3178

In [40]:
bg = gangnam_disability_background.iloc[0]

# ① 남 + 여 = 전체
gender_diff = (
    bg["disabled_male"]
    + bg["disabled_female"]
    - bg["disabled_total"]
)

# ② 심한 장애 + 심하지 않은 장애 = 전체
severity_diff = (
    bg["severe_total"]
    + bg["nonsevere_total"]
    - bg["disabled_total"]
)

# ③ 9개 연령구간 합 = 전체
age_cols = [
    "age_0_9",
    "age_10_19",
    "age_20_29",
    "age_30_39",
    "age_40_49",
    "age_50_59",
    "age_60_69",
    "age_70_79",
    "age_80_plus"
]

age_sum = bg[age_cols].sum()
age_diff = age_sum - bg["disabled_total"]

print("전체 장애인:", bg["disabled_total"])

print("\n남 + 여 차이:", gender_diff)
print("장애정도 합계 차이:", severity_diff)
print("연령구간 합계:", age_sum)
print("연령구간 합계 차이:", age_diff)

print("\n결측치:")
print(gangnam_disability_background.isna().sum())

전체 장애인: 15517

남 + 여 차이: 0
장애정도 합계 차이: 0
연령구간 합계: 15517
연령구간 합계 차이: 0

결측치:
region              0
year                0
disabled_total      0
disabled_male       0
disabled_female     0
severe_total        0
severe_male         0
severe_female       0
nonsevere_total     0
nonsevere_male      0
nonsevere_female    0
age_0_9             0
age_10_19           0
age_20_29           0
age_30_39           0
age_40_49           0
age_50_59           0
age_60_69           0
age_70_79           0
age_80_plus         0
dtype: int64

In [41]:
background_feature = gangnam_disability_background.copy()

# 전체 성별 구성
background_feature["disabled_male_ratio"] = (
    background_feature["disabled_male"]
    / background_feature["disabled_total"]
)

background_feature["disabled_female_ratio"] = (
    background_feature["disabled_female"]
    / background_feature["disabled_total"]
)

# 장애정도 구성
background_feature["severe_ratio"] = (
    background_feature["severe_total"]
    / background_feature["disabled_total"]
)

background_feature["nonsevere_ratio"] = (
    background_feature["nonsevere_total"]
    / background_feature["disabled_total"]
)

In [42]:
age_cols = [
    "age_0_9",
    "age_10_19",
    "age_20_29",
    "age_30_39",
    "age_40_49",
    "age_50_59",
    "age_60_69",
    "age_70_79",
    "age_80_plus"
]

for col in age_cols:
    background_feature[f"{col}_ratio"] = (
        background_feature[col]
        / background_feature["disabled_total"]
    )

In [43]:
age_ratio_cols = [
    f"{col}_ratio"
    for col in age_cols
]

gender_ratio_sum = (
    background_feature["disabled_male_ratio"]
    + background_feature["disabled_female_ratio"]
)

severity_ratio_sum = (
    background_feature["severe_ratio"]
    + background_feature["nonsevere_ratio"]
)

age_ratio_sum = (
    background_feature[age_ratio_cols]
    .sum(axis=1)
)

print(
    "성별 구성비 합:",
    gender_ratio_sum.iloc[0]
)

print(
    "장애정도 구성비 합:",
    severity_ratio_sum.iloc[0]
)

print(
    "연령 구성비 합:",
    age_ratio_sum.iloc[0]
)

print("\n주요 구성비:")

print(
    "심한 장애:",
    round(background_feature["severe_ratio"].iloc[0] * 100, 2),
    "%"
)

print(
    "심하지 않은 장애:",
    round(background_feature["nonsevere_ratio"].iloc[0] * 100, 2),
    "%"
)

for col in age_ratio_cols:
    print(
        col,
        round(background_feature[col].iloc[0] * 100, 2),
        "%"
    )

성별 구성비 합: 1.0
장애정도 구성비 합: 1.0
연령 구성비 합: 0.9999999999999999

주요 구성비:
심한 장애: 41.28 %
심하지 않은 장애: 58.72 %
age_0_9_ratio 2.12 %
age_10_19_ratio 4.2 %
age_20_29_ratio 4.03 %
age_30_39_ratio 4.98 %
age_40_49_ratio 8.27 %
age_50_59_ratio 12.12 %
age_60_69_ratio 20.32 %
age_70_79_ratio 23.48 %
age_80_plus_ratio 20.48 %

In [44]:
output_file = "gangnam_disability_background_2025.csv"

background_feature.round(6).to_csv(
    output_file,
    index=False,
    encoding="utf-8-sig"
)

print("저장 완료:", output_file)
print("크기:", background_feature.shape)
print("\n컬럼:")
print(background_feature.columns.tolist())

저장 완료: gangnam_disability_background_2025.csv
크기: (1, 33)

컬럼:
['region', 'year', 'disabled_total', 'disabled_male', 'disabled_female', 'severe_total', 'severe_male', 'severe_female', 'nonsevere_total', 'nonsevere_male', 'nonsevere_female', 'age_0_9', 'age_10_19', 'age_20_29', 'age_30_39', 'age_40_49', 'age_50_59', 'age_60_69', 'age_70_79', 'age_80_plus', 'disabled_male_ratio', 'disabled_female_ratio', 'severe_ratio', 'nonsevere_ratio', 'age_0_9_ratio', 'age_10_19_ratio', 'age_20_29_ratio', 'age_30_39_ratio', 'age_40_49_ratio', 'age_50_59_ratio', 'age_60_69_ratio', 'age_70_79_ratio', 'age_80_plus_ratio']

In [45]:
from google.colab import files

files.download(
    "gangnam_disability_background_2025.csv"
)