In [1]:
from google.colab import files

uploaded = files.upload()

Saving 2025.7월_29개 통신정보.xlsx to 2025.7월_29개 통신정보.xlsx
Saving 2025.8월_29개 통신정보.xlsx to 2025.8월_29개 통신정보.xlsx
Saving 2025.9월_29개 통신정보.xlsx to 2025.9월_29개 통신정보.xlsx
Saving 2025.10월_29개 통신정보.xlsx to 2025.10월_29개 통신정보.xlsx
Saving 2025.11월_29개 통신정보.xlsx to 2025.11월_29개 통신정보.xlsx
Saving 2025.12월_29개 통신정보.xlsx to 2025.12월_29개 통신정보.xlsx

In [2]:
import os

for filename in sorted(os.listdir("/content")):
    if filename.endswith(".xlsx"):
        print(filename)

2025.10월_29개 통신정보.xlsx
2025.11월_29개 통신정보.xlsx
2025.12월_29개 통신정보.xlsx
2025.7월_29개 통신정보.xlsx
2025.8월_29개 통신정보.xlsx
2025.9월_29개 통신정보.xlsx

In [3]:
import pandas as pd

files = {
    "2025-07": "2025.7월_29개 통신정보.xlsx",
    "2025-08": "2025.8월_29개 통신정보.xlsx",
    "2025-09": "2025.9월_29개 통신정보.xlsx",
    "2025-10": "2025.10월_29개 통신정보.xlsx",
    "2025-11": "2025.11월_29개 통신정보.xlsx",
    "2025-12": "2025.12월_29개 통신정보.xlsx"
}

dfs = {}

for month, filename in files.items():
    df = pd.read_excel(filename)
    dfs[month] = df

    print(f"\n[{month}]")
    print("shape:", df.shape)
    print("컬럼 수:", len(df.columns))

print("\n===== 컬럼 구조 비교 =====")
base_columns = list(dfs["2025-07"].columns)

for month, df in dfs.items():
    print(
        month,
        "7월과 컬럼 동일:",
        list(df.columns) == base_columns
    )

print("\n===== 7월 컬럼 목록 =====")
for i, col in enumerate(base_columns, start=1):
    print(i, col)

[2025-07]
shape: (10176, 143)
컬럼 수: 143

[2025-08]
shape: (10176, 143)
컬럼 수: 143

[2025-09]
shape: (10176, 143)
컬럼 수: 143

[2025-10]
shape: (10176, 143)
컬럼 수: 143

[2025-11]
shape: (10176, 143)
컬럼 수: 143

[2025-12]
shape: (10176, 143)
컬럼 수: 143

===== 컬럼 구조 비교 =====
2025-07 7월과 컬럼 동일: True
2025-08 7월과 컬럼 동일: True
2025-09 7월과 컬럼 동일: True
2025-10 7월과 컬럼 동일: True
2025-11 7월과 컬럼 동일: True
2025-12 7월과 컬럼 동일: True

===== 7월 컬럼 목록 =====
1 행정동코드
2 자치구
3 행정동
4 성별
5 연령대
6 총인구수
7 1인가구수
8 야간상주지 변경 미추정 인구 수
9 야간상주지 변경횟수 평균
10 야간상주지 변경횟수: 4분위수, 25%
11 야간상주지 변경횟수: 4분위수, 50%
12 야간상주지 변경횟수: 4분위수, 75%
13 주간상주지 변경 미추정 인구수
14 주간상주지 변경횟수 평균
15 주간상주지 변경횟수: 4분위수, 25%
16 주간상주지 변경횟수: 4분위수, 50%
17 주간상주지 변경횟수: 4분위수, 75%
18 출근 소요시간 미추정 인구수
19 평균 출근 소요시간 평균
20 평균 출근 소요시간: 4분위수, 25%
21 평균 출근 소요시간: 4분위수, 50%
22 평균 출근 소요시간: 4분위수, 75%
23 근무시간 미추정 인구수
24 평균 근무시간 평균
25 평균 근무시간: 4분위수, 25%
26 평균 근무시간: 4분위수, 50%
27 평균 근무시간: 4분위수, 75%
28 소액결재 비사용 인구수
29 소액결재 사용횟수 평균
30 소액결재 사용횟수: 4분위수, 25%
31 소액결재 사용횟수: 4분위수, 50%
32 소액결재 사용횟수: 4분위수, 75%
33 소액결재 사용 금액 없는 인구수
34 소액결재 사용금액 평균
35 소액결재 사용금액: 4분위수, 25%
36 소액결재 사용금액: 4분위수, 50%
37 소액결재 사용금액: 4분위수, 75%
38 최근 3개월 내 요금 연체 비율
39 카카오톡 비사용 인구수
40 SNS 사용횟수
41 SNS 사용횟수: 4분위수, 25%
42 SNS 사용횟수: 4분위수, 50%
43 SNS 사용횟수: 4분위수, 75%
44 평균 통화량
45 평균 통화량: 4분위수, 25%
46 평균 통화량: 4분위수, 50%
47 평균 통화량: 4분위수, 75%
48 평균 문자량
49 평균 문자량: 4분위수, 25%
50 평균 문자량: 4분위수, 50%
51 평균 문자량: 4분위수, 75%
52 평균 통화대상자 수
53 평균 통화대상자 수: 4분위수, 25%
54 평균 통화대상자 수: 4분위수, 50%
55 평균 통화대상자 수: 4분위수, 75%
56 평균 문자대상자 수
57 평균 문자대상자 수: 4분위수, 25%
58 평균 문자대상자 수: 4분위수, 50%
59 평균 문자대상자 수: 4분위수, 75%
60 데이터 사용량
61 데이터 사용량: 4분위수, 25%
62 데이터 사용량: 4분위수, 50%
63 데이터 사용량: 4분위수, 75%
64 평일 총 이동 횟수 미추정 인구수
65 평일 총 이동 횟수
66 평일 총 이동 횟수: 4분위수, 25%
67 평일 총 이동 횟수: 4분위수, 50%
68 평일 총 이동 횟수: 4분위수, 75%
69 휴일 이동 미추정 인구수
70 휴일 총 이동 횟수 평균
71 휴일 총 이동 횟수: 4분위수, 25%
72 휴일 총 이동 횟수: 4분위수, 50%
73 휴일 총 이동 횟수: 4분위수, 75%
74 집 추정 위치 평일 총 체류시간 미추정 인구수
75 집 추정 위치 평일 총 체류시간
76 집 추정 위치 평일 총 체류시간: 4분위수, 25%
77 집 추정 위치 평일 총 체류시간: 4분위수, 50%
78 집 추정 위치 평일 총 체류시간: 4분위수, 75%
79 집 추정 위치 휴일 총 체류시간 미추정 인구수
80 집 추정 위치 휴일 총 체류시간
81 집 추정 위치 휴일 총 체류시간: 4분위수, 25%
82 집 추정 위치 휴일 총 체류시간: 4분위수, 50%
83 집 추정 위치 휴일 총 체류시간: 4분위수, 75%
84 평일 총 이동 거리 미추정 인구수
85 평일 총 이동 거리 합계
86 평일 총 이동 거리 합계: 4분위수, 25%
87 평일 총 이동 거리 합계: 4분위수, 50%
88 평일 총 이동 거리 합계: 4분위수, 75%
89 휴일 총 이동 거리 미추정 인구수
90 휴일 총 이동 거리 합계
91 휴일 총 이동 거리 합계: 4분위수, 25%
92 휴일 총 이동 거리 합계: 4분위수, 50%
93 휴일 총 이동 거리 합계: 4분위수, 75%
94 지하철 이용 미추정 인구수
95 지하철이동일수 합계
96 지하철이동일수 합계: 4분위수, 25%
97 지하철이동일수 합계: 4분위수, 50%
98 지하철이동일수 합계: 4분위수, 75%
99 게임 서비스 사용 미추정 인구수
100 게임 서비스 사용일수
101 게임 서비스 사용일수: 4분위수, 25%
102 게임 서비스 사용일수: 4분위수, 50%
103 게임 서비스 사용일수: 4분위수, 75%
104 금융 서비스 사용 미추정 인구수
105 금융 서비스 사용일수
106 금융 서비스 사용일수: 4분위수, 25%
107 금융 서비스 사용일수: 4분위수, 50%
108 금융 서비스 사용일수: 4분위수, 75%
109 쇼핑 서비스 사용 미추정 인구수
110 쇼핑 서비스 사용일수
111 쇼핑 서비스 사용일수: 4분위수, 25%
112 쇼핑 서비스 사용일수: 4분위수, 50%
113 쇼핑 서비스 사용일수: 4분위수, 75%
114 동영상/방송 서비스 사용 미추정 인구수
115 동영상/방송 서비스 사용일수
116 동영상/방송 서비스 사용일수: 4분위수, 25%
117 동영상/방송 서비스 사용일수: 4분위수, 50%
118 동영상/방송 서비스 사용일수: 4분위수, 75%
119 유튜브 사용 미추정 인구수
120 유튜브 사용일수
121 유튜브 사용일수: 4분위수, 25%
122 유튜브 사용일수: 4분위수, 50%
123 유튜브 사용일수: 4분위수, 75%
124 넷플릭스 사용 미추정 인구수
125 넷플릭스 사용일수
126 넷플릭스 사용일수: 4분위수, 25%
127 넷플릭스 사용일수: 4분위수, 50%
128 넷플릭스 사용일수: 4분위수, 75%
129 배달 서비스 사용 미추정 인구수
130 배달 서비스 사용일수
131 배달 서비스 사용일수: 4분위수, 25%
132 배달 서비스 사용일수: 4분위수, 50%
133 배달 서비스 사용일수: 4분위수, 75%
134 배달_브랜드 서비스 사용 미추정 인구수
135 배달_브랜드 서비스 사용일수
136 배달_브랜드 서비스 사용일수: 4분위수, 25%
137 배달_브랜드 서비스 사용일수: 4분위수, 50%
138 배달_브랜드 서비스 사용일수: 4분위수, 75%
139 배달_식재료 서비스 사용 미추정 인구수
140 배달_식재료 서비스 사용일수
141 배달_식재료 서비스 사용일수: 4분위수, 25%
142 배달_식재료 서비스 사용일수: 4분위수, 50%
143 배달_식재료 서비스 사용일수: 4분위수, 75%

In [4]:
telecom_list = []

for month, df in dfs.items():
    temp = df.copy()
    temp["기준연월"] = month
    telecom_list.append(temp)

telecom_all = pd.concat(
    telecom_list,
    ignore_index=True
)

print("통합 shape:", telecom_all.shape)

print("\n월별 행 수:")
print(
    telecom_all["기준연월"]
    .value_counts()
    .sort_index()
)

print("\n앞부분 확인:")
display(telecom_all.head())

통합 shape: (61056, 144)

월별 행 수:
기준연월
2025-07    10176
2025-08    10176
2025-09    10176
2025-10    10176
2025-11    10176
2025-12    10176
Name: count, dtype: int64

앞부분 확인:

,행정동코드,자치구,행정동,성별,연령대,총인구수,1인가구수,야간상주지 변경 미추정 인구 수,야간상주지 변경횟수 평균,"야간상주지 변경횟수: 4분위수, 25%",...,배달_브랜드 서비스 사용일수,"배달_브랜드 서비스 사용일수: 4분위수, 25%","배달_브랜드 서비스 사용일수: 4분위수, 50%","배달_브랜드 서비스 사용일수: 4분위수, 75%",배달_식재료 서비스 사용 미추정 인구수,배달_식재료 서비스 사용일수,"배달_식재료 서비스 사용일수: 4분위수, 25%","배달_식재료 서비스 사용일수: 4분위수, 50%","배달_식재료 서비스 사용일수: 4분위수, 75%",기준연월
0,1101053,종로구,사직동,1,20,173.0,52.36,0,8.10,9,...,2.98,1.67,1.67,5.00,170.53,1.67,1.67,1.67,1.67,2025-07
1,1101053,종로구,사직동,1,25,300.0,95.41,0,8.05,8,...,2.93,1.67,1.67,3.33,297.52,1.67,1.67,1.67,1.67,2025-07
2,1101053,종로구,사직동,1,30,366.0,117.40,0,8.23,8,...,2.63,1.67,1.67,3.33,362.00,1.67,1.67,1.67,1.67,2025-07
3,1101053,종로구,사직동,1,35,376.0,109.03,0,8.14,8,...,2.81,1.67,1.67,3.33,370.00,1.67,1.67,1.67,1.67,2025-07
4,1101053,종로구,사직동,1,40,418.0,96.50,0,8.02,8,...,2.46,1.67,1.67,3.33,410.00,1.67,1.67,1.67,1.67,2025-07

In [5]:
# 기본 분류 변수 확인
basic_cols = ["행정동코드", "자치구", "행정동명", "성별", "연령대"]

print("===== 기본 컬럼 존재 여부 =====")
for col in basic_cols:
    print(col, ":", col in telecom_all.columns)

print("\n===== 기본 구조 =====")
print("행정동 수:", telecom_all["행정동코드"].nunique())
print("자치구 수:", telecom_all["자치구"].nunique())
print("성별:", sorted(telecom_all["성별"].dropna().unique()))
print("연령대:", sorted(telecom_all["연령대"].dropna().unique()))

# 월 × 행정동 × 성별 × 연령대 중복 확인
key_cols = ["기준연월", "행정동코드", "성별", "연령대"]

duplicate_count = telecom_all.duplicated(
    subset=key_cols
).sum()

print("\n===== 중복 검사 =====")
print("중복 key 수:", duplicate_count)

# 각 월의 행정동 수
print("\n===== 월별 행정동 수 =====")
print(
    telecom_all.groupby("기준연월")["행정동코드"]
    .nunique()
)

# 행정동별 월별 관측치 수가 동일한지 확인
panel_check = (
    telecom_all
    .groupby(["기준연월", "행정동코드"])
    .size()
)

print("\n===== 행정동 × 월 관측치 수 =====")
print(panel_check.describe())
print("고유한 관측치 수:", sorted(panel_check.unique()))

===== 기본 컬럼 존재 여부 =====
행정동코드 : True
자치구 : True
행정동명 : False
성별 : True
연령대 : True

===== 기본 구조 =====
행정동 수: 424
자치구 수: 25
성별: [np.int64(1), np.int64(2)]
연령대: [np.int64(20), np.int64(25), np.int64(30), np.int64(35), np.int64(40), np.int64(45), np.int64(50), np.int64(55), np.int64(60), np.int64(65), np.int64(70), np.int64(75)]

===== 중복 검사 =====
중복 key 수: 0

===== 월별 행정동 수 =====
기준연월
2025-07    424
2025-08    424
2025-09    424
2025-10    424
2025-11    424
2025-12    424
Name: 행정동코드, dtype: int64

===== 행정동 × 월 관측치 수 =====
count    2544.0
mean       24.0
std         0.0
min        24.0
25%        24.0
50%        24.0
75%        24.0
max        24.0
dtype: float64
고유한 관측치 수: [np.int64(24)]

In [6]:
print("===== 전체 컬럼 목록 =====")

for i, col in enumerate(telecom_all.columns, start=1):
    print(f"{i:3d}. {col}")

===== 전체 컬럼 목록 =====
  1. 행정동코드
  2. 자치구
  3. 행정동
  4. 성별
  5. 연령대
  6. 총인구수
  7. 1인가구수
  8. 야간상주지 변경 미추정 인구 수
  9. 야간상주지 변경횟수 평균
 10. 야간상주지 변경횟수: 4분위수, 25%
 11. 야간상주지 변경횟수: 4분위수, 50%
 12. 야간상주지 변경횟수: 4분위수, 75%
 13. 주간상주지 변경 미추정 인구수
 14. 주간상주지 변경횟수 평균
 15. 주간상주지 변경횟수: 4분위수, 25%
 16. 주간상주지 변경횟수: 4분위수, 50%
 17. 주간상주지 변경횟수: 4분위수, 75%
 18. 출근 소요시간 미추정 인구수
 19. 평균 출근 소요시간 평균
 20. 평균 출근 소요시간: 4분위수, 25%
 21. 평균 출근 소요시간: 4분위수, 50%
 22. 평균 출근 소요시간: 4분위수, 75%
 23. 근무시간 미추정 인구수
 24. 평균 근무시간 평균
 25. 평균 근무시간: 4분위수, 25%
 26. 평균 근무시간: 4분위수, 50%
 27. 평균 근무시간: 4분위수, 75%
 28. 소액결재 비사용 인구수
 29. 소액결재 사용횟수 평균
 30. 소액결재 사용횟수: 4분위수, 25%
 31. 소액결재 사용횟수: 4분위수, 50%
 32. 소액결재 사용횟수: 4분위수, 75%
 33. 소액결재 사용 금액 없는 인구수
 34. 소액결재 사용금액 평균
 35. 소액결재 사용금액: 4분위수, 25%
 36. 소액결재 사용금액: 4분위수, 50%
 37. 소액결재 사용금액: 4분위수, 75%
 38. 최근 3개월 내 요금 연체 비율
 39. 카카오톡 비사용 인구수
 40. SNS 사용횟수
 41. SNS 사용횟수: 4분위수, 25%
 42. SNS 사용횟수: 4분위수, 50%
 43. SNS 사용횟수: 4분위수, 75%
 44. 평균 통화량
 45. 평균 통화량: 4분위수, 25%
 46. 평균 통화량: 4분위수, 50%
 47. 평균 통화량: 4분위수, 75%
 48. 평균 문자량
 49. 평균 문자량: 4분위수, 25%
 50. 평균 문자량: 4분위수, 50%
 51. 평균 문자량: 4분위수, 75%
 52. 평균 통화대상자 수
 53. 평균 통화대상자 수: 4분위수, 25%
 54. 평균 통화대상자 수: 4분위수, 50%
 55. 평균 통화대상자 수: 4분위수, 75%
 56. 평균 문자대상자 수
 57. 평균 문자대상자 수: 4분위수, 25%
 58. 평균 문자대상자 수: 4분위수, 50%
 59. 평균 문자대상자 수: 4분위수, 75%
 60. 데이터 사용량
 61. 데이터 사용량: 4분위수, 25%
 62. 데이터 사용량: 4분위수, 50%
 63. 데이터 사용량: 4분위수, 75%
 64. 평일 총 이동 횟수 미추정 인구수
 65. 평일 총 이동 횟수
 66. 평일 총 이동 횟수: 4분위수, 25%
 67. 평일 총 이동 횟수: 4분위수, 50%
 68. 평일 총 이동 횟수: 4분위수, 75%
 69. 휴일 이동 미추정 인구수
 70. 휴일 총 이동 횟수 평균
 71. 휴일 총 이동 횟수: 4분위수, 25%
 72. 휴일 총 이동 횟수: 4분위수, 50%
 73. 휴일 총 이동 횟수: 4분위수, 75%
 74. 집 추정 위치 평일 총 체류시간 미추정 인구수
 75. 집 추정 위치 평일 총 체류시간
 76. 집 추정 위치 평일 총 체류시간: 4분위수, 25%
 77. 집 추정 위치 평일 총 체류시간: 4분위수, 50%
 78. 집 추정 위치 평일 총 체류시간: 4분위수, 75%
 79. 집 추정 위치 휴일 총 체류시간 미추정 인구수
 80. 집 추정 위치 휴일 총 체류시간
 81. 집 추정 위치 휴일 총 체류시간: 4분위수, 25%
 82. 집 추정 위치 휴일 총 체류시간: 4분위수, 50%
 83. 집 추정 위치 휴일 총 체류시간: 4분위수, 75%
 84. 평일 총 이동 거리 미추정 인구수
 85. 평일 총 이동 거리 합계
 86. 평일 총 이동 거리 합계: 4분위수, 25%
 87. 평일 총 이동 거리 합계: 4분위수, 50%
 88. 평일 총 이동 거리 합계: 4분위수, 75%
 89. 휴일 총 이동 거리 미추정 인구수
 90. 휴일 총 이동 거리 합계
 91. 휴일 총 이동 거리 합계: 4분위수, 25%
 92. 휴일 총 이동 거리 합계: 4분위수, 50%
 93. 휴일 총 이동 거리 합계: 4분위수, 75%
 94. 지하철 이용 미추정 인구수
 95. 지하철이동일수 합계
 96. 지하철이동일수 합계: 4분위수, 25%
 97. 지하철이동일수 합계: 4분위수, 50%
 98. 지하철이동일수 합계: 4분위수, 75%
 99. 게임 서비스 사용 미추정 인구수
100. 게임 서비스 사용일수
101. 게임 서비스 사용일수: 4분위수, 25%
102. 게임 서비스 사용일수: 4분위수, 50%
103. 게임 서비스 사용일수: 4분위수, 75%
104. 금융 서비스 사용 미추정 인구수
105. 금융 서비스 사용일수
106. 금융 서비스 사용일수: 4분위수, 25%
107. 금융 서비스 사용일수: 4분위수, 50%
108. 금융 서비스 사용일수: 4분위수, 75%
109. 쇼핑 서비스 사용 미추정 인구수
110. 쇼핑 서비스 사용일수
111. 쇼핑 서비스 사용일수: 4분위수, 25%
112. 쇼핑 서비스 사용일수: 4분위수, 50%
113. 쇼핑 서비스 사용일수: 4분위수, 75%
114. 동영상/방송 서비스 사용 미추정 인구수
115. 동영상/방송 서비스 사용일수
116. 동영상/방송 서비스 사용일수: 4분위수, 25%
117. 동영상/방송 서비스 사용일수: 4분위수, 50%
118. 동영상/방송 서비스 사용일수: 4분위수, 75%
119. 유튜브 사용 미추정 인구수
120. 유튜브 사용일수
121. 유튜브 사용일수: 4분위수, 25%
122. 유튜브 사용일수: 4분위수, 50%
123. 유튜브 사용일수: 4분위수, 75%
124. 넷플릭스 사용 미추정 인구수
125. 넷플릭스 사용일수
126. 넷플릭스 사용일수: 4분위수, 25%
127. 넷플릭스 사용일수: 4분위수, 50%
128. 넷플릭스 사용일수: 4분위수, 75%
129. 배달 서비스 사용 미추정 인구수
130. 배달 서비스 사용일수
131. 배달 서비스 사용일수: 4분위수, 25%
132. 배달 서비스 사용일수: 4분위수, 50%
133. 배달 서비스 사용일수: 4분위수, 75%
134. 배달_브랜드 서비스 사용 미추정 인구수
135. 배달_브랜드 서비스 사용일수
136. 배달_브랜드 서비스 사용일수: 4분위수, 25%
137. 배달_브랜드 서비스 사용일수: 4분위수, 50%
138. 배달_브랜드 서비스 사용일수: 4분위수, 75%
139. 배달_식재료 서비스 사용 미추정 인구수
140. 배달_식재료 서비스 사용일수
141. 배달_식재료 서비스 사용일수: 4분위수, 25%
142. 배달_식재료 서비스 사용일수: 4분위수, 50%
143. 배달_식재료 서비스 사용일수: 4분위수, 75%
144. 기준연월

In [7]:
gangnam_telecom = telecom_all[
    telecom_all["자치구"] == "강남구"
].copy()

print("강남구 shape:", gangnam_telecom.shape)

print("\n행정동 수:", gangnam_telecom["행정동코드"].nunique())

print("\n행정동 목록:")
print(
    gangnam_telecom[
        ["행정동코드", "행정동"]
    ]
    .drop_duplicates()
    .sort_values("행정동코드")
    .to_string(index=False)
)

print("\n월별 행 수:")
print(
    gangnam_telecom
    .groupby("기준연월")
    .size()
)

print("\n중복 key 수:")
print(
    gangnam_telecom.duplicated(
        subset=["기준연월", "행정동코드", "성별", "연령대"]
    ).sum()
)

강남구 shape: (3168, 144)

행정동 수: 22

행정동 목록:
  행정동코드  행정동
1123051  신사동
1123052 논현1동
1123053 논현2동
1123058 삼성1동
1123059 삼성2동
1123060 대치1동
1123063 대치4동
1123064 역삼1동
1123065 역삼2동
1123066 도곡1동
1123067 도곡2동
1123068 개포1동
1123071 개포4동
1123072 일원본동
1123073 일원1동
1123074 일원2동
1123075  수서동
1123076  세곡동
1123077 압구정동
1123078  청담동
1123079 대치2동
1123080 개포2동

월별 행 수:
기준연월
2025-07    528
2025-08    528
2025-09    528
2025-10    528
2025-11    528
2025-12    528
dtype: int64

중복 key 수:
0

In [8]:
# 1. 행정동명 현행화
gangnam_telecom.loc[
    gangnam_telecom["행정동코드"] == 1123074,
    "행정동"
] = "개포3동"

print("1123074 명칭:",
      gangnam_telecom.loc[
          gangnam_telecom["행정동코드"] == 1123074,
          "행정동"
      ].unique())


# 2. 실제 NaN 확인
missing = gangnam_telecom.isna().sum()
missing = missing[missing > 0].sort_values(ascending=False)

print("\n===== NaN이 존재하는 컬럼 =====")
print("컬럼 수:", len(missing))
print(missing)


# 3. 문자열 '-' 마스킹 확인
mask_counts = {}

for col in gangnam_telecom.columns:
    if gangnam_telecom[col].dtype == "object":
        count = (
            gangnam_telecom[col]
            .astype(str)
            .str.strip()
            .eq("-")
            .sum()
        )
        if count > 0:
            mask_counts[col] = count

print("\n===== '-'가 존재하는 컬럼 =====")
print("컬럼 수:", len(mask_counts))

for col, count in mask_counts.items():
    print(f"{col}: {count}")

1123074 명칭: ['개포3동']

===== NaN이 존재하는 컬럼 =====
컬럼 수: 0
Series([], dtype: int64)

===== '-'가 존재하는 컬럼 =====
컬럼 수: 0

In [9]:
# 식별/분류 컬럼
id_cols = [
    "행정동코드",
    "자치구",
    "행정동",
    "성별",
    "연령대",
    "기준연월"
]

# 분석 대상 컬럼
value_cols = [
    col for col in gangnam_telecom.columns
    if col not in id_cols
]

print("전체 컬럼 수:", len(gangnam_telecom.columns))
print("식별/분류 컬럼 수:", len(id_cols))
print("분석 대상 컬럼 수:", len(value_cols))

print("\n===== 분석 대상 컬럼 dtype =====")
print(
    gangnam_telecom[value_cols]
    .dtypes
    .value_counts()
)

# 숫자가 아닌 분석 컬럼 확인
non_numeric_cols = [
    col for col in value_cols
    if not pd.api.types.is_numeric_dtype(gangnam_telecom[col])
]

print("\n숫자가 아닌 분석 컬럼 수:", len(non_numeric_cols))

if non_numeric_cols:
    for col in non_numeric_cols:
        print(col, gangnam_telecom[col].dtype)
else:
    print("모든 분석 대상 컬럼이 numeric입니다.")

전체 컬럼 수: 144
식별/분류 컬럼 수: 6
분석 대상 컬럼 수: 138

===== 분석 대상 컬럼 dtype =====
float64    125
int64       13
Name: count, dtype: int64

숫자가 아닌 분석 컬럼 수: 0
모든 분석 대상 컬럼이 numeric입니다.

In [10]:
# 분위수 컬럼
q25_cols = [c for c in value_cols if "25%" in c]
q50_cols = [c for c in value_cols if "50%" in c]
q75_cols = [c for c in value_cols if "75%" in c]

# 분위수를 제외한 컬럼
base_value_cols = [
    c for c in value_cols
    if c not in q25_cols + q50_cols + q75_cols
]

print("===== 통신정보 컬럼 구조 =====")
print("분석 대상 전체:", len(value_cols))
print("25% 분위수:", len(q25_cols))
print("50% 분위수:", len(q50_cols))
print("75% 분위수:", len(q75_cols))
print("분위수 이외:", len(base_value_cols))

print("\n===== 분위수 이외 컬럼 =====")
for i, col in enumerate(base_value_cols, 1):
    print(f"{i:2d}. {col}")

===== 통신정보 컬럼 구조 =====
분석 대상 전체: 138
25% 분위수: 28
50% 분위수: 28
75% 분위수: 28
분위수 이외: 54

===== 분위수 이외 컬럼 =====
 1. 총인구수
 2. 1인가구수
 3. 야간상주지 변경 미추정 인구 수
 4. 야간상주지 변경횟수 평균
 5. 주간상주지 변경 미추정 인구수
 6. 주간상주지 변경횟수 평균
 7. 출근 소요시간 미추정 인구수
 8. 평균 출근 소요시간 평균
 9. 근무시간 미추정 인구수
10. 평균 근무시간 평균
11. 소액결재 비사용 인구수
12. 소액결재 사용횟수 평균
13. 소액결재 사용 금액 없는 인구수
14. 소액결재 사용금액 평균
15. 최근 3개월 내 요금 연체 비율
16. 카카오톡 비사용 인구수
17. SNS 사용횟수
18. 평균 통화량
19. 평균 문자량
20. 평균 통화대상자 수
21. 평균 문자대상자 수
22. 데이터 사용량
23. 평일 총 이동 횟수 미추정 인구수
24. 평일 총 이동 횟수
25. 휴일 이동 미추정 인구수
26. 휴일 총 이동 횟수 평균
27. 집 추정 위치 평일 총 체류시간 미추정 인구수
28. 집 추정 위치 평일 총 체류시간
29. 집 추정 위치 휴일 총 체류시간 미추정 인구수
30. 집 추정 위치 휴일 총 체류시간
31. 평일 총 이동 거리 미추정 인구수
32. 평일 총 이동 거리 합계
33. 휴일 총 이동 거리 미추정 인구수
34. 휴일 총 이동 거리 합계
35. 지하철 이용 미추정 인구수
36. 지하철이동일수 합계
37. 게임 서비스 사용 미추정 인구수
38. 게임 서비스 사용일수
39. 금융 서비스 사용 미추정 인구수
40. 금융 서비스 사용일수
41. 쇼핑 서비스 사용 미추정 인구수
42. 쇼핑 서비스 사용일수
43. 동영상/방송 서비스 사용 미추정 인구수
44. 동영상/방송 서비스 사용일수
45. 유튜브 사용 미추정 인구수
46. 유튜브 사용일수
47. 넷플릭스 사용 미추정 인구수
48. 넷플릭스 사용일수
49. 배달 서비스 사용 미추정 인구수
50. 배달 서비스 사용일수
51. 배달_브랜드 서비스 사용 미추정 인구수
52. 배달_브랜드 서비스 사용일수
53. 배달_식재료 서비스 사용 미추정 인구수
54. 배달_식재료 서비스 사용일수

In [11]:
telecom_variables = [
    "야간상주지 변경횟수 평균",
    "주간상주지 변경횟수 평균",
    "평균 출근 소요시간 평균",
    "평균 근무시간 평균",
    "소액결재 사용횟수 평균",
    "소액결재 사용금액 평균",
    "최근 3개월 내 요금 연체 비율",
    "SNS 사용횟수",
    "평균 통화량",
    "평균 문자량",
    "평균 통화대상자 수",
    "평균 문자대상자 수",
    "데이터 사용량",
    "평일 총 이동 횟수",
    "휴일 총 이동 횟수 평균",
    "집 추정 위치 평일 총 체류시간",
    "집 추정 위치 휴일 총 체류시간",
    "평일 총 이동 거리 합계",
    "휴일 총 이동 거리 합계",
    "지하철이동일수 합계",
    "게임 서비스 사용일수",
    "금융 서비스 사용일수",
    "쇼핑 서비스 사용일수",
    "동영상/방송 서비스 사용일수",
    "유튜브 사용일수",
    "넷플릭스 사용일수",
    "배달 서비스 사용일수",
    "배달_브랜드 서비스 사용일수",
    "배달_식재료 서비스 사용일수"
]

print("통신정보 변수 수:", len(telecom_variables))

print("\n===== 29개 통신정보 =====")
for i, col in enumerate(telecom_variables, 1):
    print(f"{i:2d}. {col}")

print("\n모든 변수가 데이터에 존재:",
      all(col in gangnam_telecom.columns for col in telecom_variables))

통신정보 변수 수: 29

===== 29개 통신정보 =====
 1. 야간상주지 변경횟수 평균
 2. 주간상주지 변경횟수 평균
 3. 평균 출근 소요시간 평균
 4. 평균 근무시간 평균
 5. 소액결재 사용횟수 평균
 6. 소액결재 사용금액 평균
 7. 최근 3개월 내 요금 연체 비율
 8. SNS 사용횟수
 9. 평균 통화량
10. 평균 문자량
11. 평균 통화대상자 수
12. 평균 문자대상자 수
13. 데이터 사용량
14. 평일 총 이동 횟수
15. 휴일 총 이동 횟수 평균
16. 집 추정 위치 평일 총 체류시간
17. 집 추정 위치 휴일 총 체류시간
18. 평일 총 이동 거리 합계
19. 휴일 총 이동 거리 합계
20. 지하철이동일수 합계
21. 게임 서비스 사용일수
22. 금융 서비스 사용일수
23. 쇼핑 서비스 사용일수
24. 동영상/방송 서비스 사용일수
25. 유튜브 사용일수
26. 넷플릭스 사용일수
27. 배달 서비스 사용일수
28. 배달_브랜드 서비스 사용일수
29. 배달_식재료 서비스 사용일수

모든 변수가 데이터에 존재: True

In [12]:
output_file = "gangnam_telecom_29info_2025_07_12.csv"

gangnam_telecom.to_csv(
    output_file,
    index=False,
    encoding="utf-8-sig"
)

print("저장 완료:", output_file)
print("shape:", gangnam_telecom.shape)

저장 완료: gangnam_telecom_29info_2025_07_12.csv
shape: (3168, 144)

In [13]:
from google.colab import files

files.download("gangnam_telecom_29info_2025_07_12.csv")

In [15]:
from google.colab import files

uploaded = files.upload()

Saving gangnam_interest_groups_2025_07_12.csv to gangnam_interest_groups_2025_07_12.csv

In [16]:
interest = pd.read_csv(
    "gangnam_interest_groups_2025_07_12.csv",
    encoding="utf-8-sig"
)

print("관심집단 shape:", interest.shape)
print("통신정보 shape:", gangnam_telecom.shape)

print("\n관심집단 컬럼:")
print(interest.columns.tolist())

관심집단 shape: (3168, 18)
통신정보 shape: (3168, 144)

관심집단 컬럼:
['행정동코드', '자치구', '행정동명', '성별', '연령대', '총인구', '1인가구수', '커뮤니케이션이 적은 집단', '평일 외출이 적은 집단', '휴일 외출이 적은 집단', '출근소요시간 및 근무시간이 많은 집단', '외출이 매우 적은 집단(전체)', '외출이 매우 많은 집단', '동영상서비스 이용이 많은 집단', '생활서비스 이용이 많은 집단', '재정상태에 대한 관심집단', '외출-커뮤니케이션이 모두 적은 집단(전체)', '기준연월']

In [17]:
key_cols = [
    "기준연월",
    "행정동코드",
    "성별",
    "연령대"
]

# 각 데이터 내부의 key 중복 확인
interest_dup = interest.duplicated(subset=key_cols).sum()
telecom_dup = gangnam_telecom.duplicated(subset=key_cols).sum()

print("===== 내부 중복 확인 =====")
print("관심집단 중복 key:", interest_dup)
print("통신정보 중복 key:", telecom_dup)


# key만 추출
interest_keys = interest[key_cols].drop_duplicates()
telecom_keys = gangnam_telecom[key_cols].drop_duplicates()

print("\n===== 고유 key 수 =====")
print("관심집단:", len(interest_keys))
print("통신정보:", len(telecom_keys))


# 두 데이터 key 비교
key_check = interest_keys.merge(
    telecom_keys,
    on=key_cols,
    how="outer",
    indicator=True
)

print("\n===== key 대응 결과 =====")
print(key_check["_merge"].value_counts())


# 서로 대응되지 않는 key 확인
unmatched = key_check[
    key_check["_merge"] != "both"
]

print("\n대응되지 않는 key 수:", len(unmatched))

if len(unmatched) > 0:
    display(unmatched.head(20))
else:
    print("모든 key가 정확히 1:1 대응합니다.")

===== 내부 중복 확인 =====
관심집단 중복 key: 0
통신정보 중복 key: 0

===== 고유 key 수 =====
관심집단: 3168
통신정보: 3168

===== key 대응 결과 =====
_merge
both          3168
left_only        0
right_only       0
Name: count, dtype: int64

대응되지 않는 key 수: 0
모든 key가 정확히 1:1 대응합니다.

In [18]:
# 비교에 필요한 컬럼만 추출
interest_check = interest[
    key_cols + ["행정동명", "총인구", "1인가구수"]
].copy()

telecom_check = gangnam_telecom[
    key_cols + ["행정동", "총인구수", "1인가구수"]
].copy()

# 이름 충돌 방지를 위해 변경
interest_check = interest_check.rename(columns={
    "행정동명": "행정동_interest",
    "총인구": "총인구_interest",
    "1인가구수": "1인가구수_interest"
})

telecom_check = telecom_check.rename(columns={
    "행정동": "행정동_telecom",
    "총인구수": "총인구_telecom",
    "1인가구수": "1인가구수_telecom"
})

# 1:1 병합
common_check = interest_check.merge(
    telecom_check,
    on=key_cols,
    how="inner",
    validate="one_to_one"
)

print("비교 행 수:", len(common_check))


# 행정동명 비교
dong_match = (
    common_check["행정동_interest"]
    == common_check["행정동_telecom"]
)

print("\n===== 행정동명 =====")
print("일치:", dong_match.sum())
print("불일치:", (~dong_match).sum())


# 총인구 비교
population_diff = (
    common_check["총인구_interest"]
    - common_check["총인구_telecom"]
).abs()

print("\n===== 총인구 =====")
print("완전 일치:", (population_diff == 0).sum())
print("불일치:", (population_diff != 0).sum())
print("최대 차이:", population_diff.max())


# 1인가구수 비교
single_diff = (
    common_check["1인가구수_interest"]
    - common_check["1인가구수_telecom"]
).abs()

print("\n===== 1인가구수 =====")
print("완전 일치:", (single_diff == 0).sum())
print("불일치:", (single_diff != 0).sum())
print("최대 차이:", single_diff.max())


# 불일치 사례가 있다면 확인
mismatch = common_check[
    (~dong_match)
    | (population_diff > 0)
    | (single_diff > 0)
]

print("\n===== 하나라도 불일치한 행 =====")
print("행 수:", len(mismatch))

if len(mismatch) > 0:
    display(mismatch.head(20))
else:
    print("공통 기본정보가 모두 정확히 일치합니다.")

비교 행 수: 3168

===== 행정동명 =====
일치: 3168
불일치: 0

===== 총인구 =====
완전 일치: 3168
불일치: 0
최대 차이: 0.0

===== 1인가구수 =====
완전 일치: 3168
불일치: 0
최대 차이: 0.0

===== 하나라도 불일치한 행 =====
행 수: 0
공통 기본정보가 모두 정확히 일치합니다.

In [19]:
# 통신정보에서 중복 기본정보 제외
telecom_exclude = [
    "자치구",
    "행정동",
    "총인구수",
    "1인가구수"
]

telecom_feature_cols = [
    col for col in gangnam_telecom.columns
    if col not in key_cols + telecom_exclude
]

print("추가할 통신정보 컬럼 수:", len(telecom_feature_cols))


# 관심집단 + 통신정보 병합
citizen_life = interest.merge(
    gangnam_telecom[
        key_cols + telecom_feature_cols
    ],
    on=key_cols,
    how="left",
    validate="one_to_one"
)

print("\n===== 병합 결과 =====")
print("shape:", citizen_life.shape)
print("행 수:", len(citizen_life))
print("컬럼 수:", len(citizen_life.columns))
print("전체 결측값 수:", citizen_life.isna().sum().sum())

print("\n===== 기본 구조 =====")
print("행정동 수:", citizen_life["행정동코드"].nunique())
print("월 수:", citizen_life["기준연월"].nunique())
print("성별:", sorted(citizen_life["성별"].unique()))
print("연령대:", sorted(citizen_life["연령대"].unique()))

print("\n===== key 중복 =====")
print(
    citizen_life.duplicated(
        subset=key_cols
    ).sum()
)

추가할 통신정보 컬럼 수: 136

===== 병합 결과 =====
shape: (3168, 154)
행 수: 3168
컬럼 수: 154
전체 결측값 수: 0

===== 기본 구조 =====
행정동 수: 22
월 수: 6
성별: [np.int64(1), np.int64(2)]
연령대: [np.int64(20), np.int64(25), np.int64(30), np.int64(35), np.int64(40), np.int64(45), np.int64(50), np.int64(55), np.int64(60), np.int64(65), np.int64(70), np.int64(75)]

===== key 중복 =====
0

In [20]:
output_file = "gangnam_citizen_life_detail_2025_07_12.csv"

citizen_life.to_csv(
    output_file,
    index=False,
    encoding="utf-8-sig"
)

print("저장 완료:", output_file)
print("shape:", citizen_life.shape)

저장 완료: gangnam_citizen_life_detail_2025_07_12.csv
shape: (3168, 154)

In [21]:
from google.colab import files

files.download("gangnam_citizen_life_detail_2025_07_12.csv")

In [22]:
interest_cols = [
    "커뮤니케이션이 적은 집단",
    "평일 외출이 적은 집단",
    "휴일 외출이 적은 집단",
    "출근소요시간 및 근무시간이 많은 집단",
    "외출이 매우 적은 집단(전체)",
    "외출이 매우 많은 집단",
    "동영상서비스 이용이 많은 집단",
    "생활서비스 이용이 많은 집단",
    "재정상태에 대한 관심집단",
    "외출-커뮤니케이션이 모두 적은 집단(전체)"
]

print("관심집단 컬럼 수:", len(interest_cols))

summary = []

for col in interest_cols:
    s = citizen_life[col]

    summary.append({
        "관심집단": col,
        "최솟값": s.min(),
        "중앙값": s.median(),
        "평균": s.mean(),
        "최댓값": s.max(),
        "0인 행": (s == 0).sum(),
        "0 비율(%)": (s == 0).mean() * 100
    })

interest_summary = pd.DataFrame(summary)

display(
    interest_summary.round(2)
)

관심집단 컬럼 수: 10

                      관심집단   최솟값    중앙값     평균     최댓값  0인 행  0 비율(%)
0            커뮤니케이션이 적은 집단  0.00   9.72  17.61  316.79   144     4.55
1             평일 외출이 적은 집단  0.00   6.36  15.06  286.66   145     4.58
2             휴일 외출이 적은 집단  0.00   7.62  14.14  183.19   166     5.24
3     출근소요시간 및 근무시간이 많은 집단  0.00   8.00  16.98  297.71   145     4.58
4         외출이 매우 적은 집단(전체)  0.00  15.87  19.71  127.26    72     2.27
5             외출이 매우 많은 집단  0.63  12.35  17.67  129.51     0     0.00
6         동영상서비스 이용이 많은 집단  0.00   8.76  17.35  299.13   144     4.55
7          생활서비스 이용이 많은 집단  0.00   8.06  19.53  297.81   147     4.64
8            재정상태에 대한 관심집단  0.00   7.64  15.21  247.01   144     4.55
9  외출-커뮤니케이션이 모두 적은 집단(전체)  0.00  16.87  19.44   99.94    18     0.57

In [23]:
print("===== 분모 상태 확인 =====")

print("총인구")
print("최솟값:", citizen_life["총인구"].min())
print("0인 행:", (citizen_life["총인구"] == 0).sum())
print("결측:", citizen_life["총인구"].isna().sum())

print("\n1인가구수")
print("최솟값:", citizen_life["1인가구수"].min())
print("0인 행:", (citizen_life["1인가구수"] == 0).sum())
print("결측:", citizen_life["1인가구수"].isna().sum())

print("\n===== 관심집단 값이 분모보다 큰 경우 =====")

single_interest_cols = [
    "커뮤니케이션이 적은 집단",
    "평일 외출이 적은 집단",
    "휴일 외출이 적은 집단",
    "출근소요시간 및 근무시간이 많은 집단",
    "동영상서비스 이용이 많은 집단",
    "생활서비스 이용이 많은 집단",
    "재정상태에 대한 관심집단"
]

for col in single_interest_cols:
    count = (citizen_life[col] > citizen_life["1인가구수"]).sum()
    print(f"{col}: {count}")

whole_interest_cols = [
    "외출이 매우 적은 집단(전체)",
    "외출-커뮤니케이션이 모두 적은 집단(전체)"
]

for col in whole_interest_cols:
    count = (citizen_life[col] > citizen_life["총인구"]).sum()
    print(f"{col}: {count}")

===== 분모 상태 확인 =====
총인구
최솟값: 216.0
0인 행: 0
결측: 0

1인가구수
최솟값: 10.01
0인 행: 0
결측: 0

===== 관심집단 값이 분모보다 큰 경우 =====
커뮤니케이션이 적은 집단: 0
평일 외출이 적은 집단: 0
휴일 외출이 적은 집단: 0
출근소요시간 및 근무시간이 많은 집단: 0
동영상서비스 이용이 많은 집단: 0
생활서비스 이용이 많은 집단: 0
재정상태에 대한 관심집단: 0
외출이 매우 적은 집단(전체): 0
외출-커뮤니케이션이 모두 적은 집단(전체): 0

In [24]:
# 1인가구 기반 관심집단
single_interest_map = {
    "커뮤니케이션이 적은 집단": "low_comm_ratio",
    "평일 외출이 적은 집단": "low_weekday_outing_ratio",
    "휴일 외출이 적은 집단": "low_holiday_outing_ratio",
    "출근소요시간 및 근무시간이 많은 집단": "high_worktime_ratio",
    "동영상서비스 이용이 많은 집단": "high_video_ratio",
    "생활서비스 이용이 많은 집단": "high_life_service_ratio",
    "재정상태에 대한 관심집단": "financial_interest_ratio"
}

for source_col, feature_col in single_interest_map.items():
    citizen_life[feature_col] = (
        citizen_life[source_col]
        / citizen_life["1인가구수"]
        * 100
    )


# 전체 인구 기반 관심집단
whole_interest_map = {
    "외출이 매우 적은 집단(전체)": "very_low_outing_ratio",
    "외출-커뮤니케이션이 모두 적은 집단(전체)": "very_low_outing_comm_ratio"
}

for source_col, feature_col in whole_interest_map.items():
    citizen_life[feature_col] = (
        citizen_life[source_col]
        / citizen_life["총인구"]
        * 100
    )


# 생성된 Feature 확인
ratio_cols = (
    list(single_interest_map.values())
    + list(whole_interest_map.values())
)

print("생성된 비율 Feature 수:", len(ratio_cols))

ratio_summary = citizen_life[ratio_cols].agg(
    ["min", "median", "mean", "max"]
).T

display(ratio_summary.round(2))

print(
    "\n100% 초과 값 수:",
    (citizen_life[ratio_cols] > 100).sum().sum()
)

print(
    "결측값 수:",
    citizen_life[ratio_cols].isna().sum().sum()
)

생성된 비율 Feature 수: 9

                            min  median  mean    max
low_comm_ratio              0.0    9.49  9.87  26.65
low_weekday_outing_ratio    0.0    7.18  7.30  21.12
low_holiday_outing_ratio    0.0    7.01  7.71  32.26
high_worktime_ratio         0.0    8.13  8.34  26.52
high_video_ratio            0.0    8.71  9.04  32.17
high_life_service_ratio     0.0    8.12  8.60  37.29
financial_interest_ratio    0.0    7.62  7.75  23.79
very_low_outing_ratio       0.0    1.85  2.04   7.77
very_low_outing_comm_ratio  0.0    1.92  2.09  14.79

100% 초과 값 수: 0
결측값 수: 0

In [25]:
monthly_interest = (
    citizen_life
    .groupby("기준연월")[ratio_cols]
    .mean()
    .round(2)
)

print("===== 월별 관심집단 비율 평균 =====")
display(monthly_interest)

print("\n===== 월별 변화 범위 =====")

monthly_range = pd.DataFrame({
    "min": monthly_interest.min(),
    "max": monthly_interest.max()
})

monthly_range["range"] = (
    monthly_range["max"]
    - monthly_range["min"]
)

display(
    monthly_range
    .sort_values("range", ascending=False)
    .round(2)
)

===== 월별 관심집단 비율 평균 =====

,low_comm_ratio,low_weekday_outing_ratio,low_holiday_outing_ratio,high_worktime_ratio,high_video_ratio,high_life_service_ratio,financial_interest_ratio,very_low_outing_ratio,very_low_outing_comm_ratio
기준연월,,,,,,,,,
2025-07,9.82,6.90,7.54,8.12,8.99,8.59,7.95,1.99,2.39
2025-08,9.88,6.73,7.72,8.11,8.95,8.61,7.93,1.94,2.02
2025-09,9.84,6.96,7.77,8.38,8.99,8.63,7.79,1.99,2.05
2025-10,9.85,7.65,7.73,8.56,9.06,8.61,7.65,2.08,1.97
2025-11,9.90,7.79,7.78,8.39,9.04,8.61,7.60,2.12,2.00
2025-12,9.96,7.75,7.71,8.47,9.23,8.56,7.58,2.11,2.10

===== 월별 변화 범위 =====

                             min   max  range
low_weekday_outing_ratio    6.73  7.79   1.06
high_worktime_ratio         8.11  8.56   0.45
very_low_outing_comm_ratio  1.97  2.39   0.42
financial_interest_ratio    7.58  7.95   0.37
high_video_ratio            8.95  9.23   0.28
low_holiday_outing_ratio    7.54  7.78   0.24
very_low_outing_ratio       1.94  2.12   0.18
low_comm_ratio              9.82  9.96   0.14
high_life_service_ratio     8.56  8.63   0.07

In [26]:
# 동 × 월 단위로 원자료 합산
dong_month_interest = (
    citizen_life
    .groupby(
        ["행정동코드", "행정동명", "기준연월"],
        as_index=False
    )
    .agg({
        "총인구": "sum",
        "1인가구수": "sum",
        "커뮤니케이션이 적은 집단": "sum",
        "평일 외출이 적은 집단": "sum",
        "휴일 외출이 적은 집단": "sum",
        "출근소요시간 및 근무시간이 많은 집단": "sum",
        "동영상서비스 이용이 많은 집단": "sum",
        "생활서비스 이용이 많은 집단": "sum",
        "재정상태에 대한 관심집단": "sum",
        "외출이 매우 적은 집단(전체)": "sum",
        "외출-커뮤니케이션이 모두 적은 집단(전체)": "sum"
    })
)

# 1인가구 기반 7개 비율
for source_col, feature_col in single_interest_map.items():
    dong_month_interest[feature_col] = (
        dong_month_interest[source_col]
        / dong_month_interest["1인가구수"]
        * 100
    )

# 전체 인구 기반 2개 비율
for source_col, feature_col in whole_interest_map.items():
    dong_month_interest[feature_col] = (
        dong_month_interest[source_col]
        / dong_month_interest["총인구"]
        * 100
    )

print("동×월 shape:", dong_month_interest.shape)
print(
    "동×월 key 중복:",
    dong_month_interest.duplicated(
        ["행정동코드", "기준연월"]
    ).sum()
)

# 각 동의 6개월 표준편차와 범위 계산
dong_variation = (
    dong_month_interest
    .groupby(["행정동코드", "행정동명"])[ratio_cols]
    .agg(["mean", "std", "min", "max"])
)

# 전체적으로 월간 변동성이 어느 정도인지 요약
variation_summary = []

for col in ratio_cols:
    variation_summary.append({
        "feature": col,
        "평균비율": dong_variation[(col, "mean")].mean(),
        "동별_평균_std": dong_variation[(col, "std")].mean(),
        "동별_최대_std": dong_variation[(col, "std")].max(),
        "동별_평균_range": (
            dong_variation[(col, "max")]
            - dong_variation[(col, "min")]
        ).mean(),
        "동별_최대_range": (
            dong_variation[(col, "max")]
            - dong_variation[(col, "min")]
        ).max()
    })

variation_summary = pd.DataFrame(variation_summary)

display(
    variation_summary
    .sort_values("동별_평균_std", ascending=False)
    .round(2)
)

동×월 shape: (132, 23)
동×월 key 중복: 0

,feature,평균비율,동별_평균_std,동별_최대_std,동별_평균_range,동별_최대_range
1,low_weekday_outing_ratio,7.21,0.69,1.94,1.74,5.02
3,high_worktime_ratio,8.40,0.61,1.65,1.60,4.58
4,high_video_ratio,8.82,0.35,1.02,0.91,2.42
2,low_holiday_outing_ratio,8.22,0.24,0.53,0.63,1.50
6,financial_interest_ratio,8.03,0.22,0.57,0.55,1.32
0,low_comm_ratio,9.45,0.21,0.37,0.58,0.98
8,very_low_outing_comm_ratio,2.04,0.21,0.40,0.56,1.11
5,high_life_service_ratio,9.07,0.17,0.35,0.44,0.89
7,very_low_outing_ratio,2.03,0.16,0.45,0.41,1.12

In [27]:
# 외출이 매우 많은 집단의 동×월 원값 추가
very_high_outing = (
    citizen_life
    .groupby(
        ["행정동코드", "행정동명", "기준연월"],
        as_index=False
    )["외출이 매우 많은 집단"]
    .sum()
)

dong_month_interest = dong_month_interest.merge(
    very_high_outing,
    on=["행정동코드", "행정동명", "기준연월"],
    how="left",
    validate="one_to_one"
)

# 분석용 동×월 Feature Table
interest_month_feature = dong_month_interest[
    [
        "행정동코드",
        "행정동명",
        "기준연월",
        "총인구",
        "1인가구수",
        *ratio_cols,
        "외출이 매우 많은 집단"
    ]
].copy()

print("Feature shape:", interest_month_feature.shape)

print(
    "key 중복:",
    interest_month_feature.duplicated(
        ["행정동코드", "기준연월"]
    ).sum()
)

print(
    "결측값:",
    interest_month_feature.isna().sum().sum()
)

display(interest_month_feature.head())

Feature shape: (132, 15)
key 중복: 0
결측값: 0

,행정동코드,행정동명,기준연월,총인구,1인가구수,low_comm_ratio,low_weekday_outing_ratio,low_holiday_outing_ratio,high_worktime_ratio,high_video_ratio,high_life_service_ratio,financial_interest_ratio,very_low_outing_ratio,very_low_outing_comm_ratio,외출이 매우 많은 집단
0,1123051,신사동,2025-07,14449.0,2417.03,11.623770,6.895239,9.537738,7.997832,10.446705,9.260539,8.092990,2.359817,2.823656,260.88
1,1123051,신사동,2025-08,14321.0,2426.57,10.664848,7.222540,10.087490,8.937719,10.371842,8.709413,8.518196,2.364709,1.862300,267.38
2,1123051,신사동,2025-09,14409.0,2434.22,10.999827,8.165655,9.768221,10.735677,10.879871,9.406299,8.469654,2.826914,2.055174,263.39
3,1123051,신사동,2025-10,14297.0,2440.18,11.028285,9.386603,9.346032,10.847560,10.877886,8.965322,8.093665,3.021893,2.031405,262.21
4,1123051,신사동,2025-11,14481.0,2436.76,10.813950,9.620151,10.843497,9.712487,10.467998,9.602505,8.264663,2.855604,2.248533,265.86

In [28]:
# 9개 관심집단 비율의 동별 평균 + 표준편차
interest_dong_agg = (
    interest_month_feature
    .groupby(
        ["행정동코드", "행정동명"]
    )[ratio_cols]
    .agg(["mean", "std"])
)

# MultiIndex 컬럼을 일반 컬럼으로 변환
interest_dong_agg.columns = [
    f"{feature}_{stat}"
    for feature, stat in interest_dong_agg.columns
]

interest_dong_feature = (
    interest_dong_agg
    .reset_index()
)

print("Feature shape:", interest_dong_feature.shape)

print(
    "행정동 수:",
    interest_dong_feature["행정동코드"].nunique()
)

print(
    "key 중복:",
    interest_dong_feature["행정동코드"].duplicated().sum()
)

print(
    "결측값:",
    interest_dong_feature.isna().sum().sum()
)

print("\n===== 컬럼 목록 =====")
for col in interest_dong_feature.columns:
    print(col)

display(interest_dong_feature.head())

Feature shape: (22, 20)
행정동 수: 22
key 중복: 0
결측값: 0

===== 컬럼 목록 =====
행정동코드
행정동명
low_comm_ratio_mean
low_comm_ratio_std
low_weekday_outing_ratio_mean
low_weekday_outing_ratio_std
low_holiday_outing_ratio_mean
low_holiday_outing_ratio_std
high_worktime_ratio_mean
high_worktime_ratio_std
high_video_ratio_mean
high_video_ratio_std
high_life_service_ratio_mean
high_life_service_ratio_std
financial_interest_ratio_mean
financial_interest_ratio_std
very_low_outing_ratio_mean
very_low_outing_ratio_std
very_low_outing_comm_ratio_mean
very_low_outing_comm_ratio_std

,행정동코드,행정동명,low_comm_ratio_mean,low_comm_ratio_std,low_weekday_outing_ratio_mean,low_weekday_outing_ratio_std,low_holiday_outing_ratio_mean,low_holiday_outing_ratio_std,high_worktime_ratio_mean,high_worktime_ratio_std,high_video_ratio_mean,high_video_ratio_std,high_life_service_ratio_mean,high_life_service_ratio_std,financial_interest_ratio_mean,financial_interest_ratio_std,very_low_outing_ratio_mean,very_low_outing_ratio_std,very_low_outing_comm_ratio_mean,very_low_outing_comm_ratio_std
0,1123051,신사동,11.038133,0.327943,8.437241,1.185785,9.952993,0.532763,9.673012,1.083989,10.666177,0.263322,9.253243,0.354368,8.270528,0.185101,2.711385,0.279544,2.210738,0.333446
1,1123052,논현1동,11.483681,0.151326,11.511320,0.312887,8.089666,0.205947,11.912275,0.512713,12.560011,0.210202,17.071437,0.151359,10.133159,0.252290,2.747626,0.166669,2.492195,0.166352
2,1123053,논현2동,11.828393,0.341758,9.444701,0.336258,7.301021,0.223154,11.570046,0.506168,11.794512,0.270501,12.434209,0.195779,8.407377,0.190052,3.206703,0.173877,2.296737,0.219735
3,1123058,삼성1동,11.625685,0.289080,8.236127,0.626572,10.039030,0.135967,8.783138,0.362549,10.685210,0.328406,8.049201,0.150123,7.560791,0.156082,2.761129,0.169083,2.586284,0.395368
4,1123059,삼성2동,10.315528,0.235645,8.872663,0.746366,6.894509,0.295869,10.910531,0.478144,10.770241,0.223922,9.988907,0.241745,8.322526,0.212178,2.473494,0.134370,2.023861,0.167761

In [29]:
# ① 행정동 × 월 Feature
month_file = "gangnam_interest_group_month_features_2025_07_12.csv"

interest_month_feature.to_csv(
    month_file,
    index=False,
    encoding="utf-8-sig"
)

# ② 행정동 Feature
dong_file = "gangnam_interest_group_dong_features_2025_07_12.csv"

interest_dong_feature.to_csv(
    dong_file,
    index=False,
    encoding="utf-8-sig"
)

print("저장 완료")
print(month_file, interest_month_feature.shape)
print(dong_file, interest_dong_feature.shape)

저장 완료
gangnam_interest_group_month_features_2025_07_12.csv (132, 15)
gangnam_interest_group_dong_features_2025_07_12.csv (22, 20)

In [30]:
from google.colab import files

files.download("gangnam_interest_group_month_features_2025_07_12.csv")
files.download("gangnam_interest_group_dong_features_2025_07_12.csv")

In [31]:
telecom_summary = []

for col in telecom_variables:
    s = citizen_life[col]

    telecom_summary.append({
        "통신정보": col,
        "min": s.min(),
        "median": s.median(),
        "mean": s.mean(),
        "max": s.max(),
        "0인_행": (s == 0).sum(),
        "0비율_pct": (s == 0).mean() * 100
    })

telecom_summary = pd.DataFrame(telecom_summary)

display(
    telecom_summary.round(2)
)

,통신정보,min,median,mean,max,0인_행,0비율_pct
0,야간상주지 변경횟수 평균,7.68,10.66,10.80,13.64,0,0.00
1,주간상주지 변경횟수 평균,0.00,7.53,6.96,14.00,158,4.99
2,평균 출근 소요시간 평균,0.00,55.58,48.57,86.65,528,16.67
3,평균 근무시간 평균,0.00,513.67,433.39,600.31,528,16.67
4,소액결재 사용횟수 평균,0.00,2.50,2.38,3.33,111,3.50
5,소액결재 사용금액 평균,916.67,4337.22,4326.38,8000.00,0,0.00
6,최근 3개월 내 요금 연체 비율,0.39,5.64,6.55,22.56,0,0.00
7,SNS 사용횟수,-0.27,0.00,-0.01,0.23,130,4.10
8,평균 통화량,27.61,69.46,73.07,127.57,0,0.00
9,평균 문자량,5.33,12.89,13.27,26.17,0,0.00
10,평균 통화대상자 수,4.16,13.45,13.12,20.63,0,0.00
11,평균 문자대상자 수,2.33,5.35,5.21,8.76,0,0.00
12,데이터 사용량,0.50,6.14,7.34,29.03,0,0.00
13,평일 총 이동 횟수,9.87,23.82,25.70,51.34,0,0.00
14,휴일 총 이동 횟수 평균,5.29,11.02,11.45,19.24,0,0.00
15,집 추정 위치 평일 총 체류시간,419598.60,668290.48,738114.63,1452868.95,0,0.00
16,집 추정 위치 휴일 총 체류시간,77072.37,141402.55,148617.87,313222.94,0,0.00
17,평일 총 이동 거리 합계,229.86,864.15,935.02,2208.65,0,0.00
18,휴일 총 이동 거리 합계,155.72,529.73,542.89,1088.63,0,0.00
19,지하철이동일수 합계,4.43,10.68,11.13,21.28,0,0.00
20,게임 서비스 사용일수,11.69,55.92,57.60,134.22,0,0.00
21,금융 서비스 사용일수,25.63,184.06,167.72,289.29,0,0.00
22,쇼핑 서비스 사용일수,67.92,254.22,237.49,377.10,0,0.00
23,동영상/방송 서비스 사용일수,20.62,82.43,78.64,134.89,0,0.00
24,유튜브 사용일수,-0.49,-0.06,-0.04,0.29,67,2.11
25,넷플릭스 사용일수,-0.66,-0.30,-0.35,0.03,1,0.03
26,배달 서비스 사용일수,3.41,12.16,11.36,21.20,0,0.00
27,배달_브랜드 서비스 사용일수,0.00,2.81,2.89,5.08,1,0.03
28,배달_식재료 서비스 사용일수,0.00,1.67,1.36,1.67,579,18.28

In [32]:
unestimated_cols = [
    col for col in citizen_life.columns
    if ("미추정 인구" in col)
    or ("미추정 인구수" in col)
    or ("비사용 인구수" in col)
    or ("사용 금액 없는 인구수" in col)
]

print("미추정/비사용 관련 컬럼 수:", len(unestimated_cols))

result = []

for col in unestimated_cols:
    s = citizen_life[col]

    result.append({
        "컬럼": col,
        "min": s.min(),
        "mean": s.mean(),
        "max": s.max(),
        "총인구수 초과": (s > citizen_life["총인구"]).sum(),
        "총인구 대비 평균비율_pct":
            (s / citizen_life["총인구"] * 100).mean()
    })

unestimated_summary = pd.DataFrame(result)

display(
    unestimated_summary.round(2)
)

미추정/비사용 관련 컬럼 수: 23

,컬럼,min,mean,max,총인구수 초과,총인구 대비 평균비율_pct
0,야간상주지 변경 미추정 인구 수,0.00,0.00,0.00,0,0.00
1,주간상주지 변경 미추정 인구수,0.00,216.75,1590.00,0,25.29
2,출근 소요시간 미추정 인구수,70.00,510.66,1590.00,0,55.42
3,근무시간 미추정 인구수,58.00,461.63,1590.00,0,50.59
4,소액결재 비사용 인구수,214.00,923.23,2805.53,0,96.89
5,소액결재 사용 금액 없는 인구수,162.00,801.58,2446.38,0,84.88
6,카카오톡 비사용 인구수,0.00,41.17,280.00,0,4.27
7,평일 총 이동 횟수 미추정 인구수,0.00,64.57,472.00,0,6.58
8,휴일 이동 미추정 인구수,2.00,97.82,664.00,0,10.20
9,집 추정 위치 평일 총 체류시간 미추정 인구수,0.00,14.56,82.00,0,1.47
10,집 추정 위치 휴일 총 체류시간 미추정 인구수,0.00,19.44,126.00,0,1.96
11,평일 총 이동 거리 미추정 인구수,0.00,71.34,496.00,0,7.35
12,휴일 총 이동 거리 미추정 인구수,2.71,108.06,694.00,0,11.40
13,지하철 이용 미추정 인구수,0.00,125.86,748.00,0,13.09
14,게임 서비스 사용 미추정 인구수,0.00,80.27,600.00,0,8.56
15,금융 서비스 사용 미추정 인구수,0.00,64.25,472.00,0,6.70
16,쇼핑 서비스 사용 미추정 인구수,0.00,48.90,306.00,0,5.05
17,동영상/방송 서비스 사용 미추정 인구수,0.00,68.09,470.00,0,7.13
18,유튜브 사용 미추정 인구수,0.00,35.43,200.00,0,3.64
19,넷플릭스 사용 미추정 인구수,56.14,481.02,1474.00,0,53.00
20,배달 서비스 사용 미추정 인구수,5.46,188.68,1068.00,0,20.75
21,배달_브랜드 서비스 사용 미추정 인구수,115.89,660.60,2526.65,0,70.01
22,배달_식재료 서비스 사용 미추정 인구수,216.00,943.53,2958.71,0,98.87

In [33]:
observation_map = {
    "야간상주지 변경횟수 평균": "야간상주지 변경 미추정 인구 수",
    "주간상주지 변경횟수 평균": "주간상주지 변경 미추정 인구수",
    "평균 출근 소요시간 평균": "출근 소요시간 미추정 인구수",
    "평균 근무시간 평균": "근무시간 미추정 인구수",

    "소액결재 사용횟수 평균": "소액결재 비사용 인구수",
    "소액결재 사용금액 평균": "소액결재 사용 금액 없는 인구수",

    "SNS 사용횟수": "카카오톡 비사용 인구수",

    "평일 총 이동 횟수": "평일 총 이동 횟수 미추정 인구수",
    "휴일 총 이동 횟수 평균": "휴일 이동 미추정 인구수",

    "집 추정 위치 평일 총 체류시간":
        "집 추정 위치 평일 총 체류시간 미추정 인구수",
    "집 추정 위치 휴일 총 체류시간":
        "집 추정 위치 휴일 총 체류시간 미추정 인구수",

    "평일 총 이동 거리 합계": "평일 총 이동 거리 미추정 인구수",
    "휴일 총 이동 거리 합계": "휴일 총 이동 거리 미추정 인구수",

    "지하철이동일수 합계": "지하철 이용 미추정 인구수",

    "게임 서비스 사용일수": "게임 서비스 사용 미추정 인구수",
    "금융 서비스 사용일수": "금융 서비스 사용 미추정 인구수",
    "쇼핑 서비스 사용일수": "쇼핑 서비스 사용 미추정 인구수",
    "동영상/방송 서비스 사용일수":
        "동영상/방송 서비스 사용 미추정 인구수",
    "유튜브 사용일수": "유튜브 사용 미추정 인구수",
    "넷플릭스 사용일수": "넷플릭스 사용 미추정 인구수",

    "배달 서비스 사용일수": "배달 서비스 사용 미추정 인구수",
    "배달_브랜드 서비스 사용일수":
        "배달_브랜드 서비스 사용 미추정 인구수",
    "배달_식재료 서비스 사용일수":
        "배달_식재료 서비스 사용 미추정 인구수"
}

print("29개 대표 변수:", len(telecom_variables))
print("관측상태 컬럼이 있는 변수:", len(observation_map))

no_observation_col = [
    col for col in telecom_variables
    if col not in observation_map
]

print("\n별도 미추정/비사용 컬럼이 없는 변수:")
for col in no_observation_col:
    print("-", col)

29개 대표 변수: 29
관측상태 컬럼이 있는 변수: 23

별도 미추정/비사용 컬럼이 없는 변수:
- 최근 3개월 내 요금 연체 비율
- 평균 통화량
- 평균 문자량
- 평균 통화대상자 수
- 평균 문자대상자 수
- 데이터 사용량

In [34]:
# '미추정'이라고 명시된 컬럼만 분리
true_unestimated_map = {
    variable: status_col
    for variable, status_col in observation_map.items()
    if "미추정" in status_col
}

print("미추정 인구 컬럼이 있는 대표변수 수:",
      len(true_unestimated_map))

effective_summary = []

for variable, status_col in true_unestimated_map.items():

    effective_n = (
        citizen_life["총인구"]
        - citizen_life[status_col]
    )

    effective_summary.append({
        "통신정보": variable,
        "상태컬럼": status_col,
        "유효인구_min": effective_n.min(),
        "유효인구_mean": effective_n.mean(),
        "유효인구_0인행": (effective_n == 0).sum(),
        "유효인구_음수행": (effective_n < 0).sum(),
        "평균_유효비율_pct":
            (effective_n / citizen_life["총인구"] * 100).mean()
    })

effective_summary = pd.DataFrame(effective_summary)

display(
    effective_summary
    .sort_values("평균_유효비율_pct")
    .round(2)
)

미추정 인구 컬럼이 있는 대표변수 수: 20

,통신정보,상태컬럼,유효인구_min,유효인구_mean,유효인구_0인행,유효인구_음수행,평균_유효비율_pct
19,배달_식재료 서비스 사용일수,배달_식재료 서비스 사용 미추정 인구수,0.0,11.86,578,0,1.13
18,배달_브랜드 서비스 사용일수,배달_브랜드 서비스 사용 미추정 인구수,0.0,294.78,1,0,29.99
2,평균 출근 소요시간 평균,출근 소요시간 미추정 인구수,0.0,444.73,527,0,44.58
16,넷플릭스 사용일수,넷플릭스 사용 미추정 인구수,10.0,474.37,0,0,47.00
3,평균 근무시간 평균,근무시간 미추정 인구수,0.0,493.76,527,0,49.41
1,주간상주지 변경횟수 평균,주간상주지 변경 미추정 인구수,0.0,738.64,158,0,74.71
17,배달 서비스 사용일수,배달 서비스 사용 미추정 인구수,142.0,766.70,0,0,79.25
10,지하철이동일수 합계,지하철 이용 미추정 인구수,186.0,829.53,0,0,86.91
9,휴일 총 이동 거리 합계,휴일 총 이동 거리 미추정 인구수,184.0,847.33,0,0,88.60
5,휴일 총 이동 횟수 평균,휴일 이동 미추정 인구수,194.0,857.56,0,0,89.80
11,게임 서비스 사용일수,게임 서비스 사용 미추정 인구수,202.0,875.12,0,0,91.44
8,평일 총 이동 거리 합계,평일 총 이동 거리 미추정 인구수,196.0,884.05,0,0,92.65
14,동영상/방송 서비스 사용일수,동영상/방송 서비스 사용 미추정 인구수,210.0,887.30,0,0,92.87
12,금융 서비스 사용일수,금융 서비스 사용 미추정 인구수,208.0,891.13,0,0,93.30
4,평일 총 이동 횟수,평일 총 이동 횟수 미추정 인구수,202.0,890.82,0,0,93.42
13,쇼핑 서비스 사용일수,쇼핑 서비스 사용 미추정 인구수,214.0,906.49,0,0,94.95
15,유튜브 사용일수,유튜브 사용 미추정 인구수,214.0,919.96,0,0,96.36
7,집 추정 위치 휴일 총 체류시간,집 추정 위치 휴일 총 체류시간 미추정 인구수,214.0,935.95,0,0,98.04
6,집 추정 위치 평일 총 체류시간,집 추정 위치 평일 총 체류시간 미추정 인구수,214.0,940.83,0,0,98.53
0,야간상주지 변경횟수 평균,야간상주지 변경 미추정 인구 수,216.0,955.39,0,0,100.00

In [35]:
zero_relation = []

for variable, status_col in true_unestimated_map.items():

    effective_n = (
        citizen_life["총인구"]
        - citizen_life[status_col]
    )

    value = citizen_life[variable]

    zero_relation.append({
        "통신정보": variable,

        # 대표값 자체가 0인 행
        "값0_행": (value == 0).sum(),

        # 유효 추정인구가 0인 행
        "유효인구0_행": (effective_n == 0).sum(),

        # 유효인구=0인데 대표값도 0
        "유효인구0_값0": (
            (effective_n == 0) &
            (value == 0)
        ).sum(),

        # 유효인구가 있는데 대표값=0
        "유효인구양수_값0": (
            (effective_n > 0) &
            (value == 0)
        ).sum(),

        # 유효인구=0인데 대표값이 0이 아님
        "유효인구0_값비0": (
            (effective_n == 0) &
            (value != 0)
        ).sum()
    })

zero_relation = pd.DataFrame(zero_relation)

display(
    zero_relation.sort_values(
        "유효인구0_행",
        ascending=False
    )
)

                 통신정보  값0_행  유효인구0_행  유효인구0_값0  유효인구양수_값0  유효인구0_값비0
19    배달_식재료 서비스 사용일수   579      578       578          1          0
3          평균 근무시간 평균   528      527       527          1          0
2       평균 출근 소요시간 평균   528      527       527          1          0
1       주간상주지 변경횟수 평균   158      158       158          0          0
18    배달_브랜드 서비스 사용일수     1        1         1          0          0
0       야간상주지 변경횟수 평균     0        0         0          0          0
4          평일 총 이동 횟수     0        0         0          0          0
5       휴일 총 이동 횟수 평균     0        0         0          0          0
8       평일 총 이동 거리 합계     0        0         0          0          0
9       휴일 총 이동 거리 합계     0        0         0          0          0
6   집 추정 위치 평일 총 체류시간     0        0         0          0          0
7   집 추정 위치 휴일 총 체류시간     0        0         0          0          0
11        게임 서비스 사용일수     0        0         0          0          0
10         지하철이동일수 합계     0        0         0          0          0
12        금융 서비스 사용일수     0        0         0          0          0
13        쇼핑 서비스 사용일수     0        0         0          0          0
15           유튜브 사용일수    67        0         0         67          0
14    동영상/방송 서비스 사용일수     0        0         0          0          0
17        배달 서비스 사용일수     0        0         0          0          0
16          넷플릭스 사용일수     1        0         0          1          0

In [36]:
no_status_vars = [
    "최근 3개월 내 요금 연체 비율",
    "평균 통화량",
    "평균 문자량",
    "평균 통화대상자 수",
    "평균 문자대상자 수",
    "데이터 사용량"
]

rows = []

for (dong_code, dong_name, month), g in citizen_life.groupby(
    ["행정동코드", "행정동명", "기준연월"]
):
    row = {
        "행정동코드": dong_code,
        "행정동명": dong_name,
        "기준연월": month
    }

    for col in no_status_vars:

        # 성별·연령대 셀의 단순평균
        simple_mean = g[col].mean()

        # 총인구 가중평균
        weighted_mean = (
            (g[col] * g["총인구"]).sum()
            / g["총인구"].sum()
        )

        row[f"{col}_simple"] = simple_mean
        row[f"{col}_weighted"] = weighted_mean
        row[f"{col}_diff"] = weighted_mean - simple_mean

    rows.append(row)

no_status_compare = pd.DataFrame(rows)

print("shape:", no_status_compare.shape)
print(
    "key 중복:",
    no_status_compare.duplicated(
        ["행정동코드", "기준연월"]
    ).sum()
)

comparison_summary = []

for col in no_status_vars:
    diff = no_status_compare[f"{col}_diff"]

    comparison_summary.append({
        "통신정보": col,
        "평균_절대차이": diff.abs().mean(),
        "최대_절대차이": diff.abs().max()
    })

comparison_summary = pd.DataFrame(comparison_summary)

display(
    comparison_summary
    .sort_values("평균_절대차이", ascending=False)
    .round(4)
)

shape: (132, 21)
key 중복: 0

                통신정보  평균_절대차이  최대_절대차이
1             평균 통화량   1.6810   5.9070
3         평균 통화대상자 수   0.4906   1.5317
5            데이터 사용량   0.4579   1.9208
2             평균 문자량   0.2989   1.7083
4         평균 문자대상자 수   0.2450   0.6732
0  최근 3개월 내 요금 연체 비율   0.2234   1.2791

In [37]:
import numpy as np
import pandas as pd

rows = []

group_keys = ["행정동코드", "행정동명", "기준연월"]

for keys, g in citizen_life.groupby(group_keys):

    dong_code, dong_name, month = keys

    row = {
        "행정동코드": dong_code,
        "행정동명": dong_name,
        "기준연월": month
    }

    for variable, status_col in true_unestimated_map.items():

        # 변수별 유효 추정인구
        weights = (
            g["총인구"]
            - g[status_col]
        )

        # 유효 추정인구 전체가 0인 경우 방어
        if weights.sum() > 0:
            weighted_value = np.average(
                g[variable],
                weights=weights
            )
        else:
            weighted_value = np.nan

        row[variable] = weighted_value

        # 해당 동×월에서 실제 추정 가능한 모집단 비율도 보존
        row[f"{variable}_coverage"] = (
            weights.sum()
            / g["총인구"].sum()
            * 100
        )

    rows.append(row)

telecom_unestimated_feature = pd.DataFrame(rows)

print("shape:", telecom_unestimated_feature.shape)

print(
    "key 중복:",
    telecom_unestimated_feature.duplicated(
        ["행정동코드", "기준연월"]
    ).sum()
)

print(
    "결측값:",
    telecom_unestimated_feature.isna().sum().sum()
)

# coverage만 따로 요약
coverage_cols = [
    c for c in telecom_unestimated_feature.columns
    if c.endswith("_coverage")
]

coverage_summary = pd.DataFrame({
    "min": telecom_unestimated_feature[coverage_cols].min(),
    "mean": telecom_unestimated_feature[coverage_cols].mean(),
    "max": telecom_unestimated_feature[coverage_cols].max()
}).sort_values("mean")

display(coverage_summary.round(2))

shape: (132, 43)
key 중복: 0
결측값: 0

                               min    mean     max
배달_식재료 서비스 사용일수_coverage      0.72    1.22    2.13
배달_브랜드 서비스 사용일수_coverage     10.98   30.79   49.34
평균 출근 소요시간 평균_coverage       38.70   46.50   55.83
넷플릭스 사용일수_coverage           35.75   48.94   54.95
평균 근무시간 평균_coverage          42.64   51.50   58.83
주간상주지 변경횟수 평균_coverage       67.86   76.90   85.36
배달 서비스 사용일수_coverage         72.00   79.88   83.99
지하철이동일수 합계_coverage          78.27   86.89   93.55
휴일 총 이동 거리 합계_coverage       80.88   88.66   94.69
휴일 총 이동 횟수 평균_coverage       83.87   89.76   95.03
게임 서비스 사용일수_coverage         87.36   91.43   94.06
평일 총 이동 거리 합계_coverage       86.63   92.60   96.86
동영상/방송 서비스 사용일수_coverage     89.58   92.76   95.05
금융 서비스 사용일수_coverage         89.98   93.17   95.17
평일 총 이동 횟수_coverage          88.51   93.31   96.69
쇼핑 서비스 사용일수_coverage         92.71   94.82   96.44
유튜브 사용일수_coverage            94.75   96.26   97.43
집 추정 위치 휴일 총 체류시간_coverage   96.86   97.99   99.04
집 추정 위치 평일 총 체류시간_coverage   97.56   98.49   99.30
야간상주지 변경횟수 평균_coverage      100.00  100.00  100.00

In [38]:
rows = []

group_keys = ["행정동코드", "행정동명", "기준연월"]

for keys, g in citizen_life.groupby(group_keys):

    dong_code, dong_name, month = keys

    row = {
        "행정동코드": dong_code,
        "행정동명": dong_name,
        "기준연월": month
    }

    weights = g["총인구"]

    for variable in no_status_vars:

        row[variable] = np.average(
            g[variable],
            weights=weights
        )

    rows.append(row)

telecom_no_status_feature = pd.DataFrame(rows)

print("shape:", telecom_no_status_feature.shape)

print(
    "key 중복:",
    telecom_no_status_feature.duplicated(
        ["행정동코드", "기준연월"]
    ).sum()
)

print(
    "결측값:",
    telecom_no_status_feature.isna().sum().sum()
)

display(telecom_no_status_feature.head())

shape: (132, 9)
key 중복: 0
결측값: 0

,행정동코드,행정동명,기준연월,최근 3개월 내 요금 연체 비율,평균 통화량,평균 문자량,평균 통화대상자 수,평균 문자대상자 수,데이터 사용량
0,1123051,신사동,2025-07,6.776245,64.885676,12.274348,13.876814,5.670051,5.866857
1,1123051,신사동,2025-08,6.392381,63.342572,12.201750,13.505467,5.593486,5.898828
2,1123051,신사동,2025-09,7.354896,93.497152,15.858435,13.784785,5.672742,8.944226
3,1123051,신사동,2025-10,7.098781,93.912874,15.355552,13.322253,5.487716,9.139346
4,1123051,신사동,2025-11,6.339821,63.251943,12.512566,13.549794,5.434375,6.226629

In [39]:
special_check = pd.DataFrame({
    # 소액결제 횟수
    "소액결제_사용자비율_pct":
        (
            (citizen_life["총인구"]
             - citizen_life["소액결재 비사용 인구수"])
            / citizen_life["총인구"] * 100
        ),

    # 소액결제 금액
    "소액결제금액_존재비율_pct":
        (
            (citizen_life["총인구"]
             - citizen_life["소액결재 사용 금액 없는 인구수"])
            / citizen_life["총인구"] * 100
        ),

    # SNS - 카카오톡 비사용률
    "카카오톡_비사용비율_pct":
        (
            citizen_life["카카오톡 비사용 인구수"]
            / citizen_life["총인구"] * 100
        )
})

display(
    special_check.describe()
    .loc[["min", "mean", "50%", "max"]]
    .T
    .round(2)
)

# 소액결제 두 상태정보가 서로 얼마나 다른지도 확인
diff = (
    citizen_life["소액결재 비사용 인구수"]
    - citizen_life["소액결재 사용 금액 없는 인구수"]
)

print(
    "소액결제 비사용 인구수 = 사용금액 없는 인구수:",
    (diff == 0).sum(),
    "/",
    len(diff)
)

print("두 컬럼 평균 절대차이:", diff.abs().mean())
print("두 컬럼 최대 절대차이:", diff.abs().max())

                  min   mean    50%    max
소액결제_사용자비율_pct   0.00   3.11   2.46  15.10
소액결제금액_존재비율_pct  0.83  15.12  15.60  33.33
카카오톡_비사용비율_pct   0.00   4.27   3.67  25.80

소액결제 비사용 인구수 = 사용금액 없는 인구수: 1 / 3168
두 컬럼 평균 절대차이: 121.64966224747475
두 컬럼 최대 절대차이: 588.4399999999998

In [40]:
rows = []

for keys, g in citizen_life.groupby(
    ["행정동코드", "행정동명", "기준연월"]
):
    dong_code, dong_name, month = keys

    row = {
        "행정동코드": dong_code,
        "행정동명": dong_name,
        "기준연월": month
    }

    total_pop = g["총인구"].sum()

    # -------------------------
    # 1. 소액결제 사용횟수
    # -------------------------
    payment_users = (
        g["총인구"]
        - g["소액결재 비사용 인구수"]
    )

    row["소액결재_사용자비율"] = (
        payment_users.sum()
        / total_pop * 100
    )

    if payment_users.sum() > 0:
        row["소액결재 사용횟수 평균"] = np.average(
            g["소액결재 사용횟수 평균"],
            weights=payment_users
        )
    else:
        row["소액결재 사용횟수 평균"] = np.nan

    # -------------------------
    # 2. 소액결제 사용금액
    # -------------------------
    payment_amount_pop = (
        g["총인구"]
        - g["소액결재 사용 금액 없는 인구수"]
    )

    row["소액결재_금액존재비율"] = (
        payment_amount_pop.sum()
        / total_pop * 100
    )

    if payment_amount_pop.sum() > 0:
        row["소액결재 사용금액 평균"] = np.average(
            g["소액결재 사용금액 평균"],
            weights=payment_amount_pop
        )
    else:
        row["소액결재 사용금액 평균"] = np.nan

    # -------------------------
    # 3. SNS
    # -------------------------
    # SNS 값 자체는 Z-score이므로 총인구 가중
    row["SNS 사용횟수"] = np.average(
        g["SNS 사용횟수"],
        weights=g["총인구"]
    )

    # 카카오톡 비사용은 별도 비율 Feature
    row["카카오톡_비사용비율"] = (
        g["카카오톡 비사용 인구수"].sum()
        / total_pop * 100
    )

    rows.append(row)

telecom_special_feature = pd.DataFrame(rows)

print("shape:", telecom_special_feature.shape)

print(
    "key 중복:",
    telecom_special_feature.duplicated(
        ["행정동코드", "기준연월"]
    ).sum()
)

print(
    "결측값:",
    telecom_special_feature.isna().sum().sum()
)

display(
    telecom_special_feature[
        [
            "소액결재_사용자비율",
            "소액결재 사용횟수 평균",
            "소액결재_금액존재비율",
            "소액결재 사용금액 평균",
            "SNS 사용횟수",
            "카카오톡_비사용비율"
        ]
    ].describe().T.round(3)
)

shape: (132, 9)
key 중복: 0
결측값: 0

,count,mean,std,min,25%,50%,75%,max
소액결재_사용자비율,132.0,3.235,1.697,1.291,2.088,2.931,3.665,8.035
소액결재 사용횟수 평균,132.0,2.500,0.077,2.299,2.443,2.499,2.557,2.655
소액결재_금액존재비율,132.0,15.803,3.012,10.851,13.417,15.712,17.218,23.230
소액결재 사용금액 평균,132.0,4450.605,460.026,3737.580,4065.887,4406.482,4751.411,5743.871
SNS 사용횟수,132.0,-0.001,0.019,-0.038,-0.014,-0.001,0.009,0.050
카카오톡_비사용비율,132.0,4.384,0.840,3.028,3.705,4.274,4.971,7.144

In [41]:
key_cols = [
    "행정동코드",
    "행정동명",
    "기준연월"
]

# 20개 미추정형
telecom_month_feature = telecom_unestimated_feature.copy()

# 상태정보 없는 6개 결합
telecom_month_feature = telecom_month_feature.merge(
    telecom_no_status_feature,
    on=key_cols,
    how="left",
    validate="one_to_one"
)

# 특수 처리 3개 + 보조 Feature 결합
telecom_month_feature = telecom_month_feature.merge(
    telecom_special_feature,
    on=key_cols,
    how="left",
    validate="one_to_one"
)

print("통합 shape:", telecom_month_feature.shape)

print(
    "행정동 수:",
    telecom_month_feature["행정동코드"].nunique()
)

print(
    "월 수:",
    telecom_month_feature["기준연월"].nunique()
)

print(
    "key 중복:",
    telecom_month_feature.duplicated(
        ["행정동코드", "기준연월"]
    ).sum()
)

print(
    "결측값:",
    telecom_month_feature.isna().sum().sum()
)

print("전체 컬럼 수:", len(telecom_month_feature.columns))

통합 shape: (132, 55)
행정동 수: 22
월 수: 6
key 중복: 0
결측값: 0
전체 컬럼 수: 55

In [42]:
column_role = []

for col in telecom_month_feature.columns:

    if col in ["행정동코드", "행정동명", "기준연월"]:
        role = "ID"

    elif col.endswith("_coverage"):
        role = "QC"

    elif col in [
        "소액결재_사용자비율",
        "소액결재_금액존재비율",
        "카카오톡_비사용비율"
    ]:
        role = "보조 Feature"

    else:
        role = "행동 Feature"

    column_role.append({
        "컬럼명": col,
        "역할": role
    })

column_role = pd.DataFrame(column_role)

print(column_role["역할"].value_counts())

display(column_role)

역할
행동 Feature    29
QC            20
ID             3
보조 Feature     3
Name: count, dtype: int64

                           컬럼명          역할
0                        행정동코드          ID
1                         행정동명          ID
2                         기준연월          ID
3                야간상주지 변경횟수 평균  행동 Feature
4       야간상주지 변경횟수 평균_coverage          QC
5                주간상주지 변경횟수 평균  행동 Feature
6       주간상주지 변경횟수 평균_coverage          QC
7                평균 출근 소요시간 평균  행동 Feature
8       평균 출근 소요시간 평균_coverage          QC
9                   평균 근무시간 평균  행동 Feature
10         평균 근무시간 평균_coverage          QC
11                  평일 총 이동 횟수  행동 Feature
12         평일 총 이동 횟수_coverage          QC
13               휴일 총 이동 횟수 평균  행동 Feature
14      휴일 총 이동 횟수 평균_coverage          QC
15           집 추정 위치 평일 총 체류시간  행동 Feature
16  집 추정 위치 평일 총 체류시간_coverage          QC
17           집 추정 위치 휴일 총 체류시간  행동 Feature
18  집 추정 위치 휴일 총 체류시간_coverage          QC
19               평일 총 이동 거리 합계  행동 Feature
20      평일 총 이동 거리 합계_coverage          QC
21               휴일 총 이동 거리 합계  행동 Feature
22      휴일 총 이동 거리 합계_coverage          QC
23                  지하철이동일수 합계  행동 Feature
24         지하철이동일수 합계_coverage          QC
25                 게임 서비스 사용일수  행동 Feature
26        게임 서비스 사용일수_coverage          QC
27                 금융 서비스 사용일수  행동 Feature
28        금융 서비스 사용일수_coverage          QC
29                 쇼핑 서비스 사용일수  행동 Feature
30        쇼핑 서비스 사용일수_coverage          QC
31             동영상/방송 서비스 사용일수  행동 Feature
32    동영상/방송 서비스 사용일수_coverage          QC
33                    유튜브 사용일수  행동 Feature
34           유튜브 사용일수_coverage          QC
35                   넷플릭스 사용일수  행동 Feature
36          넷플릭스 사용일수_coverage          QC
37                 배달 서비스 사용일수  행동 Feature
38        배달 서비스 사용일수_coverage          QC
39             배달_브랜드 서비스 사용일수  행동 Feature
40    배달_브랜드 서비스 사용일수_coverage          QC
41             배달_식재료 서비스 사용일수  행동 Feature
42    배달_식재료 서비스 사용일수_coverage          QC
43           최근 3개월 내 요금 연체 비율  행동 Feature
44                      평균 통화량  행동 Feature
45                      평균 문자량  행동 Feature
46                  평균 통화대상자 수  행동 Feature
47                  평균 문자대상자 수  행동 Feature
48                     데이터 사용량  행동 Feature
49                  소액결재_사용자비율  보조 Feature
50                소액결재 사용횟수 평균  행동 Feature
51                 소액결재_금액존재비율  보조 Feature
52                소액결재 사용금액 평균  행동 Feature
53                    SNS 사용횟수  행동 Feature
54                  카카오톡_비사용비율  보조 Feature

In [43]:
behavior_cols = column_role.loc[
    column_role["역할"] == "행동 Feature",
    "컬럼명"
].tolist()

support_cols = column_role.loc[
    column_role["역할"] == "보조 Feature",
    "컬럼명"
].tolist()

analysis_cols = behavior_cols + support_cols

corr = telecom_month_feature[analysis_cols].corr()

high_corr_pairs = []

for i in range(len(analysis_cols)):
    for j in range(i + 1, len(analysis_cols)):

        r = corr.iloc[i, j]

        if abs(r) >= 0.8:
            high_corr_pairs.append({
                "변수1": analysis_cols[i],
                "변수2": analysis_cols[j],
                "상관계수": r
            })

high_corr_pairs = pd.DataFrame(high_corr_pairs)

if len(high_corr_pairs) > 0:
    high_corr_pairs["절대상관"] = (
        high_corr_pairs["상관계수"].abs()
    )

    high_corr_pairs = (
        high_corr_pairs
        .sort_values("절대상관", ascending=False)
        .drop(columns="절대상관")
        .reset_index(drop=True)
    )

print("분석 대상 Feature 수:", len(analysis_cols))
print("|r| >= 0.8 조합 수:", len(high_corr_pairs))

display(high_corr_pairs.round(3))

분석 대상 Feature 수: 32
|r| >= 0.8 조합 수: 41

                  변수1                변수2   상관계수
0       야간상주지 변경횟수 평균      주간상주지 변경횟수 평균  0.976
1          평일 총 이동 횟수      평일 총 이동 거리 합계  0.969
2   최근 3개월 내 요금 연체 비율         소액결재_사용자비율  0.968
3   집 추정 위치 평일 총 체류시간             평균 통화량  0.938
4         금융 서비스 사용일수        쇼핑 서비스 사용일수  0.933
5   최근 3개월 내 요금 연체 비율       소액결재 사용금액 평균  0.931
6        소액결재 사용금액 평균         소액결재_사용자비율  0.927
7          소액결재_사용자비율        소액결재_금액존재비율  0.926
8          평일 총 이동 횟수  집 추정 위치 평일 총 체류시간  0.915
9          평일 총 이동 횟수         지하철이동일수 합계  0.914
10        배달 서비스 사용일수         소액결재_사용자비율  0.913
11             평균 문자량            데이터 사용량  0.894
12             평균 통화량             평균 문자량  0.884
13      평일 총 이동 거리 합계         지하철이동일수 합계  0.879
14        배달 서비스 사용일수  최근 3개월 내 요금 연체 비율  0.879
15         평균 통화대상자 수         평균 문자대상자 수  0.873
16        게임 서비스 사용일수    배달_브랜드 서비스 사용일수  0.873
17  집 추정 위치 평일 총 체류시간      평일 총 이동 거리 합계  0.871
18             평균 통화량            데이터 사용량  0.862
19  집 추정 위치 휴일 총 체류시간      휴일 총 이동 거리 합계  0.859
20      휴일 총 이동 횟수 평균      휴일 총 이동 거리 합계  0.858
21      야간상주지 변경횟수 평균        게임 서비스 사용일수  0.851
22  집 추정 위치 평일 총 체류시간         지하철이동일수 합계  0.850
23       소액결재 사용금액 평균        소액결재_금액존재비율  0.847
24  최근 3개월 내 요금 연체 비율        소액결재_금액존재비율  0.847
25      휴일 총 이동 횟수 평균         지하철이동일수 합계  0.845
26      휴일 총 이동 횟수 평균      평일 총 이동 거리 합계  0.844
27        배달 서비스 사용일수        소액결재_금액존재비율  0.842
28      주간상주지 변경횟수 평균        게임 서비스 사용일수  0.836
29  집 추정 위치 평일 총 체류시간             평균 문자량  0.836
30         평일 총 이동 횟수      휴일 총 이동 횟수 평균  0.835
31    동영상/방송 서비스 사용일수             평균 통화량  0.831
32  집 추정 위치 휴일 총 체류시간             평균 통화량  0.829
33         평일 총 이동 횟수             평균 통화량  0.828
34    동영상/방송 서비스 사용일수             평균 문자량  0.825
35      휴일 총 이동 횟수 평균             평균 통화량  0.817
36  집 추정 위치 휴일 총 체류시간            데이터 사용량  0.806
37  집 추정 위치 평일 총 체류시간  집 추정 위치 휴일 총 체류시간  0.805
38        배달 서비스 사용일수           SNS 사용횟수  0.805
39      평일 총 이동 거리 합계             평균 통화량  0.802
40    동영상/방송 서비스 사용일수            데이터 사용량  0.802

In [44]:
# 32개 분석 후보 Feature의 6개월 동별 평균
telecom_dong_mean = (
    telecom_month_feature
    .groupby(["행정동코드", "행정동명"])[analysis_cols]
    .mean()
    .reset_index()
)

print("동 단위 shape:", telecom_dong_mean.shape)

# 22개 동 사이의 상관관계
dong_corr = telecom_dong_mean[analysis_cols].corr()

dong_high_corr_pairs = []

for i in range(len(analysis_cols)):
    for j in range(i + 1, len(analysis_cols)):

        r = dong_corr.iloc[i, j]

        if abs(r) >= 0.8:
            dong_high_corr_pairs.append({
                "변수1": analysis_cols[i],
                "변수2": analysis_cols[j],
                "상관계수": r
            })

dong_high_corr_pairs = pd.DataFrame(dong_high_corr_pairs)

if len(dong_high_corr_pairs) > 0:

    dong_high_corr_pairs["절대상관"] = (
        dong_high_corr_pairs["상관계수"].abs()
    )

    dong_high_corr_pairs = (
        dong_high_corr_pairs
        .sort_values("절대상관", ascending=False)
        .drop(columns="절대상관")
        .reset_index(drop=True)
    )

print("|r| >= 0.8 동 단위 조합 수:",
      len(dong_high_corr_pairs))

display(dong_high_corr_pairs.round(3))

동 단위 shape: (22, 34)
|r| >= 0.8 동 단위 조합 수: 44

                  변수1                변수2   상관계수
0   최근 3개월 내 요금 연체 비율         소액결재_사용자비율  0.975
1   최근 3개월 내 요금 연체 비율       소액결재 사용금액 평균  0.969
2     동영상/방송 서비스 사용일수           SNS 사용횟수  0.964
3        소액결재 사용금액 평균         소액결재_사용자비율  0.962
4         금융 서비스 사용일수        쇼핑 서비스 사용일수  0.952
5         배달 서비스 사용일수         소액결재_사용자비율  0.950
6         게임 서비스 사용일수           SNS 사용횟수  0.946
7         게임 서비스 사용일수    동영상/방송 서비스 사용일수  0.936
8         배달 서비스 사용일수            데이터 사용량  0.936
9          소액결재_사용자비율        소액결재_금액존재비율  0.933
10        쇼핑 서비스 사용일수    동영상/방송 서비스 사용일수  0.933
11         평균 통화대상자 수         평균 문자대상자 수  0.924
12        배달 서비스 사용일수  최근 3개월 내 요금 연체 비율  0.921
13         평일 총 이동 횟수      평일 총 이동 거리 합계  0.915
14  최근 3개월 내 요금 연체 비율            데이터 사용량  0.914
15        게임 서비스 사용일수            데이터 사용량  0.910
16        배달 서비스 사용일수        소액결재_금액존재비율  0.900
17            데이터 사용량         소액결재_사용자비율  0.900
18         평일 총 이동 횟수      휴일 총 이동 횟수 평균  0.897
19             평균 통화량        소액결재_금액존재비율  0.897
20         평일 총 이동 횟수       소액결재 사용금액 평균 -0.888
21             평균 통화량         평균 통화대상자 수  0.887
22        금융 서비스 사용일수    동영상/방송 서비스 사용일수  0.885
23      평일 총 이동 거리 합계       소액결재 사용금액 평균 -0.885
24            데이터 사용량           SNS 사용횟수  0.882
25        배달 서비스 사용일수       소액결재 사용금액 평균  0.881
26         평일 총 이동 횟수        배달 서비스 사용일수 -0.874
27        쇼핑 서비스 사용일수           SNS 사용횟수  0.872
28         평일 총 이동 횟수         소액결재_사용자비율 -0.871
29         평일 총 이동 횟수  최근 3개월 내 요금 연체 비율 -0.870
30       소액결재 사용금액 평균        소액결재_금액존재비율  0.869
31            데이터 사용량       소액결재 사용금액 평균  0.865
32  최근 3개월 내 요금 연체 비율        소액결재_금액존재비율  0.851
33        게임 서비스 사용일수        쇼핑 서비스 사용일수  0.844
34    동영상/방송 서비스 사용일수            데이터 사용량  0.842
35         평일 총 이동 횟수            데이터 사용량 -0.836
36      평일 총 이동 거리 합계  최근 3개월 내 요금 연체 비율 -0.834
37        배달 서비스 사용일수             평균 문자량  0.831
38        금융 서비스 사용일수           유튜브 사용일수  0.823
39        배달 서비스 사용일수           SNS 사용횟수  0.822
40        게임 서비스 사용일수        배달 서비스 사용일수  0.818
41        금융 서비스 사용일수           SNS 사용횟수  0.814
42      평일 총 이동 거리 합계         소액결재_사용자비율 -0.811
43    동영상/방송 서비스 사용일수        배달 서비스 사용일수  0.802

In [45]:
feature_domain = {
    # 상주지 변화
    "야간상주지 변경횟수 평균": "상주지 변화",
    "주간상주지 변경횟수 평균": "상주지 변화",

    # 직장생활
    "평균 출근 소요시간 평균": "직장생활",
    "평균 근무시간 평균": "직장생활",

    # 이동·외출
    "평일 총 이동 횟수": "이동·외출",
    "휴일 총 이동 횟수 평균": "이동·외출",
    "평일 총 이동 거리 합계": "이동·외출",
    "휴일 총 이동 거리 합계": "이동·외출",
    "지하철이동일수 합계": "이동·외출",

    # 자택체류
    "집 추정 위치 평일 총 체류시간": "자택체류",
    "집 추정 위치 휴일 총 체류시간": "자택체류",

    # 커뮤니케이션
    "평균 통화량": "커뮤니케이션",
    "평균 문자량": "커뮤니케이션",
    "평균 통화대상자 수": "커뮤니케이션",
    "평균 문자대상자 수": "커뮤니케이션",
    "SNS 사용횟수": "커뮤니케이션",
    "카카오톡_비사용비율": "커뮤니케이션",

    # 재정·결제
    "최근 3개월 내 요금 연체 비율": "재정·결제",
    "소액결재_사용자비율": "재정·결제",
    "소액결재 사용횟수 평균": "재정·결제",
    "소액결재_금액존재비율": "재정·결제",
    "소액결재 사용금액 평균": "재정·결제",

    # 디지털·영상
    "데이터 사용량": "디지털·영상",
    "게임 서비스 사용일수": "디지털·영상",
    "동영상/방송 서비스 사용일수": "디지털·영상",
    "유튜브 사용일수": "디지털·영상",
    "넷플릭스 사용일수": "디지털·영상",

    # 생활서비스
    "금융 서비스 사용일수": "생활서비스",
    "쇼핑 서비스 사용일수": "생활서비스",
    "배달 서비스 사용일수": "생활서비스",
    "배달_브랜드 서비스 사용일수": "생활서비스",
    "배달_식재료 서비스 사용일수": "생활서비스"
}

feature_domain_df = pd.DataFrame({
    "컬럼명": analysis_cols,
    "영역": [feature_domain[x] for x in analysis_cols]
})

print("Feature 수:", len(feature_domain_df))

display(
    feature_domain_df.groupby("영역")
    .size()
    .reset_index(name="Feature수")
)

display(feature_domain_df)

Feature 수: 32

       영역  Feature수
0  디지털·영상         5
1  상주지 변화         2
2   생활서비스         5
3   이동·외출         5
4    자택체류         2
5   재정·결제         5
6    직장생활         2
7  커뮤니케이션         6

                  컬럼명      영역
0       야간상주지 변경횟수 평균  상주지 변화
1       주간상주지 변경횟수 평균  상주지 변화
2       평균 출근 소요시간 평균    직장생활
3          평균 근무시간 평균    직장생활
4          평일 총 이동 횟수   이동·외출
5       휴일 총 이동 횟수 평균   이동·외출
6   집 추정 위치 평일 총 체류시간    자택체류
7   집 추정 위치 휴일 총 체류시간    자택체류
8       평일 총 이동 거리 합계   이동·외출
9       휴일 총 이동 거리 합계   이동·외출
10         지하철이동일수 합계   이동·외출
11        게임 서비스 사용일수  디지털·영상
12        금융 서비스 사용일수   생활서비스
13        쇼핑 서비스 사용일수   생활서비스
14    동영상/방송 서비스 사용일수  디지털·영상
15           유튜브 사용일수  디지털·영상
16          넷플릭스 사용일수  디지털·영상
17        배달 서비스 사용일수   생활서비스
18    배달_브랜드 서비스 사용일수   생활서비스
19    배달_식재료 서비스 사용일수   생활서비스
20  최근 3개월 내 요금 연체 비율   재정·결제
21             평균 통화량  커뮤니케이션
22             평균 문자량  커뮤니케이션
23         평균 통화대상자 수  커뮤니케이션
24         평균 문자대상자 수  커뮤니케이션
25            데이터 사용량  디지털·영상
26       소액결재 사용횟수 평균   재정·결제
27       소액결재 사용금액 평균   재정·결제
28           SNS 사용횟수  커뮤니케이션
29         소액결재_사용자비율   재정·결제
30        소액결재_금액존재비율   재정·결제
31         카카오톡_비사용비율  커뮤니케이션

In [46]:
# 기존 영역표 복사
feature_review = feature_domain_df.copy()

# 기본값
feature_review["평균_coverage"] = np.nan

# 미추정형 20개 변수의 평균 coverage 연결
for variable in true_unestimated_map.keys():

    coverage_col = f"{variable}_coverage"

    feature_review.loc[
        feature_review["컬럼명"] == variable,
        "평균_coverage"
    ] = telecom_month_feature[coverage_col].mean()

# coverage 기준 품질 구분
def coverage_grade(x):
    if pd.isna(x):
        return "해당 없음"
    elif x >= 80:
        return "높음"
    elif x >= 50:
        return "중간"
    elif x >= 30:
        return "낮음"
    else:
        return "매우 낮음"

feature_review["coverage_평가"] = (
    feature_review["평균_coverage"]
    .apply(coverage_grade)
)

print(
    feature_review["coverage_평가"]
    .value_counts()
)

display(
    feature_review.sort_values(
        ["영역", "평균_coverage"],
        ascending=[True, False],
        na_position="last"
    ).round(2)
)

coverage_평가
높음       13
해당 없음    12
중간        3
낮음        3
매우 낮음     1
Name: count, dtype: int64

                  컬럼명      영역  평균_coverage coverage_평가
15           유튜브 사용일수  디지털·영상        96.26          높음
14    동영상/방송 서비스 사용일수  디지털·영상        92.76          높음
11        게임 서비스 사용일수  디지털·영상        91.43          높음
16          넷플릭스 사용일수  디지털·영상        48.94          낮음
25            데이터 사용량  디지털·영상          NaN       해당 없음
0       야간상주지 변경횟수 평균  상주지 변화       100.00          높음
1       주간상주지 변경횟수 평균  상주지 변화        76.90          중간
13        쇼핑 서비스 사용일수   생활서비스        94.82          높음
12        금융 서비스 사용일수   생활서비스        93.17          높음
17        배달 서비스 사용일수   생활서비스        79.88          중간
18    배달_브랜드 서비스 사용일수   생활서비스        30.79          낮음
19    배달_식재료 서비스 사용일수   생활서비스         1.22       매우 낮음
4          평일 총 이동 횟수   이동·외출        93.31          높음
8       평일 총 이동 거리 합계   이동·외출        92.60          높음
5       휴일 총 이동 횟수 평균   이동·외출        89.76          높음
9       휴일 총 이동 거리 합계   이동·외출        88.66          높음
10         지하철이동일수 합계   이동·외출        86.89          높음
6   집 추정 위치 평일 총 체류시간    자택체류        98.49          높음
7   집 추정 위치 휴일 총 체류시간    자택체류        97.99          높음
20  최근 3개월 내 요금 연체 비율   재정·결제          NaN       해당 없음
26       소액결재 사용횟수 평균   재정·결제          NaN       해당 없음
27       소액결재 사용금액 평균   재정·결제          NaN       해당 없음
29         소액결재_사용자비율   재정·결제          NaN       해당 없음
30        소액결재_금액존재비율   재정·결제          NaN       해당 없음
3          평균 근무시간 평균    직장생활        51.50          중간
2       평균 출근 소요시간 평균    직장생활        46.50          낮음
21             평균 통화량  커뮤니케이션          NaN       해당 없음
22             평균 문자량  커뮤니케이션          NaN       해당 없음
23         평균 통화대상자 수  커뮤니케이션          NaN       해당 없음
24         평균 문자대상자 수  커뮤니케이션          NaN       해당 없음
28           SNS 사용횟수  커뮤니케이션          NaN       해당 없음
31         카카오톡_비사용비율  커뮤니케이션          NaN       해당 없음

In [47]:
selection_map = {
    # 상주지 변화
    "야간상주지 변경횟수 평균": "핵심 후보",
    "주간상주지 변경횟수 평균": "보조 후보",

    # 직장생활
    "평균 근무시간 평균": "핵심 후보",
    "평균 출근 소요시간 평균": "보조 후보",

    # 이동·외출
    "평일 총 이동 횟수": "핵심 후보",
    "휴일 총 이동 횟수 평균": "핵심 후보",
    "지하철이동일수 합계": "보조 후보",
    "평일 총 이동 거리 합계": "제외 후보",
    "휴일 총 이동 거리 합계": "제외 후보",

    # 자택체류
    "집 추정 위치 평일 총 체류시간": "핵심 후보",
    "집 추정 위치 휴일 총 체류시간": "핵심 후보",

    # 커뮤니케이션
    "평균 통화대상자 수": "핵심 후보",
    "카카오톡_비사용비율": "핵심 후보",
    "평균 통화량": "보조 후보",
    "평균 문자량": "보조 후보",
    "평균 문자대상자 수": "보조 후보",
    "SNS 사용횟수": "보조 후보",

    # 재정·결제
    "최근 3개월 내 요금 연체 비율": "핵심 후보",
    "소액결재_사용자비율": "보조 후보",
    "소액결재 사용횟수 평균": "보조 후보",
    "소액결재_금액존재비율": "보조 후보",
    "소액결재 사용금액 평균": "보조 후보",

    # 디지털·영상
    "데이터 사용량": "핵심 후보",
    "동영상/방송 서비스 사용일수": "보조 후보",
    "게임 서비스 사용일수": "보조 후보",
    "유튜브 사용일수": "보조 후보",
    "넷플릭스 사용일수": "제외 후보",

    # 생활서비스
    "금융 서비스 사용일수": "핵심 후보",
    "쇼핑 서비스 사용일수": "핵심 후보",
    "배달 서비스 사용일수": "핵심 후보",
    "배달_브랜드 서비스 사용일수": "제외 후보",
    "배달_식재료 서비스 사용일수": "제외 후보"
}

feature_review["선별"] = (
    feature_review["컬럼명"]
    .map(selection_map)
)

print("미분류:",
      feature_review["선별"].isna().sum())

print()
print(feature_review["선별"].value_counts())

display(
    feature_review.sort_values(
        ["영역", "선별"]
    )
)

미분류: 0

선별
보조 후보    14
핵심 후보    13
제외 후보     5
Name: count, dtype: int64

                  컬럼명      영역  평균_coverage coverage_평가     선별
11        게임 서비스 사용일수  디지털·영상    91.432802          높음  보조 후보
14    동영상/방송 서비스 사용일수  디지털·영상    92.755266          높음  보조 후보
15           유튜브 사용일수  디지털·영상    96.263231          높음  보조 후보
16          넷플릭스 사용일수  디지털·영상    48.944402          낮음  제외 후보
25            데이터 사용량  디지털·영상          NaN       해당 없음  핵심 후보
1       주간상주지 변경횟수 평균  상주지 변화    76.897464          중간  보조 후보
0       야간상주지 변경횟수 평균  상주지 변화   100.000000          높음  핵심 후보
18    배달_브랜드 서비스 사용일수   생활서비스    30.794601          낮음  제외 후보
19    배달_식재료 서비스 사용일수   생활서비스     1.223635       매우 낮음  제외 후보
12        금융 서비스 사용일수   생활서비스    93.169293          높음  핵심 후보
13        쇼핑 서비스 사용일수   생활서비스    94.818248          높음  핵심 후보
17        배달 서비스 사용일수   생활서비스    79.881365          중간  핵심 후보
10         지하철이동일수 합계   이동·외출    86.890319          높음  보조 후보
8       평일 총 이동 거리 합계   이동·외출    92.596102          높음  제외 후보
9       휴일 총 이동 거리 합계   이동·외출    88.659587          높음  제외 후보
4          평일 총 이동 횟수   이동·외출    93.311118          높음  핵심 후보
5       휴일 총 이동 횟수 평균   이동·외출    89.763328          높음  핵심 후보
6   집 추정 위치 평일 총 체류시간    자택체류    98.494854          높음  핵심 후보
7   집 추정 위치 휴일 총 체류시간    자택체류    97.987867          높음  핵심 후보
26       소액결재 사용횟수 평균   재정·결제          NaN       해당 없음  보조 후보
27       소액결재 사용금액 평균   재정·결제          NaN       해당 없음  보조 후보
29         소액결재_사용자비율   재정·결제          NaN       해당 없음  보조 후보
30        소액결재_금액존재비율   재정·결제          NaN       해당 없음  보조 후보
20  최근 3개월 내 요금 연체 비율   재정·결제          NaN       해당 없음  핵심 후보
2       평균 출근 소요시간 평균    직장생활    46.502586          낮음  보조 후보
3          평균 근무시간 평균    직장생활    51.504332          중간  핵심 후보
21             평균 통화량  커뮤니케이션          NaN       해당 없음  보조 후보
22             평균 문자량  커뮤니케이션          NaN       해당 없음  보조 후보
24         평균 문자대상자 수  커뮤니케이션          NaN       해당 없음  보조 후보
28           SNS 사용횟수  커뮤니케이션          NaN       해당 없음  보조 후보
23         평균 통화대상자 수  커뮤니케이션          NaN       해당 없음  핵심 후보
31         카카오톡_비사용비율  커뮤니케이션          NaN       해당 없음  핵심 후보

In [48]:
core_cols = feature_review.loc[
    feature_review["선별"] == "핵심 후보",
    "컬럼명"
].tolist()

print("핵심 후보 수:", len(core_cols))
print(core_cols)

# --------------------------------
# 1. 132행 동×월 상관관계
# --------------------------------
corr_132 = (
    telecom_month_feature[core_cols]
    .corr()
)

# --------------------------------
# 2. 22개 동 평균 상관관계
# --------------------------------
core_dong_mean = (
    telecom_month_feature
    .groupby(["행정동코드", "행정동명"])[core_cols]
    .mean()
    .reset_index()
)

corr_22 = (
    core_dong_mean[core_cols]
    .corr()
)

# --------------------------------
# 두 분석에서 |r| >= 0.8인 조합 정리
# --------------------------------
result = []

for i in range(len(core_cols)):
    for j in range(i + 1, len(core_cols)):

        var1 = core_cols[i]
        var2 = core_cols[j]

        r132 = corr_132.loc[var1, var2]
        r22 = corr_22.loc[var1, var2]

        if abs(r132) >= 0.8 or abs(r22) >= 0.8:

            result.append({
                "변수1": var1,
                "변수2": var2,
                "r_132": r132,
                "r_22": r22,
                "132행_고상관": abs(r132) >= 0.8,
                "22동_고상관": abs(r22) >= 0.8
            })

core_high_corr = pd.DataFrame(result)

if len(core_high_corr) > 0:

    core_high_corr["max_abs_r"] = (
        core_high_corr[["r_132", "r_22"]]
        .abs()
        .max(axis=1)
    )

    core_high_corr = (
        core_high_corr
        .sort_values("max_abs_r", ascending=False)
        .drop(columns="max_abs_r")
        .reset_index(drop=True)
    )

print("|r| >= 0.8 조합 수:", len(core_high_corr))

display(core_high_corr.round(3))

핵심 후보 수: 13
['야간상주지 변경횟수 평균', '평균 근무시간 평균', '평일 총 이동 횟수', '휴일 총 이동 횟수 평균', '집 추정 위치 평일 총 체류시간', '집 추정 위치 휴일 총 체류시간', '금융 서비스 사용일수', '쇼핑 서비스 사용일수', '배달 서비스 사용일수', '최근 3개월 내 요금 연체 비율', '평균 통화대상자 수', '데이터 사용량', '카카오톡_비사용비율']
|r| >= 0.8 조합 수: 11

                  변수1                변수2  r_132   r_22  132행_고상관  22동_고상관
0         금융 서비스 사용일수        쇼핑 서비스 사용일수  0.933  0.952      True     True
1         배달 서비스 사용일수            데이터 사용량  0.596  0.936     False     True
2         배달 서비스 사용일수  최근 3개월 내 요금 연체 비율  0.879  0.921      True     True
3          평일 총 이동 횟수  집 추정 위치 평일 총 체류시간  0.915 -0.514      True    False
4   최근 3개월 내 요금 연체 비율            데이터 사용량  0.568  0.914     False     True
5          평일 총 이동 횟수      휴일 총 이동 횟수 평균  0.835  0.897      True     True
6          평일 총 이동 횟수        배달 서비스 사용일수 -0.220 -0.874     False     True
7          평일 총 이동 횟수  최근 3개월 내 요금 연체 비율 -0.191 -0.870     False     True
8          평일 총 이동 횟수            데이터 사용량  0.586 -0.836     False     True
9   집 추정 위치 휴일 총 체류시간            데이터 사용량  0.806  0.407      True    False
10  집 추정 위치 평일 총 체류시간  집 추정 위치 휴일 총 체류시간  0.805  0.706      True    False

In [49]:
compare_vars = [
    "금융 서비스 사용일수",
    "쇼핑 서비스 사용일수"
]

other_core = [
    x for x in core_cols
    if x not in compare_vars
]

rows = []

for var in compare_vars:

    corr132 = (
        telecom_month_feature[
            [var] + other_core
        ]
        .corr()
        .loc[var, other_core]
        .abs()
    )

    corr22 = (
        core_dong_mean[
            [var] + other_core
        ]
        .corr()
        .loc[var, other_core]
        .abs()
    )

    rows.append({
        "변수": var,
        "132행_평균절대상관": corr132.mean(),
        "132행_최대절대상관": corr132.max(),
        "22동_평균절대상관": corr22.mean(),
        "22동_최대절대상관": corr22.max(),
        "132행_0.8이상_개수": (corr132 >= 0.8).sum(),
        "22동_0.8이상_개수": (corr22 >= 0.8).sum()
    })

finance_shopping_compare = pd.DataFrame(rows)

display(
    finance_shopping_compare.round(3)
)

,변수,132행_평균절대상관,132행_최대절대상관,22동_평균절대상관,22동_최대절대상관,132행_0.8이상_개수,22동_0.8이상_개수
0,금융 서비스 사용일수,0.339,0.564,0.374,0.579,0,0
1,쇼핑 서비스 사용일수,0.339,0.566,0.384,0.636,0,0

In [50]:
core_id_cols = [
    "행정동코드",
    "행정동명",
    "기준연월"
]

telecom_core_month_feature = (
    telecom_month_feature[
        core_id_cols + core_cols
    ]
    .copy()
)

print(
    "shape:",
    telecom_core_month_feature.shape
)

print(
    "행정동 수:",
    telecom_core_month_feature["행정동코드"].nunique()
)

print(
    "월 수:",
    telecom_core_month_feature["기준연월"].nunique()
)

print(
    "key 중복:",
    telecom_core_month_feature
    .duplicated(["행정동코드", "기준연월"])
    .sum()
)

print(
    "결측값:",
    telecom_core_month_feature
    .isna()
    .sum()
    .sum()
)

display(
    telecom_core_month_feature.head()
)

shape: (132, 16)
행정동 수: 22
월 수: 6
key 중복: 0
결측값: 0

,행정동코드,행정동명,기준연월,야간상주지 변경횟수 평균,평균 근무시간 평균,평일 총 이동 횟수,휴일 총 이동 횟수 평균,집 추정 위치 평일 총 체류시간,집 추정 위치 휴일 총 체류시간,금융 서비스 사용일수,쇼핑 서비스 사용일수,배달 서비스 사용일수,최근 3개월 내 요금 연체 비율,평균 통화대상자 수,데이터 사용량,카카오톡_비사용비율
0,1123051,신사동,2025-07,8.428059,520.410434,20.415689,11.205907,5.535830e+05,113811.790351,149.557951,217.714911,11.734033,6.776245,13.876814,5.866857,5.425012
1,1123051,신사동,2025-08,9.390207,522.494227,22.212160,9.251042,6.383970e+05,112938.999838,156.225831,222.780758,11.686835,6.392381,13.505467,5.898828,5.592277
2,1123051,신사동,2025-09,10.339089,503.586393,33.630830,12.961381,1.027583e+06,165015.675619,163.113892,230.586333,12.035779,7.354896,13.784785,8.944226,5.433271
3,1123051,신사동,2025-10,11.295327,522.463533,31.122560,15.004846,9.463711e+05,197617.172372,166.766962,239.640731,12.345874,7.098781,13.322253,9.139346,5.108904
4,1123051,신사동,2025-11,12.184634,513.144667,21.424146,9.925350,6.184314e+05,135405.774827,163.744602,239.962233,12.419794,6.339821,13.549794,6.226629,5.240453

In [51]:
# 전체 통신정보 중간 Feature
telecom_month_feature.to_csv(
    "gangnam_telecom_month_features_2025_07_12.csv",
    index=False,
    encoding="utf-8-sig"
)

# 선별된 핵심 통신정보 Feature
telecom_core_month_feature.to_csv(
    "gangnam_telecom_core_month_features_2025_07_12.csv",
    index=False,
    encoding="utf-8-sig"
)

print(
    "전체 중간 Feature:",
    telecom_month_feature.shape
)

print(
    "핵심 분석 Feature:",
    telecom_core_month_feature.shape
)

전체 중간 Feature: (132, 55)
핵심 분석 Feature: (132, 16)

In [52]:
from google.colab import files

files.download(
    "gangnam_telecom_month_features_2025_07_12.csv"
)

files.download(
    "gangnam_telecom_core_month_features_2025_07_12.csv"
)

In [53]:
# 비교 키
key_cols = [
    "행정동코드",
    "행정동명",
    "기준연월"
]

# -----------------------------------
# 1. 각 테이블 기본 구조 확인
# -----------------------------------
print("관심집단:", interest_month_feature.shape)
print("통신정보:", telecom_core_month_feature.shape)

print(
    "관심집단 key 중복:",
    interest_month_feature
    .duplicated(["행정동코드", "기준연월"])
    .sum()
)

print(
    "통신정보 key 중복:",
    telecom_core_month_feature
    .duplicated(["행정동코드", "기준연월"])
    .sum()
)

# -----------------------------------
# 2. 행정동×월 키 일치 여부 확인
# -----------------------------------
key_check = (
    interest_month_feature[key_cols]
    .merge(
        telecom_core_month_feature[key_cols],
        on=key_cols,
        how="outer",
        indicator=True
    )
)

print("\n키 비교 결과")
print(key_check["_merge"].value_counts())

# -----------------------------------
# 3. 한쪽에만 존재하는 키 확인
# -----------------------------------
unmatched = key_check[
    key_check["_merge"] != "both"
]

print(
    "\n불일치 key 수:",
    len(unmatched)
)

if len(unmatched) > 0:
    display(unmatched)

관심집단: (132, 15)
통신정보: (132, 16)
관심집단 key 중복: 0
통신정보 key 중복: 0

키 비교 결과
_merge
both          132
left_only       0
right_only      0
Name: count, dtype: int64

불일치 key 수: 0

In [54]:
# 관심집단에서 사용할 9개 비율 Feature
interest_ratio_cols = [
    "low_comm_ratio",
    "low_weekday_outing_ratio",
    "low_holiday_outing_ratio",
    "high_worktime_ratio",
    "high_video_ratio",
    "high_life_service_ratio",
    "financial_interest_ratio",
    "very_low_outing_ratio",
    "very_low_outing_comm_ratio"
]

# -----------------------------------
# 1. 두 테이블 임시 결합
# -----------------------------------
relation_check = (
    interest_month_feature[
        key_cols + interest_ratio_cols
    ]
    .merge(
        telecom_core_month_feature[
            key_cols + core_cols
        ],
        on=key_cols,
        how="inner",
        validate="one_to_one"
    )
)

print("임시 결합 shape:", relation_check.shape)
print("결측값:", relation_check.isna().sum().sum())

# -----------------------------------
# 2. 관심집단 × 통신정보 교차상관
# -----------------------------------
cross_corr = relation_check[
    interest_ratio_cols + core_cols
].corr().loc[
    interest_ratio_cols,
    core_cols
]

# |r| >= 0.7인 관계만 추출
cross_pairs = []

for interest_var in interest_ratio_cols:
    for telecom_var in core_cols:

        r = cross_corr.loc[
            interest_var,
            telecom_var
        ]

        if abs(r) >= 0.7:
            cross_pairs.append({
                "관심집단_Feature": interest_var,
                "통신정보_Feature": telecom_var,
                "상관계수": r
            })

cross_pairs = pd.DataFrame(cross_pairs)

if len(cross_pairs) > 0:

    cross_pairs["절대상관"] = (
        cross_pairs["상관계수"].abs()
    )

    cross_pairs = (
        cross_pairs
        .sort_values(
            "절대상관",
            ascending=False
        )
        .drop(columns="절대상관")
        .reset_index(drop=True)
    )

print(
    "|r| >= 0.7 교차 관계 수:",
    len(cross_pairs)
)

display(cross_pairs.round(3))

임시 결합 shape: (132, 25)
결측값: 0
|r| >= 0.7 교차 관계 수: 4

               관심집단_Feature       통신정보_Feature   상관계수
0  low_weekday_outing_ratio        배달 서비스 사용일수  0.737
1   high_life_service_ratio  최근 3개월 내 요금 연체 비율  0.736
2       high_worktime_ratio        배달 서비스 사용일수  0.714
3       high_worktime_ratio  최근 3개월 내 요금 연체 비율  0.704

In [55]:
# 22개 행정동의 6개월 평균
relation_dong = (
    relation_check
    .groupby(
        ["행정동코드", "행정동명"]
    )[interest_ratio_cols + core_cols]
    .mean()
    .reset_index()
)

print("동 단위 shape:", relation_dong.shape)

# 관심집단 × 통신정보 교차상관
cross_corr_22 = (
    relation_dong[
        interest_ratio_cols + core_cols
    ]
    .corr()
    .loc[
        interest_ratio_cols,
        core_cols
    ]
)

cross_pairs_22 = []

for interest_var in interest_ratio_cols:
    for telecom_var in core_cols:

        r = cross_corr_22.loc[
            interest_var,
            telecom_var
        ]

        if abs(r) >= 0.7:
            cross_pairs_22.append({
                "관심집단_Feature": interest_var,
                "통신정보_Feature": telecom_var,
                "상관계수": r
            })

cross_pairs_22 = pd.DataFrame(
    cross_pairs_22
)

if len(cross_pairs_22) > 0:

    cross_pairs_22["절대상관"] = (
        cross_pairs_22[
            "상관계수"
        ].abs()
    )

    cross_pairs_22 = (
        cross_pairs_22
        .sort_values(
            "절대상관",
            ascending=False
        )
        .drop(columns="절대상관")
        .reset_index(drop=True)
    )

print(
    "|r| >= 0.7 동 단위 교차 관계 수:",
    len(cross_pairs_22)
)

display(
    cross_pairs_22.round(3)
)

동 단위 shape: (22, 24)
|r| >= 0.7 동 단위 교차 관계 수: 15

                  관심집단_Feature       통신정보_Feature   상관계수
0   very_low_outing_comm_ratio      야간상주지 변경횟수 평균 -0.773
1     low_weekday_outing_ratio        배달 서비스 사용일수  0.751
2        very_low_outing_ratio         평일 총 이동 횟수 -0.742
3      high_life_service_ratio  최근 3개월 내 요금 연체 비율  0.741
4          high_worktime_ratio        배달 서비스 사용일수  0.738
5   very_low_outing_comm_ratio         카카오톡_비사용비율  0.733
6     low_weekday_outing_ratio  최근 3개월 내 요금 연체 비율  0.728
7          high_worktime_ratio  최근 3개월 내 요금 연체 비율  0.724
8   very_low_outing_comm_ratio         평일 총 이동 횟수 -0.716
9             high_video_ratio        배달 서비스 사용일수  0.715
10    low_weekday_outing_ratio            데이터 사용량  0.713
11       very_low_outing_ratio        배달 서비스 사용일수  0.710
12         high_worktime_ratio         평일 총 이동 횟수 -0.710
13       very_low_outing_ratio  최근 3개월 내 요금 연체 비율  0.707
14     high_life_service_ratio         카카오톡_비사용비율  0.701

In [56]:
# 관심집단 9개 + 통신정보 핵심 13개 결합

citizen_life_month_feature = (
    interest_month_feature[
        key_cols + interest_ratio_cols
    ]
    .merge(
        telecom_core_month_feature[
            key_cols + core_cols
        ],
        on=key_cols,
        how="inner",
        validate="one_to_one"
    )
)

print(
    "shape:",
    citizen_life_month_feature.shape
)

print(
    "행정동 수:",
    citizen_life_month_feature["행정동코드"].nunique()
)

print(
    "월 수:",
    citizen_life_month_feature["기준연월"].nunique()
)

print(
    "key 중복:",
    citizen_life_month_feature
    .duplicated(["행정동코드", "기준연월"])
    .sum()
)

print(
    "결측값:",
    citizen_life_month_feature
    .isna()
    .sum()
    .sum()
)

print(
    "관심집단 Feature:",
    len(interest_ratio_cols)
)

print(
    "통신정보 Feature:",
    len(core_cols)
)

display(
    citizen_life_month_feature.head()
)

shape: (132, 25)
행정동 수: 22
월 수: 6
key 중복: 0
결측값: 0
관심집단 Feature: 9
통신정보 Feature: 13

,행정동코드,행정동명,기준연월,low_comm_ratio,low_weekday_outing_ratio,low_holiday_outing_ratio,high_worktime_ratio,high_video_ratio,high_life_service_ratio,financial_interest_ratio,...,휴일 총 이동 횟수 평균,집 추정 위치 평일 총 체류시간,집 추정 위치 휴일 총 체류시간,금융 서비스 사용일수,쇼핑 서비스 사용일수,배달 서비스 사용일수,최근 3개월 내 요금 연체 비율,평균 통화대상자 수,데이터 사용량,카카오톡_비사용비율
0,1123051,신사동,2025-07,11.623770,6.895239,9.537738,7.997832,10.446705,9.260539,8.092990,...,11.205907,5.535830e+05,113811.790351,149.557951,217.714911,11.734033,6.776245,13.876814,5.866857,5.425012
1,1123051,신사동,2025-08,10.664848,7.222540,10.087490,8.937719,10.371842,8.709413,8.518196,...,9.251042,6.383970e+05,112938.999838,156.225831,222.780758,11.686835,6.392381,13.505467,5.898828,5.592277
2,1123051,신사동,2025-09,10.999827,8.165655,9.768221,10.735677,10.879871,9.406299,8.469654,...,12.961381,1.027583e+06,165015.675619,163.113892,230.586333,12.035779,7.354896,13.784785,8.944226,5.433271
3,1123051,신사동,2025-10,11.028285,9.386603,9.346032,10.847560,10.877886,8.965322,8.093665,...,15.004846,9.463711e+05,197617.172372,166.766962,239.640731,12.345874,7.098781,13.322253,9.139346,5.108904
4,1123051,신사동,2025-11,10.813950,9.620151,10.843497,9.712487,10.467998,9.602505,8.264663,...,9.925350,6.184314e+05,135405.774827,163.744602,239.962233,12.419794,6.339821,13.549794,6.226629,5.240453

In [57]:
citizen_life_month_feature.to_csv(
    "gangnam_citizen_life_month_features_2025_07_12.csv",
    index=False,
    encoding="utf-8-sig"
)

print(
    "저장 완료:",
    citizen_life_month_feature.shape
)

저장 완료: (132, 25)

In [58]:
from google.colab import files

files.download(
    "gangnam_citizen_life_month_features_2025_07_12.csv"
)